In [2]:
import os
import sys
import json
from pathlib import Path
from typing import Any, Dict, List, Optional
import logging

import numpy as np
import pandas as pd
from sqlalchemy.orm import Session

# konfiguracja logowania w notebooku
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("dataset-notebook")

# ustawienie ścieżki do backendu, żeby móc importować moduły app.*
PROJECT_ROOT = Path("..").resolve()
BACKEND_PATH = PROJECT_ROOT / "backend"
if str(BACKEND_PATH) not in sys.path:
    sys.path.insert(0, str(BACKEND_PATH))

from app.database import SessionLocal
from app.models.user import User
from app.models.symptom_profile import SymptomProfile
from app.services.embedding_service import generate_embedding, generate_embeddings_batch
from app.services.matching_service import find_matching_group, add_user_to_group
from app.routers.auth import _hash_password

DATA_PATH = PROJECT_ROOT / "data" / "test_data.json"
DRY_RUN = False

/home/mario/miniconda3/envs/zebrapoint/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from contextlib import contextmanager
from collections import Counter


@contextmanager
def get_db() -> Session:
    """Kontekst menedżer na sesję DB (tak jak w backendzie, ale dla notebooka)."""
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def load_dataset(path: Path) -> List[Dict[str, Any]]:
    """Wczytuje testowy zbiór danych z JSON-a."""
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError("Plik JSON powinien zawierać listę obiektów")

    records: List[Dict[str, Any]] = []
    for idx, raw in enumerate(data, start=1):
        email = raw.get("email")
        password = raw.get("haslo")
        description = raw.get("opis")
        display_name = raw.get("display_name")

        if not email or not password or not description:
            raise ValueError(f"Rekord {idx} ma brakujące pola (email/haslo/opis)")

        # display_name jest wymagany zgodnie z planem; jeśli go nie ma,
        # można doraźnie użyć prefiksu z emaila.
        if not display_name:
            display_name = email.split("@")[0]

        description = str(description).strip()
        if len(description) < 100:
            raise ValueError(
                f"Opis w rekordzie {idx} jest za krótki ({len(description)} znaków). "
                "Potrzebne >= 100 znaków."
            )

        records.append(
            {
                "email": str(email).strip(),
                "password": str(password),
                "display_name": str(display_name).strip(),
                "description": description,
            }
        )

    logger.info("Wczytano %d rekordów z %s", len(records), path)
    return records


def create_user_from_record(db: Session, record: Dict[str, Any]) -> User:
    """Tworzy użytkownika na podstawie rekordu z JSON-a albo zwraca istniejącego."""
    email = record["email"]
    display_name = record["display_name"]
    password = record["password"]

    user = db.query(User).filter(User.email == email).first()
    if user:
        logger.info("Użytkownik %s już istnieje — pomijam tworzenie", email)
        return user

    user = User(
        email=email,
        password_hash=_hash_password(password),
        display_name=display_name,
    )
    db.add(user)
    db.flush()
    logger.info("Utworzono użytkownika %s", email)
    return user


def create_or_update_symptom_profile(
    db: Session,
    user: User,
    description: str,
) -> SymptomProfile:
    """Tworzy lub aktualizuje profil objawów i dopasowuje grupę."""
    profile = (
        db.query(SymptomProfile)
        .filter(SymptomProfile.user_id == user.id)
        .first()
    )

    embedding = generate_embedding(description)
    match = find_matching_group(db, embedding, user.id)
    group_id = match["group_id"]

    if profile is None:
        profile = SymptomProfile(
            user_id=user.id,
            description=description,
            embedding=embedding,
            group_id=group_id,
            match_score=match["score"],
        )
        db.add(profile)
        logger.info("Utworzono profil objawów dla %s", user.email)
    else:
        profile.description = description
        profile.embedding = embedding
        profile.group_id = group_id
        profile.match_score = match["score"]
        logger.info("Zaktualizowano profil objawów dla %s", user.email)

    add_user_to_group(db, user.id, group_id)

    db.flush()
    return profile

In [4]:
# Test połączenia z bazą Supabase

with get_db() as db:
    try:
        user_count = db.query(User).count()
        print(f"Połączenie OK. Liczba użytkowników w bazie: {user_count}")
    except Exception as exc:
        print("Błąd połączenia z bazą:", exc)
        raise

2026-03-12 18:12:30,865 INFO sqlalchemy.engine.Engine select pg_catalog.version()

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()

2026-03-12 18:12:30,866 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2026-03-12 18:12:30,927 INFO sqlalchemy.engine.Engine select current_schema()

INFO:sqlalchemy.engine.Engine:select current_schema()

2026-03-12 18:12:30,928 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2026-03-12 18:12:30,985 INFO sqlalchemy.engine.Engine show standard_conforming_strings

INFO:sqlalchemy.engine.Engine:show standard_conforming_strings

2026-03-12 18:12:30,987 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2026-03-12 18:12:31,045 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-12 18:12:31,050 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users) AS anon_1

INFO:sqlalchemy.engine.Engine:SELECT count(*) AS count_1
FROM (SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users) AS anon_1

2026-03-12 18:12:31,051 INFO sqlalchemy.engine.Engine [generated in 0.00090s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00090s] {}

Połączenie OK. Liczba użytkowników w bazie: 4
2026-03-12 18:12:31,124 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

In [8]:
# Wczytanie danych z JSON i podgląd struktury

records = load_dataset(DATA_PATH)
print(f"Liczba rekordów w zbiorze: {len(records)}")

df_preview = pd.DataFrame(records)
df_preview.head()

INFO:dataset-notebook:Wczytano 27 rekordów z /home/mario/workspace/zebrapoint/data/test_data.json

Liczba rekordów w zbiorze: 27

,email,password,display_name,description
0,test0004@zebra.pl,test1234,Mama 4,Nasze dziecko urodziło się z bardzo niską masą...
1,test0005@zebra.pl,test1234,Mama 5,Od urodzenia zauważyliśmy u córki bardzo jasną...
2,test0006@zebra.pl,test1234,Mama 6,Syn od pierwszych miesięcy życia miał trudnośc...
3,test0007@zebra.pl,test1234,Mama 7,Nasze dziecko od małego bardzo mało mówiło. Te...
4,test0008@zebra.pl,test1234,Mama 8,Córka od niemowlęctwa miała częste napady drga...

In [9]:
# Utworzenie użytkowników w tabeli `users` na podstawie rekordów

created = 0
existing = 0

with get_db() as db:
    for rec in records:
        user_before = db.query(User).filter(User.email == rec["email"]).first()
        user = create_user_from_record(db, rec)
        if user_before is None:
            created += 1
        else:
            existing += 1

print(f"Nowo utworzonych użytkowników: {created}")
print(f"Użytkownicy już istniejący:   {existing}")

2026-03-12 18:23:01,813 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-12 18:23:01,818 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:01,819 INFO sqlalchemy.engine.Engine [generated in 0.00129s] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00129s] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

2026-03-12 18:23:01,958 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:01,962 INFO sqlalchemy.engine.Engine [cached since 0.1443s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.1443s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

2026-03-12 18:23:02,247 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:02,248 INFO sqlalchemy.engine.Engine [generated in 0.00149s] {'id': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'email': 'test0004@zebra.pl', 'password_hash': '$2b$12$1wlrsRwdEu2JDiub7swrM.msC7lYpXt4WbK7xpKwczC0N6IMJsPES', 'display_name': 'Mama 4', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[generated in 0.00149s] {'id': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'email': 'test0004@zebra.pl', 'password_hash': '$2b$12$1wlrsRwdEu2JDiub7swrM.msC7lYpXt4WbK7xpKwczC0N6IMJsPES', 'display_name': 'Mama 4', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0004@zebra.pl

2026-03-12 18:23:02,290 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:02,291 INFO sqlalchemy.engine.Engine [cached since 0.4738s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.4738s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

2026-03-12 18:23:02,322 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:02,323 INFO sqlalchemy.engine.Engine [cached since 0.5056s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.5056s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

2026-03-12 18:23:02,581 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:02,582 INFO sqlalchemy.engine.Engine [cached since 0.3351s ago] {'id': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'email': 'test0005@zebra.pl', 'password_hash': '$2b$12$OZ/I.ViinxKIylGiugnGEOMp.xiYhlSy9uPd0j9szu/PjZEXlxDV.', 'display_name': 'Mama 5', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 0.3351s ago] {'id': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'email': 'test0005@zebra.pl', 'password_hash': '$2b$12$OZ/I.ViinxKIylGiugnGEOMp.xiYhlSy9uPd0j9szu/PjZEXlxDV.', 'display_name': 'Mama 5', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0005@zebra.pl

2026-03-12 18:23:02,614 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:02,615 INFO sqlalchemy.engine.Engine [cached since 0.7979s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.7979s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

2026-03-12 18:23:02,649 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:02,650 INFO sqlalchemy.engine.Engine [cached since 0.8324s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.8324s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

2026-03-12 18:23:02,921 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:02,922 INFO sqlalchemy.engine.Engine [cached since 0.6759s ago] {'id': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'email': 'test0006@zebra.pl', 'password_hash': '$2b$12$XRDzFvidYKX4p9SV0hH.VObjj5DZp2DsoNkEv289K5rUudBTYXUcq', 'display_name': 'Mama 6', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 0.6759s ago] {'id': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'email': 'test0006@zebra.pl', 'password_hash': '$2b$12$XRDzFvidYKX4p9SV0hH.VObjj5DZp2DsoNkEv289K5rUudBTYXUcq', 'display_name': 'Mama 6', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0006@zebra.pl

2026-03-12 18:23:02,955 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:02,956 INFO sqlalchemy.engine.Engine [cached since 1.139s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.139s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

2026-03-12 18:23:02,984 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:02,985 INFO sqlalchemy.engine.Engine [cached since 1.168s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.168s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

2026-03-12 18:23:03,251 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:03,252 INFO sqlalchemy.engine.Engine [cached since 1.005s ago] {'id': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'email': 'test0007@zebra.pl', 'password_hash': '$2b$12$Xm7wVy3Wiek1lUTpn.7GUeUO4wsVb4OLT42N6GIxo3fEJFSW8aOiC', 'display_name': 'Mama 7', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 1.005s ago] {'id': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'email': 'test0007@zebra.pl', 'password_hash': '$2b$12$Xm7wVy3Wiek1lUTpn.7GUeUO4wsVb4OLT42N6GIxo3fEJFSW8aOiC', 'display_name': 'Mama 7', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0007@zebra.pl

2026-03-12 18:23:03,282 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:03,283 INFO sqlalchemy.engine.Engine [cached since 1.466s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.466s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

2026-03-12 18:23:03,313 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:03,314 INFO sqlalchemy.engine.Engine [cached since 1.497s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.497s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

2026-03-12 18:23:03,582 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:03,583 INFO sqlalchemy.engine.Engine [cached since 1.336s ago] {'id': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'email': 'test0008@zebra.pl', 'password_hash': '$2b$12$G1kJDtWzyzzFVQT0jQ2SKeFxUO.OUHzShX5RbKSogFTpEmozBW68C', 'display_name': 'Mama 8', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 1.336s ago] {'id': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'email': 'test0008@zebra.pl', 'password_hash': '$2b$12$G1kJDtWzyzzFVQT0jQ2SKeFxUO.OUHzShX5RbKSogFTpEmozBW68C', 'display_name': 'Mama 8', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0008@zebra.pl

2026-03-12 18:23:03,615 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:03,616 INFO sqlalchemy.engine.Engine [cached since 1.799s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.799s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

2026-03-12 18:23:03,645 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:03,646 INFO sqlalchemy.engine.Engine [cached since 1.829s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.829s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

2026-03-12 18:23:03,914 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:03,915 INFO sqlalchemy.engine.Engine [cached since 1.669s ago] {'id': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'email': 'test0009@zebra.pl', 'password_hash': '$2b$12$tmsaMMS/TwMP8OutpfJUWOV5ge83PxNLd9D8dQ9np5U3KowLCPp0q', 'display_name': 'Mama 9', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 1.669s ago] {'id': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'email': 'test0009@zebra.pl', 'password_hash': '$2b$12$tmsaMMS/TwMP8OutpfJUWOV5ge83PxNLd9D8dQ9np5U3KowLCPp0q', 'display_name': 'Mama 9', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0009@zebra.pl

2026-03-12 18:23:03,946 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:03,948 INFO sqlalchemy.engine.Engine [cached since 2.13s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.13s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

2026-03-12 18:23:03,977 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:03,979 INFO sqlalchemy.engine.Engine [cached since 2.162s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.162s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

2026-03-12 18:23:04,248 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:04,249 INFO sqlalchemy.engine.Engine [cached since 2.002s ago] {'id': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'email': 'test0010@zebra.pl', 'password_hash': '$2b$12$Ph2Uxe0wo9qhIDLx7nOpMOOCgiBiwT60ZiuLV54jv4J/JxWbVnWOG', 'display_name': 'Mama 10', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.002s ago] {'id': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'email': 'test0010@zebra.pl', 'password_hash': '$2b$12$Ph2Uxe0wo9qhIDLx7nOpMOOCgiBiwT60ZiuLV54jv4J/JxWbVnWOG', 'display_name': 'Mama 10', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0010@zebra.pl

2026-03-12 18:23:04,279 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:04,281 INFO sqlalchemy.engine.Engine [cached since 2.463s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.463s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

2026-03-12 18:23:04,309 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:04,311 INFO sqlalchemy.engine.Engine [cached since 2.493s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.493s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

2026-03-12 18:23:04,578 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:04,579 INFO sqlalchemy.engine.Engine [cached since 2.333s ago] {'id': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'email': 'test0011@zebra.pl', 'password_hash': '$2b$12$LPzXf4s4hPE0wmMC.wbPMeh79LQEp7HLBbN.3GHacVvdpsAndlLl2', 'display_name': 'Mama 11', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.333s ago] {'id': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'email': 'test0011@zebra.pl', 'password_hash': '$2b$12$LPzXf4s4hPE0wmMC.wbPMeh79LQEp7HLBbN.3GHacVvdpsAndlLl2', 'display_name': 'Mama 11', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0011@zebra.pl

2026-03-12 18:23:04,610 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:04,612 INFO sqlalchemy.engine.Engine [cached since 2.794s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.794s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

2026-03-12 18:23:04,641 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:04,642 INFO sqlalchemy.engine.Engine [cached since 2.825s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.825s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

2026-03-12 18:23:04,910 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:04,911 INFO sqlalchemy.engine.Engine [cached since 2.664s ago] {'id': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'email': 'test0012@zebra.pl', 'password_hash': '$2b$12$kVnD5nentPYemKWeZWwgyOlndIQ4bK3JX2LppkI7na29e1UuR7ex2', 'display_name': 'Mama 12', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.664s ago] {'id': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'email': 'test0012@zebra.pl', 'password_hash': '$2b$12$kVnD5nentPYemKWeZWwgyOlndIQ4bK3JX2LppkI7na29e1UuR7ex2', 'display_name': 'Mama 12', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0012@zebra.pl

2026-03-12 18:23:04,942 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:04,943 INFO sqlalchemy.engine.Engine [cached since 3.125s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.125s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

2026-03-12 18:23:04,974 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:04,975 INFO sqlalchemy.engine.Engine [cached since 3.158s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.158s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

2026-03-12 18:23:05,240 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:05,241 INFO sqlalchemy.engine.Engine [cached since 2.994s ago] {'id': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'email': 'test0013@zebra.pl', 'password_hash': '$2b$12$oRRanClZId6BNUbW82yeoekJ5Z7XXRaZqI0eb5xIy8pWF0oHNE.uu', 'display_name': 'Mama 13', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.994s ago] {'id': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'email': 'test0013@zebra.pl', 'password_hash': '$2b$12$oRRanClZId6BNUbW82yeoekJ5Z7XXRaZqI0eb5xIy8pWF0oHNE.uu', 'display_name': 'Mama 13', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0013@zebra.pl

2026-03-12 18:23:05,271 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:05,272 INFO sqlalchemy.engine.Engine [cached since 3.454s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.454s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

2026-03-12 18:23:05,302 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:05,303 INFO sqlalchemy.engine.Engine [cached since 3.486s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.486s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

2026-03-12 18:23:05,572 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:05,573 INFO sqlalchemy.engine.Engine [cached since 3.326s ago] {'id': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'email': 'test0014@zebra.pl', 'password_hash': '$2b$12$m12JopTF34ynprENLmQmd.yE8MSguK2XcU7K13P2StEbGP7a/YXjK', 'display_name': 'Mama 14', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 3.326s ago] {'id': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'email': 'test0014@zebra.pl', 'password_hash': '$2b$12$m12JopTF34ynprENLmQmd.yE8MSguK2XcU7K13P2StEbGP7a/YXjK', 'display_name': 'Mama 14', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0014@zebra.pl

2026-03-12 18:23:05,603 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:05,605 INFO sqlalchemy.engine.Engine [cached since 3.788s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.788s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

2026-03-12 18:23:05,634 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:05,636 INFO sqlalchemy.engine.Engine [cached since 3.818s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.818s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

2026-03-12 18:23:05,918 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:05,919 INFO sqlalchemy.engine.Engine [cached since 3.673s ago] {'id': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'email': 'test0015@zebra.pl', 'password_hash': '$2b$12$u117f19rTXFR4UVDO7wwtef.GzdoGWzZ/kwOhyombfXR7BVi/s1SK', 'display_name': 'Mama 15', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 3.673s ago] {'id': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'email': 'test0015@zebra.pl', 'password_hash': '$2b$12$u117f19rTXFR4UVDO7wwtef.GzdoGWzZ/kwOhyombfXR7BVi/s1SK', 'display_name': 'Mama 15', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0015@zebra.pl

2026-03-12 18:23:05,951 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:05,952 INFO sqlalchemy.engine.Engine [cached since 4.135s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.135s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

2026-03-12 18:23:05,982 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:05,984 INFO sqlalchemy.engine.Engine [cached since 4.166s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.166s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

2026-03-12 18:23:06,253 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:06,254 INFO sqlalchemy.engine.Engine [cached since 4.007s ago] {'id': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'email': 'test0016@zebra.pl', 'password_hash': '$2b$12$8AtATer5kiJ2Ehq5aEWIlOKbDP30e11EfJEVH/8lOrRx723eNWCxy', 'display_name': 'Mama 16', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 4.007s ago] {'id': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'email': 'test0016@zebra.pl', 'password_hash': '$2b$12$8AtATer5kiJ2Ehq5aEWIlOKbDP30e11EfJEVH/8lOrRx723eNWCxy', 'display_name': 'Mama 16', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0016@zebra.pl

2026-03-12 18:23:06,287 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:06,288 INFO sqlalchemy.engine.Engine [cached since 4.47s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.47s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

2026-03-12 18:23:06,318 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:06,319 INFO sqlalchemy.engine.Engine [cached since 4.502s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.502s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

2026-03-12 18:23:06,588 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:06,589 INFO sqlalchemy.engine.Engine [cached since 4.342s ago] {'id': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'email': 'test0017@zebra.pl', 'password_hash': '$2b$12$BNpa7FLXFgayfJ5Wwf5UCON0LS7EJUqR0oUdznwNZLj0.o63Oirlm', 'display_name': 'Mama 17', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 4.342s ago] {'id': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'email': 'test0017@zebra.pl', 'password_hash': '$2b$12$BNpa7FLXFgayfJ5Wwf5UCON0LS7EJUqR0oUdznwNZLj0.o63Oirlm', 'display_name': 'Mama 17', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0017@zebra.pl

2026-03-12 18:23:06,620 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:06,621 INFO sqlalchemy.engine.Engine [cached since 4.803s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.803s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

2026-03-12 18:23:06,650 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:06,651 INFO sqlalchemy.engine.Engine [cached since 4.834s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.834s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

2026-03-12 18:23:06,917 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:06,918 INFO sqlalchemy.engine.Engine [cached since 4.672s ago] {'id': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'email': 'test0018@zebra.pl', 'password_hash': '$2b$12$k9n0Bt8xaGL6CoPSPLsGNetyoDymXgGWP0OsxWFH79Dzwj1tuujlq', 'display_name': 'Mama 18', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 4.672s ago] {'id': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'email': 'test0018@zebra.pl', 'password_hash': '$2b$12$k9n0Bt8xaGL6CoPSPLsGNetyoDymXgGWP0OsxWFH79Dzwj1tuujlq', 'display_name': 'Mama 18', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0018@zebra.pl

2026-03-12 18:23:06,947 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:06,949 INFO sqlalchemy.engine.Engine [cached since 5.131s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.131s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

2026-03-12 18:23:06,978 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:06,979 INFO sqlalchemy.engine.Engine [cached since 5.162s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.162s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

2026-03-12 18:23:07,249 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:07,250 INFO sqlalchemy.engine.Engine [cached since 5.004s ago] {'id': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'email': 'test0019@zebra.pl', 'password_hash': '$2b$12$fF5RNtOvZesS27U68kbwjOIT2CJa6jQJc0vkUWrhArC5To9bkiSb2', 'display_name': 'Mama 19', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 5.004s ago] {'id': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'email': 'test0019@zebra.pl', 'password_hash': '$2b$12$fF5RNtOvZesS27U68kbwjOIT2CJa6jQJc0vkUWrhArC5To9bkiSb2', 'display_name': 'Mama 19', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0019@zebra.pl

2026-03-12 18:23:07,279 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:07,280 INFO sqlalchemy.engine.Engine [cached since 5.463s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.463s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

2026-03-12 18:23:07,310 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:07,312 INFO sqlalchemy.engine.Engine [cached since 5.494s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.494s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

2026-03-12 18:23:07,580 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:07,581 INFO sqlalchemy.engine.Engine [cached since 5.334s ago] {'id': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'email': 'test0020@zebra.pl', 'password_hash': '$2b$12$X2F5zm2Vh7AvuvTgeQVrsuZOBwiolC5AtT/nrNJGur2xI4agJikqi', 'display_name': 'Mama 20', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 5.334s ago] {'id': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'email': 'test0020@zebra.pl', 'password_hash': '$2b$12$X2F5zm2Vh7AvuvTgeQVrsuZOBwiolC5AtT/nrNJGur2xI4agJikqi', 'display_name': 'Mama 20', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0020@zebra.pl

2026-03-12 18:23:07,610 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:07,612 INFO sqlalchemy.engine.Engine [cached since 5.795s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.795s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

2026-03-12 18:23:07,643 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:07,644 INFO sqlalchemy.engine.Engine [cached since 5.827s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.827s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

2026-03-12 18:23:07,931 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:07,932 INFO sqlalchemy.engine.Engine [cached since 5.686s ago] {'id': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'email': 'test0021@zebra.pl', 'password_hash': '$2b$12$EZpbx7q4WkYy6vj89bhrGePqo6yCCL994rFqJWMgxmh6.XGb67lia', 'display_name': 'Mama 21', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 5.686s ago] {'id': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'email': 'test0021@zebra.pl', 'password_hash': '$2b$12$EZpbx7q4WkYy6vj89bhrGePqo6yCCL994rFqJWMgxmh6.XGb67lia', 'display_name': 'Mama 21', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0021@zebra.pl

2026-03-12 18:23:07,963 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:07,964 INFO sqlalchemy.engine.Engine [cached since 6.147s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.147s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

2026-03-12 18:23:07,994 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:07,996 INFO sqlalchemy.engine.Engine [cached since 6.178s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.178s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

2026-03-12 18:23:08,272 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:08,272 INFO sqlalchemy.engine.Engine [cached since 6.026s ago] {'id': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'email': 'test0022@zebra.pl', 'password_hash': '$2b$12$k1566ZOSkLgHdj3Mu0vRrOUjAjBsvHy8l/3Me4yej5.cASaBz8zBq', 'display_name': 'Mama 22', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 6.026s ago] {'id': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'email': 'test0022@zebra.pl', 'password_hash': '$2b$12$k1566ZOSkLgHdj3Mu0vRrOUjAjBsvHy8l/3Me4yej5.cASaBz8zBq', 'display_name': 'Mama 22', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0022@zebra.pl

2026-03-12 18:23:08,302 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:08,304 INFO sqlalchemy.engine.Engine [cached since 6.486s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.486s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

2026-03-12 18:23:08,334 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:08,335 INFO sqlalchemy.engine.Engine [cached since 6.517s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.517s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

2026-03-12 18:23:08,607 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:08,608 INFO sqlalchemy.engine.Engine [cached since 6.362s ago] {'id': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'email': 'test0023@zebra.pl', 'password_hash': '$2b$12$MuNh89k35MdsdFof21NupO1Lh/ulS0WxNstgYqS7g0dg.uEvRZBuq', 'display_name': 'Mama 23', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 6.362s ago] {'id': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'email': 'test0023@zebra.pl', 'password_hash': '$2b$12$MuNh89k35MdsdFof21NupO1Lh/ulS0WxNstgYqS7g0dg.uEvRZBuq', 'display_name': 'Mama 23', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0023@zebra.pl

2026-03-12 18:23:08,639 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:08,640 INFO sqlalchemy.engine.Engine [cached since 6.823s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.823s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

2026-03-12 18:23:08,670 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:08,671 INFO sqlalchemy.engine.Engine [cached since 6.854s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.854s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

2026-03-12 18:23:08,939 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:08,940 INFO sqlalchemy.engine.Engine [cached since 6.693s ago] {'id': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'email': 'test0024@zebra.pl', 'password_hash': '$2b$12$ttm019sOodn4D0tOZ0mGxuMDGL6acX0FLPKMxTyXFC/FB/8uFgfdy', 'display_name': 'Mama 24', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 6.693s ago] {'id': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'email': 'test0024@zebra.pl', 'password_hash': '$2b$12$ttm019sOodn4D0tOZ0mGxuMDGL6acX0FLPKMxTyXFC/FB/8uFgfdy', 'display_name': 'Mama 24', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0024@zebra.pl

2026-03-12 18:23:08,971 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:08,972 INFO sqlalchemy.engine.Engine [cached since 7.154s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.154s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

2026-03-12 18:23:09,002 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:09,003 INFO sqlalchemy.engine.Engine [cached since 7.186s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.186s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

2026-03-12 18:23:09,274 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:09,275 INFO sqlalchemy.engine.Engine [cached since 7.028s ago] {'id': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'email': 'test0025@zebra.pl', 'password_hash': '$2b$12$mpWLmZaMHj9P7s.ErclXKO16DyxTt8iWwo7qb9uFOPWk4SzCVfsxO', 'display_name': 'Mama 25', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 7.028s ago] {'id': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'email': 'test0025@zebra.pl', 'password_hash': '$2b$12$mpWLmZaMHj9P7s.ErclXKO16DyxTt8iWwo7qb9uFOPWk4SzCVfsxO', 'display_name': 'Mama 25', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0025@zebra.pl

2026-03-12 18:23:09,308 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:09,311 INFO sqlalchemy.engine.Engine [cached since 7.493s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.493s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

2026-03-12 18:23:09,344 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:09,345 INFO sqlalchemy.engine.Engine [cached since 7.528s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.528s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

2026-03-12 18:23:09,615 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:09,616 INFO sqlalchemy.engine.Engine [cached since 7.369s ago] {'id': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'email': 'test0026@zebra.pl', 'password_hash': '$2b$12$4GBO5XnjQy0jeQIqwBHxJ.fdDvfVM4Amy7lfYlJ6mZ40A3hewhKre', 'display_name': 'Mama 26', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 7.369s ago] {'id': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'email': 'test0026@zebra.pl', 'password_hash': '$2b$12$4GBO5XnjQy0jeQIqwBHxJ.fdDvfVM4Amy7lfYlJ6mZ40A3hewhKre', 'display_name': 'Mama 26', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0026@zebra.pl

2026-03-12 18:23:09,647 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:09,648 INFO sqlalchemy.engine.Engine [cached since 7.83s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.83s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

2026-03-12 18:23:09,678 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:09,678 INFO sqlalchemy.engine.Engine [cached since 7.861s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.861s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

2026-03-12 18:23:09,960 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:09,961 INFO sqlalchemy.engine.Engine [cached since 7.715s ago] {'id': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'email': 'test0027@zebra.pl', 'password_hash': '$2b$12$qidre5y6iD13N3QrmdYnpOYcmT28Yo0OUZfs0pJkb/d5riPzMWyMu', 'display_name': 'Mama 27', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 7.715s ago] {'id': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'email': 'test0027@zebra.pl', 'password_hash': '$2b$12$qidre5y6iD13N3QrmdYnpOYcmT28Yo0OUZfs0pJkb/d5riPzMWyMu', 'display_name': 'Mama 27', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0027@zebra.pl

2026-03-12 18:23:09,991 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:09,993 INFO sqlalchemy.engine.Engine [cached since 8.175s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.175s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

2026-03-12 18:23:10,022 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:10,024 INFO sqlalchemy.engine.Engine [cached since 8.207s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.207s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

2026-03-12 18:23:10,298 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:10,299 INFO sqlalchemy.engine.Engine [cached since 8.052s ago] {'id': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'email': 'test0028@zebra.pl', 'password_hash': '$2b$12$9VMQBd22LbSuR0uYC1d6meCXCUyEUaCwlOKxJtrOn7qS5mgnsCKdS', 'display_name': 'Mama 28', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 8.052s ago] {'id': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'email': 'test0028@zebra.pl', 'password_hash': '$2b$12$9VMQBd22LbSuR0uYC1d6meCXCUyEUaCwlOKxJtrOn7qS5mgnsCKdS', 'display_name': 'Mama 28', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0028@zebra.pl

2026-03-12 18:23:10,329 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:10,330 INFO sqlalchemy.engine.Engine [cached since 8.512s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.512s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

2026-03-12 18:23:10,358 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:10,359 INFO sqlalchemy.engine.Engine [cached since 8.542s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.542s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

2026-03-12 18:23:10,635 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:10,636 INFO sqlalchemy.engine.Engine [cached since 8.39s ago] {'id': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'email': 'test0029@zebra.pl', 'password_hash': '$2b$12$ooHwa81eEYUz4aJwdOTZeOK1zAwiL0ZDX4uwSpg9V14mj/zsIm7n6', 'display_name': 'Mama 29', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 8.39s ago] {'id': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'email': 'test0029@zebra.pl', 'password_hash': '$2b$12$ooHwa81eEYUz4aJwdOTZeOK1zAwiL0ZDX4uwSpg9V14mj/zsIm7n6', 'display_name': 'Mama 29', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0029@zebra.pl

2026-03-12 18:23:10,667 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:10,668 INFO sqlalchemy.engine.Engine [cached since 8.851s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.851s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

2026-03-12 18:23:10,698 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:10,699 INFO sqlalchemy.engine.Engine [cached since 8.882s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.882s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

2026-03-12 18:23:10,971 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-12 18:23:10,972 INFO sqlalchemy.engine.Engine [cached since 8.725s ago] {'id': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'email': 'test0030@zebra.pl', 'password_hash': '$2b$12$xIqusIwkecfIwjWLGp6fZurDLPrTUTLFkbDmBzNH9WUuDk6fPWc5K', 'display_name': 'Mama 30', 'avatar_url': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 8.725s ago] {'id': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'email': 'test0030@zebra.pl', 'password_hash': '$2b$12$xIqusIwkecfIwjWLGp6fZurDLPrTUTLFkbDmBzNH9WUuDk6fPWc5K', 'display_name': 'Mama 30', 'avatar_url': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0030@zebra.pl

2026-03-12 18:23:11,002 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

Nowo utworzonych użytkowników: 27
Użytkownicy już istniejący:   0

In [10]:
# Utworzenie / aktualizacja profili objawów i dopasowanie do grup

profiles_created = 0
profiles_updated = 0

with get_db() as db:
    for rec in records:
        email = rec["email"]
        user = db.query(User).filter(User.email == email).first()
        if user is None:
            logger.warning("Brak użytkownika %s — pomijam profil objawów", email)
            continue

        existing_profile = (
            db.query(SymptomProfile)
            .filter(SymptomProfile.user_id == user.id)
            .first()
        )

        profile = create_or_update_symptom_profile(db, user, rec["description"])

        if existing_profile is None:
            profiles_created += 1
        else:
            profiles_updated += 1

print(f"Nowo utworzonych profili objawów: {profiles_created}")
print(f"Zaktualizowanych profili objawów: {profiles_updated}")

2026-03-12 18:23:45,785 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-12 18:23:45,787 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:45,788 INFO sqlalchemy.engine.Engine [cached since 43.97s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 43.97s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

2026-03-12 18:23:45,849 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:45,850 INFO sqlalchemy.engine.Engine [generated in 0.00113s] {'user_id_1': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00113s] {'user_id_1': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'param_1': 1}

2026-03-12 18:23:45,885 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:45,886 INFO sqlalchemy.engine.Engine [cached since 0.03733s ago] {'user_id_1': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.03733s ago] {'user_id_1': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'param_1': 1}
INFO:app.services.embedding_service:Ładowanie modelu embeddingów: paraphrase-multilingual-MiniLM-L12-v2
INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cuda:0
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: paraphrase-multilingual-MiniLM-L12-v2
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/modules.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config_sentence_transformers.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config_sentence_transformers.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/README.md "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/modules.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/sentence_bert_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5976.16it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 "HTTP/1.1 200 OK"
INFO:app.services.embedding_service:Model załadowany pomyślnie

2026-03-12 18:23:50,785 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:50,786 INFO sqlalchemy.engine.Engine [generated in 0.00116s] {'embedding': '[-0.01170038,0.08736201,0.00047701,0.05830201,-0.02403772,0.03101498,-0.06217707,0.02666057,0.00986602,-0.01551092,0.08019260,-0.03409501,-0.05637489 ... (4122 characters truncated) ... .00461103,-0.08954022,0.03071420,-0.00750065,-0.00175550,-0.02537874,0.00347901,-0.01184422,0.05438648,0.08173411,-0.03993118,0.08391429,-0.00731025]', 'user_id': '293de121-60ad-482d-ba9b-b47b2608f5e9', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[generated in 0.00116s] {'embedding': '[-0.01170038,0.08736201,0.00047701,0.05830201,-0.02403772,0.03101498,-0.06217707,0.02666057,0.00986602,-0.01551092,0.08019260,-0.03409501,-0.05637489 ... (4122 characters truncated) ... .00461103,-0.08954022,0.03071420,-0.00750065,-0.00175550,-0.02537874,0.00347901,-0.01184422,0.05438648,0.08173411,-0.03993118,0.08391429,-0.00731025]', 'user_id': '293de121-60ad-482d-ba9b-b47b2608f5e9', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6482, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a
INFO:app.services.matching_service:Score 0.6482 < threshold 0.72 — nowa grupa

2026-03-12 18:23:50,845 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:50,846 INFO sqlalchemy.engine.Engine [generated in 0.00084s] {'id': UUID('81673b39-a3a1-4a66-8e03-c6ace83cdf6b'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[generated in 0.00084s] {'id': UUID('81673b39-a3a1-4a66-8e03-c6ace83cdf6b'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 81673b39-a3a1-4a66-8e03-c6ace83cdf6b
INFO:dataset-notebook:Utworzono profil objawów dla test0004@zebra.pl

2026-03-12 18:23:50,881 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:50,882 INFO sqlalchemy.engine.Engine [generated in 0.00122s] {'user_id_1': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'group_id_1': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00122s] {'user_id_1': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'group_id_1': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b', 'param_1': 1}

2026-03-12 18:23:50,915 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:50,916 INFO sqlalchemy.engine.Engine [generated in 0.00134s] {'member_count_1': 1, 'id_1': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b'}

INFO:sqlalchemy.engine.Engine:[generated in 0.00134s] {'member_count_1': 1, 'id_1': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b'}
INFO:app.services.matching_service:Dodano user 293de121-60ad-482d-ba9b-b47b2608f5e9 do grupy 81673b39-a3a1-4a66-8e03-c6ace83cdf6b

2026-03-12 18:23:50,952 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:50,954 INFO sqlalchemy.engine.Engine [generated in 0.00215s] {'user_id': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'group_id': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b'}

INFO:sqlalchemy.engine.Engine:[generated in 0.00215s] {'user_id': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'group_id': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b'}

2026-03-12 18:23:50,986 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:50,987 INFO sqlalchemy.engine.Engine [generated in 0.00188s] {'id': UUID('7c792cec-8508-408a-978d-d90b0a311a11'), 'user_id': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'description': 'Nasze dziecko urodziło się z bardzo niską masą ciała i mimo upływu lat nadal jest dużo mniejsze od rówieśników. Je mało, szybko się męczy i ma trudności z przybieraniem na wadze.', 'embedding': '[-0.011700375936925411,0.08736201375722885,0.0004770079394802451,0.058302007615566254,-0.024037720635533333,0.031014980748295784,-0.06217707321047783 ... (7755 characters truncated) ... ,0.0034790136851370335,-0.011844215914607048,0.054386481642723083,0.08173410594463348,-0.03993118181824684,0.08391429483890533,-0.007310246583074331]', 'group_id': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[generated in 0.00188s] {'id': UUID('7c792cec-8508-408a-978d-d90b0a311a11'), 'user_id': UUID('293de121-60ad-482d-ba9b-b47b2608f5e9'), 'description': 'Nasze dziecko urodziło się z bardzo niską masą ciała i mimo upływu lat nadal jest dużo mniejsze od rówieśników. Je mało, szybko się męczy i ma trudności z przybieraniem na wadze.', 'embedding': '[-0.011700375936925411,0.08736201375722885,0.0004770079394802451,0.058302007615566254,-0.024037720635533333,0.031014980748295784,-0.06217707321047783 ... (7755 characters truncated) ... ,0.0034790136851370335,-0.011844215914607048,0.054386481642723083,0.08173410594463348,-0.03993118181824684,0.08391429483890533,-0.007310246583074331]', 'group_id': '81673b39-a3a1-4a66-8e03-c6ace83cdf6b', 'match_score': 0.0}

2026-03-12 18:23:51,032 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:51,037 INFO sqlalchemy.engine.Engine [cached since 49.22s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 49.22s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

2026-03-12 18:23:51,073 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,077 INFO sqlalchemy.engine.Engine [cached since 5.228s ago] {'user_id_1': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.228s ago] {'user_id_1': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'param_1': 1}

2026-03-12 18:23:51,109 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,110 INFO sqlalchemy.engine.Engine [cached since 5.261s ago] {'user_id_1': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.261s ago] {'user_id_1': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'param_1': 1}

2026-03-12 18:23:51,155 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:51,156 INFO sqlalchemy.engine.Engine [cached since 0.3713s ago] {'embedding': '[-0.03089460,-0.02492462,0.04322285,0.17820163,-0.00587031,0.04237681,0.04210230,-0.03063671,0.02629008,0.00139020,0.08498203,-0.04209322,-0.04514635 ... (4131 characters truncated) ... .00055756,-0.07347213,-0.03782245,-0.11108062,-0.00666794,0.10907601,-0.06276625,-0.00608027,0.00650298,0.04843165,0.02189480,0.05755539,-0.01459977]', 'user_id': '1fd3a075-0194-46fd-8405-fddf0ac325d8', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 0.3713s ago] {'embedding': '[-0.03089460,-0.02492462,0.04322285,0.17820163,-0.00587031,0.04237681,0.04210230,-0.03063671,0.02629008,0.00139020,0.08498203,-0.04209322,-0.04514635 ... (4131 characters truncated) ... .00055756,-0.07347213,-0.03782245,-0.11108062,-0.00666794,0.10907601,-0.06276625,-0.00608027,0.00650298,0.04843165,0.02189480,0.05755539,-0.01459977]', 'user_id': '1fd3a075-0194-46fd-8405-fddf0ac325d8', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5046, group_id=13b24b56-7537-41b2-b484-fa811047b471
INFO:app.services.matching_service:Score 0.5046 < threshold 0.72 — nowa grupa

2026-03-12 18:23:51,192 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:51,193 INFO sqlalchemy.engine.Engine [cached since 0.3483s ago] {'id': UUID('52430a0b-05ed-41fb-8c80-6390c23cd7bd'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 0.3483s ago] {'id': UUID('52430a0b-05ed-41fb-8c80-6390c23cd7bd'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 52430a0b-05ed-41fb-8c80-6390c23cd7bd
INFO:dataset-notebook:Utworzono profil objawów dla test0005@zebra.pl

2026-03-12 18:23:51,226 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,227 INFO sqlalchemy.engine.Engine [cached since 0.3466s ago] {'user_id_1': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'group_id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.3466s ago] {'user_id_1': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'group_id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'param_1': 1}

2026-03-12 18:23:51,256 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:51,258 INFO sqlalchemy.engine.Engine [cached since 0.3431s ago] {'member_count_1': 1, 'id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}

INFO:sqlalchemy.engine.Engine:[cached since 0.3431s ago] {'member_count_1': 1, 'id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}
INFO:app.services.matching_service:Dodano user 1fd3a075-0194-46fd-8405-fddf0ac325d8 do grupy 52430a0b-05ed-41fb-8c80-6390c23cd7bd

2026-03-12 18:23:51,289 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:51,290 INFO sqlalchemy.engine.Engine [cached since 0.3383s ago] {'user_id': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}

INFO:sqlalchemy.engine.Engine:[cached since 0.3383s ago] {'user_id': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}

2026-03-12 18:23:51,320 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:51,322 INFO sqlalchemy.engine.Engine [cached since 0.3362s ago] {'id': UUID('b561476f-d1bd-48bb-aa1c-be135fddf07e'), 'user_id': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'description': 'Od urodzenia zauważyliśmy u córki bardzo jasną skórę i włosy, a oczy są bardzo wrażliwe na światło. Dodatkowo ma problemy ze wzrokiem i często mruży oczy nawet przy zwykłym świetle.', 'embedding': '[-0.030894597992300987,-0.024924617260694504,0.04322285205125809,0.17820163071155548,-0.005870305933058262,0.042376808822155,0.042102303355932236,-0. ... (7787 characters truncated) ... 5,-0.06276625394821167,-0.006080270279198885,0.0065029761753976345,0.048431646078825,0.021894795820116997,0.057555392384529114,-0.014599771238863468]', 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 0.3362s ago] {'id': UUID('b561476f-d1bd-48bb-aa1c-be135fddf07e'), 'user_id': UUID('1fd3a075-0194-46fd-8405-fddf0ac325d8'), 'description': 'Od urodzenia zauważyliśmy u córki bardzo jasną skórę i włosy, a oczy są bardzo wrażliwe na światło. Dodatkowo ma problemy ze wzrokiem i często mruży oczy nawet przy zwykłym świetle.', 'embedding': '[-0.030894597992300987,-0.024924617260694504,0.04322285205125809,0.17820163071155548,-0.005870305933058262,0.042376808822155,0.042102303355932236,-0. ... (7787 characters truncated) ... 5,-0.06276625394821167,-0.006080270279198885,0.0065029761753976345,0.048431646078825,0.021894795820116997,0.057555392384529114,-0.014599771238863468]', 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'match_score': 0.0}

2026-03-12 18:23:51,354 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:51,356 INFO sqlalchemy.engine.Engine [cached since 49.54s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 49.54s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

2026-03-12 18:23:51,388 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,389 INFO sqlalchemy.engine.Engine [cached since 5.54s ago] {'user_id_1': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.54s ago] {'user_id_1': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'param_1': 1}

2026-03-12 18:23:51,418 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,419 INFO sqlalchemy.engine.Engine [cached since 5.57s ago] {'user_id_1': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.57s ago] {'user_id_1': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'param_1': 1}

2026-03-12 18:23:51,461 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:51,462 INFO sqlalchemy.engine.Engine [cached since 0.6774s ago] {'embedding': '[0.01609320,0.01428038,0.04049388,0.06799550,-0.01998046,0.02653297,-0.02103715,-0.01120310,-0.04462305,-0.09683438,0.04222182,-0.00411592,-0.0674272 ... (4120 characters truncated) ... 181,0.01777355,-0.01076199,0.03105320,0.05370527,0.00838884,-0.01879131,0.03357606,0.02116206,0.01904633,0.05660240,0.00272894,0.04683480,0.01403198]', 'user_id': '22a86012-9d57-484f-988d-a57c65faec3d', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 0.6774s ago] {'embedding': '[0.01609320,0.01428038,0.04049388,0.06799550,-0.01998046,0.02653297,-0.02103715,-0.01120310,-0.04462305,-0.09683438,0.04222182,-0.00411592,-0.0674272 ... (4120 characters truncated) ... 181,0.01777355,-0.01076199,0.03105320,0.05370527,0.00838884,-0.01879131,0.03357606,0.02116206,0.01904633,0.05660240,0.00272894,0.04683480,0.01403198]', 'user_id': '22a86012-9d57-484f-988d-a57c65faec3d', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6848, group_id=81673b39-a3a1-4a66-8e03-c6ace83cdf6b
INFO:app.services.matching_service:Score 0.6848 < threshold 0.72 — nowa grupa

2026-03-12 18:23:51,495 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:51,497 INFO sqlalchemy.engine.Engine [cached since 0.6518s ago] {'id': UUID('d08e312f-e27d-4546-ad2b-aee50f883b60'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 0.6518s ago] {'id': UUID('d08e312f-e27d-4546-ad2b-aee50f883b60'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: d08e312f-e27d-4546-ad2b-aee50f883b60
INFO:dataset-notebook:Utworzono profil objawów dla test0006@zebra.pl

2026-03-12 18:23:51,530 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,531 INFO sqlalchemy.engine.Engine [cached since 0.6504s ago] {'user_id_1': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'group_id_1': 'd08e312f-e27d-4546-ad2b-aee50f883b60', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.6504s ago] {'user_id_1': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'group_id_1': 'd08e312f-e27d-4546-ad2b-aee50f883b60', 'param_1': 1}

2026-03-12 18:23:51,561 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:51,563 INFO sqlalchemy.engine.Engine [cached since 0.6479s ago] {'member_count_1': 1, 'id_1': 'd08e312f-e27d-4546-ad2b-aee50f883b60'}

INFO:sqlalchemy.engine.Engine:[cached since 0.6479s ago] {'member_count_1': 1, 'id_1': 'd08e312f-e27d-4546-ad2b-aee50f883b60'}
INFO:app.services.matching_service:Dodano user 22a86012-9d57-484f-988d-a57c65faec3d do grupy d08e312f-e27d-4546-ad2b-aee50f883b60

2026-03-12 18:23:51,593 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:51,594 INFO sqlalchemy.engine.Engine [cached since 0.6422s ago] {'user_id': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'group_id': 'd08e312f-e27d-4546-ad2b-aee50f883b60'}

INFO:sqlalchemy.engine.Engine:[cached since 0.6422s ago] {'user_id': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'group_id': 'd08e312f-e27d-4546-ad2b-aee50f883b60'}

2026-03-12 18:23:51,625 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:51,625 INFO sqlalchemy.engine.Engine [cached since 0.64s ago] {'id': UUID('be4b76e8-a42f-4f5d-b425-561a998953e9'), 'user_id': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'description': 'Syn od pierwszych miesięcy życia miał trudności z jedzeniem. Często się krztusił i długo trwało zanim nauczył się jeść stałe pokarmy. Nadal ma problem z połykaniem i wolno przybiera na wadze.', 'embedding': '[0.01609320007264614,0.01428038440644741,0.04049387946724892,0.06799550354480743,-0.019980458542704582,0.026532970368862152,-0.021037153899669647,-0. ... (7754 characters truncated) ... 55,0.03357606381177902,0.021162061020731926,0.019046325236558914,0.05660239979624748,0.0027289357967674732,0.046834804117679596,0.014031980186700821]', 'group_id': 'd08e312f-e27d-4546-ad2b-aee50f883b60', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 0.64s ago] {'id': UUID('be4b76e8-a42f-4f5d-b425-561a998953e9'), 'user_id': UUID('22a86012-9d57-484f-988d-a57c65faec3d'), 'description': 'Syn od pierwszych miesięcy życia miał trudności z jedzeniem. Często się krztusił i długo trwało zanim nauczył się jeść stałe pokarmy. Nadal ma problem z połykaniem i wolno przybiera na wadze.', 'embedding': '[0.01609320007264614,0.01428038440644741,0.04049387946724892,0.06799550354480743,-0.019980458542704582,0.026532970368862152,-0.021037153899669647,-0. ... (7754 characters truncated) ... 55,0.03357606381177902,0.021162061020731926,0.019046325236558914,0.05660239979624748,0.0027289357967674732,0.046834804117679596,0.014031980186700821]', 'group_id': 'd08e312f-e27d-4546-ad2b-aee50f883b60', 'match_score': 0.0}

2026-03-12 18:23:51,657 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:51,658 INFO sqlalchemy.engine.Engine [cached since 49.84s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 49.84s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

2026-03-12 18:23:51,689 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,690 INFO sqlalchemy.engine.Engine [cached since 5.841s ago] {'user_id_1': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.841s ago] {'user_id_1': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'param_1': 1}

2026-03-12 18:23:51,721 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,722 INFO sqlalchemy.engine.Engine [cached since 5.873s ago] {'user_id_1': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.873s ago] {'user_id_1': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'param_1': 1}

2026-03-12 18:23:51,766 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:51,768 INFO sqlalchemy.engine.Engine [cached since 0.9827s ago] {'embedding': '[0.05154181,0.00020816,0.08085735,0.00310334,-0.08716795,-0.02166121,0.01074693,-0.01581975,0.03634820,-0.00687062,0.07993109,0.04965154,-0.03255358, ... (4106 characters truncated) ... ,-0.00189141,-0.05961429,0.05986775,0.05866943,-0.00203133,0.07717548,-0.00506058,0.00996690,0.07968204,0.02879803,0.15309143,0.06576195,-0.00901362]', 'user_id': '694bed2f-c501-44e0-88e8-fbcd19e3fc08', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 0.9827s ago] {'embedding': '[0.05154181,0.00020816,0.08085735,0.00310334,-0.08716795,-0.02166121,0.01074693,-0.01581975,0.03634820,-0.00687062,0.07993109,0.04965154,-0.03255358, ... (4106 characters truncated) ... ,-0.00189141,-0.05961429,0.05986775,0.05866943,-0.00203133,0.07717548,-0.00506058,0.00996690,0.07968204,0.02879803,0.15309143,0.06576195,-0.00901362]', 'user_id': '694bed2f-c501-44e0-88e8-fbcd19e3fc08', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7676, group_id=66204af3-89e7-4ec6-838e-0fcd7e54e4c7

2026-03-12 18:23:51,799 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,801 INFO sqlalchemy.engine.Engine [generated in 0.00132s] {'id_1': UUID('66204af3-89e7-4ec6-838e-0fcd7e54e4c7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00132s] {'id_1': UUID('66204af3-89e7-4ec6-838e-0fcd7e54e4c7'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7676)
INFO:dataset-notebook:Utworzono profil objawów dla test0007@zebra.pl

2026-03-12 18:23:51,830 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,832 INFO sqlalchemy.engine.Engine [cached since 0.9511s ago] {'user_id_1': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'group_id_1': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.9511s ago] {'user_id_1': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'group_id_1': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7', 'param_1': 1}

2026-03-12 18:23:51,862 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:51,864 INFO sqlalchemy.engine.Engine [cached since 0.9494s ago] {'member_count_1': 1, 'id_1': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7'}

INFO:sqlalchemy.engine.Engine:[cached since 0.9494s ago] {'member_count_1': 1, 'id_1': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7'}
INFO:app.services.matching_service:Dodano user 694bed2f-c501-44e0-88e8-fbcd19e3fc08 do grupy 66204af3-89e7-4ec6-838e-0fcd7e54e4c7

2026-03-12 18:23:51,894 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:51,896 INFO sqlalchemy.engine.Engine [cached since 0.9437s ago] {'user_id': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'group_id': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7'}

INFO:sqlalchemy.engine.Engine:[cached since 0.9437s ago] {'user_id': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'group_id': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7'}

2026-03-12 18:23:51,925 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:51,926 INFO sqlalchemy.engine.Engine [cached since 0.94s ago] {'id': UUID('87a08a07-0c03-4a70-9ab5-17a768e4f6f2'), 'user_id': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'description': 'Nasze dziecko od małego bardzo mało mówiło. Teraz ma kilka lat i nadal używa głównie gestów. Rozumie dużo, ale nie potrafi wyrazić tego słowami.', 'embedding': '[0.051541805267333984,0.00020815643074456602,0.08085735142230988,0.0031033395789563656,-0.08716794848442078,-0.021661214530467987,0.01074693072587251 ... (7730 characters truncated) ... 6683,-0.005060578230768442,0.009966898709535599,0.07968204468488693,0.02879803441464901,0.1530914306640625,0.06576195359230042,-0.009013617411255836]', 'group_id': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7', 'match_score': 0.767552742441247}

INFO:sqlalchemy.engine.Engine:[cached since 0.94s ago] {'id': UUID('87a08a07-0c03-4a70-9ab5-17a768e4f6f2'), 'user_id': UUID('694bed2f-c501-44e0-88e8-fbcd19e3fc08'), 'description': 'Nasze dziecko od małego bardzo mało mówiło. Teraz ma kilka lat i nadal używa głównie gestów. Rozumie dużo, ale nie potrafi wyrazić tego słowami.', 'embedding': '[0.051541805267333984,0.00020815643074456602,0.08085735142230988,0.0031033395789563656,-0.08716794848442078,-0.021661214530467987,0.01074693072587251 ... (7730 characters truncated) ... 6683,-0.005060578230768442,0.009966898709535599,0.07968204468488693,0.02879803441464901,0.1530914306640625,0.06576195359230042,-0.009013617411255836]', 'group_id': '66204af3-89e7-4ec6-838e-0fcd7e54e4c7', 'match_score': 0.767552742441247}

2026-03-12 18:23:51,958 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:51,959 INFO sqlalchemy.engine.Engine [cached since 50.14s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 50.14s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

2026-03-12 18:23:51,990 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:51,991 INFO sqlalchemy.engine.Engine [cached since 6.142s ago] {'user_id_1': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.142s ago] {'user_id_1': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'param_1': 1}

2026-03-12 18:23:52,021 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,022 INFO sqlalchemy.engine.Engine [cached since 6.173s ago] {'user_id_1': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.173s ago] {'user_id_1': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'param_1': 1}

2026-03-12 18:23:52,063 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:52,065 INFO sqlalchemy.engine.Engine [cached since 1.28s ago] {'embedding': '[-0.01861245,-0.02305471,0.02720429,0.11545839,0.03426404,0.03037733,-0.05075784,0.00952559,0.04303708,-0.00838239,0.05299957,0.07997695,-0.05517856, ... (4126 characters truncated) ... 0.02343685,-0.05070234,-0.01156512,0.03653574,0.03168761,-0.05119545,-0.03467692,-0.05764566,0.05846259,-0.00855322,0.03623850,0.06568573,0.03633332]', 'user_id': '6c20df67-2f7c-4b7a-a1ed-cf643cea1495', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 1.28s ago] {'embedding': '[-0.01861245,-0.02305471,0.02720429,0.11545839,0.03426404,0.03037733,-0.05075784,0.00952559,0.04303708,-0.00838239,0.05299957,0.07997695,-0.05517856, ... (4126 characters truncated) ... 0.02343685,-0.05070234,-0.01156512,0.03653574,0.03168761,-0.05119545,-0.03467692,-0.05764566,0.05846259,-0.00855322,0.03623850,0.06568573,0.03633332]', 'user_id': '6c20df67-2f7c-4b7a-a1ed-cf643cea1495', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8050, group_id=cb092a24-2831-48f5-b35f-7add54e19d6b

2026-03-12 18:23:52,095 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,096 INFO sqlalchemy.engine.Engine [cached since 0.2971s ago] {'id_1': UUID('cb092a24-2831-48f5-b35f-7add54e19d6b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.2971s ago] {'id_1': UUID('cb092a24-2831-48f5-b35f-7add54e19d6b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.8050)
INFO:dataset-notebook:Utworzono profil objawów dla test0008@zebra.pl

2026-03-12 18:23:52,127 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,129 INFO sqlalchemy.engine.Engine [cached since 1.248s ago] {'user_id_1': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'group_id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.248s ago] {'user_id_1': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'group_id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'param_1': 1}

2026-03-12 18:23:52,158 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:52,159 INFO sqlalchemy.engine.Engine [cached since 1.245s ago] {'member_count_1': 1, 'id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

INFO:sqlalchemy.engine.Engine:[cached since 1.245s ago] {'member_count_1': 1, 'id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}
INFO:app.services.matching_service:Dodano user 6c20df67-2f7c-4b7a-a1ed-cf643cea1495 do grupy cb092a24-2831-48f5-b35f-7add54e19d6b

2026-03-12 18:23:52,191 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:52,196 INFO sqlalchemy.engine.Engine [cached since 1.244s ago] {'user_id': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

INFO:sqlalchemy.engine.Engine:[cached since 1.244s ago] {'user_id': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

2026-03-12 18:23:52,227 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:52,230 INFO sqlalchemy.engine.Engine [cached since 1.245s ago] {'id': UUID('1fc5e285-2ace-4b86-bfe5-3d120d953433'), 'user_id': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'description': 'Córka od niemowlęctwa miała częste napady drgawek. Oprócz tego rozwój ruchowy jest opóźniony. Nadal ma trudności z chodzeniem i utrzymaniem równowagi.', 'embedding': '[-0.0186124499887228,-0.023054705932736397,0.02720428816974163,0.11545839160680771,0.03426403924822807,0.030377332121133804,-0.050757840275764465,0.0 ... (7742 characters truncated) ... 85,-0.0346769243478775,-0.057645656168460846,0.058462586253881454,-0.00855321902781725,0.036238495260477066,0.06568573415279388,0.036333318799734116]', 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'match_score': 0.805049192604472}

INFO:sqlalchemy.engine.Engine:[cached since 1.245s ago] {'id': UUID('1fc5e285-2ace-4b86-bfe5-3d120d953433'), 'user_id': UUID('6c20df67-2f7c-4b7a-a1ed-cf643cea1495'), 'description': 'Córka od niemowlęctwa miała częste napady drgawek. Oprócz tego rozwój ruchowy jest opóźniony. Nadal ma trudności z chodzeniem i utrzymaniem równowagi.', 'embedding': '[-0.0186124499887228,-0.023054705932736397,0.02720428816974163,0.11545839160680771,0.03426403924822807,0.030377332121133804,-0.050757840275764465,0.0 ... (7742 characters truncated) ... 85,-0.0346769243478775,-0.057645656168460846,0.058462586253881454,-0.00855321902781725,0.036238495260477066,0.06568573415279388,0.036333318799734116]', 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'match_score': 0.805049192604472}

2026-03-12 18:23:52,264 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:52,266 INFO sqlalchemy.engine.Engine [cached since 50.45s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 50.45s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

2026-03-12 18:23:52,297 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,299 INFO sqlalchemy.engine.Engine [cached since 6.45s ago] {'user_id_1': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.45s ago] {'user_id_1': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'param_1': 1}

2026-03-12 18:23:52,329 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,333 INFO sqlalchemy.engine.Engine [cached since 6.484s ago] {'user_id_1': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.484s ago] {'user_id_1': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'param_1': 1}

2026-03-12 18:23:52,373 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:52,374 INFO sqlalchemy.engine.Engine [cached since 1.589s ago] {'embedding': '[0.03400708,0.07946135,0.01549847,0.07987374,-0.00844862,0.02102082,-0.03513885,0.04925292,0.04253215,-0.00983174,0.11092716,-0.03863214,-0.02745391, ... (4123 characters truncated) ... 0,0.05431163,-0.05646854,-0.01383348,0.02728386,0.04386005,0.00226450,0.02402486,-0.01481984,0.03386899,0.03064375,0.07007224,0.06827873,-0.01327370]', 'user_id': 'b86c1e73-6573-4fe1-ba0d-4baed8e2aa94', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 1.589s ago] {'embedding': '[0.03400708,0.07946135,0.01549847,0.07987374,-0.00844862,0.02102082,-0.03513885,0.04925292,0.04253215,-0.00983174,0.11092716,-0.03863214,-0.02745391, ... (4123 characters truncated) ... 0,0.05431163,-0.05646854,-0.01383348,0.02728386,0.04386005,0.00226450,0.02402486,-0.01481984,0.03386899,0.03064375,0.07007224,0.06827873,-0.01327370]', 'user_id': 'b86c1e73-6573-4fe1-ba0d-4baed8e2aa94', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7315, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:52,409 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,414 INFO sqlalchemy.engine.Engine [cached since 0.6152s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.6152s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7315)
INFO:dataset-notebook:Utworzono profil objawów dla test0009@zebra.pl

2026-03-12 18:23:52,451 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,452 INFO sqlalchemy.engine.Engine [cached since 1.571s ago] {'user_id_1': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.571s ago] {'user_id_1': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:52,483 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:52,484 INFO sqlalchemy.engine.Engine [cached since 1.569s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 1.569s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user b86c1e73-6573-4fe1-ba0d-4baed8e2aa94 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:52,515 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:52,516 INFO sqlalchemy.engine.Engine [cached since 1.563s ago] {'user_id': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 1.563s ago] {'user_id': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:52,546 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:52,548 INFO sqlalchemy.engine.Engine [cached since 1.562s ago] {'id': UUID('cc5ec702-08c0-4965-b7c9-2b7a52aa163f'), 'user_id': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'description': 'Syn urodził się z bardzo małą głową w stosunku do reszty ciała. W miarę dorastania zaczęliśmy zauważać też trudności w nauce i koncentracji.', 'embedding': '[0.034007079899311066,0.07946135103702545,0.015498465858399868,0.07987374067306519,-0.00844862125813961,0.02102082036435604,-0.03513885289430618,0.04 ... (7733 characters truncated) ... 16342,0.024024859070777893,-0.014819837175309658,0.03386898711323738,0.030643753707408905,0.070072241127491,0.0682787299156189,-0.013273704797029495]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.731467263015087}

INFO:sqlalchemy.engine.Engine:[cached since 1.562s ago] {'id': UUID('cc5ec702-08c0-4965-b7c9-2b7a52aa163f'), 'user_id': UUID('b86c1e73-6573-4fe1-ba0d-4baed8e2aa94'), 'description': 'Syn urodził się z bardzo małą głową w stosunku do reszty ciała. W miarę dorastania zaczęliśmy zauważać też trudności w nauce i koncentracji.', 'embedding': '[0.034007079899311066,0.07946135103702545,0.015498465858399868,0.07987374067306519,-0.00844862125813961,0.02102082036435604,-0.03513885289430618,0.04 ... (7733 characters truncated) ... 16342,0.024024859070777893,-0.014819837175309658,0.03386898711323738,0.030643753707408905,0.070072241127491,0.0682787299156189,-0.013273704797029495]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.731467263015087}

2026-03-12 18:23:52,578 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:52,579 INFO sqlalchemy.engine.Engine [cached since 50.76s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 50.76s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

2026-03-12 18:23:52,610 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,611 INFO sqlalchemy.engine.Engine [cached since 6.763s ago] {'user_id_1': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.763s ago] {'user_id_1': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'param_1': 1}

2026-03-12 18:23:52,641 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,642 INFO sqlalchemy.engine.Engine [cached since 6.793s ago] {'user_id_1': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.793s ago] {'user_id_1': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'param_1': 1}

2026-03-12 18:23:52,683 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:52,684 INFO sqlalchemy.engine.Engine [cached since 1.899s ago] {'embedding': '[-0.02853801,-0.05344074,0.08271848,0.06142166,-0.00604627,-0.04511746,-0.01848768,0.03423043,0.00890277,0.00475002,0.00939462,0.15349920,-0.06569830 ... (4119 characters truncated) ... 0.01787806,-0.05055827,-0.03879230,-0.02825746,0.01900731,-0.01649765,-0.03481507,-0.03758900,0.03226066,0.01176796,0.04888741,0.00975866,0.05785647]', 'user_id': 'cf7e143c-2587-48d7-a170-9e701275cb30', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 1.899s ago] {'embedding': '[-0.02853801,-0.05344074,0.08271848,0.06142166,-0.00604627,-0.04511746,-0.01848768,0.03423043,0.00890277,0.00475002,0.00939462,0.15349920,-0.06569830 ... (4119 characters truncated) ... 0.01787806,-0.05055827,-0.03879230,-0.02825746,0.01900731,-0.01649765,-0.03481507,-0.03758900,0.03226066,0.01176796,0.04888741,0.00975866,0.05785647]', 'user_id': 'cf7e143c-2587-48d7-a170-9e701275cb30', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6980, group_id=cb092a24-2831-48f5-b35f-7add54e19d6b
INFO:app.services.matching_service:Score 0.6980 < threshold 0.72 — nowa grupa

2026-03-12 18:23:52,718 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:52,720 INFO sqlalchemy.engine.Engine [cached since 1.875s ago] {'id': UUID('55c850c8-071d-4f86-a619-16e010387f42'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 1.875s ago] {'id': UUID('55c850c8-071d-4f86-a619-16e010387f42'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 55c850c8-071d-4f86-a619-16e010387f42
INFO:dataset-notebook:Utworzono profil objawów dla test0010@zebra.pl

2026-03-12 18:23:52,750 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,751 INFO sqlalchemy.engine.Engine [cached since 1.871s ago] {'user_id_1': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'group_id_1': '55c850c8-071d-4f86-a619-16e010387f42', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.871s ago] {'user_id_1': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'group_id_1': '55c850c8-071d-4f86-a619-16e010387f42', 'param_1': 1}

2026-03-12 18:23:52,781 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:52,782 INFO sqlalchemy.engine.Engine [cached since 1.867s ago] {'member_count_1': 1, 'id_1': '55c850c8-071d-4f86-a619-16e010387f42'}

INFO:sqlalchemy.engine.Engine:[cached since 1.867s ago] {'member_count_1': 1, 'id_1': '55c850c8-071d-4f86-a619-16e010387f42'}
INFO:app.services.matching_service:Dodano user cf7e143c-2587-48d7-a170-9e701275cb30 do grupy 55c850c8-071d-4f86-a619-16e010387f42

2026-03-12 18:23:52,814 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:52,815 INFO sqlalchemy.engine.Engine [cached since 1.863s ago] {'user_id': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'group_id': '55c850c8-071d-4f86-a619-16e010387f42'}

INFO:sqlalchemy.engine.Engine:[cached since 1.863s ago] {'user_id': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'group_id': '55c850c8-071d-4f86-a619-16e010387f42'}

2026-03-12 18:23:52,845 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:52,846 INFO sqlalchemy.engine.Engine [cached since 1.86s ago] {'id': UUID('7facadd5-ca27-471c-b0a7-92292cdbb8ee'), 'user_id': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'description': 'Nasza córka ma bardzo elastyczne stawy. Może wyginać ręce i palce w nienaturalny sposób. Często skarży się też na bóle stawów po dłuższym chodzeniu.', 'embedding': '[-0.028538011014461517,-0.05344073846936226,0.08271848410367966,0.061421655118465424,-0.00604627188295126,-0.04511745646595955,-0.018487678840756416, ... (7720 characters truncated) ... 9554,-0.034815073013305664,-0.03758900240063667,0.03226066008210182,0.011767962947487831,0.04888741299510002,0.0097586615011096,0.057856470346450806]', 'group_id': '55c850c8-071d-4f86-a619-16e010387f42', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 1.86s ago] {'id': UUID('7facadd5-ca27-471c-b0a7-92292cdbb8ee'), 'user_id': UUID('cf7e143c-2587-48d7-a170-9e701275cb30'), 'description': 'Nasza córka ma bardzo elastyczne stawy. Może wyginać ręce i palce w nienaturalny sposób. Często skarży się też na bóle stawów po dłuższym chodzeniu.', 'embedding': '[-0.028538011014461517,-0.05344073846936226,0.08271848410367966,0.061421655118465424,-0.00604627188295126,-0.04511745646595955,-0.018487678840756416, ... (7720 characters truncated) ... 9554,-0.034815073013305664,-0.03758900240063667,0.03226066008210182,0.011767962947487831,0.04888741299510002,0.0097586615011096,0.057856470346450806]', 'group_id': '55c850c8-071d-4f86-a619-16e010387f42', 'match_score': 0.0}

2026-03-12 18:23:52,877 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:52,878 INFO sqlalchemy.engine.Engine [cached since 51.06s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 51.06s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

2026-03-12 18:23:52,909 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,910 INFO sqlalchemy.engine.Engine [cached since 7.062s ago] {'user_id_1': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.062s ago] {'user_id_1': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'param_1': 1}

2026-03-12 18:23:52,941 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:52,942 INFO sqlalchemy.engine.Engine [cached since 7.093s ago] {'user_id_1': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.093s ago] {'user_id_1': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'param_1': 1}

2026-03-12 18:23:52,983 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:52,984 INFO sqlalchemy.engine.Engine [cached since 2.199s ago] {'embedding': '[-0.00113006,0.02758824,0.03500392,0.03201396,-0.00952318,0.04841946,-0.05751581,-0.01003307,-0.00634425,-0.04225761,0.11307989,0.08122981,-0.0293003 ... (4115 characters truncated) ... 0.05300842,-0.03095406,-0.03886995,0.05529933,-0.01415248,-0.13148145,0.02509262,-0.06897712,-0.00956264,0.03620234,0.06094301,0.01339537,0.03822947]', 'user_id': 'cab0e66c-0e6a-4ec5-bd2c-10499340f453', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 2.199s ago] {'embedding': '[-0.00113006,0.02758824,0.03500392,0.03201396,-0.00952318,0.04841946,-0.05751581,-0.01003307,-0.00634425,-0.04225761,0.11307989,0.08122981,-0.0293003 ... (4115 characters truncated) ... 0.05300842,-0.03095406,-0.03886995,0.05529933,-0.01415248,-0.13148145,0.02509262,-0.06897712,-0.00956264,0.03620234,0.06094301,0.01339537,0.03822947]', 'user_id': 'cab0e66c-0e6a-4ec5-bd2c-10499340f453', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7882, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:53,014 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,016 INFO sqlalchemy.engine.Engine [cached since 1.216s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.216s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7882)
INFO:dataset-notebook:Utworzono profil objawów dla test0011@zebra.pl

2026-03-12 18:23:53,047 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,048 INFO sqlalchemy.engine.Engine [cached since 2.168s ago] {'user_id_1': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.168s ago] {'user_id_1': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:53,079 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:53,080 INFO sqlalchemy.engine.Engine [cached since 2.165s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 2.165s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user cab0e66c-0e6a-4ec5-bd2c-10499340f453 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:53,110 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:53,111 INFO sqlalchemy.engine.Engine [cached since 2.159s ago] {'user_id': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 2.159s ago] {'user_id': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:53,142 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:53,143 INFO sqlalchemy.engine.Engine [cached since 2.157s ago] {'id': UUID('61a28917-76cf-481b-8899-21a9f845a5db'), 'user_id': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'description': 'Syn od małego miał problemy z napięciem mięśniowym. Był bardzo sztywny, a później pojawiły się trudności z chodzeniem. Teraz jego ruchy są powolne i niezgrabne.', 'embedding': '[-0.0011300613405182958,0.027588242664933205,0.035003919154405594,0.03201396390795708,-0.009523184970021248,0.04841945692896843,-0.057515814900398254 ... (7736 characters truncated) ... 956,0.02509262226521969,-0.06897711753845215,-0.009562642313539982,0.036202337592840195,0.060943011194467545,0.01339537464082241,0.03822946920990944]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.788225650787359}

INFO:sqlalchemy.engine.Engine:[cached since 2.157s ago] {'id': UUID('61a28917-76cf-481b-8899-21a9f845a5db'), 'user_id': UUID('cab0e66c-0e6a-4ec5-bd2c-10499340f453'), 'description': 'Syn od małego miał problemy z napięciem mięśniowym. Był bardzo sztywny, a później pojawiły się trudności z chodzeniem. Teraz jego ruchy są powolne i niezgrabne.', 'embedding': '[-0.0011300613405182958,0.027588242664933205,0.035003919154405594,0.03201396390795708,-0.009523184970021248,0.04841945692896843,-0.057515814900398254 ... (7736 characters truncated) ... 956,0.02509262226521969,-0.06897711753845215,-0.009562642313539982,0.036202337592840195,0.060943011194467545,0.01339537464082241,0.03822946920990944]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.788225650787359}

2026-03-12 18:23:53,174 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:53,175 INFO sqlalchemy.engine.Engine [cached since 51.36s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 51.36s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

2026-03-12 18:23:53,204 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,205 INFO sqlalchemy.engine.Engine [cached since 7.356s ago] {'user_id_1': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.356s ago] {'user_id_1': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'param_1': 1}

2026-03-12 18:23:53,234 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,234 INFO sqlalchemy.engine.Engine [cached since 7.386s ago] {'user_id_1': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.386s ago] {'user_id_1': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'param_1': 1}

2026-03-12 18:23:53,276 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:53,277 INFO sqlalchemy.engine.Engine [cached since 2.492s ago] {'embedding': '[0.02631584,0.02412429,0.03351023,0.03258931,-0.09127256,0.01889204,-0.04003087,0.03156363,-0.00876825,-0.03922767,0.09239659,0.11695259,-0.02509193, ... (4114 characters truncated) ... ,0.04220047,-0.08355015,0.01488694,0.06514746,-0.02138217,0.00575160,0.04542048,-0.09511195,0.03497684,-0.01393508,0.10082942,0.05903621,-0.01486600]', 'user_id': '0a4e7f35-35f4-4d0d-901e-c42e0aea4578', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 2.492s ago] {'embedding': '[0.02631584,0.02412429,0.03351023,0.03258931,-0.09127256,0.01889204,-0.04003087,0.03156363,-0.00876825,-0.03922767,0.09239659,0.11695259,-0.02509193, ... (4114 characters truncated) ... ,0.04220047,-0.08355015,0.01488694,0.06514746,-0.02138217,0.00575160,0.04542048,-0.09511195,0.03497684,-0.01393508,0.10082942,0.05903621,-0.01486600]', 'user_id': '0a4e7f35-35f4-4d0d-901e-c42e0aea4578', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7134, group_id=66204af3-89e7-4ec6-838e-0fcd7e54e4c7
INFO:app.services.matching_service:Score 0.7134 < threshold 0.72 — nowa grupa

2026-03-12 18:23:53,309 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:53,310 INFO sqlalchemy.engine.Engine [cached since 2.465s ago] {'id': UUID('708a6370-ea74-4374-a698-5adad01af45a'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 2.465s ago] {'id': UUID('708a6370-ea74-4374-a698-5adad01af45a'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 708a6370-ea74-4374-a698-5adad01af45a
INFO:dataset-notebook:Utworzono profil objawów dla test0012@zebra.pl

2026-03-12 18:23:53,340 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,341 INFO sqlalchemy.engine.Engine [cached since 2.46s ago] {'user_id_1': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'group_id_1': '708a6370-ea74-4374-a698-5adad01af45a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.46s ago] {'user_id_1': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'group_id_1': '708a6370-ea74-4374-a698-5adad01af45a', 'param_1': 1}

2026-03-12 18:23:53,371 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:53,372 INFO sqlalchemy.engine.Engine [cached since 2.457s ago] {'member_count_1': 1, 'id_1': '708a6370-ea74-4374-a698-5adad01af45a'}

INFO:sqlalchemy.engine.Engine:[cached since 2.457s ago] {'member_count_1': 1, 'id_1': '708a6370-ea74-4374-a698-5adad01af45a'}
INFO:app.services.matching_service:Dodano user 0a4e7f35-35f4-4d0d-901e-c42e0aea4578 do grupy 708a6370-ea74-4374-a698-5adad01af45a

2026-03-12 18:23:53,403 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:53,403 INFO sqlalchemy.engine.Engine [cached since 2.451s ago] {'user_id': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'group_id': '708a6370-ea74-4374-a698-5adad01af45a'}

INFO:sqlalchemy.engine.Engine:[cached since 2.451s ago] {'user_id': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'group_id': '708a6370-ea74-4374-a698-5adad01af45a'}

2026-03-12 18:23:53,434 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:53,435 INFO sqlalchemy.engine.Engine [cached since 2.45s ago] {'id': UUID('37528c7b-2e81-44f7-8755-80e3a89b662f'), 'user_id': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'description': 'Nasze dziecko rozwijało się prawidłowo do około drugiego roku życia, a potem zaczęło tracić niektóre umiejętności. Przestało mówić kilka słów, które wcześniej używało.', 'embedding': '[0.026315838098526,0.02412429079413414,0.0335102304816246,0.03258930891752243,-0.09127256274223328,0.018892044201493263,-0.04003087431192398,0.031563 ... (7735 characters truncated) ... 46,0.04542047530412674,-0.09511195123195648,0.034976836293935776,-0.013935078866779804,0.10082941502332687,0.05903621390461922,-0.014866004697978497]', 'group_id': '708a6370-ea74-4374-a698-5adad01af45a', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 2.45s ago] {'id': UUID('37528c7b-2e81-44f7-8755-80e3a89b662f'), 'user_id': UUID('0a4e7f35-35f4-4d0d-901e-c42e0aea4578'), 'description': 'Nasze dziecko rozwijało się prawidłowo do około drugiego roku życia, a potem zaczęło tracić niektóre umiejętności. Przestało mówić kilka słów, które wcześniej używało.', 'embedding': '[0.026315838098526,0.02412429079413414,0.0335102304816246,0.03258930891752243,-0.09127256274223328,0.018892044201493263,-0.04003087431192398,0.031563 ... (7735 characters truncated) ... 46,0.04542047530412674,-0.09511195123195648,0.034976836293935776,-0.013935078866779804,0.10082941502332687,0.05903621390461922,-0.014866004697978497]', 'group_id': '708a6370-ea74-4374-a698-5adad01af45a', 'match_score': 0.0}

2026-03-12 18:23:53,468 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:53,469 INFO sqlalchemy.engine.Engine [cached since 51.65s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 51.65s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

2026-03-12 18:23:53,498 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,499 INFO sqlalchemy.engine.Engine [cached since 7.65s ago] {'user_id_1': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.65s ago] {'user_id_1': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'param_1': 1}

2026-03-12 18:23:53,530 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,531 INFO sqlalchemy.engine.Engine [cached since 7.682s ago] {'user_id_1': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.682s ago] {'user_id_1': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'param_1': 1}

2026-03-12 18:23:53,573 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:53,574 INFO sqlalchemy.engine.Engine [cached since 2.789s ago] {'embedding': '[0.05182690,0.01194671,-0.01251733,0.02988250,-0.04598739,0.01701355,-0.05570947,-0.04121823,0.06017403,-0.01617073,0.02947735,0.05836197,-0.02402732 ... (4121 characters truncated) ... ,-0.01746114,-0.03948716,-0.01968628,0.02809809,0.05406713,0.02635900,0.03515280,-0.04663209,0.10088474,-0.02399559,0.07112296,0.04828358,0.00512848]', 'user_id': 'bdcfbc3f-df5b-4c93-9e37-d34b8322f90e', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 2.789s ago] {'embedding': '[0.05182690,0.01194671,-0.01251733,0.02988250,-0.04598739,0.01701355,-0.05570947,-0.04121823,0.06017403,-0.01617073,0.02947735,0.05836197,-0.02402732 ... (4121 characters truncated) ... ,-0.01746114,-0.03948716,-0.01968628,0.02809809,0.05406713,0.02635900,0.03515280,-0.04663209,0.10088474,-0.02399559,0.07112296,0.04828358,0.00512848]', 'user_id': 'bdcfbc3f-df5b-4c93-9e37-d34b8322f90e', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5550, group_id=13b24b56-7537-41b2-b484-fa811047b471
INFO:app.services.matching_service:Score 0.5550 < threshold 0.72 — nowa grupa

2026-03-12 18:23:53,604 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:53,605 INFO sqlalchemy.engine.Engine [cached since 2.76s ago] {'id': UUID('75f17305-fcd8-4ee6-a2bf-d80329866d08'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 2.76s ago] {'id': UUID('75f17305-fcd8-4ee6-a2bf-d80329866d08'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 75f17305-fcd8-4ee6-a2bf-d80329866d08
INFO:dataset-notebook:Utworzono profil objawów dla test0013@zebra.pl

2026-03-12 18:23:53,635 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,636 INFO sqlalchemy.engine.Engine [cached since 2.756s ago] {'user_id_1': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'group_id_1': '75f17305-fcd8-4ee6-a2bf-d80329866d08', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.756s ago] {'user_id_1': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'group_id_1': '75f17305-fcd8-4ee6-a2bf-d80329866d08', 'param_1': 1}

2026-03-12 18:23:53,665 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:53,666 INFO sqlalchemy.engine.Engine [cached since 2.752s ago] {'member_count_1': 1, 'id_1': '75f17305-fcd8-4ee6-a2bf-d80329866d08'}

INFO:sqlalchemy.engine.Engine:[cached since 2.752s ago] {'member_count_1': 1, 'id_1': '75f17305-fcd8-4ee6-a2bf-d80329866d08'}
INFO:app.services.matching_service:Dodano user bdcfbc3f-df5b-4c93-9e37-d34b8322f90e do grupy 75f17305-fcd8-4ee6-a2bf-d80329866d08

2026-03-12 18:23:53,698 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:53,699 INFO sqlalchemy.engine.Engine [cached since 2.747s ago] {'user_id': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'group_id': '75f17305-fcd8-4ee6-a2bf-d80329866d08'}

INFO:sqlalchemy.engine.Engine:[cached since 2.747s ago] {'user_id': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'group_id': '75f17305-fcd8-4ee6-a2bf-d80329866d08'}

2026-03-12 18:23:53,729 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:53,730 INFO sqlalchemy.engine.Engine [cached since 2.745s ago] {'id': UUID('b0718f79-9a91-4adc-85f1-229e627d2b8b'), 'user_id': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'description': 'Córka od urodzenia ma problemy ze słuchem. Musimy mówić bardzo głośno, żeby reagowała. Dodatkowo rozwój mowy jest opóźniony.', 'embedding': '[0.051826901733875275,0.01194671168923378,-0.012517333962023258,0.02988249808549881,-0.045987386256456375,0.01701355166733265,-0.055709466338157654,- ... (7749 characters truncated) ... 21428,0.03515280410647392,-0.04663209244608879,0.10088474303483963,-0.02399558760225773,0.07112295925617218,0.04828358069062233,0.005128476768732071]', 'group_id': '75f17305-fcd8-4ee6-a2bf-d80329866d08', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 2.745s ago] {'id': UUID('b0718f79-9a91-4adc-85f1-229e627d2b8b'), 'user_id': UUID('bdcfbc3f-df5b-4c93-9e37-d34b8322f90e'), 'description': 'Córka od urodzenia ma problemy ze słuchem. Musimy mówić bardzo głośno, żeby reagowała. Dodatkowo rozwój mowy jest opóźniony.', 'embedding': '[0.051826901733875275,0.01194671168923378,-0.012517333962023258,0.02988249808549881,-0.045987386256456375,0.01701355166733265,-0.055709466338157654,- ... (7749 characters truncated) ... 21428,0.03515280410647392,-0.04663209244608879,0.10088474303483963,-0.02399558760225773,0.07112295925617218,0.04828358069062233,0.005128476768732071]', 'group_id': '75f17305-fcd8-4ee6-a2bf-d80329866d08', 'match_score': 0.0}

2026-03-12 18:23:53,762 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:53,763 INFO sqlalchemy.engine.Engine [cached since 51.95s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 51.95s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

2026-03-12 18:23:53,793 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,794 INFO sqlalchemy.engine.Engine [cached since 7.946s ago] {'user_id_1': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.946s ago] {'user_id_1': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'param_1': 1}

2026-03-12 18:23:53,825 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,827 INFO sqlalchemy.engine.Engine [cached since 7.978s ago] {'user_id_1': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.978s ago] {'user_id_1': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'param_1': 1}

2026-03-12 18:23:53,871 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:53,873 INFO sqlalchemy.engine.Engine [cached since 3.088s ago] {'embedding': '[0.06421631,0.00213744,-0.00630814,0.00474825,-0.05020940,-0.00640019,-0.00305837,0.02629711,0.00677375,-0.06209184,0.09135442,0.04314631,-0.08393059 ... (4117 characters truncated) ... 0.01890947,0.00779494,-0.01590099,0.00601790,0.02659780,-0.08280694,-0.02975976,-0.10260633,-0.01164955,0.04688633,0.06410019,-0.00216987,0.05183434]', 'user_id': '32afce86-bcbb-471b-919e-0de8202a4a87', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 3.088s ago] {'embedding': '[0.06421631,0.00213744,-0.00630814,0.00474825,-0.05020940,-0.00640019,-0.00305837,0.02629711,0.00677375,-0.06209184,0.09135442,0.04314631,-0.08393059 ... (4117 characters truncated) ... 0.01890947,0.00779494,-0.01590099,0.00601790,0.02659780,-0.08280694,-0.02975976,-0.10260633,-0.01164955,0.04688633,0.06410019,-0.00216987,0.05183434]', 'user_id': '32afce86-bcbb-471b-919e-0de8202a4a87', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7544, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:53,906 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,908 INFO sqlalchemy.engine.Engine [cached since 2.109s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.109s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7544)
INFO:dataset-notebook:Utworzono profil objawów dla test0014@zebra.pl

2026-03-12 18:23:53,943 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:53,944 INFO sqlalchemy.engine.Engine [cached since 3.063s ago] {'user_id_1': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.063s ago] {'user_id_1': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:53,973 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:53,974 INFO sqlalchemy.engine.Engine [cached since 3.06s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 3.06s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user 32afce86-bcbb-471b-919e-0de8202a4a87 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:54,006 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:54,007 INFO sqlalchemy.engine.Engine [cached since 3.055s ago] {'user_id': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 3.055s ago] {'user_id': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:54,037 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:54,038 INFO sqlalchemy.engine.Engine [cached since 3.053s ago] {'id': UUID('198ec0aa-5661-4922-9109-501dd92c8bec'), 'user_id': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'description': 'Syn ma bardzo charakterystyczny sposób chodzenia. Chodzi na szeroko rozstawionych nogach i często traci równowagę. Lekarze podejrzewają problem neurologiczny.', 'embedding': '[0.06421630829572678,0.0021374444477260113,-0.006308143958449364,0.0047482457011938095,-0.050209399312734604,-0.006400190759450197,-0.003058365313336 ... (7748 characters truncated) ... 4,-0.029759762808680534,-0.10260633379220963,-0.011649549938738346,0.04688633233308792,0.06410019099712372,-0.0021698682103306055,0.0518343448638916]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.754430845115732}

INFO:sqlalchemy.engine.Engine:[cached since 3.053s ago] {'id': UUID('198ec0aa-5661-4922-9109-501dd92c8bec'), 'user_id': UUID('32afce86-bcbb-471b-919e-0de8202a4a87'), 'description': 'Syn ma bardzo charakterystyczny sposób chodzenia. Chodzi na szeroko rozstawionych nogach i często traci równowagę. Lekarze podejrzewają problem neurologiczny.', 'embedding': '[0.06421630829572678,0.0021374444477260113,-0.006308143958449364,0.0047482457011938095,-0.050209399312734604,-0.006400190759450197,-0.003058365313336 ... (7748 characters truncated) ... 4,-0.029759762808680534,-0.10260633379220963,-0.011649549938738346,0.04688633233308792,0.06410019099712372,-0.0021698682103306055,0.0518343448638916]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.754430845115732}

2026-03-12 18:23:54,069 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:54,071 INFO sqlalchemy.engine.Engine [cached since 52.25s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 52.25s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

2026-03-12 18:23:54,101 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,102 INFO sqlalchemy.engine.Engine [cached since 8.254s ago] {'user_id_1': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.254s ago] {'user_id_1': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'param_1': 1}

2026-03-12 18:23:54,135 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,136 INFO sqlalchemy.engine.Engine [cached since 8.287s ago] {'user_id_1': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.287s ago] {'user_id_1': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'param_1': 1}

2026-03-12 18:23:54,180 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:54,182 INFO sqlalchemy.engine.Engine [cached since 3.397s ago] {'embedding': '[0.06006022,0.03177679,0.03914338,0.03786054,-0.00566782,-0.01177613,-0.05056935,0.00808809,0.05443941,-0.03629730,0.11514042,0.12822102,0.03269989,0 ... (4112 characters truncated) ... 8,0.03974755,-0.07773712,0.04373819,0.05531846,-0.01608494,0.01919725,0.00467376,-0.01332905,0.02495747,-0.00081165,0.12868980,0.03057404,0.01494475]', 'user_id': '9adf5879-5e8e-4df0-b1ec-5574850d8280', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 3.397s ago] {'embedding': '[0.06006022,0.03177679,0.03914338,0.03786054,-0.00566782,-0.01177613,-0.05056935,0.00808809,0.05443941,-0.03629730,0.11514042,0.12822102,0.03269989,0 ... (4112 characters truncated) ... 8,0.03974755,-0.07773712,0.04373819,0.05531846,-0.01608494,0.01919725,0.00467376,-0.01332905,0.02495747,-0.00081165,0.12868980,0.03057404,0.01494475]', 'user_id': '9adf5879-5e8e-4df0-b1ec-5574850d8280', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6683, group_id=708a6370-ea74-4374-a698-5adad01af45a
INFO:app.services.matching_service:Score 0.6683 < threshold 0.72 — nowa grupa

2026-03-12 18:23:54,214 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:54,216 INFO sqlalchemy.engine.Engine [cached since 3.371s ago] {'id': UUID('29938bd3-d18f-49a2-83c1-697340b25a31'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 3.371s ago] {'id': UUID('29938bd3-d18f-49a2-83c1-697340b25a31'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 29938bd3-d18f-49a2-83c1-697340b25a31
INFO:dataset-notebook:Utworzono profil objawów dla test0015@zebra.pl

2026-03-12 18:23:54,249 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,250 INFO sqlalchemy.engine.Engine [cached since 3.37s ago] {'user_id_1': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'group_id_1': '29938bd3-d18f-49a2-83c1-697340b25a31', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.37s ago] {'user_id_1': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'group_id_1': '29938bd3-d18f-49a2-83c1-697340b25a31', 'param_1': 1}

2026-03-12 18:23:54,281 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:54,283 INFO sqlalchemy.engine.Engine [cached since 3.368s ago] {'member_count_1': 1, 'id_1': '29938bd3-d18f-49a2-83c1-697340b25a31'}

INFO:sqlalchemy.engine.Engine:[cached since 3.368s ago] {'member_count_1': 1, 'id_1': '29938bd3-d18f-49a2-83c1-697340b25a31'}
INFO:app.services.matching_service:Dodano user 9adf5879-5e8e-4df0-b1ec-5574850d8280 do grupy 29938bd3-d18f-49a2-83c1-697340b25a31

2026-03-12 18:23:54,314 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:54,315 INFO sqlalchemy.engine.Engine [cached since 3.363s ago] {'user_id': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31'}

INFO:sqlalchemy.engine.Engine:[cached since 3.363s ago] {'user_id': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31'}

2026-03-12 18:23:54,345 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:54,346 INFO sqlalchemy.engine.Engine [cached since 3.361s ago] {'id': UUID('b168d253-556d-4ec6-9ca7-99b1505ef3c9'), 'user_id': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'description': 'Nasza córka od małego była bardzo spokojna i mało reagowała na otoczenie. Z czasem zauważyliśmy też opóźnienie w rozwoju mowy i trudności w kontaktach z innymi dziećmi.', 'embedding': '[0.06006022170186043,0.0317767895758152,0.03914337605237961,0.03786054253578186,-0.00566782196983695,-0.011776130646467209,-0.05056934803724289,0.008 ... (7772 characters truncated) ... ,0.004673756193369627,-0.013329047709703445,0.02495746687054634,-0.0008116544922813773,0.12868979573249817,0.030574044212698936,0.014944746159017086]', 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 3.361s ago] {'id': UUID('b168d253-556d-4ec6-9ca7-99b1505ef3c9'), 'user_id': UUID('9adf5879-5e8e-4df0-b1ec-5574850d8280'), 'description': 'Nasza córka od małego była bardzo spokojna i mało reagowała na otoczenie. Z czasem zauważyliśmy też opóźnienie w rozwoju mowy i trudności w kontaktach z innymi dziećmi.', 'embedding': '[0.06006022170186043,0.0317767895758152,0.03914337605237961,0.03786054253578186,-0.00566782196983695,-0.011776130646467209,-0.05056934803724289,0.008 ... (7772 characters truncated) ... ,0.004673756193369627,-0.013329047709703445,0.02495746687054634,-0.0008116544922813773,0.12868979573249817,0.030574044212698936,0.014944746159017086]', 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31', 'match_score': 0.0}

2026-03-12 18:23:54,379 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:54,380 INFO sqlalchemy.engine.Engine [cached since 52.56s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 52.56s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

2026-03-12 18:23:54,409 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,411 INFO sqlalchemy.engine.Engine [cached since 8.562s ago] {'user_id_1': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.562s ago] {'user_id_1': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'param_1': 1}

2026-03-12 18:23:54,445 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,446 INFO sqlalchemy.engine.Engine [cached since 8.597s ago] {'user_id_1': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.597s ago] {'user_id_1': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'param_1': 1}

2026-03-12 18:23:54,491 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:54,495 INFO sqlalchemy.engine.Engine [cached since 3.71s ago] {'embedding': '[0.01747264,0.00362267,0.01728810,0.02525896,-0.07426368,-0.02183855,-0.01232756,0.06578290,-0.01237864,-0.06345405,0.09125170,0.01847524,-0.03709397 ... (4122 characters truncated) ... 5,0.04425350,0.01164719,0.01015476,-0.01247816,0.07267667,-0.00811437,-0.03369617,-0.05553079,0.02120228,0.01282829,0.04711100,0.06449312,0.02359789]', 'user_id': '90e6669e-eee4-4fc5-970a-f32df6563c22', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 3.71s ago] {'embedding': '[0.01747264,0.00362267,0.01728810,0.02525896,-0.07426368,-0.02183855,-0.01232756,0.06578290,-0.01237864,-0.06345405,0.09125170,0.01847524,-0.03709397 ... (4122 characters truncated) ... 5,0.04425350,0.01164719,0.01015476,-0.01247816,0.07267667,-0.00811437,-0.03369617,-0.05553079,0.02120228,0.01282829,0.04711100,0.06449312,0.02359789]', 'user_id': '90e6669e-eee4-4fc5-970a-f32df6563c22', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7533, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:54,527 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,528 INFO sqlalchemy.engine.Engine [cached since 2.729s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.729s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7533)
INFO:dataset-notebook:Utworzono profil objawów dla test0016@zebra.pl

2026-03-12 18:23:54,558 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,560 INFO sqlalchemy.engine.Engine [cached since 3.679s ago] {'user_id_1': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.679s ago] {'user_id_1': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:54,589 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:54,591 INFO sqlalchemy.engine.Engine [cached since 3.676s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 3.676s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user 90e6669e-eee4-4fc5-970a-f32df6563c22 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:54,623 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:54,629 INFO sqlalchemy.engine.Engine [cached since 3.677s ago] {'user_id': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 3.677s ago] {'user_id': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:54,662 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:54,664 INFO sqlalchemy.engine.Engine [cached since 3.678s ago] {'id': UUID('e21b83fa-d24d-418e-ba1b-ab0c840da938'), 'user_id': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'description': 'Syn ma bardzo duży obwód głowy w porównaniu do reszty ciała. Lekarz zauważył to już w pierwszych miesiącach życia. Oprócz tego ma trudności z koordynacją ruchów.', 'embedding': '[0.017472635954618454,0.00362266693264246,0.017288103699684143,0.02525896206498146,-0.07426367700099945,-0.02183854766190052,-0.012327558360993862,0. ... (7752 characters truncated) ... 3269,-0.03369617089629173,-0.055530793964862823,0.02120228298008442,0.012828287668526173,0.04711100459098816,0.06449311971664429,0.02359788864850998]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.753324956098194}

INFO:sqlalchemy.engine.Engine:[cached since 3.678s ago] {'id': UUID('e21b83fa-d24d-418e-ba1b-ab0c840da938'), 'user_id': UUID('90e6669e-eee4-4fc5-970a-f32df6563c22'), 'description': 'Syn ma bardzo duży obwód głowy w porównaniu do reszty ciała. Lekarz zauważył to już w pierwszych miesiącach życia. Oprócz tego ma trudności z koordynacją ruchów.', 'embedding': '[0.017472635954618454,0.00362266693264246,0.017288103699684143,0.02525896206498146,-0.07426367700099945,-0.02183854766190052,-0.012327558360993862,0. ... (7752 characters truncated) ... 3269,-0.03369617089629173,-0.055530793964862823,0.02120228298008442,0.012828287668526173,0.04711100459098816,0.06449311971664429,0.02359788864850998]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.753324956098194}

2026-03-12 18:23:54,697 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:54,699 INFO sqlalchemy.engine.Engine [cached since 52.88s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 52.88s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

2026-03-12 18:23:54,730 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,732 INFO sqlalchemy.engine.Engine [cached since 8.883s ago] {'user_id_1': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.883s ago] {'user_id_1': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'param_1': 1}

2026-03-12 18:23:54,763 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,764 INFO sqlalchemy.engine.Engine [cached since 8.915s ago] {'user_id_1': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.915s ago] {'user_id_1': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'param_1': 1}

2026-03-12 18:23:54,811 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:54,813 INFO sqlalchemy.engine.Engine [cached since 4.028s ago] {'embedding': '[0.00474843,-0.01619523,0.06555618,0.11018252,-0.00893738,0.00623267,0.00219768,-0.03308358,0.03633459,-0.00613007,0.09178884,0.00835776,-0.07076819, ... (4121 characters truncated) ... .02067350,-0.04992684,-0.01939117,-0.04204066,-0.00597446,0.08894024,-0.02958523,-0.04260920,0.01610316,0.02453537,0.06646787,0.04258755,-0.00418427]', 'user_id': 'a498e4db-1c35-4338-bf06-70ec7b4e862f', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 4.028s ago] {'embedding': '[0.00474843,-0.01619523,0.06555618,0.11018252,-0.00893738,0.00623267,0.00219768,-0.03308358,0.03633459,-0.00613007,0.09178884,0.00835776,-0.07076819, ... (4121 characters truncated) ... .02067350,-0.04992684,-0.01939117,-0.04204066,-0.00597446,0.08894024,-0.02958523,-0.04260920,0.01610316,0.02453537,0.06646787,0.04258755,-0.00418427]', 'user_id': 'a498e4db-1c35-4338-bf06-70ec7b4e862f', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7768, group_id=52430a0b-05ed-41fb-8c80-6390c23cd7bd

2026-03-12 18:23:54,845 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,846 INFO sqlalchemy.engine.Engine [cached since 3.047s ago] {'id_1': UUID('52430a0b-05ed-41fb-8c80-6390c23cd7bd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.047s ago] {'id_1': UUID('52430a0b-05ed-41fb-8c80-6390c23cd7bd'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7768)
INFO:dataset-notebook:Utworzono profil objawów dla test0017@zebra.pl

2026-03-12 18:23:54,876 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:54,878 INFO sqlalchemy.engine.Engine [cached since 3.998s ago] {'user_id_1': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'group_id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.998s ago] {'user_id_1': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'group_id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'param_1': 1}

2026-03-12 18:23:54,907 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:54,908 INFO sqlalchemy.engine.Engine [cached since 3.993s ago] {'member_count_1': 1, 'id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}

INFO:sqlalchemy.engine.Engine:[cached since 3.993s ago] {'member_count_1': 1, 'id_1': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}
INFO:app.services.matching_service:Dodano user a498e4db-1c35-4338-bf06-70ec7b4e862f do grupy 52430a0b-05ed-41fb-8c80-6390c23cd7bd

2026-03-12 18:23:54,940 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:54,941 INFO sqlalchemy.engine.Engine [cached since 3.989s ago] {'user_id': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}

INFO:sqlalchemy.engine.Engine:[cached since 3.989s ago] {'user_id': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd'}

2026-03-12 18:23:54,970 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:54,971 INFO sqlalchemy.engine.Engine [cached since 3.986s ago] {'id': UUID('cf054dd2-389f-44e2-b373-19d4804fd7c2'), 'user_id': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'description': 'Nasze dziecko ma problemy ze wzrokiem od urodzenia. Nie skupia wzroku na przedmiotach i często mruży oczy.', 'embedding': '[0.004748430568724871,-0.016195232048630714,0.06555618345737457,0.1101825162768364,-0.008937384001910686,0.006232670042663813,0.002197680529206991,-0 ... (7752 characters truncated) ... 84,-0.029585234820842743,-0.04260920360684395,0.01610315963625908,0.024535372853279114,0.06646786630153656,0.04258755221962929,-0.004184267017990351]', 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'match_score': 0.776755998440623}

INFO:sqlalchemy.engine.Engine:[cached since 3.986s ago] {'id': UUID('cf054dd2-389f-44e2-b373-19d4804fd7c2'), 'user_id': UUID('a498e4db-1c35-4338-bf06-70ec7b4e862f'), 'description': 'Nasze dziecko ma problemy ze wzrokiem od urodzenia. Nie skupia wzroku na przedmiotach i często mruży oczy.', 'embedding': '[0.004748430568724871,-0.016195232048630714,0.06555618345737457,0.1101825162768364,-0.008937384001910686,0.006232670042663813,0.002197680529206991,-0 ... (7752 characters truncated) ... 84,-0.029585234820842743,-0.04260920360684395,0.01610315963625908,0.024535372853279114,0.06646786630153656,0.04258755221962929,-0.004184267017990351]', 'group_id': '52430a0b-05ed-41fb-8c80-6390c23cd7bd', 'match_score': 0.776755998440623}

2026-03-12 18:23:55,003 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:55,004 INFO sqlalchemy.engine.Engine [cached since 53.19s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 53.19s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

2026-03-12 18:23:55,034 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,035 INFO sqlalchemy.engine.Engine [cached since 9.186s ago] {'user_id_1': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.186s ago] {'user_id_1': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'param_1': 1}

2026-03-12 18:23:55,066 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,067 INFO sqlalchemy.engine.Engine [cached since 9.218s ago] {'user_id_1': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.218s ago] {'user_id_1': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'param_1': 1}

2026-03-12 18:23:55,111 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:55,112 INFO sqlalchemy.engine.Engine [cached since 4.327s ago] {'embedding': '[0.03305450,0.03662824,0.05656090,0.07057133,0.11451592,-0.00961563,-0.06333815,-0.00244509,0.05543257,0.01454765,0.05847095,0.07241084,-0.05220919,- ... (4108 characters truncated) ... ,0.00773876,-0.07076246,-0.02634196,0.06542242,-0.03418753,-0.09460346,0.01164366,-0.04896039,0.00025781,0.02769489,0.03599297,0.01703264,0.02140411]', 'user_id': '696d909b-c15c-4a72-a570-eb7ba300d576', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 4.327s ago] {'embedding': '[0.03305450,0.03662824,0.05656090,0.07057133,0.11451592,-0.00961563,-0.06333815,-0.00244509,0.05543257,0.01454765,0.05847095,0.07241084,-0.05220919,- ... (4108 characters truncated) ... ,0.00773876,-0.07076246,-0.02634196,0.06542242,-0.03418753,-0.09460346,0.01164366,-0.04896039,0.00025781,0.02769489,0.03599297,0.01703264,0.02140411]', 'user_id': '696d909b-c15c-4a72-a570-eb7ba300d576', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7201, group_id=cb092a24-2831-48f5-b35f-7add54e19d6b

2026-03-12 18:23:55,144 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,145 INFO sqlalchemy.engine.Engine [cached since 3.345s ago] {'id_1': UUID('cb092a24-2831-48f5-b35f-7add54e19d6b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.345s ago] {'id_1': UUID('cb092a24-2831-48f5-b35f-7add54e19d6b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7201)
INFO:dataset-notebook:Utworzono profil objawów dla test0018@zebra.pl

2026-03-12 18:23:55,176 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,177 INFO sqlalchemy.engine.Engine [cached since 4.296s ago] {'user_id_1': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'group_id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.296s ago] {'user_id_1': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'group_id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'param_1': 1}

2026-03-12 18:23:55,207 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:55,208 INFO sqlalchemy.engine.Engine [cached since 4.293s ago] {'member_count_1': 1, 'id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

INFO:sqlalchemy.engine.Engine:[cached since 4.293s ago] {'member_count_1': 1, 'id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}
INFO:app.services.matching_service:Dodano user 696d909b-c15c-4a72-a570-eb7ba300d576 do grupy cb092a24-2831-48f5-b35f-7add54e19d6b

2026-03-12 18:23:55,238 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:55,240 INFO sqlalchemy.engine.Engine [cached since 4.287s ago] {'user_id': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

INFO:sqlalchemy.engine.Engine:[cached since 4.287s ago] {'user_id': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

2026-03-12 18:23:55,271 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:55,272 INFO sqlalchemy.engine.Engine [cached since 4.286s ago] {'id': UUID('a991b3cf-28ab-4c71-9d60-5daaac77ea3d'), 'user_id': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'description': 'Córka bardzo późno zaczęła chodzić. Nawet teraz porusza się wolniej niż rówieśnicy i szybko się męczy.', 'embedding': '[0.03305450454354286,0.03662823513150215,0.05656089633703232,0.07057132571935654,0.11451591551303864,-0.009615628980100155,-0.06333815306425095,-0.00 ... (7722 characters truncated) ... 9703,0.011643663048744202,-0.04896038770675659,0.0002578071434982121,0.02769489400088787,0.03599296882748604,0.01703263819217682,0.02140411175787449]', 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'match_score': 0.720056376458895}

INFO:sqlalchemy.engine.Engine:[cached since 4.286s ago] {'id': UUID('a991b3cf-28ab-4c71-9d60-5daaac77ea3d'), 'user_id': UUID('696d909b-c15c-4a72-a570-eb7ba300d576'), 'description': 'Córka bardzo późno zaczęła chodzić. Nawet teraz porusza się wolniej niż rówieśnicy i szybko się męczy.', 'embedding': '[0.03305450454354286,0.03662823513150215,0.05656089633703232,0.07057132571935654,0.11451591551303864,-0.009615628980100155,-0.06333815306425095,-0.00 ... (7722 characters truncated) ... 9703,0.011643663048744202,-0.04896038770675659,0.0002578071434982121,0.02769489400088787,0.03599296882748604,0.01703263819217682,0.02140411175787449]', 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'match_score': 0.720056376458895}

2026-03-12 18:23:55,303 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:55,307 INFO sqlalchemy.engine.Engine [cached since 53.49s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 53.49s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

2026-03-12 18:23:55,342 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,346 INFO sqlalchemy.engine.Engine [cached since 9.498s ago] {'user_id_1': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.498s ago] {'user_id_1': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'param_1': 1}

2026-03-12 18:23:55,378 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,379 INFO sqlalchemy.engine.Engine [cached since 9.531s ago] {'user_id_1': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.531s ago] {'user_id_1': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'param_1': 1}

2026-03-12 18:23:55,426 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:55,427 INFO sqlalchemy.engine.Engine [cached since 4.642s ago] {'embedding': '[-0.01892481,0.07899613,0.06916965,0.02728091,0.01326280,0.05047319,0.00923037,-0.00531948,-0.06909049,-0.08954705,0.10386628,-0.03138943,0.01654595, ... (4116 characters truncated) ... ,-0.01445106,-0.05109416,0.02512645,-0.06431341,-0.02522041,-0.00203477,0.03497908,0.04777738,0.06095440,0.07899790,0.00858840,0.10518075,0.03620875]', 'user_id': '282ee831-a78a-4567-82f4-818d197f949e', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 4.642s ago] {'embedding': '[-0.01892481,0.07899613,0.06916965,0.02728091,0.01326280,0.05047319,0.00923037,-0.00531948,-0.06909049,-0.08954705,0.10386628,-0.03138943,0.01654595, ... (4116 characters truncated) ... ,-0.01445106,-0.05109416,0.02512645,-0.06431341,-0.02522041,-0.00203477,0.03497908,0.04777738,0.06095440,0.07899790,0.00858840,0.10518075,0.03620875]', 'user_id': '282ee831-a78a-4567-82f4-818d197f949e', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5631, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a
INFO:app.services.matching_service:Score 0.5631 < threshold 0.72 — nowa grupa

2026-03-12 18:23:55,459 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:55,461 INFO sqlalchemy.engine.Engine [cached since 4.616s ago] {'id': UUID('da9964cc-5ab7-40e8-8d34-dce853914c8f'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 4.616s ago] {'id': UUID('da9964cc-5ab7-40e8-8d34-dce853914c8f'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: da9964cc-5ab7-40e8-8d34-dce853914c8f
INFO:dataset-notebook:Utworzono profil objawów dla test0019@zebra.pl

2026-03-12 18:23:55,494 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,495 INFO sqlalchemy.engine.Engine [cached since 4.614s ago] {'user_id_1': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'group_id_1': 'da9964cc-5ab7-40e8-8d34-dce853914c8f', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.614s ago] {'user_id_1': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'group_id_1': 'da9964cc-5ab7-40e8-8d34-dce853914c8f', 'param_1': 1}

2026-03-12 18:23:55,525 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:55,526 INFO sqlalchemy.engine.Engine [cached since 4.611s ago] {'member_count_1': 1, 'id_1': 'da9964cc-5ab7-40e8-8d34-dce853914c8f'}

INFO:sqlalchemy.engine.Engine:[cached since 4.611s ago] {'member_count_1': 1, 'id_1': 'da9964cc-5ab7-40e8-8d34-dce853914c8f'}
INFO:app.services.matching_service:Dodano user 282ee831-a78a-4567-82f4-818d197f949e do grupy da9964cc-5ab7-40e8-8d34-dce853914c8f

2026-03-12 18:23:55,554 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:55,554 INFO sqlalchemy.engine.Engine [cached since 4.602s ago] {'user_id': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'group_id': 'da9964cc-5ab7-40e8-8d34-dce853914c8f'}

INFO:sqlalchemy.engine.Engine:[cached since 4.602s ago] {'user_id': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'group_id': 'da9964cc-5ab7-40e8-8d34-dce853914c8f'}

2026-03-12 18:23:55,585 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:55,586 INFO sqlalchemy.engine.Engine [cached since 4.601s ago] {'id': UUID('45c00656-05c7-4bb2-afbb-d5223f2910ae'), 'user_id': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'description': 'Syn ma bardzo cienką i delikatną skórę. Nawet małe zadrapania długo się goją i zostawiają ślady. Zawsze jego skóra była blada', 'embedding': '[-0.018924811854958534,0.07899612933397293,0.06916964799165726,0.027280911803245544,0.013262797147035599,0.05047319456934929,0.009230367839336395,-0. ... (7701 characters truncated) ... 939644,0.03497907891869545,0.047777384519577026,0.060954395681619644,0.078997902572155,0.008588404394686222,0.10518074780702591,0.036208752542734146]', 'group_id': 'da9964cc-5ab7-40e8-8d34-dce853914c8f', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 4.601s ago] {'id': UUID('45c00656-05c7-4bb2-afbb-d5223f2910ae'), 'user_id': UUID('282ee831-a78a-4567-82f4-818d197f949e'), 'description': 'Syn ma bardzo cienką i delikatną skórę. Nawet małe zadrapania długo się goją i zostawiają ślady. Zawsze jego skóra była blada', 'embedding': '[-0.018924811854958534,0.07899612933397293,0.06916964799165726,0.027280911803245544,0.013262797147035599,0.05047319456934929,0.009230367839336395,-0. ... (7701 characters truncated) ... 939644,0.03497907891869545,0.047777384519577026,0.060954395681619644,0.078997902572155,0.008588404394686222,0.10518074780702591,0.036208752542734146]', 'group_id': 'da9964cc-5ab7-40e8-8d34-dce853914c8f', 'match_score': 0.0}

2026-03-12 18:23:55,617 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:55,618 INFO sqlalchemy.engine.Engine [cached since 53.8s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 53.8s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

2026-03-12 18:23:55,649 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,650 INFO sqlalchemy.engine.Engine [cached since 9.802s ago] {'user_id_1': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.802s ago] {'user_id_1': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'param_1': 1}

2026-03-12 18:23:55,681 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,682 INFO sqlalchemy.engine.Engine [cached since 9.833s ago] {'user_id_1': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.833s ago] {'user_id_1': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'param_1': 1}

2026-03-12 18:23:55,726 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:55,733 INFO sqlalchemy.engine.Engine [cached since 4.948s ago] {'embedding': '[0.04319210,-0.02134777,0.03202398,-0.00329263,-0.05966551,0.01480455,0.01183620,0.00278675,-0.00415840,0.05860941,0.02414868,0.04609301,-0.02881386, ... (4127 characters truncated) ... ,0.03191638,-0.04824365,-0.02592346,0.08538254,0.05275400,-0.03937469,0.04862728,-0.03971012,0.03450913,-0.03004709,0.06216458,0.03933800,0.04431498]', 'user_id': 'cd573fac-3699-4e24-a227-ba96a735bf1f', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 4.948s ago] {'embedding': '[0.04319210,-0.02134777,0.03202398,-0.00329263,-0.05966551,0.01480455,0.01183620,0.00278675,-0.00415840,0.05860941,0.02414868,0.04609301,-0.02881386, ... (4127 characters truncated) ... ,0.03191638,-0.04824365,-0.02592346,0.08538254,0.05275400,-0.03937469,0.04862728,-0.03971012,0.03450913,-0.03004709,0.06216458,0.03933800,0.04431498]', 'user_id': 'cd573fac-3699-4e24-a227-ba96a735bf1f', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7239, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:55,766 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,767 INFO sqlalchemy.engine.Engine [cached since 3.968s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.968s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7239)
INFO:dataset-notebook:Utworzono profil objawów dla test0020@zebra.pl

2026-03-12 18:23:55,800 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,801 INFO sqlalchemy.engine.Engine [cached since 4.92s ago] {'user_id_1': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.92s ago] {'user_id_1': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:55,830 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:55,831 INFO sqlalchemy.engine.Engine [cached since 4.917s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 4.917s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user cd573fac-3699-4e24-a227-ba96a735bf1f do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:55,865 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:55,865 INFO sqlalchemy.engine.Engine [cached since 4.913s ago] {'user_id': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 4.913s ago] {'user_id': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:55,895 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:55,896 INFO sqlalchemy.engine.Engine [cached since 4.911s ago] {'id': UUID('b450e05b-44e5-4bab-9a3b-49a2630bdaa4'), 'user_id': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'description': 'Nasze dziecko ma problemy z koordynacją ruchową. Trudno mu łapać piłkę, rysować czy zapinać guziki. Nie lubi bawić się w zabawy sprawnościowe.', 'embedding': '[0.04319210350513458,-0.0213477686047554,0.03202398493885994,-0.0032926294952630997,-0.059665508568286896,0.014804553240537643,0.011836203746497631,0 ... (7746 characters truncated) ... 2004,0.048627275973558426,-0.03971012309193611,0.03450912609696388,-0.030047085136175156,0.06216457858681679,0.03933800011873245,0.04431498423218727]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.723870363696857}

INFO:sqlalchemy.engine.Engine:[cached since 4.911s ago] {'id': UUID('b450e05b-44e5-4bab-9a3b-49a2630bdaa4'), 'user_id': UUID('cd573fac-3699-4e24-a227-ba96a735bf1f'), 'description': 'Nasze dziecko ma problemy z koordynacją ruchową. Trudno mu łapać piłkę, rysować czy zapinać guziki. Nie lubi bawić się w zabawy sprawnościowe.', 'embedding': '[0.04319210350513458,-0.0213477686047554,0.03202398493885994,-0.0032926294952630997,-0.059665508568286896,0.014804553240537643,0.011836203746497631,0 ... (7746 characters truncated) ... 2004,0.048627275973558426,-0.03971012309193611,0.03450912609696388,-0.030047085136175156,0.06216457858681679,0.03933800011873245,0.04431498423218727]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.723870363696857}

2026-03-12 18:23:55,928 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:55,929 INFO sqlalchemy.engine.Engine [cached since 54.11s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 54.11s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

2026-03-12 18:23:55,956 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,957 INFO sqlalchemy.engine.Engine [cached since 10.11s ago] {'user_id_1': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.11s ago] {'user_id_1': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'param_1': 1}

2026-03-12 18:23:55,989 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:55,990 INFO sqlalchemy.engine.Engine [cached since 10.14s ago] {'user_id_1': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.14s ago] {'user_id_1': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'param_1': 1}

2026-03-12 18:23:56,033 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:56,034 INFO sqlalchemy.engine.Engine [cached since 5.249s ago] {'embedding': '[0.00362473,-0.03290119,0.02499861,0.10442703,-0.08267200,0.02936026,-0.00266387,-0.01057005,-0.00546879,-0.02693137,0.03738307,-0.04636298,-0.003045 ... (4115 characters truncated) ... -0.01937000,-0.06936682,-0.03178544,-0.04438495,0.07722981,0.00364226,0.00968812,-0.01864358,0.08928104,0.01698750,0.05323987,0.09742285,-0.06482635]', 'user_id': '2787133b-27cb-427d-846b-5ff30ff8cfd7', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 5.249s ago] {'embedding': '[0.00362473,-0.03290119,0.02499861,0.10442703,-0.08267200,0.02936026,-0.00266387,-0.01057005,-0.00546879,-0.02693137,0.03738307,-0.04636298,-0.003045 ... (4115 characters truncated) ... -0.01937000,-0.06936682,-0.03178544,-0.04438495,0.07722981,0.00364226,0.00968812,-0.01864358,0.08928104,0.01698750,0.05323987,0.09742285,-0.06482635]', 'user_id': '2787133b-27cb-427d-846b-5ff30ff8cfd7', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7264, group_id=cb092a24-2831-48f5-b35f-7add54e19d6b

2026-03-12 18:23:56,066 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,067 INFO sqlalchemy.engine.Engine [cached since 4.268s ago] {'id_1': UUID('cb092a24-2831-48f5-b35f-7add54e19d6b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.268s ago] {'id_1': UUID('cb092a24-2831-48f5-b35f-7add54e19d6b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7264)
INFO:dataset-notebook:Utworzono profil objawów dla test0021@zebra.pl

2026-03-12 18:23:56,098 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,100 INFO sqlalchemy.engine.Engine [cached since 5.219s ago] {'user_id_1': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'group_id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.219s ago] {'user_id_1': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'group_id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'param_1': 1}

2026-03-12 18:23:56,132 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:56,136 INFO sqlalchemy.engine.Engine [cached since 5.222s ago] {'member_count_1': 1, 'id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

INFO:sqlalchemy.engine.Engine:[cached since 5.222s ago] {'member_count_1': 1, 'id_1': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}
INFO:app.services.matching_service:Dodano user 2787133b-27cb-427d-846b-5ff30ff8cfd7 do grupy cb092a24-2831-48f5-b35f-7add54e19d6b

2026-03-12 18:23:56,171 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:56,172 INFO sqlalchemy.engine.Engine [cached since 5.22s ago] {'user_id': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

INFO:sqlalchemy.engine.Engine:[cached since 5.22s ago] {'user_id': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b'}

2026-03-12 18:23:56,201 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:56,202 INFO sqlalchemy.engine.Engine [cached since 5.216s ago] {'id': UUID('95f273b9-8745-477b-9af0-3ac47731f0a8'), 'user_id': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'description': 'Córka od urodzenia ma bardzo słabe mięśnie twarzy. Często ma otwarte usta i trudniej jej wyraźnie mówić. Jest apatyczna.', 'embedding': '[0.0036247274838387966,-0.03290119394659996,0.024998614564538002,0.1044270321726799,-0.08267199993133545,0.02936026267707348,-0.002663874067366123,-0 ... (7739 characters truncated) ... 6457,0.009688117541372776,-0.018643584102392197,0.08928103744983673,0.016987498849630356,0.05323987081646919,0.09742284566164017,-0.0648263469338417]', 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'match_score': 0.726404070854187}

INFO:sqlalchemy.engine.Engine:[cached since 5.216s ago] {'id': UUID('95f273b9-8745-477b-9af0-3ac47731f0a8'), 'user_id': UUID('2787133b-27cb-427d-846b-5ff30ff8cfd7'), 'description': 'Córka od urodzenia ma bardzo słabe mięśnie twarzy. Często ma otwarte usta i trudniej jej wyraźnie mówić. Jest apatyczna.', 'embedding': '[0.0036247274838387966,-0.03290119394659996,0.024998614564538002,0.1044270321726799,-0.08267199993133545,0.02936026267707348,-0.002663874067366123,-0 ... (7739 characters truncated) ... 6457,0.009688117541372776,-0.018643584102392197,0.08928103744983673,0.016987498849630356,0.05323987081646919,0.09742284566164017,-0.0648263469338417]', 'group_id': 'cb092a24-2831-48f5-b35f-7add54e19d6b', 'match_score': 0.726404070854187}

2026-03-12 18:23:56,233 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:56,234 INFO sqlalchemy.engine.Engine [cached since 54.42s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 54.42s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

2026-03-12 18:23:56,264 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,265 INFO sqlalchemy.engine.Engine [cached since 10.42s ago] {'user_id_1': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.42s ago] {'user_id_1': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'param_1': 1}

2026-03-12 18:23:56,297 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,298 INFO sqlalchemy.engine.Engine [cached since 10.45s ago] {'user_id_1': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.45s ago] {'user_id_1': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'param_1': 1}

2026-03-12 18:23:56,340 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:56,341 INFO sqlalchemy.engine.Engine [cached since 5.556s ago] {'embedding': '[0.06472843,0.02412558,-0.01942816,0.01216509,-0.00991621,0.04569459,-0.05341363,0.02674446,-0.02239660,-0.01848339,0.01029615,0.05204863,-0.05255579 ... (4119 characters truncated) ... 0.04163726,-0.01804171,-0.05463419,0.06713845,-0.01687902,-0.12249288,0.01541799,-0.06688941,-0.01664777,0.02794162,0.03253588,0.03362908,0.06345037]', 'user_id': '8d115b54-593b-4bbe-8f84-6e2e477fa9f2', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 5.556s ago] {'embedding': '[0.06472843,0.02412558,-0.01942816,0.01216509,-0.00991621,0.04569459,-0.05341363,0.02674446,-0.02239660,-0.01848339,0.01029615,0.05204863,-0.05255579 ... (4119 characters truncated) ... 0.04163726,-0.01804171,-0.05463419,0.06713845,-0.01687902,-0.12249288,0.01541799,-0.06688941,-0.01664777,0.02794162,0.03253588,0.03362908,0.06345037]', 'user_id': '8d115b54-593b-4bbe-8f84-6e2e477fa9f2', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8091, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:56,373 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,374 INFO sqlalchemy.engine.Engine [cached since 4.574s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.574s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.8091)
INFO:dataset-notebook:Utworzono profil objawów dla test0022@zebra.pl

2026-03-12 18:23:56,405 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,406 INFO sqlalchemy.engine.Engine [cached since 5.526s ago] {'user_id_1': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.526s ago] {'user_id_1': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:56,436 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:56,437 INFO sqlalchemy.engine.Engine [cached since 5.522s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 5.522s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user 8d115b54-593b-4bbe-8f84-6e2e477fa9f2 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:56,466 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:56,467 INFO sqlalchemy.engine.Engine [cached since 5.515s ago] {'user_id': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 5.515s ago] {'user_id': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:56,497 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:56,498 INFO sqlalchemy.engine.Engine [cached since 5.513s ago] {'id': UUID('c926f27d-bd1d-4340-9a77-bdf58de9f8b3'), 'user_id': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'description': 'Syn od kilku lat ma coraz większy problem z bieganiem. Wcześniej radził sobie dobrze, ale z czasem jego mięśnie nóg wydają się słabsze.', 'embedding': '[0.06472843140363693,0.02412557788193226,-0.019428156316280365,0.01216509472578764,-0.009916205890476704,0.045694585889577866,-0.05341362953186035,0. ... (7731 characters truncated) ... 513,0.01541798934340477,-0.06688941270112991,-0.016647769138216972,0.027941621840000153,0.03253588452935219,0.033629078418016434,0.06345036625862122]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.809058260377751}

INFO:sqlalchemy.engine.Engine:[cached since 5.513s ago] {'id': UUID('c926f27d-bd1d-4340-9a77-bdf58de9f8b3'), 'user_id': UUID('8d115b54-593b-4bbe-8f84-6e2e477fa9f2'), 'description': 'Syn od kilku lat ma coraz większy problem z bieganiem. Wcześniej radził sobie dobrze, ale z czasem jego mięśnie nóg wydają się słabsze.', 'embedding': '[0.06472843140363693,0.02412557788193226,-0.019428156316280365,0.01216509472578764,-0.009916205890476704,0.045694585889577866,-0.05341362953186035,0. ... (7731 characters truncated) ... 513,0.01541798934340477,-0.06688941270112991,-0.016647769138216972,0.027941621840000153,0.03253588452935219,0.033629078418016434,0.06345036625862122]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.809058260377751}

2026-03-12 18:23:56,530 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:56,531 INFO sqlalchemy.engine.Engine [cached since 54.71s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 54.71s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

2026-03-12 18:23:56,560 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,561 INFO sqlalchemy.engine.Engine [cached since 10.71s ago] {'user_id_1': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.71s ago] {'user_id_1': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'param_1': 1}

2026-03-12 18:23:56,589 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,591 INFO sqlalchemy.engine.Engine [cached since 10.74s ago] {'user_id_1': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.74s ago] {'user_id_1': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'param_1': 1}

2026-03-12 18:23:56,634 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:56,635 INFO sqlalchemy.engine.Engine [cached since 5.85s ago] {'embedding': '[0.02938037,-0.01470889,0.02369665,0.01164539,-0.06185066,0.02765669,-0.01423237,-0.02074102,0.05931488,0.01143019,0.01714929,0.09691373,0.00000147,0 ... (4119 characters truncated) ... 883,-0.00400682,0.00332481,0.02516565,0.09164410,0.03168911,0.02037975,0.00682232,0.01089526,0.06828276,0.00183170,0.13546987,0.00786121,-0.01526108]', 'user_id': 'f90aed21-4d4c-4846-b69d-d681c3da442b', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 5.85s ago] {'embedding': '[0.02938037,-0.01470889,0.02369665,0.01164539,-0.06185066,0.02765669,-0.01423237,-0.02074102,0.05931488,0.01143019,0.01714929,0.09691373,0.00000147,0 ... (4119 characters truncated) ... 883,-0.00400682,0.00332481,0.02516565,0.09164410,0.03168911,0.02037975,0.00682232,0.01089526,0.06828276,0.00183170,0.13546987,0.00786121,-0.01526108]', 'user_id': 'f90aed21-4d4c-4846-b69d-d681c3da442b', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6718, group_id=66204af3-89e7-4ec6-838e-0fcd7e54e4c7
INFO:app.services.matching_service:Score 0.6718 < threshold 0.72 — nowa grupa

2026-03-12 18:23:56,666 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:56,668 INFO sqlalchemy.engine.Engine [cached since 5.823s ago] {'id': UUID('88e3bb48-85f0-4605-88f5-2253111c0785'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 5.823s ago] {'id': UUID('88e3bb48-85f0-4605-88f5-2253111c0785'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 88e3bb48-85f0-4605-88f5-2253111c0785
INFO:dataset-notebook:Utworzono profil objawów dla test0023@zebra.pl

2026-03-12 18:23:56,698 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,699 INFO sqlalchemy.engine.Engine [cached since 5.818s ago] {'user_id_1': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'group_id_1': '88e3bb48-85f0-4605-88f5-2253111c0785', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.818s ago] {'user_id_1': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'group_id_1': '88e3bb48-85f0-4605-88f5-2253111c0785', 'param_1': 1}

2026-03-12 18:23:56,729 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:56,730 INFO sqlalchemy.engine.Engine [cached since 5.815s ago] {'member_count_1': 1, 'id_1': '88e3bb48-85f0-4605-88f5-2253111c0785'}

INFO:sqlalchemy.engine.Engine:[cached since 5.815s ago] {'member_count_1': 1, 'id_1': '88e3bb48-85f0-4605-88f5-2253111c0785'}
INFO:app.services.matching_service:Dodano user f90aed21-4d4c-4846-b69d-d681c3da442b do grupy 88e3bb48-85f0-4605-88f5-2253111c0785

2026-03-12 18:23:56,761 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:56,761 INFO sqlalchemy.engine.Engine [cached since 5.809s ago] {'user_id': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'group_id': '88e3bb48-85f0-4605-88f5-2253111c0785'}

INFO:sqlalchemy.engine.Engine:[cached since 5.809s ago] {'user_id': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'group_id': '88e3bb48-85f0-4605-88f5-2253111c0785'}

2026-03-12 18:23:56,792 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:56,793 INFO sqlalchemy.engine.Engine [cached since 5.808s ago] {'id': UUID('522feb50-3601-496b-b51b-3cdc111f6733'), 'user_id': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'description': 'Nasze dziecko bardzo wolno uczy się nowych rzeczy. Potrzebuje dużo powtórzeń, żeby zapamiętać proste czynności.', 'embedding': '[0.029380369931459427,-0.014708886854350567,0.0236966535449028,0.011645391583442688,-0.0618506595492363,0.027656693011522293,-0.01423237007111311,-0. ... (7750 characters truncated) ... 073,0.006822324823588133,0.010895263403654099,0.06828276067972183,0.0018316995119675994,0.13546986877918243,0.00786120630800724,-0.01526107918471098]', 'group_id': '88e3bb48-85f0-4605-88f5-2253111c0785', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 5.808s ago] {'id': UUID('522feb50-3601-496b-b51b-3cdc111f6733'), 'user_id': UUID('f90aed21-4d4c-4846-b69d-d681c3da442b'), 'description': 'Nasze dziecko bardzo wolno uczy się nowych rzeczy. Potrzebuje dużo powtórzeń, żeby zapamiętać proste czynności.', 'embedding': '[0.029380369931459427,-0.014708886854350567,0.0236966535449028,0.011645391583442688,-0.0618506595492363,0.027656693011522293,-0.01423237007111311,-0. ... (7750 characters truncated) ... 073,0.006822324823588133,0.010895263403654099,0.06828276067972183,0.0018316995119675994,0.13546986877918243,0.00786120630800724,-0.01526107918471098]', 'group_id': '88e3bb48-85f0-4605-88f5-2253111c0785', 'match_score': 0.0}

2026-03-12 18:23:56,825 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:56,826 INFO sqlalchemy.engine.Engine [cached since 55.01s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 55.01s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

2026-03-12 18:23:56,856 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,857 INFO sqlalchemy.engine.Engine [cached since 11.01s ago] {'user_id_1': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.01s ago] {'user_id_1': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'param_1': 1}

2026-03-12 18:23:56,884 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,886 INFO sqlalchemy.engine.Engine [cached since 11.04s ago] {'user_id_1': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.04s ago] {'user_id_1': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'param_1': 1}

2026-03-12 18:23:56,928 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:56,929 INFO sqlalchemy.engine.Engine [cached since 6.144s ago] {'embedding': '[-0.09482035,0.03773231,0.08726990,0.05980779,-0.00643649,-0.06643806,-0.03057096,0.08790338,0.05846317,0.01170444,0.04685832,0.06017015,-0.05628748, ... (4123 characters truncated) ... 8,0.00944080,-0.03684212,0.04150507,-0.05192475,0.07891989,0.00959013,-0.01756023,-0.06179714,0.05060394,0.03915527,0.06036740,0.03859881,0.04559767]', 'user_id': '556e72f7-b67e-48db-9943-64f1ea1d0033', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 6.144s ago] {'embedding': '[-0.09482035,0.03773231,0.08726990,0.05980779,-0.00643649,-0.06643806,-0.03057096,0.08790338,0.05846317,0.01170444,0.04685832,0.06017015,-0.05628748, ... (4123 characters truncated) ... 8,0.00944080,-0.03684212,0.04150507,-0.05192475,0.07891989,0.00959013,-0.01756023,-0.06179714,0.05060394,0.03915527,0.06036740,0.03859881,0.04559767]', 'user_id': '556e72f7-b67e-48db-9943-64f1ea1d0033', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6607, group_id=55c850c8-071d-4f86-a619-16e010387f42
INFO:app.services.matching_service:Score 0.6607 < threshold 0.72 — nowa grupa

2026-03-12 18:23:56,958 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:56,960 INFO sqlalchemy.engine.Engine [cached since 6.115s ago] {'id': UUID('3d2f5bd7-90e7-4062-bb72-108b9c7f61bb'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 6.115s ago] {'id': UUID('3d2f5bd7-90e7-4062-bb72-108b9c7f61bb'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 3d2f5bd7-90e7-4062-bb72-108b9c7f61bb
INFO:dataset-notebook:Utworzono profil objawów dla test0024@zebra.pl

2026-03-12 18:23:56,990 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:56,991 INFO sqlalchemy.engine.Engine [cached since 6.111s ago] {'user_id_1': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'group_id_1': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.111s ago] {'user_id_1': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'group_id_1': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb', 'param_1': 1}

2026-03-12 18:23:57,021 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:57,022 INFO sqlalchemy.engine.Engine [cached since 6.107s ago] {'member_count_1': 1, 'id_1': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb'}

INFO:sqlalchemy.engine.Engine:[cached since 6.107s ago] {'member_count_1': 1, 'id_1': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb'}
INFO:app.services.matching_service:Dodano user 556e72f7-b67e-48db-9943-64f1ea1d0033 do grupy 3d2f5bd7-90e7-4062-bb72-108b9c7f61bb

2026-03-12 18:23:57,054 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:57,056 INFO sqlalchemy.engine.Engine [cached since 6.103s ago] {'user_id': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'group_id': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb'}

INFO:sqlalchemy.engine.Engine:[cached since 6.103s ago] {'user_id': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'group_id': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb'}

2026-03-12 18:23:57,085 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:57,087 INFO sqlalchemy.engine.Engine [cached since 6.102s ago] {'id': UUID('befaacfb-cbd8-4013-9b1c-a0871404dd36'), 'user_id': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'description': 'Córka ma bardzo małe dłonie i stopy w porównaniu do reszty ciała. Lekarze zwrócili na to uwagę podczas badań.', 'embedding': '[-0.09482035040855408,0.037732310593128204,0.08726990222930908,0.05980778858065605,-0.006436485797166824,-0.06643806397914886,-0.03057095967233181,0. ... (7762 characters truncated) ... 7403946,-0.01756022684276104,-0.061797138303518295,0.05060394108295441,0.0391552671790123,0.0603673979640007,0.03859880939126015,0.04559767246246338]', 'group_id': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 6.102s ago] {'id': UUID('befaacfb-cbd8-4013-9b1c-a0871404dd36'), 'user_id': UUID('556e72f7-b67e-48db-9943-64f1ea1d0033'), 'description': 'Córka ma bardzo małe dłonie i stopy w porównaniu do reszty ciała. Lekarze zwrócili na to uwagę podczas badań.', 'embedding': '[-0.09482035040855408,0.037732310593128204,0.08726990222930908,0.05980778858065605,-0.006436485797166824,-0.06643806397914886,-0.03057095967233181,0. ... (7762 characters truncated) ... 7403946,-0.01756022684276104,-0.061797138303518295,0.05060394108295441,0.0391552671790123,0.0603673979640007,0.03859880939126015,0.04559767246246338]', 'group_id': '3d2f5bd7-90e7-4062-bb72-108b9c7f61bb', 'match_score': 0.0}

2026-03-12 18:23:57,118 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:57,120 INFO sqlalchemy.engine.Engine [cached since 55.3s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 55.3s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

2026-03-12 18:23:57,149 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,151 INFO sqlalchemy.engine.Engine [cached since 11.3s ago] {'user_id_1': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.3s ago] {'user_id_1': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'param_1': 1}

2026-03-12 18:23:57,181 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,182 INFO sqlalchemy.engine.Engine [cached since 11.33s ago] {'user_id_1': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.33s ago] {'user_id_1': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'param_1': 1}

2026-03-12 18:23:57,226 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:57,227 INFO sqlalchemy.engine.Engine [cached since 6.442s ago] {'embedding': '[0.02128641,0.02214614,0.02542375,0.01552286,-0.02946643,0.02252624,-0.05946942,0.02115862,0.01407179,-0.04199671,0.07189141,0.05347175,-0.02574515,0 ... (4122 characters truncated) ... ,0.03653669,-0.00070670,-0.03307657,0.07703535,-0.01762371,-0.01540658,0.03883591,-0.05737233,0.02075332,0.05934902,0.06073153,0.06037147,0.03859269]', 'user_id': '2f389a97-b36f-4200-aba2-d204dd1d7de7', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 6.442s ago] {'embedding': '[0.02128641,0.02214614,0.02542375,0.01552286,-0.02946643,0.02252624,-0.05946942,0.02115862,0.01407179,-0.04199671,0.07189141,0.05347175,-0.02574515,0 ... (4122 characters truncated) ... ,0.03653669,-0.00070670,-0.03307657,0.07703535,-0.01762371,-0.01540658,0.03883591,-0.05737233,0.02075332,0.05934902,0.06073153,0.06037147,0.03859269]', 'user_id': '2f389a97-b36f-4200-aba2-d204dd1d7de7', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8629, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:57,258 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,260 INFO sqlalchemy.engine.Engine [cached since 5.461s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.461s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.8629)
INFO:dataset-notebook:Utworzono profil objawów dla test0025@zebra.pl

2026-03-12 18:23:57,294 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,295 INFO sqlalchemy.engine.Engine [cached since 6.414s ago] {'user_id_1': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.414s ago] {'user_id_1': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:57,324 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:57,325 INFO sqlalchemy.engine.Engine [cached since 6.41s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 6.41s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user 2f389a97-b36f-4200-aba2-d204dd1d7de7 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:57,353 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:57,354 INFO sqlalchemy.engine.Engine [cached since 6.402s ago] {'user_id': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 6.402s ago] {'user_id': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:57,384 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:57,385 INFO sqlalchemy.engine.Engine [cached since 6.4s ago] {'id': UUID('14e1bf54-4a26-402f-89f7-5b50454429c4'), 'user_id': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'description': 'Syn od małego miał trudności z utrzymaniem równowagi. Nawet teraz często się przewraca bez wyraźnego powodu.', 'embedding': '[0.021286407485604286,0.022146137431263924,0.025423754006624222,0.015522862784564495,-0.029466427862644196,0.022526239976286888,-0.059469420462846756 ... (7723 characters truncated) ... 8305,0.038835905492305756,-0.0573723278939724,0.020753318443894386,0.059349022805690765,0.06073153018951416,0.06037146598100662,0.038592688739299774]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.862882069521075}

INFO:sqlalchemy.engine.Engine:[cached since 6.4s ago] {'id': UUID('14e1bf54-4a26-402f-89f7-5b50454429c4'), 'user_id': UUID('2f389a97-b36f-4200-aba2-d204dd1d7de7'), 'description': 'Syn od małego miał trudności z utrzymaniem równowagi. Nawet teraz często się przewraca bez wyraźnego powodu.', 'embedding': '[0.021286407485604286,0.022146137431263924,0.025423754006624222,0.015522862784564495,-0.029466427862644196,0.022526239976286888,-0.059469420462846756 ... (7723 characters truncated) ... 8305,0.038835905492305756,-0.0573723278939724,0.020753318443894386,0.059349022805690765,0.06073153018951416,0.06037146598100662,0.038592688739299774]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.862882069521075}

2026-03-12 18:23:57,417 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:57,418 INFO sqlalchemy.engine.Engine [cached since 55.6s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 55.6s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

2026-03-12 18:23:57,446 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,447 INFO sqlalchemy.engine.Engine [cached since 11.6s ago] {'user_id_1': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.6s ago] {'user_id_1': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'param_1': 1}

2026-03-12 18:23:57,478 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,478 INFO sqlalchemy.engine.Engine [cached since 11.63s ago] {'user_id_1': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.63s ago] {'user_id_1': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'param_1': 1}

2026-03-12 18:23:57,516 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:57,517 INFO sqlalchemy.engine.Engine [cached since 6.732s ago] {'embedding': '[0.02563283,-0.00708231,0.02807124,0.05348949,0.01676046,-0.03376587,-0.02741249,0.00455371,0.02974730,-0.00456056,0.07170791,0.07958625,-0.10019911, ... (4114 characters truncated) ... .00504139,-0.03697906,-0.04458899,-0.00168616,0.00232169,-0.08841027,-0.06558406,-0.05576925,0.01586567,0.06311198,0.03085253,-0.01728966,0.06425573]', 'user_id': '4884429a-d5a3-49ef-b4e5-253f62888991', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 6.732s ago] {'embedding': '[0.02563283,-0.00708231,0.02807124,0.05348949,0.01676046,-0.03376587,-0.02741249,0.00455371,0.02974730,-0.00456056,0.07170791,0.07958625,-0.10019911, ... (4114 characters truncated) ... .00504139,-0.03697906,-0.04458899,-0.00168616,0.00232169,-0.08841027,-0.06558406,-0.05576925,0.01586567,0.06311198,0.03085253,-0.01728966,0.06425573]', 'user_id': '4884429a-d5a3-49ef-b4e5-253f62888991', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8270, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:57,547 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,548 INFO sqlalchemy.engine.Engine [cached since 5.749s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.749s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.8270)
INFO:dataset-notebook:Utworzono profil objawów dla test0026@zebra.pl

2026-03-12 18:23:57,579 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,580 INFO sqlalchemy.engine.Engine [cached since 6.7s ago] {'user_id_1': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.7s ago] {'user_id_1': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:57,611 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:57,612 INFO sqlalchemy.engine.Engine [cached since 6.697s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 6.697s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user 4884429a-d5a3-49ef-b4e5-253f62888991 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:57,643 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:57,645 INFO sqlalchemy.engine.Engine [cached since 6.693s ago] {'user_id': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 6.693s ago] {'user_id': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:57,674 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:57,675 INFO sqlalchemy.engine.Engine [cached since 6.689s ago] {'id': UUID('243e9818-c8f9-4181-b97b-bb93f310b3f9'), 'user_id': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'description': 'Nasze dziecko ma bardzo wysokie podbicie stóp i nietypowy sposób chodzenia. Często skarży się też na bóle nóg.', 'embedding': '[0.02563282661139965,-0.007082308176904917,0.028071235865354538,0.05348948761820793,0.016760462895035744,-0.033765874803066254,-0.027412494644522667, ... (7761 characters truncated) ... 73245,-0.06558405607938766,-0.05576925352215767,0.015865670517086983,0.06311198323965073,0.030852532014250755,-0.0172896571457386,0.0642557293176651]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.826977133750916}

INFO:sqlalchemy.engine.Engine:[cached since 6.689s ago] {'id': UUID('243e9818-c8f9-4181-b97b-bb93f310b3f9'), 'user_id': UUID('4884429a-d5a3-49ef-b4e5-253f62888991'), 'description': 'Nasze dziecko ma bardzo wysokie podbicie stóp i nietypowy sposób chodzenia. Często skarży się też na bóle nóg.', 'embedding': '[0.02563282661139965,-0.007082308176904917,0.028071235865354538,0.05348948761820793,0.016760462895035744,-0.033765874803066254,-0.027412494644522667, ... (7761 characters truncated) ... 73245,-0.06558405607938766,-0.05576925352215767,0.015865670517086983,0.06311198323965073,0.030852532014250755,-0.0172896571457386,0.0642557293176651]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.826977133750916}

2026-03-12 18:23:57,707 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:57,708 INFO sqlalchemy.engine.Engine [cached since 55.89s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 55.89s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

2026-03-12 18:23:57,738 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,739 INFO sqlalchemy.engine.Engine [cached since 11.89s ago] {'user_id_1': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.89s ago] {'user_id_1': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'param_1': 1}

2026-03-12 18:23:57,770 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,771 INFO sqlalchemy.engine.Engine [cached since 11.92s ago] {'user_id_1': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.92s ago] {'user_id_1': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'param_1': 1}

2026-03-12 18:23:57,813 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:57,814 INFO sqlalchemy.engine.Engine [cached since 7.029s ago] {'embedding': '[0.01335831,-0.00793532,-0.00166413,0.16073908,0.04493880,0.05321841,0.03189824,0.02730006,0.05400142,0.00619524,-0.03482692,-0.02658239,-0.09876566, ... (4123 characters truncated) ... ,0.02952432,0.01812623,-0.04458192,-0.02687005,0.02164253,0.03197503,0.01198954,0.00216119,0.00947266,-0.02402181,-0.02401546,0.03252518,-0.05780312]', 'user_id': 'a13af735-b70e-430a-ad01-d9c09f39b340', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.029s ago] {'embedding': '[0.01335831,-0.00793532,-0.00166413,0.16073908,0.04493880,0.05321841,0.03189824,0.02730006,0.05400142,0.00619524,-0.03482692,-0.02658239,-0.09876566, ... (4123 characters truncated) ... ,0.02952432,0.01812623,-0.04458192,-0.02687005,0.02164253,0.03197503,0.01198954,0.00216119,0.00947266,-0.02402181,-0.02401546,0.03252518,-0.05780312]', 'user_id': 'a13af735-b70e-430a-ad01-d9c09f39b340', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5761, group_id=cb092a24-2831-48f5-b35f-7add54e19d6b
INFO:app.services.matching_service:Score 0.5761 < threshold 0.72 — nowa grupa

2026-03-12 18:23:57,847 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:57,848 INFO sqlalchemy.engine.Engine [cached since 7.004s ago] {'id': UUID('7836116a-3678-4346-b347-f1319d70885b'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 7.004s ago] {'id': UUID('7836116a-3678-4346-b347-f1319d70885b'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 7836116a-3678-4346-b347-f1319d70885b
INFO:dataset-notebook:Utworzono profil objawów dla test0027@zebra.pl

2026-03-12 18:23:57,880 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:57,881 INFO sqlalchemy.engine.Engine [cached since 7s ago] {'user_id_1': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'group_id_1': '7836116a-3678-4346-b347-f1319d70885b', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7s ago] {'user_id_1': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'group_id_1': '7836116a-3678-4346-b347-f1319d70885b', 'param_1': 1}

2026-03-12 18:23:57,911 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:57,913 INFO sqlalchemy.engine.Engine [cached since 6.998s ago] {'member_count_1': 1, 'id_1': '7836116a-3678-4346-b347-f1319d70885b'}

INFO:sqlalchemy.engine.Engine:[cached since 6.998s ago] {'member_count_1': 1, 'id_1': '7836116a-3678-4346-b347-f1319d70885b'}
INFO:app.services.matching_service:Dodano user a13af735-b70e-430a-ad01-d9c09f39b340 do grupy 7836116a-3678-4346-b347-f1319d70885b

2026-03-12 18:23:57,943 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:57,944 INFO sqlalchemy.engine.Engine [cached since 6.992s ago] {'user_id': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'group_id': '7836116a-3678-4346-b347-f1319d70885b'}

INFO:sqlalchemy.engine.Engine:[cached since 6.992s ago] {'user_id': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'group_id': '7836116a-3678-4346-b347-f1319d70885b'}

2026-03-12 18:23:57,974 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:57,975 INFO sqlalchemy.engine.Engine [cached since 6.99s ago] {'id': UUID('51207804-d182-4a7f-826c-5be30780fc66'), 'user_id': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'description': 'Córka od urodzenia ma problemy z oddychaniem podczas snu. Często budzi się w nocy i jest bardzo zmęczona w ciągu dnia.', 'embedding': '[0.013358313590288162,-0.007935317233204842,-0.0016641333932057023,0.16073907911777496,0.044938795268535614,0.05321840941905975,0.031898241490125656, ... (7743 characters truncated) ... 0.011989538557827473,0.0021611948031932116,0.009472662582993507,-0.024021806195378304,-0.024015456438064575,0.03252518177032471,-0.05780312046408653]', 'group_id': '7836116a-3678-4346-b347-f1319d70885b', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 6.99s ago] {'id': UUID('51207804-d182-4a7f-826c-5be30780fc66'), 'user_id': UUID('a13af735-b70e-430a-ad01-d9c09f39b340'), 'description': 'Córka od urodzenia ma problemy z oddychaniem podczas snu. Często budzi się w nocy i jest bardzo zmęczona w ciągu dnia.', 'embedding': '[0.013358313590288162,-0.007935317233204842,-0.0016641333932057023,0.16073907911777496,0.044938795268535614,0.05321840941905975,0.031898241490125656, ... (7743 characters truncated) ... 0.011989538557827473,0.0021611948031932116,0.009472662582993507,-0.024021806195378304,-0.024015456438064575,0.03252518177032471,-0.05780312046408653]', 'group_id': '7836116a-3678-4346-b347-f1319d70885b', 'match_score': 0.0}

2026-03-12 18:23:58,007 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:58,008 INFO sqlalchemy.engine.Engine [cached since 56.19s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 56.19s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

2026-03-12 18:23:58,037 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,038 INFO sqlalchemy.engine.Engine [cached since 12.19s ago] {'user_id_1': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.19s ago] {'user_id_1': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'param_1': 1}

2026-03-12 18:23:58,070 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,071 INFO sqlalchemy.engine.Engine [cached since 12.22s ago] {'user_id_1': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.22s ago] {'user_id_1': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'param_1': 1}

2026-03-12 18:23:58,113 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:58,114 INFO sqlalchemy.engine.Engine [cached since 7.329s ago] {'embedding': '[0.01685104,-0.01106608,0.05569014,0.04483961,-0.02937247,-0.02580776,0.00791708,0.00445086,0.02262718,0.01351362,0.06707018,0.10776126,-0.07474469,0 ... (4116 characters truncated) ... 63,0.03752411,0.01292058,-0.03561295,0.07150262,0.03683193,-0.01148808,0.01510019,-0.03985498,0.04711135,0.05270528,0.09393539,0.00243185,0.06528758]', 'user_id': 'dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.329s ago] {'embedding': '[0.01685104,-0.01106608,0.05569014,0.04483961,-0.02937247,-0.02580776,0.00791708,0.00445086,0.02262718,0.01351362,0.06707018,0.10776126,-0.07474469,0 ... (4116 characters truncated) ... 63,0.03752411,0.01292058,-0.03561295,0.07150262,0.03683193,-0.01148808,0.01510019,-0.03985498,0.04711135,0.05270528,0.09393539,0.00243185,0.06528758]', 'user_id': 'dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7621, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:58,146 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,147 INFO sqlalchemy.engine.Engine [cached since 6.348s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.348s ago] {'id_1': UUID('2d2a759b-f914-4b1f-925e-f11e72c3585a'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7621)
INFO:dataset-notebook:Utworzono profil objawów dla test0028@zebra.pl

2026-03-12 18:23:58,178 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,179 INFO sqlalchemy.engine.Engine [cached since 7.298s ago] {'user_id_1': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.298s ago] {'user_id_1': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'group_id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'param_1': 1}

2026-03-12 18:23:58,210 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:58,212 INFO sqlalchemy.engine.Engine [cached since 7.297s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 7.297s ago] {'member_count_1': 1, 'id_1': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}
INFO:app.services.matching_service:Dodano user dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2 do grupy 2d2a759b-f914-4b1f-925e-f11e72c3585a

2026-03-12 18:23:58,242 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:58,242 INFO sqlalchemy.engine.Engine [cached since 7.29s ago] {'user_id': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

INFO:sqlalchemy.engine.Engine:[cached since 7.29s ago] {'user_id': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a'}

2026-03-12 18:23:58,272 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:58,273 INFO sqlalchemy.engine.Engine [cached since 7.288s ago] {'id': UUID('9bd54178-5bc3-4494-aee3-04454ccaf95f'), 'user_id': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'description': 'Syn ma trudności z kontrolą ruchów rąk. Czasami pojawiają się mimowolne ruchy, których nie potrafi zatrzymać.', 'embedding': '[0.016851037740707397,-0.011066083796322346,0.05569013953208923,0.044839613139629364,-0.02937247045338154,-0.025807755067944527,0.007917080074548721, ... (7745 characters truncated) ... 19238,0.015100188553333282,-0.0398549847304821,0.047111351042985916,0.05270528048276901,0.09393538534641266,0.002431847620755434,0.06528757512569427]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.762093887453908}

INFO:sqlalchemy.engine.Engine:[cached since 7.288s ago] {'id': UUID('9bd54178-5bc3-4494-aee3-04454ccaf95f'), 'user_id': UUID('dfbff6dd-7f9f-4af3-9bb1-4bee90deadb2'), 'description': 'Syn ma trudności z kontrolą ruchów rąk. Czasami pojawiają się mimowolne ruchy, których nie potrafi zatrzymać.', 'embedding': '[0.016851037740707397,-0.011066083796322346,0.05569013953208923,0.044839613139629364,-0.02937247045338154,-0.025807755067944527,0.007917080074548721, ... (7745 characters truncated) ... 19238,0.015100188553333282,-0.0398549847304821,0.047111351042985916,0.05270528048276901,0.09393538534641266,0.002431847620755434,0.06528757512569427]', 'group_id': '2d2a759b-f914-4b1f-925e-f11e72c3585a', 'match_score': 0.762093887453908}

2026-03-12 18:23:58,306 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:58,307 INFO sqlalchemy.engine.Engine [cached since 56.49s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 56.49s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

2026-03-12 18:23:58,337 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,338 INFO sqlalchemy.engine.Engine [cached since 12.49s ago] {'user_id_1': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.49s ago] {'user_id_1': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'param_1': 1}

2026-03-12 18:23:58,368 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,370 INFO sqlalchemy.engine.Engine [cached since 12.52s ago] {'user_id_1': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.52s ago] {'user_id_1': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'param_1': 1}

2026-03-12 18:23:58,411 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:58,412 INFO sqlalchemy.engine.Engine [cached since 7.627s ago] {'embedding': '[0.06847957,0.02291247,0.04036281,0.05222930,-0.00772258,0.07978035,-0.03672556,0.02019346,0.01219581,-0.01494820,-0.00346324,0.01492727,-0.04724448, ... (4113 characters truncated) ... 242,0.02560424,0.00605563,0.01289658,0.01440664,0.02500080,0.01531588,0.05111583,-0.01813028,0.01613093,0.05466235,0.03824419,0.02656125,-0.00340922]', 'user_id': '3abeccf8-ad40-43d4-9062-7a4a1c9a8eab', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.627s ago] {'embedding': '[0.06847957,0.02291247,0.04036281,0.05222930,-0.00772258,0.07978035,-0.03672556,0.02019346,0.01219581,-0.01494820,-0.00346324,0.01492727,-0.04724448, ... (4113 characters truncated) ... 242,0.02560424,0.00605563,0.01289658,0.01440664,0.02500080,0.01531588,0.05111583,-0.01813028,0.01613093,0.05466235,0.03824419,0.02656125,-0.00340922]', 'user_id': '3abeccf8-ad40-43d4-9062-7a4a1c9a8eab', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6823, group_id=2d2a759b-f914-4b1f-925e-f11e72c3585a
INFO:app.services.matching_service:Score 0.6823 < threshold 0.72 — nowa grupa

2026-03-12 18:23:58,446 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s) RETURNING groups.created_at, groups.updated_at

2026-03-12 18:23:58,447 INFO sqlalchemy.engine.Engine [cached since 7.603s ago] {'id': UUID('6c19d249-d587-4ae0-a7cb-216551c5d268'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}

INFO:sqlalchemy.engine.Engine:[cached since 7.603s ago] {'id': UUID('6c19d249-d587-4ae0-a7cb-216551c5d268'), 'name': 'Nowa grupa — oczekuje na dopasowania', 'description': 'Grupa tymczasowa. Zostanie nazwana gdy zbierze więcej członków.', 'cluster_id': None, 'is_active': True, 'member_count': 0}
INFO:app.services.matching_service:Utworzono nową grupę: 6c19d249-d587-4ae0-a7cb-216551c5d268
INFO:dataset-notebook:Utworzono profil objawów dla test0029@zebra.pl

2026-03-12 18:23:58,479 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,480 INFO sqlalchemy.engine.Engine [cached since 7.599s ago] {'user_id_1': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'group_id_1': '6c19d249-d587-4ae0-a7cb-216551c5d268', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.599s ago] {'user_id_1': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'group_id_1': '6c19d249-d587-4ae0-a7cb-216551c5d268', 'param_1': 1}

2026-03-12 18:23:58,509 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:58,511 INFO sqlalchemy.engine.Engine [cached since 7.596s ago] {'member_count_1': 1, 'id_1': '6c19d249-d587-4ae0-a7cb-216551c5d268'}

INFO:sqlalchemy.engine.Engine:[cached since 7.596s ago] {'member_count_1': 1, 'id_1': '6c19d249-d587-4ae0-a7cb-216551c5d268'}
INFO:app.services.matching_service:Dodano user 3abeccf8-ad40-43d4-9062-7a4a1c9a8eab do grupy 6c19d249-d587-4ae0-a7cb-216551c5d268

2026-03-12 18:23:58,542 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:58,543 INFO sqlalchemy.engine.Engine [cached since 7.591s ago] {'user_id': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'group_id': '6c19d249-d587-4ae0-a7cb-216551c5d268'}

INFO:sqlalchemy.engine.Engine:[cached since 7.591s ago] {'user_id': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'group_id': '6c19d249-d587-4ae0-a7cb-216551c5d268'}

2026-03-12 18:23:58,573 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:58,574 INFO sqlalchemy.engine.Engine [cached since 7.588s ago] {'id': UUID('a7b13566-ade6-4205-b66e-39de3fd17390'), 'user_id': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'description': 'Nasze dziecko ma bardzo niską tolerancję na wysiłek. Po krótkiej zabawie musi długo odpoczywać. Często jest zmęczone.', 'embedding': '[0.06847956776618958,0.02291247248649597,0.04036281257867813,0.052229300141334534,-0.007722578942775726,0.07978034764528275,-0.03672555834054947,0.02 ... (7746 characters truncated) ... 8,0.05111582949757576,-0.018130281940102577,0.016130927950143814,0.05466235429048538,0.03824419155716896,0.026561252772808075,-0.0034092217683792114]', 'group_id': '6c19d249-d587-4ae0-a7cb-216551c5d268', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 7.588s ago] {'id': UUID('a7b13566-ade6-4205-b66e-39de3fd17390'), 'user_id': UUID('3abeccf8-ad40-43d4-9062-7a4a1c9a8eab'), 'description': 'Nasze dziecko ma bardzo niską tolerancję na wysiłek. Po krótkiej zabawie musi długo odpoczywać. Często jest zmęczone.', 'embedding': '[0.06847956776618958,0.02291247248649597,0.04036281257867813,0.052229300141334534,-0.007722578942775726,0.07978034764528275,-0.03672555834054947,0.02 ... (7746 characters truncated) ... 8,0.05111582949757576,-0.018130281940102577,0.016130927950143814,0.05466235429048538,0.03824419155716896,0.026561252772808075,-0.0034092217683792114]', 'group_id': '6c19d249-d587-4ae0-a7cb-216551c5d268', 'match_score': 0.0}

2026-03-12 18:23:58,605 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-12 18:23:58,606 INFO sqlalchemy.engine.Engine [cached since 56.79s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 56.79s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

2026-03-12 18:23:58,637 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,639 INFO sqlalchemy.engine.Engine [cached since 12.79s ago] {'user_id_1': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.79s ago] {'user_id_1': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'param_1': 1}

2026-03-12 18:23:58,669 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,670 INFO sqlalchemy.engine.Engine [cached since 12.82s ago] {'user_id_1': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.82s ago] {'user_id_1': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'param_1': 1}

2026-03-12 18:23:58,721 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-12 18:23:58,723 INFO sqlalchemy.engine.Engine [cached since 7.938s ago] {'embedding': '[0.06316517,-0.00194938,0.03590529,0.05773227,-0.05324123,0.00328636,-0.04048978,0.02262559,0.07954863,-0.04414425,0.01418231,0.12773399,-0.01734386, ... (4123 characters truncated) ... 73,0.03138115,-0.04212645,0.03658512,0.04799293,0.04513753,0.00904396,0.02689574,-0.05071231,0.03528808,0.03273147,0.07506852,0.00290412,-0.00741978]', 'user_id': 'a0be9ef9-5920-45ca-8cef-769a8e12ec70', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.938s ago] {'embedding': '[0.06316517,-0.00194938,0.03590529,0.05773227,-0.05324123,0.00328636,-0.04048978,0.02262559,0.07954863,-0.04414425,0.01418231,0.12773399,-0.01734386, ... (4123 characters truncated) ... 73,0.03138115,-0.04212645,0.03658512,0.04799293,0.04513753,0.00904396,0.02689574,-0.05071231,0.03528808,0.03273147,0.07506852,0.00290412,-0.00741978]', 'user_id': 'a0be9ef9-5920-45ca-8cef-769a8e12ec70', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7476, group_id=29938bd3-d18f-49a2-83c1-697340b25a31

2026-03-12 18:23:58,754 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,755 INFO sqlalchemy.engine.Engine [cached since 6.955s ago] {'id_1': UUID('29938bd3-d18f-49a2-83c1-697340b25a31'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.955s ago] {'id_1': UUID('29938bd3-d18f-49a2-83c1-697340b25a31'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Nowa grupa — oczekuje na dopasowania' (score=0.7476)
INFO:dataset-notebook:Utworzono profil objawów dla test0030@zebra.pl

2026-03-12 18:23:58,786 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-12 18:23:58,787 INFO sqlalchemy.engine.Engine [cached since 7.907s ago] {'user_id_1': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'group_id_1': '29938bd3-d18f-49a2-83c1-697340b25a31', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.907s ago] {'user_id_1': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'group_id_1': '29938bd3-d18f-49a2-83c1-697340b25a31', 'param_1': 1}

2026-03-12 18:23:58,818 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-12 18:23:58,819 INFO sqlalchemy.engine.Engine [cached since 7.904s ago] {'member_count_1': 1, 'id_1': '29938bd3-d18f-49a2-83c1-697340b25a31'}

INFO:sqlalchemy.engine.Engine:[cached since 7.904s ago] {'member_count_1': 1, 'id_1': '29938bd3-d18f-49a2-83c1-697340b25a31'}
INFO:app.services.matching_service:Dodano user a0be9ef9-5920-45ca-8cef-769a8e12ec70 do grupy 29938bd3-d18f-49a2-83c1-697340b25a31

2026-03-12 18:23:58,850 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-12 18:23:58,851 INFO sqlalchemy.engine.Engine [cached since 7.899s ago] {'user_id': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31'}

INFO:sqlalchemy.engine.Engine:[cached since 7.899s ago] {'user_id': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31'}

2026-03-12 18:23:58,881 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-12 18:23:58,882 INFO sqlalchemy.engine.Engine [cached since 7.897s ago] {'id': UUID('cfa7d648-9257-4254-877b-d0b3af07a294'), 'user_id': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'description': 'Córka rozwijała się dobrze przez pierwsze lata, ale w ostatnim czasie zauważyliśmy pogorszenie pamięci i koncentracji. Zaczęła też mieć trudności z mówieniem.', 'embedding': '[0.06316517293453217,-0.001949384342879057,0.03590528666973114,0.057732272893190384,-0.05324122682213783,0.0032863644883036613,-0.04048977792263031,0 ... (7742 characters truncated) ... 58,0.02689574472606182,-0.050712306052446365,0.03528808429837227,0.03273146599531174,0.07506851851940155,0.0029041199013590813,-0.007419778499752283]', 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31', 'match_score': 0.747617207396552}

INFO:sqlalchemy.engine.Engine:[cached since 7.897s ago] {'id': UUID('cfa7d648-9257-4254-877b-d0b3af07a294'), 'user_id': UUID('a0be9ef9-5920-45ca-8cef-769a8e12ec70'), 'description': 'Córka rozwijała się dobrze przez pierwsze lata, ale w ostatnim czasie zauważyliśmy pogorszenie pamięci i koncentracji. Zaczęła też mieć trudności z mówieniem.', 'embedding': '[0.06316517293453217,-0.001949384342879057,0.03590528666973114,0.057732272893190384,-0.05324122682213783,0.0032863644883036613,-0.04048977792263031,0 ... (7742 characters truncated) ... 58,0.02689574472606182,-0.050712306052446365,0.03528808429837227,0.03273146599531174,0.07506851851940155,0.0029041199013590813,-0.007419778499752283]', 'group_id': '29938bd3-d18f-49a2-83c1-697340b25a31', 'match_score': 0.747617207396552}

2026-03-12 18:23:58,913 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

Nowo utworzonych profili objawów: 27
Zaktualizowanych profili objawów: 0

In [12]:
# Diagnostyka: liczba profili i rozkład po grupach

with get_db() as db:
    total_profiles = db.query(SymptomProfile).count()
    print(f"Liczba profili objawów w bazie: {total_profiles}")

    rows = (
        db.query(SymptomProfile.group_id)
        .all()
    )


group_ids = [row[0] for row in rows]
counts = Counter(group_ids)

print("\nRozkład liczby profili w grupach:")
for group_id, cnt in counts.items():
    print(f"  grupa={group_id}: {cnt} profili")

2026-03-12 18:24:56,359 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-12 18:24:56,361 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles) AS anon_1

INFO:sqlalchemy.engine.Engine:SELECT count(*) AS count_1
FROM (SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles) AS anon_1

2026-03-12 18:24:56,362 INFO sqlalchemy.engine.Engine [cached since 12.81s ago] {}

INFO:sqlalchemy.engine.Engine:[cached since 12.81s ago] {}

Liczba profili objawów w bazie: 31
2026-03-12 18:24:56,418 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.group_id AS symptom_profiles_group_id
FROM symptom_profiles

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.group_id AS symptom_profiles_group_id
FROM symptom_profiles

2026-03-12 18:24:56,419 INFO sqlalchemy.engine.Engine [cached since 12.81s ago] {}

INFO:sqlalchemy.engine.Engine:[cached since 12.81s ago] {}

2026-03-12 18:24:56,446 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

Rozkład liczby profili w grupach:
  grupa=66204af3-89e7-4ec6-838e-0fcd7e54e4c7: 2 profili
  grupa=2d2a759b-f914-4b1f-925e-f11e72c3585a: 10 profili
  grupa=cb092a24-2831-48f5-b35f-7add54e19d6b: 4 profili
  grupa=13b24b56-7537-41b2-b484-fa811047b471: 1 profili
  grupa=81673b39-a3a1-4a66-8e03-c6ace83cdf6b: 1 profili
  grupa=52430a0b-05ed-41fb-8c80-6390c23cd7bd: 2 profili
  grupa=d08e312f-e27d-4546-ad2b-aee50f883b60: 1 profili
  grupa=55c850c8-071d-4f86-a619-16e010387f42: 1 profili
  grupa=708a6370-ea74-4374-a698-5adad01af45a: 1 profili
  grupa=75f17305-fcd8-4ee6-a2bf-d80329866d08: 1 profili
  grupa=29938bd3-d18f-49a2-83c1-697340b25a31: 2 profili
  grupa=da9964cc-5ab7-40e8-8d34-dce853914c8f: 1 profili
  grupa=88e3bb48-85f0-4605-88f5-2253111c0785: 1 profili
  grupa=3d2f5bd7-90e7-4062-bb72-108b9c7f61bb: 1 profili
  grupa=7836116a-3678-4346-b347-f1319d70885b: 1 profili
  grupa=6c19d249-d587-4ae0-a7cb-216551c5d268: 1 profili

In [13]:
# Eksperyment ML: prosta klasteryzacja KMeans na embeddingach

from sklearn.cluster import KMeans

# Weźmy embeddingi dla opisów z JSON-a (bez czytania z bazy)
texts = [rec["description"] for rec in records]
embeddings = generate_embeddings_batch(texts)

X = np.array(embeddings)
print("Macierz embeddingów:", X.shape)

# Przy niewielkiej liczbie rekordów spróbujmy np. 3 klastry
n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init="auto")
cluster_labels = kmeans.fit_predict(X)

# Podgląd wyników w DataFrame
ml_df = pd.DataFrame(
    {
        "email": [rec["email"] for rec in records],
        "cluster": cluster_labels,
    }
)

display(ml_df.head())
print("\nLiczność klastrów:")
print(ml_df["cluster"].value_counts())

Batches: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]

Macierz embeddingów: (27, 384)

               email  cluster
0  test0004@zebra.pl        0
1  test0005@zebra.pl        2
2  test0006@zebra.pl        0
3  test0007@zebra.pl        1
4  test0008@zebra.pl        0

Liczność klastrów:
cluster
0    14
1     9
2     4
Name: count, dtype: int64

In [ ]:
def run_full_seed(dry_run: bool = False) -> None:
    """Wysokopoziomowa funkcja do ponownego uruchamiania całego seeda.

    Kroki:
    - wczytanie JSON,
    - stworzenie użytkowników,
    - stworzenie / aktualizacja profili objawów i dopasowanie grup.
    """
    global DRY_RUN, records
    DRY_RUN = dry_run

    # wczytaj dane
    records = load_dataset(DATA_PATH)
    logger.info("Start seeda. Rekordów: %d (DRY_RUN=%s)", len(records), DRY_RUN)

    created = 0
    existing = 0
    profiles_created = 0
    profiles_updated = 0

    with get_db() as db:
        for rec in records:
            # użytkownik
            user_before = db.query(User).filter(User.email == rec["email"]).first()
            user = create_user_from_record(db, rec)
            if user_before is None:
                created += 1
            else:
                existing += 1

            # profil objawów
            existing_profile = (
                db.query(SymptomProfile)
                .filter(SymptomProfile.user_id == user.id)
                .first()
            )
            profile = create_or_update_symptom_profile(db, user, rec["description"])
            if existing_profile is None:
                profiles_created += 1
            else:
                profiles_updated += 1

        if DRY_RUN:
            logger.info("DRY_RUN=True — wykonuję rollback zmian")
            db.rollback()
        else:
            logger.info("Zatwierdzam zmiany w bazie")

    print("Seed zakończony:\n")
    print(f"  Nowo utworzonych użytkowników: {created}")
    print(f"  Użytkownicy już istniejący:   {existing}")
    print(f"  Nowo utworzonych profili:     {profiles_created}")
    print(f"  Zaktualizowanych profili:     {profiles_updated}")


# Przykład użycia:
# run_full_seed(dry_run=True)  # test bez zapisywania do bazy
# run_full_seed(dry_run=False) # realny seed do bazy