In [1]:
import os
import sys
import json
from pathlib import Path
from typing import Any, Dict, List, Optional
import logging

import numpy as np
import pandas as pd
from sqlalchemy.orm import Session

# konfiguracja logowania w notebooku
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("dataset-notebook")

# ustawienie ścieżki do backendu, żeby móc importować moduły app.*
PROJECT_ROOT = Path("..").resolve()
BACKEND_PATH = PROJECT_ROOT / "backend"
if str(BACKEND_PATH) not in sys.path:
    sys.path.insert(0, str(BACKEND_PATH))

from app.database import SessionLocal
from app.models.user import User
from app.models.symptom_profile import SymptomProfile
from app.services.embedding_service import generate_embedding, generate_embeddings_batch
from app.services.matching_service import find_matching_group, add_user_to_group
from app.services.group_characteristics import update_group_characteristics
from app.routers.auth import _hash_password

DATA_PATH = PROJECT_ROOT / "data" / "test_data.json"
DRY_RUN = False

/home/mario/miniconda3/envs/zebrapoint/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from contextlib import contextmanager
from collections import Counter


@contextmanager
def get_db() -> Session:
    """Kontekst menedżer na sesję DB (tak jak w backendzie, ale dla notebooka)."""
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def load_dataset(path: Path) -> List[Dict[str, Any]]:
    """Wczytuje testowy zbiór danych z JSON-a."""
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError("Plik JSON powinien zawierać listę obiektów")

    records: List[Dict[str, Any]] = []
    for idx, raw in enumerate(data, start=1):
        email = raw.get("email")
        password = raw.get("haslo")
        description = raw.get("opis")
        display_name = raw.get("display_name")

        if not email or not password or not description:
            raise ValueError(f"Rekord {idx} ma brakujące pola (email/haslo/opis)")

        # display_name jest wymagany zgodnie z planem; jeśli go nie ma,
        # można doraźnie użyć prefiksu z emaila.
        if not display_name:
            display_name = email.split("@")[0]

        description = str(description).strip()
        if len(description) < 100:
            raise ValueError(
                f"Opis w rekordzie {idx} jest za krótki ({len(description)} znaków). "
                "Potrzebne >= 100 znaków."
            )

        rec = {
            "email": str(email).strip(),
            "password": str(password),
            "display_name": str(display_name).strip(),
            "description": description,
        }
        if raw.get("age_range") is not None:
            rec["age_range"] = str(raw["age_range"]).strip()
        records.append(rec)

    logger.info("Wczytano %d rekordów z %s", len(records), path)
    return records


def create_user_from_record(db: Session, record: Dict[str, Any]) -> User:
    """Tworzy użytkownika na podstawie rekordu z JSON-a albo zwraca istniejącego."""
    email = record["email"]
    display_name = record["display_name"]
    password = record["password"]

    user = db.query(User).filter(User.email == email).first()
    if user:
        logger.info("Użytkownik %s już istnieje — pomijam tworzenie", email)
        return user

    user = User(
        email=email,
        password_hash=_hash_password(password),
        display_name=display_name,
    )
    if record.get("age_range") is not None:
        user.age_range = record.get("age_range")
    db.add(user)
    db.flush()
    logger.info("Utworzono użytkownika %s", email)
    return user


def create_or_update_symptom_profile(
    db: Session,
    user: User,
    description: str,
) -> SymptomProfile:
    """Tworzy lub aktualizuje profil objawów i dopasowuje grupę."""
    profile = (
        db.query(SymptomProfile)
        .filter(SymptomProfile.user_id == user.id)
        .first()
    )

    embedding = generate_embedding(description)
    match = find_matching_group(db, embedding, user.id)
    group_id = match["group_id"]

    if profile is None:
        profile = SymptomProfile(
            user_id=user.id,
            description=description,
            embedding=embedding,
            group_id=group_id,
            match_score=match["score"],
        )
        db.add(profile)
        logger.info("Utworzono profil objawów dla %s", user.email)
    else:
        profile.description = description
        profile.embedding = embedding
        profile.group_id = group_id
        profile.match_score = match["score"]
        logger.info("Zaktualizowano profil objawów dla %s", user.email)

    add_user_to_group(db, user.id, group_id)

    db.flush()
    return profile

In [3]:
# Test połączenia z bazą Supabase

with get_db() as db:
    try:
        user_count = db.query(User).count()
        print(f"Połączenie OK. Liczba użytkowników w bazie: {user_count}")
    except Exception as exc:
        print("Błąd połączenia z bazą:", exc)
        raise

/tmp/ipykernel_45274/2424083691.py:5: SAWarning: relationship 'Comment.reactions' will copy column comments.id to column reactions.target_id, which conflicts with relationship(s): 'Post.reactions' (copies posts.id to reactions.target_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="reactions"' to the 'Comment.reactions' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
  user_count = db.query(User).count()

2026-03-14 20:47:06,500 INFO sqlalchemy.engine.Engine select pg_catalog.version()

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()

2026-03-14 20:47:06,501 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2026-03-14 20:47:06,563 INFO sqlalchemy.engine.Engine select current_schema()

INFO:sqlalchemy.engine.Engine:select current_schema()

2026-03-14 20:47:06,564 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2026-03-14 20:47:06,626 INFO sqlalchemy.engine.Engine show standard_conforming_strings

INFO:sqlalchemy.engine.Engine:show standard_conforming_strings

2026-03-14 20:47:06,627 INFO sqlalchemy.engine.Engine [raw sql] {}

INFO:sqlalchemy.engine.Engine:[raw sql] {}

2026-03-14 20:47:06,690 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:47:06,696 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users) AS anon_1

INFO:sqlalchemy.engine.Engine:SELECT count(*) AS count_1
FROM (SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users) AS anon_1

2026-03-14 20:47:06,697 INFO sqlalchemy.engine.Engine [generated in 0.00096s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00096s] {}

Połączenie OK. Liczba użytkowników w bazie: 0
2026-03-14 20:47:06,769 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

In [4]:
# Wczytanie danych z JSON i podgląd struktury

records = load_dataset(DATA_PATH)
print(f"Liczba rekordów w zbiorze: {len(records)}")

df_preview = pd.DataFrame(records)
df_preview.head()

INFO:dataset-notebook:Wczytano 40 rekordów z /home/mario/workspace/zebrapoint/data/test_data.json

Liczba rekordów w zbiorze: 40

,email,password,display_name,description
0,test0001@zebra.pl,test1234,Mama 1,Syn od urodzenia ma bardzo obniżone napięcie m...
1,test0002@zebra.pl,test1234,Mama 2,Córka ma zdiagnozowaną rzadką chorobę metaboli...
2,test0003@zebra.pl,test1234,Mama 3,"Nasze dziecko urodziło się z wadą serca, która..."
3,test0004@zebra.pl,test1234,Mama 4,Nasze dziecko urodziło się z bardzo niską masą...
4,test0005@zebra.pl,test1234,Mama 5,Od urodzenia zauważyliśmy u córki bardzo jasną...

In [5]:
# Utworzenie użytkowników w tabeli `users` na podstawie rekordów

created = 0
existing = 0

with get_db() as db:
    for rec in records:
        user_before = db.query(User).filter(User.email == rec["email"]).first()
        user = create_user_from_record(db, rec)
        if user_before is None:
            created += 1
        else:
            existing += 1

print(f"Nowo utworzonych użytkowników: {created}")
print(f"Użytkownicy już istniejący:   {existing}")

2026-03-14 20:47:27,190 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:47:27,194 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:27,195 INFO sqlalchemy.engine.Engine [generated in 0.00140s] {'email_1': 'test0001@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00140s] {'email_1': 'test0001@zebra.pl', 'param_1': 1}

2026-03-14 20:47:27,262 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:27,264 INFO sqlalchemy.engine.Engine [cached since 0.07053s ago] {'email_1': 'test0001@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.07053s ago] {'email_1': 'test0001@zebra.pl', 'param_1': 1}

2026-03-14 20:47:27,561 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:27,562 INFO sqlalchemy.engine.Engine [generated in 0.00132s] {'id': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'email': 'test0001@zebra.pl', 'password_hash': '$2b$12$9oT0UAa51UsvqQ5C0DNEZOCn1VhlIMDpBvVInQLpU7LXQbp81N8TW', 'display_name': 'Mama 1', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[generated in 0.00132s] {'id': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'email': 'test0001@zebra.pl', 'password_hash': '$2b$12$9oT0UAa51UsvqQ5C0DNEZOCn1VhlIMDpBvVInQLpU7LXQbp81N8TW', 'display_name': 'Mama 1', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0001@zebra.pl

2026-03-14 20:47:27,597 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:27,599 INFO sqlalchemy.engine.Engine [cached since 0.4054s ago] {'email_1': 'test0002@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.4054s ago] {'email_1': 'test0002@zebra.pl', 'param_1': 1}

2026-03-14 20:47:27,631 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:27,632 INFO sqlalchemy.engine.Engine [cached since 0.4387s ago] {'email_1': 'test0002@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.4387s ago] {'email_1': 'test0002@zebra.pl', 'param_1': 1}

2026-03-14 20:47:27,892 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:27,893 INFO sqlalchemy.engine.Engine [cached since 0.3319s ago] {'id': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'email': 'test0002@zebra.pl', 'password_hash': '$2b$12$gN.30GAycdTXykC9YR32Uu0P8V.wb3BOUrzZmJQfG9oGpojgNJznq', 'display_name': 'Mama 2', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 0.3319s ago] {'id': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'email': 'test0002@zebra.pl', 'password_hash': '$2b$12$gN.30GAycdTXykC9YR32Uu0P8V.wb3BOUrzZmJQfG9oGpojgNJznq', 'display_name': 'Mama 2', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0002@zebra.pl

2026-03-14 20:47:27,929 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:27,930 INFO sqlalchemy.engine.Engine [cached since 0.7366s ago] {'email_1': 'test0003@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.7366s ago] {'email_1': 'test0003@zebra.pl', 'param_1': 1}

2026-03-14 20:47:27,962 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:27,964 INFO sqlalchemy.engine.Engine [cached since 0.7704s ago] {'email_1': 'test0003@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.7704s ago] {'email_1': 'test0003@zebra.pl', 'param_1': 1}

2026-03-14 20:47:28,222 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:28,223 INFO sqlalchemy.engine.Engine [cached since 0.6626s ago] {'id': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'email': 'test0003@zebra.pl', 'password_hash': '$2b$12$42HIJYCc5EEF5OU.VGmL.ODIiXZzhB0FbNQTJqEpbP/1PUoc.skaq', 'display_name': 'Mama 3', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 0.6626s ago] {'id': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'email': 'test0003@zebra.pl', 'password_hash': '$2b$12$42HIJYCc5EEF5OU.VGmL.ODIiXZzhB0FbNQTJqEpbP/1PUoc.skaq', 'display_name': 'Mama 3', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0003@zebra.pl

2026-03-14 20:47:28,256 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:28,257 INFO sqlalchemy.engine.Engine [cached since 1.064s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.064s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

2026-03-14 20:47:28,288 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:28,290 INFO sqlalchemy.engine.Engine [cached since 1.096s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.096s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

2026-03-14 20:47:28,550 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:28,551 INFO sqlalchemy.engine.Engine [cached since 0.99s ago] {'id': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'email': 'test0004@zebra.pl', 'password_hash': '$2b$12$8lmCzDFz3AN5iL9UeJVw9ehsrBj46ybsqeTL5vJ/sc3HS86zJdvOq', 'display_name': 'Mama 4', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 0.99s ago] {'id': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'email': 'test0004@zebra.pl', 'password_hash': '$2b$12$8lmCzDFz3AN5iL9UeJVw9ehsrBj46ybsqeTL5vJ/sc3HS86zJdvOq', 'display_name': 'Mama 4', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0004@zebra.pl

2026-03-14 20:47:28,585 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:28,586 INFO sqlalchemy.engine.Engine [cached since 1.393s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.393s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

2026-03-14 20:47:28,618 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:28,619 INFO sqlalchemy.engine.Engine [cached since 1.426s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.426s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

2026-03-14 20:47:28,887 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:28,888 INFO sqlalchemy.engine.Engine [cached since 1.327s ago] {'id': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'email': 'test0005@zebra.pl', 'password_hash': '$2b$12$YdjRP2jaFihCdggD242kf.ORKUK6gFk5AV5gdDK6vApmgaftEUOne', 'display_name': 'Mama 5', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 1.327s ago] {'id': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'email': 'test0005@zebra.pl', 'password_hash': '$2b$12$YdjRP2jaFihCdggD242kf.ORKUK6gFk5AV5gdDK6vApmgaftEUOne', 'display_name': 'Mama 5', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0005@zebra.pl

2026-03-14 20:47:28,920 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:28,921 INFO sqlalchemy.engine.Engine [cached since 1.728s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.728s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

2026-03-14 20:47:28,956 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:28,957 INFO sqlalchemy.engine.Engine [cached since 1.763s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.763s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

2026-03-14 20:47:29,221 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:29,222 INFO sqlalchemy.engine.Engine [cached since 1.661s ago] {'id': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'email': 'test0006@zebra.pl', 'password_hash': '$2b$12$.AaFO80iyVG/BYXtyzHCfuVCF1vgOegp1cXJA6bjB2e5xvbhWw5di', 'display_name': 'Mama 6', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 1.661s ago] {'id': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'email': 'test0006@zebra.pl', 'password_hash': '$2b$12$.AaFO80iyVG/BYXtyzHCfuVCF1vgOegp1cXJA6bjB2e5xvbhWw5di', 'display_name': 'Mama 6', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0006@zebra.pl

2026-03-14 20:47:29,255 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:29,256 INFO sqlalchemy.engine.Engine [cached since 2.063s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.063s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

2026-03-14 20:47:29,287 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:29,288 INFO sqlalchemy.engine.Engine [cached since 2.095s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.095s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

2026-03-14 20:47:29,574 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:29,575 INFO sqlalchemy.engine.Engine [cached since 2.014s ago] {'id': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'email': 'test0007@zebra.pl', 'password_hash': '$2b$12$dt8.qPzPd6o0VUBMXdkWXeRoPAcD1QQ6pa3dD7vgB25VU5dWtbbwa', 'display_name': 'Mama 7', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.014s ago] {'id': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'email': 'test0007@zebra.pl', 'password_hash': '$2b$12$dt8.qPzPd6o0VUBMXdkWXeRoPAcD1QQ6pa3dD7vgB25VU5dWtbbwa', 'display_name': 'Mama 7', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0007@zebra.pl

2026-03-14 20:47:29,609 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:29,610 INFO sqlalchemy.engine.Engine [cached since 2.416s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.416s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

2026-03-14 20:47:29,641 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:29,642 INFO sqlalchemy.engine.Engine [cached since 2.449s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.449s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

2026-03-14 20:47:29,908 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:29,909 INFO sqlalchemy.engine.Engine [cached since 2.348s ago] {'id': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'email': 'test0008@zebra.pl', 'password_hash': '$2b$12$PDZGJyschAbOvlg9mCAcIO0ntpeXZcdJExypeGc7qaa7tPGm.PqYe', 'display_name': 'Mama 8', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.348s ago] {'id': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'email': 'test0008@zebra.pl', 'password_hash': '$2b$12$PDZGJyschAbOvlg9mCAcIO0ntpeXZcdJExypeGc7qaa7tPGm.PqYe', 'display_name': 'Mama 8', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0008@zebra.pl

2026-03-14 20:47:29,948 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:29,951 INFO sqlalchemy.engine.Engine [cached since 2.757s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.757s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

2026-03-14 20:47:29,990 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:29,993 INFO sqlalchemy.engine.Engine [cached since 2.8s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.8s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

2026-03-14 20:47:30,259 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:30,260 INFO sqlalchemy.engine.Engine [cached since 2.699s ago] {'id': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'email': 'test0009@zebra.pl', 'password_hash': '$2b$12$eHMoFyYeS8IomUHUi5Ddn.CtavMpPiGNiCn91KTWvUlAGilgy.Mp2', 'display_name': 'Mama 9', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 2.699s ago] {'id': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'email': 'test0009@zebra.pl', 'password_hash': '$2b$12$eHMoFyYeS8IomUHUi5Ddn.CtavMpPiGNiCn91KTWvUlAGilgy.Mp2', 'display_name': 'Mama 9', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0009@zebra.pl

2026-03-14 20:47:30,292 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:30,293 INFO sqlalchemy.engine.Engine [cached since 3.1s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.1s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

2026-03-14 20:47:30,327 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:30,328 INFO sqlalchemy.engine.Engine [cached since 3.135s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.135s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

2026-03-14 20:47:30,597 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:30,598 INFO sqlalchemy.engine.Engine [cached since 3.037s ago] {'id': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'email': 'test0010@zebra.pl', 'password_hash': '$2b$12$8RrwXMgqvlif75XGKhOxUuEL86FSOfZRdQe.T4xNuAjWo/CCJZ/eC', 'display_name': 'Mama 10', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 3.037s ago] {'id': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'email': 'test0010@zebra.pl', 'password_hash': '$2b$12$8RrwXMgqvlif75XGKhOxUuEL86FSOfZRdQe.T4xNuAjWo/CCJZ/eC', 'display_name': 'Mama 10', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0010@zebra.pl

2026-03-14 20:47:30,631 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:30,633 INFO sqlalchemy.engine.Engine [cached since 3.44s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.44s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

2026-03-14 20:47:30,665 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:30,667 INFO sqlalchemy.engine.Engine [cached since 3.473s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.473s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

2026-03-14 20:47:30,931 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:30,932 INFO sqlalchemy.engine.Engine [cached since 3.371s ago] {'id': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'email': 'test0011@zebra.pl', 'password_hash': '$2b$12$ygfNHuSogPmYfLRVj86jYeaT18lbZ4kMLXCrilNUAAkVA4oGASBIO', 'display_name': 'Mama 11', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 3.371s ago] {'id': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'email': 'test0011@zebra.pl', 'password_hash': '$2b$12$ygfNHuSogPmYfLRVj86jYeaT18lbZ4kMLXCrilNUAAkVA4oGASBIO', 'display_name': 'Mama 11', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0011@zebra.pl

2026-03-14 20:47:30,969 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:30,970 INFO sqlalchemy.engine.Engine [cached since 3.777s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.777s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

2026-03-14 20:47:31,002 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:31,003 INFO sqlalchemy.engine.Engine [cached since 3.81s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.81s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

2026-03-14 20:47:31,297 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:31,298 INFO sqlalchemy.engine.Engine [cached since 3.738s ago] {'id': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'email': 'test0012@zebra.pl', 'password_hash': '$2b$12$wcUbDCz7A2zirQeKEyKWb.H19MRzk9Rk8KwPAF.ClDbXJPksdK1SC', 'display_name': 'Mama 12', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 3.738s ago] {'id': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'email': 'test0012@zebra.pl', 'password_hash': '$2b$12$wcUbDCz7A2zirQeKEyKWb.H19MRzk9Rk8KwPAF.ClDbXJPksdK1SC', 'display_name': 'Mama 12', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0012@zebra.pl

2026-03-14 20:47:31,332 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:31,333 INFO sqlalchemy.engine.Engine [cached since 4.14s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.14s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

2026-03-14 20:47:31,363 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:31,365 INFO sqlalchemy.engine.Engine [cached since 4.171s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.171s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

2026-03-14 20:47:31,640 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:31,641 INFO sqlalchemy.engine.Engine [cached since 4.08s ago] {'id': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'email': 'test0013@zebra.pl', 'password_hash': '$2b$12$KjBYAac3oiUFYKQPmE.L2.JCpdbJt.PYLNZkZju/CnGeMFDvk6AE6', 'display_name': 'Mama 13', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 4.08s ago] {'id': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'email': 'test0013@zebra.pl', 'password_hash': '$2b$12$KjBYAac3oiUFYKQPmE.L2.JCpdbJt.PYLNZkZju/CnGeMFDvk6AE6', 'display_name': 'Mama 13', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0013@zebra.pl

2026-03-14 20:47:31,676 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:31,678 INFO sqlalchemy.engine.Engine [cached since 4.485s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.485s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

2026-03-14 20:47:31,709 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:31,711 INFO sqlalchemy.engine.Engine [cached since 4.517s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.517s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

2026-03-14 20:47:31,985 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:31,986 INFO sqlalchemy.engine.Engine [cached since 4.426s ago] {'id': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'email': 'test0014@zebra.pl', 'password_hash': '$2b$12$5ACKESinrcQ08TzskuHn7OsSuzm8E4fjshLOkkZL/N/EuhkWRAYP6', 'display_name': 'Mama 14', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 4.426s ago] {'id': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'email': 'test0014@zebra.pl', 'password_hash': '$2b$12$5ACKESinrcQ08TzskuHn7OsSuzm8E4fjshLOkkZL/N/EuhkWRAYP6', 'display_name': 'Mama 14', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0014@zebra.pl

2026-03-14 20:47:32,019 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:32,021 INFO sqlalchemy.engine.Engine [cached since 4.827s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.827s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

2026-03-14 20:47:32,051 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:32,052 INFO sqlalchemy.engine.Engine [cached since 4.858s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.858s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

2026-03-14 20:47:32,323 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:32,324 INFO sqlalchemy.engine.Engine [cached since 4.763s ago] {'id': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'email': 'test0015@zebra.pl', 'password_hash': '$2b$12$GB1qh0w3VBsaoZtn4yQeGOQqpDsS8AeypGUGPMv3r7PYbNyJoV6nS', 'display_name': 'Mama 15', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 4.763s ago] {'id': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'email': 'test0015@zebra.pl', 'password_hash': '$2b$12$GB1qh0w3VBsaoZtn4yQeGOQqpDsS8AeypGUGPMv3r7PYbNyJoV6nS', 'display_name': 'Mama 15', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0015@zebra.pl

2026-03-14 20:47:32,357 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:32,358 INFO sqlalchemy.engine.Engine [cached since 5.164s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.164s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

2026-03-14 20:47:32,392 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:32,394 INFO sqlalchemy.engine.Engine [cached since 5.2s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.2s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

2026-03-14 20:47:32,669 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:32,670 INFO sqlalchemy.engine.Engine [cached since 5.109s ago] {'id': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'email': 'test0016@zebra.pl', 'password_hash': '$2b$12$cO7E3pOFr3lqwJo3rO5ad.ZgrlRxxp/iI/nJshIIn39/8ZwnkHOXa', 'display_name': 'Mama 16', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 5.109s ago] {'id': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'email': 'test0016@zebra.pl', 'password_hash': '$2b$12$cO7E3pOFr3lqwJo3rO5ad.ZgrlRxxp/iI/nJshIIn39/8ZwnkHOXa', 'display_name': 'Mama 16', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0016@zebra.pl

2026-03-14 20:47:32,700 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:32,701 INFO sqlalchemy.engine.Engine [cached since 5.508s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.508s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

2026-03-14 20:47:32,734 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:32,735 INFO sqlalchemy.engine.Engine [cached since 5.542s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.542s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

2026-03-14 20:47:33,034 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:33,035 INFO sqlalchemy.engine.Engine [cached since 5.475s ago] {'id': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'email': 'test0017@zebra.pl', 'password_hash': '$2b$12$RfToKbipxsy7LvZ8AlbL6u.4u965imt4PnA6bHQjQhwYXpLaJ/kvG', 'display_name': 'Mama 17', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 5.475s ago] {'id': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'email': 'test0017@zebra.pl', 'password_hash': '$2b$12$RfToKbipxsy7LvZ8AlbL6u.4u965imt4PnA6bHQjQhwYXpLaJ/kvG', 'display_name': 'Mama 17', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0017@zebra.pl

2026-03-14 20:47:33,072 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:33,074 INFO sqlalchemy.engine.Engine [cached since 5.88s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.88s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

2026-03-14 20:47:33,105 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:33,106 INFO sqlalchemy.engine.Engine [cached since 5.913s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.913s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

2026-03-14 20:47:33,392 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:33,393 INFO sqlalchemy.engine.Engine [cached since 5.832s ago] {'id': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'email': 'test0018@zebra.pl', 'password_hash': '$2b$12$GRHxVm3Ts0WC6kdSCqO7gu5JwKEF67i9/Krc8bkNJC1iQtxP3FEq2', 'display_name': 'Mama 18', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 5.832s ago] {'id': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'email': 'test0018@zebra.pl', 'password_hash': '$2b$12$GRHxVm3Ts0WC6kdSCqO7gu5JwKEF67i9/Krc8bkNJC1iQtxP3FEq2', 'display_name': 'Mama 18', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0018@zebra.pl

2026-03-14 20:47:33,428 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:33,429 INFO sqlalchemy.engine.Engine [cached since 6.236s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.236s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

2026-03-14 20:47:33,460 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:33,462 INFO sqlalchemy.engine.Engine [cached since 6.268s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.268s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

2026-03-14 20:47:33,750 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:33,751 INFO sqlalchemy.engine.Engine [cached since 6.19s ago] {'id': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'email': 'test0019@zebra.pl', 'password_hash': '$2b$12$dXwHA4BPOKjiDKafeHXW1ejegC2h1jeeQNn73H3a8DWKwNiLBqgcq', 'display_name': 'Mama 19', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 6.19s ago] {'id': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'email': 'test0019@zebra.pl', 'password_hash': '$2b$12$dXwHA4BPOKjiDKafeHXW1ejegC2h1jeeQNn73H3a8DWKwNiLBqgcq', 'display_name': 'Mama 19', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0019@zebra.pl

2026-03-14 20:47:33,784 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:33,785 INFO sqlalchemy.engine.Engine [cached since 6.591s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.591s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

2026-03-14 20:47:33,819 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:33,821 INFO sqlalchemy.engine.Engine [cached since 6.627s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.627s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

2026-03-14 20:47:34,099 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:34,100 INFO sqlalchemy.engine.Engine [cached since 6.539s ago] {'id': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'email': 'test0020@zebra.pl', 'password_hash': '$2b$12$cNb38WNCUxcXHeVIH9ViFu.dGXgOhl9vHMxqx4Y/ITitQXfCu4lmq', 'display_name': 'Mama 20', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 6.539s ago] {'id': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'email': 'test0020@zebra.pl', 'password_hash': '$2b$12$cNb38WNCUxcXHeVIH9ViFu.dGXgOhl9vHMxqx4Y/ITitQXfCu4lmq', 'display_name': 'Mama 20', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0020@zebra.pl

2026-03-14 20:47:34,133 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:34,135 INFO sqlalchemy.engine.Engine [cached since 6.941s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.941s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

2026-03-14 20:47:34,168 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:34,170 INFO sqlalchemy.engine.Engine [cached since 6.977s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.977s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

2026-03-14 20:47:34,448 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:34,450 INFO sqlalchemy.engine.Engine [cached since 6.889s ago] {'id': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'email': 'test0021@zebra.pl', 'password_hash': '$2b$12$psAiMCqAN5PRvtTZBb9xMu0xZNW1HA7ZYF.5dd58w1gHkz1gifeC2', 'display_name': 'Mama 21', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 6.889s ago] {'id': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'email': 'test0021@zebra.pl', 'password_hash': '$2b$12$psAiMCqAN5PRvtTZBb9xMu0xZNW1HA7ZYF.5dd58w1gHkz1gifeC2', 'display_name': 'Mama 21', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0021@zebra.pl

2026-03-14 20:47:34,482 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:34,483 INFO sqlalchemy.engine.Engine [cached since 7.29s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.29s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

2026-03-14 20:47:34,515 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:34,519 INFO sqlalchemy.engine.Engine [cached since 7.326s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.326s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

2026-03-14 20:47:34,814 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:34,816 INFO sqlalchemy.engine.Engine [cached since 7.255s ago] {'id': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'email': 'test0022@zebra.pl', 'password_hash': '$2b$12$pAPBwa13pVWkR2LR1OM6re3Jn4PBsPMuS8x7VOArxdjc7siVllbu6', 'display_name': 'Mama 22', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 7.255s ago] {'id': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'email': 'test0022@zebra.pl', 'password_hash': '$2b$12$pAPBwa13pVWkR2LR1OM6re3Jn4PBsPMuS8x7VOArxdjc7siVllbu6', 'display_name': 'Mama 22', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0022@zebra.pl

2026-03-14 20:47:34,848 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:34,850 INFO sqlalchemy.engine.Engine [cached since 7.656s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.656s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

2026-03-14 20:47:34,879 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:34,880 INFO sqlalchemy.engine.Engine [cached since 7.687s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.687s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

2026-03-14 20:47:35,182 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:35,183 INFO sqlalchemy.engine.Engine [cached since 7.622s ago] {'id': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'email': 'test0023@zebra.pl', 'password_hash': '$2b$12$LDpCxhuq5xt.d0j4sotKwuuwgZe7e54eIiQgzTCCmjimDtHIEbo.u', 'display_name': 'Mama 23', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 7.622s ago] {'id': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'email': 'test0023@zebra.pl', 'password_hash': '$2b$12$LDpCxhuq5xt.d0j4sotKwuuwgZe7e54eIiQgzTCCmjimDtHIEbo.u', 'display_name': 'Mama 23', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0023@zebra.pl

2026-03-14 20:47:35,215 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:35,217 INFO sqlalchemy.engine.Engine [cached since 8.024s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.024s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

2026-03-14 20:47:35,250 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:35,253 INFO sqlalchemy.engine.Engine [cached since 8.059s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.059s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

2026-03-14 20:47:35,532 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:35,533 INFO sqlalchemy.engine.Engine [cached since 7.972s ago] {'id': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'email': 'test0024@zebra.pl', 'password_hash': '$2b$12$YyLxf/u.ijk/GkEnQWelQ.IKU4HRbucbF2AnCVYaVCkElXAbijQJe', 'display_name': 'Mama 24', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 7.972s ago] {'id': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'email': 'test0024@zebra.pl', 'password_hash': '$2b$12$YyLxf/u.ijk/GkEnQWelQ.IKU4HRbucbF2AnCVYaVCkElXAbijQJe', 'display_name': 'Mama 24', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0024@zebra.pl

2026-03-14 20:47:35,564 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:35,565 INFO sqlalchemy.engine.Engine [cached since 8.372s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.372s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

2026-03-14 20:47:35,598 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:35,599 INFO sqlalchemy.engine.Engine [cached since 8.406s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.406s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

2026-03-14 20:47:35,874 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:35,876 INFO sqlalchemy.engine.Engine [cached since 8.315s ago] {'id': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'email': 'test0025@zebra.pl', 'password_hash': '$2b$12$95Z6YYrWPJajPiv3u95F1O/R3dtCsnWWo2Svf4LAi8SR1Gwd3vP36', 'display_name': 'Mama 25', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 8.315s ago] {'id': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'email': 'test0025@zebra.pl', 'password_hash': '$2b$12$95Z6YYrWPJajPiv3u95F1O/R3dtCsnWWo2Svf4LAi8SR1Gwd3vP36', 'display_name': 'Mama 25', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0025@zebra.pl

2026-03-14 20:47:35,906 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:35,907 INFO sqlalchemy.engine.Engine [cached since 8.714s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.714s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

2026-03-14 20:47:35,937 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:35,939 INFO sqlalchemy.engine.Engine [cached since 8.745s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.745s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

2026-03-14 20:47:36,214 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:36,214 INFO sqlalchemy.engine.Engine [cached since 8.654s ago] {'id': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'email': 'test0026@zebra.pl', 'password_hash': '$2b$12$FvF1u1Tc.QK/8e5YQHXk3epF9H9i.vRv9zPV2RNdFMmKoXXOO1CUm', 'display_name': 'Mama 26', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 8.654s ago] {'id': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'email': 'test0026@zebra.pl', 'password_hash': '$2b$12$FvF1u1Tc.QK/8e5YQHXk3epF9H9i.vRv9zPV2RNdFMmKoXXOO1CUm', 'display_name': 'Mama 26', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0026@zebra.pl

2026-03-14 20:47:36,249 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:36,250 INFO sqlalchemy.engine.Engine [cached since 9.057s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.057s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

2026-03-14 20:47:36,282 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:36,283 INFO sqlalchemy.engine.Engine [cached since 9.09s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.09s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

2026-03-14 20:47:36,580 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:36,581 INFO sqlalchemy.engine.Engine [cached since 9.02s ago] {'id': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'email': 'test0027@zebra.pl', 'password_hash': '$2b$12$tA1TbLd6KXHe..OSlWT8TugGcrFt4IeoxERnwiP5SLkQVDh.DOjEK', 'display_name': 'Mama 27', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 9.02s ago] {'id': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'email': 'test0027@zebra.pl', 'password_hash': '$2b$12$tA1TbLd6KXHe..OSlWT8TugGcrFt4IeoxERnwiP5SLkQVDh.DOjEK', 'display_name': 'Mama 27', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0027@zebra.pl

2026-03-14 20:47:36,619 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:36,620 INFO sqlalchemy.engine.Engine [cached since 9.427s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.427s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

2026-03-14 20:47:36,650 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:36,652 INFO sqlalchemy.engine.Engine [cached since 9.458s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.458s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

2026-03-14 20:47:36,936 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:36,937 INFO sqlalchemy.engine.Engine [cached since 9.376s ago] {'id': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'email': 'test0028@zebra.pl', 'password_hash': '$2b$12$JasUp.4xSF7KYO2gxHaZM.a/nnYtz5JQaw1.PDxcSZ1.fOEXpsn.6', 'display_name': 'Mama 28', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 9.376s ago] {'id': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'email': 'test0028@zebra.pl', 'password_hash': '$2b$12$JasUp.4xSF7KYO2gxHaZM.a/nnYtz5JQaw1.PDxcSZ1.fOEXpsn.6', 'display_name': 'Mama 28', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0028@zebra.pl

2026-03-14 20:47:36,971 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:36,972 INFO sqlalchemy.engine.Engine [cached since 9.778s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.778s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

2026-03-14 20:47:37,002 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:37,003 INFO sqlalchemy.engine.Engine [cached since 9.809s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.809s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

2026-03-14 20:47:37,295 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:37,296 INFO sqlalchemy.engine.Engine [cached since 9.736s ago] {'id': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'email': 'test0029@zebra.pl', 'password_hash': '$2b$12$9X8Vh8m3Tz9n.MYK.S6nD.qj0rLORUmfjTjj2qfxMLDRpO5FadrMy', 'display_name': 'Mama 29', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 9.736s ago] {'id': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'email': 'test0029@zebra.pl', 'password_hash': '$2b$12$9X8Vh8m3Tz9n.MYK.S6nD.qj0rLORUmfjTjj2qfxMLDRpO5FadrMy', 'display_name': 'Mama 29', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0029@zebra.pl

2026-03-14 20:47:37,328 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:37,329 INFO sqlalchemy.engine.Engine [cached since 10.14s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.14s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

2026-03-14 20:47:37,362 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:37,364 INFO sqlalchemy.engine.Engine [cached since 10.17s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.17s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

2026-03-14 20:47:37,651 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:37,652 INFO sqlalchemy.engine.Engine [cached since 10.09s ago] {'id': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'email': 'test0030@zebra.pl', 'password_hash': '$2b$12$Tl0aznYvl5TFyispMfqSauwUZHMmrudIRA75tYWe0gO3x6ISeuI76', 'display_name': 'Mama 30', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 10.09s ago] {'id': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'email': 'test0030@zebra.pl', 'password_hash': '$2b$12$Tl0aznYvl5TFyispMfqSauwUZHMmrudIRA75tYWe0gO3x6ISeuI76', 'display_name': 'Mama 30', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0030@zebra.pl

2026-03-14 20:47:37,683 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:37,686 INFO sqlalchemy.engine.Engine [cached since 10.49s ago] {'email_1': 'test0031@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.49s ago] {'email_1': 'test0031@zebra.pl', 'param_1': 1}

2026-03-14 20:47:37,719 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:37,720 INFO sqlalchemy.engine.Engine [cached since 10.53s ago] {'email_1': 'test0031@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.53s ago] {'email_1': 'test0031@zebra.pl', 'param_1': 1}

2026-03-14 20:47:38,012 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:38,014 INFO sqlalchemy.engine.Engine [cached since 10.45s ago] {'id': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'email': 'test0031@zebra.pl', 'password_hash': '$2b$12$5vKLKQtt6IjpJfzDHWxdPeNzK7Lo36942sHyhq2x0TrZY0DQaE.Ra', 'display_name': 'Mama 31', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 10.45s ago] {'id': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'email': 'test0031@zebra.pl', 'password_hash': '$2b$12$5vKLKQtt6IjpJfzDHWxdPeNzK7Lo36942sHyhq2x0TrZY0DQaE.Ra', 'display_name': 'Mama 31', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0031@zebra.pl

2026-03-14 20:47:38,048 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:38,051 INFO sqlalchemy.engine.Engine [cached since 10.86s ago] {'email_1': 'test0032@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.86s ago] {'email_1': 'test0032@zebra.pl', 'param_1': 1}

2026-03-14 20:47:38,082 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:38,083 INFO sqlalchemy.engine.Engine [cached since 10.89s ago] {'email_1': 'test0032@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.89s ago] {'email_1': 'test0032@zebra.pl', 'param_1': 1}

2026-03-14 20:47:38,367 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:38,368 INFO sqlalchemy.engine.Engine [cached since 10.81s ago] {'id': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'email': 'test0032@zebra.pl', 'password_hash': '$2b$12$s13542fIDZ4jsWbyAgRqj.hreUTM9EMzB6TWyeHO9KoT7q0VlvZiq', 'display_name': 'Mama 32', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 10.81s ago] {'id': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'email': 'test0032@zebra.pl', 'password_hash': '$2b$12$s13542fIDZ4jsWbyAgRqj.hreUTM9EMzB6TWyeHO9KoT7q0VlvZiq', 'display_name': 'Mama 32', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0032@zebra.pl

2026-03-14 20:47:38,400 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:38,401 INFO sqlalchemy.engine.Engine [cached since 11.21s ago] {'email_1': 'test0033@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.21s ago] {'email_1': 'test0033@zebra.pl', 'param_1': 1}

2026-03-14 20:47:38,434 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:38,436 INFO sqlalchemy.engine.Engine [cached since 11.24s ago] {'email_1': 'test0033@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.24s ago] {'email_1': 'test0033@zebra.pl', 'param_1': 1}

2026-03-14 20:47:38,732 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:38,733 INFO sqlalchemy.engine.Engine [cached since 11.17s ago] {'id': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'email': 'test0033@zebra.pl', 'password_hash': '$2b$12$t5.KqBWNCRQPxykqyH9zVew/0tmE1qL/.AOFypHAamdhbVvMrsMH6', 'display_name': 'Mama 33', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 11.17s ago] {'id': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'email': 'test0033@zebra.pl', 'password_hash': '$2b$12$t5.KqBWNCRQPxykqyH9zVew/0tmE1qL/.AOFypHAamdhbVvMrsMH6', 'display_name': 'Mama 33', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0033@zebra.pl

2026-03-14 20:47:38,766 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:38,768 INFO sqlalchemy.engine.Engine [cached since 11.57s ago] {'email_1': 'test0034@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.57s ago] {'email_1': 'test0034@zebra.pl', 'param_1': 1}

2026-03-14 20:47:38,798 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:38,799 INFO sqlalchemy.engine.Engine [cached since 11.61s ago] {'email_1': 'test0034@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.61s ago] {'email_1': 'test0034@zebra.pl', 'param_1': 1}

2026-03-14 20:47:39,093 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:39,093 INFO sqlalchemy.engine.Engine [cached since 11.53s ago] {'id': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'email': 'test0034@zebra.pl', 'password_hash': '$2b$12$/FrFHlo3ffB/zEMEkBHTU.88m.grWdeiTbrsZ10zRfA3OHp7IUJaK', 'display_name': 'Mama 34', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 11.53s ago] {'id': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'email': 'test0034@zebra.pl', 'password_hash': '$2b$12$/FrFHlo3ffB/zEMEkBHTU.88m.grWdeiTbrsZ10zRfA3OHp7IUJaK', 'display_name': 'Mama 34', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0034@zebra.pl

2026-03-14 20:47:39,129 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:39,130 INFO sqlalchemy.engine.Engine [cached since 11.94s ago] {'email_1': 'test0035@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.94s ago] {'email_1': 'test0035@zebra.pl', 'param_1': 1}

2026-03-14 20:47:39,162 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:39,163 INFO sqlalchemy.engine.Engine [cached since 11.97s ago] {'email_1': 'test0035@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.97s ago] {'email_1': 'test0035@zebra.pl', 'param_1': 1}

2026-03-14 20:47:39,444 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:39,445 INFO sqlalchemy.engine.Engine [cached since 11.88s ago] {'id': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'email': 'test0035@zebra.pl', 'password_hash': '$2b$12$l/EWOlOKZE50jUP05rv.zuoHwjSCyIgnVOZoPk0pgIpkFHeA1mJzO', 'display_name': 'Mama 35', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 11.88s ago] {'id': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'email': 'test0035@zebra.pl', 'password_hash': '$2b$12$l/EWOlOKZE50jUP05rv.zuoHwjSCyIgnVOZoPk0pgIpkFHeA1mJzO', 'display_name': 'Mama 35', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0035@zebra.pl

2026-03-14 20:47:39,478 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:39,480 INFO sqlalchemy.engine.Engine [cached since 12.29s ago] {'email_1': 'test0036@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.29s ago] {'email_1': 'test0036@zebra.pl', 'param_1': 1}

2026-03-14 20:47:39,514 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:39,515 INFO sqlalchemy.engine.Engine [cached since 12.32s ago] {'email_1': 'test0036@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.32s ago] {'email_1': 'test0036@zebra.pl', 'param_1': 1}

2026-03-14 20:47:39,812 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:39,813 INFO sqlalchemy.engine.Engine [cached since 12.25s ago] {'id': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'email': 'test0036@zebra.pl', 'password_hash': '$2b$12$ihHXS4U.9QE.Y8SjFlIROe30GYXaMSRxZLkCS.RPi2WP6dOHI/20y', 'display_name': 'Mama 36', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 12.25s ago] {'id': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'email': 'test0036@zebra.pl', 'password_hash': '$2b$12$ihHXS4U.9QE.Y8SjFlIROe30GYXaMSRxZLkCS.RPi2WP6dOHI/20y', 'display_name': 'Mama 36', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0036@zebra.pl

2026-03-14 20:47:39,848 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:39,850 INFO sqlalchemy.engine.Engine [cached since 12.66s ago] {'email_1': 'test0037@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.66s ago] {'email_1': 'test0037@zebra.pl', 'param_1': 1}

2026-03-14 20:47:39,882 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:39,883 INFO sqlalchemy.engine.Engine [cached since 12.69s ago] {'email_1': 'test0037@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.69s ago] {'email_1': 'test0037@zebra.pl', 'param_1': 1}

2026-03-14 20:47:40,199 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:40,200 INFO sqlalchemy.engine.Engine [cached since 12.64s ago] {'id': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'email': 'test0037@zebra.pl', 'password_hash': '$2b$12$efvVRopt6EbzVIrZLjm/5Odu.GYgqqj.rbUE5cMVLAL.Rkhq7ONIm', 'display_name': 'Mama 37', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 12.64s ago] {'id': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'email': 'test0037@zebra.pl', 'password_hash': '$2b$12$efvVRopt6EbzVIrZLjm/5Odu.GYgqqj.rbUE5cMVLAL.Rkhq7ONIm', 'display_name': 'Mama 37', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0037@zebra.pl

2026-03-14 20:47:40,234 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:40,235 INFO sqlalchemy.engine.Engine [cached since 13.04s ago] {'email_1': 'test0038@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.04s ago] {'email_1': 'test0038@zebra.pl', 'param_1': 1}

2026-03-14 20:47:40,265 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:40,266 INFO sqlalchemy.engine.Engine [cached since 13.07s ago] {'email_1': 'test0038@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.07s ago] {'email_1': 'test0038@zebra.pl', 'param_1': 1}

2026-03-14 20:47:40,554 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:40,555 INFO sqlalchemy.engine.Engine [cached since 12.99s ago] {'id': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'email': 'test0038@zebra.pl', 'password_hash': '$2b$12$uJYPP1pfTi9AtBv4S61jLe/UuBIG5fZoqDPcg6tPOWPa2u2LadX4m', 'display_name': 'Mama 38', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 12.99s ago] {'id': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'email': 'test0038@zebra.pl', 'password_hash': '$2b$12$uJYPP1pfTi9AtBv4S61jLe/UuBIG5fZoqDPcg6tPOWPa2u2LadX4m', 'display_name': 'Mama 38', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0038@zebra.pl

2026-03-14 20:47:40,586 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:40,588 INFO sqlalchemy.engine.Engine [cached since 13.39s ago] {'email_1': 'test0039@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.39s ago] {'email_1': 'test0039@zebra.pl', 'param_1': 1}

2026-03-14 20:47:40,617 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:40,619 INFO sqlalchemy.engine.Engine [cached since 13.43s ago] {'email_1': 'test0039@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.43s ago] {'email_1': 'test0039@zebra.pl', 'param_1': 1}

2026-03-14 20:47:40,916 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:40,918 INFO sqlalchemy.engine.Engine [cached since 13.36s ago] {'id': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'email': 'test0039@zebra.pl', 'password_hash': '$2b$12$hz5Sac0wnxVEta/STM1p9.C5JKBQ/oWqC7Nugmj0G5.CHI3SKGGIG', 'display_name': 'Mama 39', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 13.36s ago] {'id': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'email': 'test0039@zebra.pl', 'password_hash': '$2b$12$hz5Sac0wnxVEta/STM1p9.C5JKBQ/oWqC7Nugmj0G5.CHI3SKGGIG', 'display_name': 'Mama 39', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0039@zebra.pl

2026-03-14 20:47:40,951 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:40,953 INFO sqlalchemy.engine.Engine [cached since 13.76s ago] {'email_1': 'test0040@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.76s ago] {'email_1': 'test0040@zebra.pl', 'param_1': 1}

2026-03-14 20:47:40,986 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:47:40,987 INFO sqlalchemy.engine.Engine [cached since 13.79s ago] {'email_1': 'test0040@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.79s ago] {'email_1': 'test0040@zebra.pl', 'param_1': 1}

2026-03-14 20:47:41,277 INFO sqlalchemy.engine.Engine INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO users (id, email, password_hash, display_name, avatar_url, role, age_range, is_active) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(display_name)s, %(avatar_url)s, %(role)s, %(age_range)s, %(is_active)s) RETURNING users.created_at, users.updated_at

2026-03-14 20:47:41,279 INFO sqlalchemy.engine.Engine [cached since 13.72s ago] {'id': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'email': 'test0040@zebra.pl', 'password_hash': '$2b$12$LDXrCCSyIQMG7334seClD.yLNwoS9Aw5vToToMJIVayxa8owYWzC2', 'display_name': 'Mama 40', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}

INFO:sqlalchemy.engine.Engine:[cached since 13.72s ago] {'id': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'email': 'test0040@zebra.pl', 'password_hash': '$2b$12$LDXrCCSyIQMG7334seClD.yLNwoS9Aw5vToToMJIVayxa8owYWzC2', 'display_name': 'Mama 40', 'avatar_url': None, 'role': 'user', 'age_range': None, 'is_active': True}
INFO:dataset-notebook:Utworzono użytkownika test0040@zebra.pl

2026-03-14 20:47:41,311 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

Nowo utworzonych użytkowników: 40
Użytkownicy już istniejący:   0

In [6]:
# Utworzenie / aktualizacja profili objawów i dopasowanie do grup

profiles_created = 0
profiles_updated = 0

with get_db() as db:
    for rec in records:
        email = rec["email"]
        user = db.query(User).filter(User.email == email).first()
        if user is None:
            logger.warning("Brak użytkownika %s — pomijam profil objawów", email)
            continue

        existing_profile = (
            db.query(SymptomProfile)
            .filter(SymptomProfile.user_id == user.id)
            .first()
        )

        profile = create_or_update_symptom_profile(db, user, rec["description"])

        if existing_profile is None:
            profiles_created += 1
        else:
            profiles_updated += 1

    # Uzupełnienie charakterystyk grup (keywords, symptom_category, avg_match_score),
    # gdy Celery nie działa — update_group_characteristics robi commit wewnętrznie.
    group_ids = {row[0] for row in db.query(SymptomProfile.group_id).all() if row[0] is not None}
    for gid in group_ids:
        update_group_characteristics(db, str(gid))

print(f"Nowo utworzonych profili objawów: {profiles_created}")
print(f"Zaktualizowanych profili objawów: {profiles_updated}")

2026-03-14 20:48:25,648 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:25,650 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:25,650 INFO sqlalchemy.engine.Engine [cached since 58.46s ago] {'email_1': 'test0001@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 58.46s ago] {'email_1': 'test0001@zebra.pl', 'param_1': 1}

2026-03-14 20:48:25,717 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:25,729 INFO sqlalchemy.engine.Engine [generated in 0.01188s] {'user_id_1': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.01188s] {'user_id_1': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'param_1': 1}

2026-03-14 20:48:25,769 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:25,771 INFO sqlalchemy.engine.Engine [cached since 0.05463s ago] {'user_id_1': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.05463s ago] {'user_id_1': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'param_1': 1}
INFO:app.services.embedding_service:Ładowanie modelu embeddingów: paraphrase-multilingual-MiniLM-L12-v2
INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cpu
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: paraphrase-multilingual-MiniLM-L12-v2
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/modules.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config_sentence_transformers.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config_sentence_transformers.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/README.md "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/modules.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/sentence_bert_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5582.72it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 "HTTP/1.1 200 OK"
INFO:app.services.embedding_service:Model załadowany pomyślnie

2026-03-14 20:48:30,658 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:30,660 INFO sqlalchemy.engine.Engine [generated in 0.00149s] {'embedding': '[0.03879793,0.02517908,0.03030772,0.03354456,-0.03728069,0.06958893,-0.04126158,0.01336413,0.01987986,-0.02862488,0.08611352,0.05212132,-0.05430003,0 ... (4114 characters truncated) ... 8,0.02269836,-0.03061268,-0.03724700,0.06554460,0.00565153,-0.04183669,0.00679470,-0.04613909,0.02729654,0.02859912,0.05513959,0.06224400,0.00242029]', 'user_id': '4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[generated in 0.00149s] {'embedding': '[0.03879793,0.02517908,0.03030772,0.03354456,-0.03728069,0.06958893,-0.04126158,0.01336413,0.01987986,-0.02862488,0.08611352,0.05212132,-0.05430003,0 ... (4114 characters truncated) ... 8,0.02269836,-0.03061268,-0.03724700,0.06554460,0.00565153,-0.04183669,0.00679470,-0.04613909,0.02729654,0.02859912,0.05513959,0.06224400,0.00242029]', 'user_id': '4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2', 'top_k': 5}
INFO:app.services.matching_service:Brak podobnych profili w bazie — tworzę nową grupę dla user 4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2

2026-03-14 20:48:30,705 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:30,707 INFO sqlalchemy.engine.Engine [generated in 0.00223s] {'id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'name': 'Jadeitowy Topaz', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#06b6d4', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[generated in 0.00223s] {'id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'name': 'Jadeitowy Topaz', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#06b6d4', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:dataset-notebook:Utworzono profil objawów dla test0001@zebra.pl

2026-03-14 20:48:30,749 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:30,750 INFO sqlalchemy.engine.Engine [generated in 0.00117s] {'user_id_1': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00117s] {'user_id_1': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:30,787 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:30,788 INFO sqlalchemy.engine.Engine [generated in 0.00124s] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[generated in 0.00124s] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2 do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:31,215 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:31,216 INFO sqlalchemy.engine.Engine [generated in 0.00134s] {'user_id': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[generated in 0.00134s] {'user_id': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:31,252 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:31,253 INFO sqlalchemy.engine.Engine [generated in 0.00203s] {'id': UUID('fefa04a9-1096-40fd-a3f2-b05b0f082f9d'), 'user_id': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'description': 'Syn od urodzenia ma bardzo obniżone napięcie mięśniowe. Przez długi czas nie trzymał główki, późno zaczął siadać i raczkować. Teraz chodzi, ale szybk ... (25 characters truncated) ... i z utrzymaniem równowagi. Rozwój mowy też jest opóźniony — mówi niewyraźnie i mało. Szukamy kontaktu z innymi rodzicami dzieci z podobnymi objawami.', 'embedding': '[0.038797926157712936,0.025179076939821243,0.030307721346616745,0.03354455903172493,-0.03728068992495537,0.06958892941474915,-0.04126157984137535,0.0 ... (7746 characters truncated) ... 519,0.0067946999333798885,-0.04613909125328064,0.027296539396047592,0.02859911508858204,0.05513959378004074,0.0622439980506897,0.0024202873464673758]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[generated in 0.00203s] {'id': UUID('fefa04a9-1096-40fd-a3f2-b05b0f082f9d'), 'user_id': UUID('4c9c1c46-938c-40aa-9165-ddd8b1bb4bb2'), 'description': 'Syn od urodzenia ma bardzo obniżone napięcie mięśniowe. Przez długi czas nie trzymał główki, późno zaczął siadać i raczkować. Teraz chodzi, ale szybk ... (25 characters truncated) ... i z utrzymaniem równowagi. Rozwój mowy też jest opóźniony — mówi niewyraźnie i mało. Szukamy kontaktu z innymi rodzicami dzieci z podobnymi objawami.', 'embedding': '[0.038797926157712936,0.025179076939821243,0.030307721346616745,0.03354455903172493,-0.03728068992495537,0.06958892941474915,-0.04126157984137535,0.0 ... (7746 characters truncated) ... 519,0.0067946999333798885,-0.04613909125328064,0.027296539396047592,0.02859911508858204,0.05513959378004074,0.0622439980506897,0.0024202873464673758]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.0}

2026-03-14 20:48:31,292 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:31,294 INFO sqlalchemy.engine.Engine [cached since 64.1s ago] {'email_1': 'test0002@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 64.1s ago] {'email_1': 'test0002@zebra.pl', 'param_1': 1}

2026-03-14 20:48:31,324 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:31,325 INFO sqlalchemy.engine.Engine [cached since 5.609s ago] {'user_id_1': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.609s ago] {'user_id_1': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'param_1': 1}

2026-03-14 20:48:31,356 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:31,358 INFO sqlalchemy.engine.Engine [cached since 5.641s ago] {'user_id_1': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.641s ago] {'user_id_1': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'param_1': 1}

2026-03-14 20:48:31,455 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:31,457 INFO sqlalchemy.engine.Engine [cached since 0.7984s ago] {'embedding': '[0.02364973,0.00439674,0.06021897,0.07515612,-0.00045372,-0.00574761,0.03433704,0.06121382,-0.02848938,-0.02127527,-0.00745455,-0.00960218,-0.0515261 ... (4135 characters truncated) ... -0.00487539,0.03707982,0.00766731,-0.00970121,0.07248892,-0.00147793,0.02125867,-0.06544944,-0.01042897,0.08214788,0.02299745,-0.00370626,0.00671458]', 'user_id': 'dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 0.7984s ago] {'embedding': '[0.02364973,0.00439674,0.06021897,0.07515612,-0.00045372,-0.00574761,0.03433704,0.06121382,-0.02848938,-0.02127527,-0.00745455,-0.00960218,-0.0515261 ... (4135 characters truncated) ... -0.00487539,0.03707982,0.00766731,-0.00970121,0.07248892,-0.00147793,0.02125867,-0.06544944,-0.01042897,0.08214788,0.02299745,-0.00370626,0.00671458]', 'user_id': 'dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.4661, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.4661 < threshold 0.72 — nowa grupa

2026-03-14 20:48:31,492 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:31,494 INFO sqlalchemy.engine.Engine [cached since 0.7884s ago] {'id': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09'), 'name': 'Perłowy Sosna', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 0.7884s ago] {'id': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09'), 'name': 'Perłowy Sosna', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: ee9f537e-dc5a-4927-ac9c-7fb86211aa09
INFO:dataset-notebook:Utworzono profil objawów dla test0002@zebra.pl

2026-03-14 20:48:31,528 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:31,530 INFO sqlalchemy.engine.Engine [cached since 0.7811s ago] {'user_id_1': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'group_id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.7811s ago] {'user_id_1': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'group_id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09'), 'param_1': 1}

2026-03-14 20:48:31,561 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:31,562 INFO sqlalchemy.engine.Engine [cached since 0.7753s ago] {'member_count_1': 1, 'id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

INFO:sqlalchemy.engine.Engine:[cached since 0.7753s ago] {'member_count_1': 1, 'id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}
INFO:app.services.matching_service:Dodano user dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5 do grupy ee9f537e-dc5a-4927-ac9c-7fb86211aa09

2026-03-14 20:48:31,601 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:31,602 INFO sqlalchemy.engine.Engine [cached since 0.387s ago] {'user_id': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'group_id': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

INFO:sqlalchemy.engine.Engine:[cached since 0.387s ago] {'user_id': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'group_id': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

2026-03-14 20:48:31,636 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:31,637 INFO sqlalchemy.engine.Engine [cached since 0.3856s ago] {'id': UUID('4d5cc046-f1cc-4e33-a51a-1a5ba02f8969'), 'user_id': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'description': 'Córka ma zdiagnozowaną rzadką chorobę metaboliczną. Po nawet krótkim wysiłku fizycznym bardzo się męczy, a potem przez długi czas skarży się na bóle  ... (66 characters truncated) ... kole potrzebuje przerw i nie może uczestniczyć we wszystkich zajęciach sportowych. Chciałabym porozmawiać z kimś, kto przechodzi przez coś podobnego.', 'embedding': '[0.023649729788303375,0.004396740812808275,0.060218967497348785,0.07515612244606018,-0.0004537213535513729,-0.005747610237449408,0.034337036311626434 ... (7756 characters truncated) ... 0.021258670836687088,-0.06544943898916245,-0.010428969748318195,0.08214788138866425,0.022997448220849037,-0.0037062568590044975,0.006714576855301857]', 'group_id': 'ee9f537e-dc5a-4927-ac9c-7fb86211aa09', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 0.3856s ago] {'id': UUID('4d5cc046-f1cc-4e33-a51a-1a5ba02f8969'), 'user_id': UUID('dcc11e9d-d3e5-4f6d-afaa-e0bf9061b0e5'), 'description': 'Córka ma zdiagnozowaną rzadką chorobę metaboliczną. Po nawet krótkim wysiłku fizycznym bardzo się męczy, a potem przez długi czas skarży się na bóle  ... (66 characters truncated) ... kole potrzebuje przerw i nie może uczestniczyć we wszystkich zajęciach sportowych. Chciałabym porozmawiać z kimś, kto przechodzi przez coś podobnego.', 'embedding': '[0.023649729788303375,0.004396740812808275,0.060218967497348785,0.07515612244606018,-0.0004537213535513729,-0.005747610237449408,0.034337036311626434 ... (7756 characters truncated) ... 0.021258670836687088,-0.06544943898916245,-0.010428969748318195,0.08214788138866425,0.022997448220849037,-0.0037062568590044975,0.006714576855301857]', 'group_id': 'ee9f537e-dc5a-4927-ac9c-7fb86211aa09', 'match_score': 0.0}

2026-03-14 20:48:31,675 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:31,676 INFO sqlalchemy.engine.Engine [cached since 64.48s ago] {'email_1': 'test0003@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 64.48s ago] {'email_1': 'test0003@zebra.pl', 'param_1': 1}

2026-03-14 20:48:31,707 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:31,708 INFO sqlalchemy.engine.Engine [cached since 5.992s ago] {'user_id_1': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.992s ago] {'user_id_1': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'param_1': 1}

2026-03-14 20:48:31,740 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:31,742 INFO sqlalchemy.engine.Engine [cached since 6.025s ago] {'user_id_1': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.025s ago] {'user_id_1': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'param_1': 1}

2026-03-14 20:48:31,835 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:31,851 INFO sqlalchemy.engine.Engine [cached since 1.192s ago] {'embedding': '[0.00315289,0.05093948,-0.04200033,0.11624883,0.00533633,0.07085814,-0.06086941,-0.00867092,0.02446891,0.01025276,0.03710046,0.03447995,-0.08846924,0 ... (4108 characters truncated) ... .03733110,-0.01379931,-0.07947366,0.00653581,0.04053178,-0.05026214,0.01545450,-0.06135153,-0.00100355,-0.00321497,-0.02523615,0.08705719,0.00400376]', 'user_id': '6be69daf-9c96-4ac0-a239-57f23e3b0117', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 1.192s ago] {'embedding': '[0.00315289,0.05093948,-0.04200033,0.11624883,0.00533633,0.07085814,-0.06086941,-0.00867092,0.02446891,0.01025276,0.03710046,0.03447995,-0.08846924,0 ... (4108 characters truncated) ... .03733110,-0.01379931,-0.07947366,0.00653581,0.04053178,-0.05026214,0.01545450,-0.06135153,-0.00100355,-0.00321497,-0.02523615,0.08705719,0.00400376]', 'user_id': '6be69daf-9c96-4ac0-a239-57f23e3b0117', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6477, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6477 < threshold 0.72 — nowa grupa

2026-03-14 20:48:31,886 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:31,888 INFO sqlalchemy.engine.Engine [cached since 1.182s ago] {'id': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9'), 'name': 'Szafirowy Brzoza', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#8b5cf6', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 1.182s ago] {'id': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9'), 'name': 'Szafirowy Brzoza', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#8b5cf6', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: e816d3a6-a075-45f7-92c4-3d1f38818ea9
INFO:dataset-notebook:Utworzono profil objawów dla test0003@zebra.pl

2026-03-14 20:48:31,926 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:31,929 INFO sqlalchemy.engine.Engine [cached since 1.18s ago] {'user_id_1': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'group_id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.18s ago] {'user_id_1': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'group_id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9'), 'param_1': 1}

2026-03-14 20:48:31,966 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:31,970 INFO sqlalchemy.engine.Engine [cached since 1.183s ago] {'member_count_1': 1, 'id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

INFO:sqlalchemy.engine.Engine:[cached since 1.183s ago] {'member_count_1': 1, 'id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}
INFO:app.services.matching_service:Dodano user 6be69daf-9c96-4ac0-a239-57f23e3b0117 do grupy e816d3a6-a075-45f7-92c4-3d1f38818ea9

2026-03-14 20:48:32,009 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:32,010 INFO sqlalchemy.engine.Engine [cached since 0.7949s ago] {'user_id': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'group_id': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

INFO:sqlalchemy.engine.Engine:[cached since 0.7949s ago] {'user_id': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'group_id': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

2026-03-14 20:48:32,045 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:32,046 INFO sqlalchemy.engine.Engine [cached since 0.7949s ago] {'id': UUID('ec2bc043-212c-4b36-9021-c0dfb2472606'), 'user_id': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'description': 'Nasze dziecko urodziło się z wadą serca, która wymaga regularnych kontroli i leków. Nie może się zbytnio forsować, unikamy gwałtownych zabaw i sportu ... (37 characters truncated) ... iej niż rówieśnicy. Życie codzienne wymaga planowania pod kątem wizyt u kardiologa i badań. Szukam wsparcia u innych opiekunów dzieci z wadami serca.', 'embedding': '[0.003152892692014575,0.05093947798013687,-0.04200032725930214,0.11624883115291595,0.005336333531886339,0.07085814327001572,-0.06086941063404083,-0.0 ... (7728 characters truncated) ... 0.01545450184494257,-0.061351533979177475,-0.0010035521117970347,-0.0032149662729352713,-0.02523614652454853,0.0870571881532669,0.004003760404884815]', 'group_id': 'e816d3a6-a075-45f7-92c4-3d1f38818ea9', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 0.7949s ago] {'id': UUID('ec2bc043-212c-4b36-9021-c0dfb2472606'), 'user_id': UUID('6be69daf-9c96-4ac0-a239-57f23e3b0117'), 'description': 'Nasze dziecko urodziło się z wadą serca, która wymaga regularnych kontroli i leków. Nie może się zbytnio forsować, unikamy gwałtownych zabaw i sportu ... (37 characters truncated) ... iej niż rówieśnicy. Życie codzienne wymaga planowania pod kątem wizyt u kardiologa i badań. Szukam wsparcia u innych opiekunów dzieci z wadami serca.', 'embedding': '[0.003152892692014575,0.05093947798013687,-0.04200032725930214,0.11624883115291595,0.005336333531886339,0.07085814327001572,-0.06086941063404083,-0.0 ... (7728 characters truncated) ... 0.01545450184494257,-0.061351533979177475,-0.0010035521117970347,-0.0032149662729352713,-0.02523614652454853,0.0870571881532669,0.004003760404884815]', 'group_id': 'e816d3a6-a075-45f7-92c4-3d1f38818ea9', 'match_score': 0.0}

2026-03-14 20:48:32,081 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:32,082 INFO sqlalchemy.engine.Engine [cached since 64.89s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 64.89s ago] {'email_1': 'test0004@zebra.pl', 'param_1': 1}

2026-03-14 20:48:32,115 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,116 INFO sqlalchemy.engine.Engine [cached since 6.4s ago] {'user_id_1': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.4s ago] {'user_id_1': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'param_1': 1}

2026-03-14 20:48:32,148 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,150 INFO sqlalchemy.engine.Engine [cached since 6.433s ago] {'user_id_1': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.433s ago] {'user_id_1': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'param_1': 1}

2026-03-14 20:48:32,247 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:32,250 INFO sqlalchemy.engine.Engine [cached since 1.592s ago] {'embedding': '[-0.01170038,0.08736201,0.00047701,0.05830202,-0.02403772,0.03101499,-0.06217712,0.02666057,0.00986602,-0.01551091,0.08019257,-0.03409498,-0.05637488 ... (4122 characters truncated) ... .00461100,-0.08954022,0.03071419,-0.00750066,-0.00175551,-0.02537874,0.00347903,-0.01184420,0.05438650,0.08173410,-0.03993118,0.08391432,-0.00731022]', 'user_id': 'bab0167d-dc4e-4ab0-a815-4c44773a2ff0', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 1.592s ago] {'embedding': '[-0.01170038,0.08736201,0.00047701,0.05830202,-0.02403772,0.03101499,-0.06217712,0.02666057,0.00986602,-0.01551091,0.08019257,-0.03409498,-0.05637488 ... (4122 characters truncated) ... .00461100,-0.08954022,0.03071419,-0.00750066,-0.00175551,-0.02537874,0.00347903,-0.01184420,0.05438650,0.08173410,-0.03993118,0.08391432,-0.00731022]', 'user_id': 'bab0167d-dc4e-4ab0-a815-4c44773a2ff0', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6663, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6663 < threshold 0.72 — nowa grupa

2026-03-14 20:48:32,286 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:32,287 INFO sqlalchemy.engine.Engine [cached since 1.582s ago] {'id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'name': 'Kremowy Przylądek', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#6366f1', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 1.582s ago] {'id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'name': 'Kremowy Przylądek', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#6366f1', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 49357027-f555-473a-8c72-cafd78dc5fc2
INFO:dataset-notebook:Utworzono profil objawów dla test0004@zebra.pl

2026-03-14 20:48:32,321 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,322 INFO sqlalchemy.engine.Engine [cached since 1.573s ago] {'user_id_1': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.573s ago] {'user_id_1': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

2026-03-14 20:48:32,357 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:32,358 INFO sqlalchemy.engine.Engine [cached since 1.572s ago] {'member_count_1': 1, 'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 1.572s ago] {'member_count_1': 1, 'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}
INFO:app.services.matching_service:Dodano user bab0167d-dc4e-4ab0-a815-4c44773a2ff0 do grupy 49357027-f555-473a-8c72-cafd78dc5fc2

2026-03-14 20:48:32,397 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:32,398 INFO sqlalchemy.engine.Engine [cached since 1.183s ago] {'user_id': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'group_id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 1.183s ago] {'user_id': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'group_id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

2026-03-14 20:48:32,434 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:32,435 INFO sqlalchemy.engine.Engine [cached since 1.184s ago] {'id': UUID('3ba26c9d-b501-48e9-9ea0-02fb48e4c3c1'), 'user_id': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'description': 'Nasze dziecko urodziło się z bardzo niską masą ciała i mimo upływu lat nadal jest dużo mniejsze od rówieśników. Je mało, szybko się męczy i ma trudności z przybieraniem na wadze.', 'embedding': '[-0.011700383387506008,0.08736201375722885,0.00047700622235424817,0.05830201879143715,-0.024037715047597885,0.03101498633623123,-0.06217711791396141, ... (7751 characters truncated) ... 06,0.003479027422145009,-0.01184419821947813,0.054386500269174576,0.08173409849405289,-0.03993118181824684,0.08391432464122772,-0.007310221903026104]', 'group_id': '49357027-f555-473a-8c72-cafd78dc5fc2', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 1.184s ago] {'id': UUID('3ba26c9d-b501-48e9-9ea0-02fb48e4c3c1'), 'user_id': UUID('bab0167d-dc4e-4ab0-a815-4c44773a2ff0'), 'description': 'Nasze dziecko urodziło się z bardzo niską masą ciała i mimo upływu lat nadal jest dużo mniejsze od rówieśników. Je mało, szybko się męczy i ma trudności z przybieraniem na wadze.', 'embedding': '[-0.011700383387506008,0.08736201375722885,0.00047700622235424817,0.05830201879143715,-0.024037715047597885,0.03101498633623123,-0.06217711791396141, ... (7751 characters truncated) ... 06,0.003479027422145009,-0.01184419821947813,0.054386500269174576,0.08173409849405289,-0.03993118181824684,0.08391432464122772,-0.007310221903026104]', 'group_id': '49357027-f555-473a-8c72-cafd78dc5fc2', 'match_score': 0.0}

2026-03-14 20:48:32,468 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:32,469 INFO sqlalchemy.engine.Engine [cached since 65.28s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 65.28s ago] {'email_1': 'test0005@zebra.pl', 'param_1': 1}

2026-03-14 20:48:32,500 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,501 INFO sqlalchemy.engine.Engine [cached since 6.784s ago] {'user_id_1': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.784s ago] {'user_id_1': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'param_1': 1}

2026-03-14 20:48:32,531 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,533 INFO sqlalchemy.engine.Engine [cached since 6.816s ago] {'user_id_1': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.816s ago] {'user_id_1': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'param_1': 1}

2026-03-14 20:48:32,618 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:32,619 INFO sqlalchemy.engine.Engine [cached since 1.961s ago] {'embedding': '[-0.03089456,-0.02492464,0.04322281,0.17820162,-0.00587033,0.04237683,0.04210227,-0.03063672,0.02629010,0.00139019,0.08498203,-0.04209319,-0.04514636 ... (4131 characters truncated) ... .00055758,-0.07347211,-0.03782245,-0.11108061,-0.00666794,0.10907600,-0.06276628,-0.00608027,0.00650299,0.04843161,0.02189479,0.05755542,-0.01459978]', 'user_id': '848f2ad9-2568-4a2d-b8a1-03669dcace5d', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 1.961s ago] {'embedding': '[-0.03089456,-0.02492464,0.04322281,0.17820162,-0.00587033,0.04237683,0.04210227,-0.03063672,0.02629010,0.00139019,0.08498203,-0.04209319,-0.04514636 ... (4131 characters truncated) ... .00055758,-0.07347211,-0.03782245,-0.11108061,-0.00666794,0.10907600,-0.06276628,-0.00608027,0.00650299,0.04843161,0.02189479,0.05755542,-0.01459978]', 'user_id': '848f2ad9-2568-4a2d-b8a1-03669dcace5d', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.3239, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.3239 < threshold 0.72 — nowa grupa

2026-03-14 20:48:32,653 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:32,654 INFO sqlalchemy.engine.Engine [cached since 1.949s ago] {'id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'name': 'Fioletowy Cypel', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 1.949s ago] {'id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'name': 'Fioletowy Cypel', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 0946e26a-2416-427b-80d3-cb4e30902b5b
INFO:dataset-notebook:Utworzono profil objawów dla test0005@zebra.pl

2026-03-14 20:48:32,691 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,692 INFO sqlalchemy.engine.Engine [cached since 1.943s ago] {'user_id_1': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.943s ago] {'user_id_1': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

2026-03-14 20:48:32,724 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:32,725 INFO sqlalchemy.engine.Engine [cached since 1.939s ago] {'member_count_1': 1, 'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 1.939s ago] {'member_count_1': 1, 'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}
INFO:app.services.matching_service:Dodano user 848f2ad9-2568-4a2d-b8a1-03669dcace5d do grupy 0946e26a-2416-427b-80d3-cb4e30902b5b

2026-03-14 20:48:32,759 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:32,760 INFO sqlalchemy.engine.Engine [cached since 1.545s ago] {'user_id': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'group_id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 1.545s ago] {'user_id': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'group_id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

2026-03-14 20:48:32,794 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:32,796 INFO sqlalchemy.engine.Engine [cached since 1.544s ago] {'id': UUID('2e1ed364-0710-430b-b752-f0b49ad56ab1'), 'user_id': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'description': 'Od urodzenia zauważyliśmy u córki bardzo jasną skórę i włosy, a oczy są bardzo wrażliwe na światło. Dodatkowo ma problemy ze wzrokiem i często mruży oczy nawet przy zwykłym świetle.', 'embedding': '[-0.030894555151462555,-0.024924635887145996,0.043222811073064804,0.1782016158103943,-0.005870329216122627,0.04237682744860649,0.04210227355360985,-0 ... (7778 characters truncated) ... 06485,-0.06276627629995346,-0.006080268882215023,0.006502991076558828,0.04843161255121231,0.0218947920948267,0.0575554221868515,-0.01459977775812149]', 'group_id': '0946e26a-2416-427b-80d3-cb4e30902b5b', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 1.544s ago] {'id': UUID('2e1ed364-0710-430b-b752-f0b49ad56ab1'), 'user_id': UUID('848f2ad9-2568-4a2d-b8a1-03669dcace5d'), 'description': 'Od urodzenia zauważyliśmy u córki bardzo jasną skórę i włosy, a oczy są bardzo wrażliwe na światło. Dodatkowo ma problemy ze wzrokiem i często mruży oczy nawet przy zwykłym świetle.', 'embedding': '[-0.030894555151462555,-0.024924635887145996,0.043222811073064804,0.1782016158103943,-0.005870329216122627,0.04237682744860649,0.04210227355360985,-0 ... (7778 characters truncated) ... 06485,-0.06276627629995346,-0.006080268882215023,0.006502991076558828,0.04843161255121231,0.0218947920948267,0.0575554221868515,-0.01459977775812149]', 'group_id': '0946e26a-2416-427b-80d3-cb4e30902b5b', 'match_score': 0.0}

2026-03-14 20:48:32,835 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:32,836 INFO sqlalchemy.engine.Engine [cached since 65.64s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 65.64s ago] {'email_1': 'test0006@zebra.pl', 'param_1': 1}

2026-03-14 20:48:32,868 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,869 INFO sqlalchemy.engine.Engine [cached since 7.152s ago] {'user_id_1': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.152s ago] {'user_id_1': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'param_1': 1}

2026-03-14 20:48:32,900 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:32,901 INFO sqlalchemy.engine.Engine [cached since 7.185s ago] {'user_id_1': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.185s ago] {'user_id_1': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'param_1': 1}

2026-03-14 20:48:32,990 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:32,991 INFO sqlalchemy.engine.Engine [cached since 2.333s ago] {'embedding': '[0.01609316,0.01428041,0.04049387,0.06799552,-0.01998048,0.02653299,-0.02103716,-0.01120311,-0.04462304,-0.09683438,0.04222181,-0.00411588,-0.0674272 ... (4120 characters truncated) ... 181,0.01777355,-0.01076198,0.03105317,0.05370526,0.00838882,-0.01879131,0.03357609,0.02116206,0.01904630,0.05660239,0.00272892,0.04683479,0.01403199]', 'user_id': '5c88b4dc-bbe5-461a-8982-ef2d3e10601b', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 2.333s ago] {'embedding': '[0.01609316,0.01428041,0.04049387,0.06799552,-0.01998048,0.02653299,-0.02103716,-0.01120311,-0.04462304,-0.09683438,0.04222181,-0.00411588,-0.0674272 ... (4120 characters truncated) ... 181,0.01777355,-0.01076198,0.03105317,0.05370526,0.00838882,-0.01879131,0.03357609,0.02116206,0.01904630,0.05660239,0.00272892,0.04683479,0.01403199]', 'user_id': '5c88b4dc-bbe5-461a-8982-ef2d3e10601b', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6848, group_id=49357027-f555-473a-8c72-cafd78dc5fc2
INFO:app.services.matching_service:Score 0.6848 < threshold 0.72 — nowa grupa

2026-03-14 20:48:33,029 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:33,031 INFO sqlalchemy.engine.Engine [cached since 2.326s ago] {'id': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee'), 'name': 'Koralowy Chmura', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 2.326s ago] {'id': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee'), 'name': 'Koralowy Chmura', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee
INFO:dataset-notebook:Utworzono profil objawów dla test0006@zebra.pl

2026-03-14 20:48:33,066 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,068 INFO sqlalchemy.engine.Engine [cached since 2.319s ago] {'user_id_1': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'group_id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.319s ago] {'user_id_1': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'group_id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee'), 'param_1': 1}

2026-03-14 20:48:33,103 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:33,105 INFO sqlalchemy.engine.Engine [cached since 2.318s ago] {'member_count_1': 1, 'id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

INFO:sqlalchemy.engine.Engine:[cached since 2.318s ago] {'member_count_1': 1, 'id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}
INFO:app.services.matching_service:Dodano user 5c88b4dc-bbe5-461a-8982-ef2d3e10601b do grupy bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee

2026-03-14 20:48:33,138 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:33,140 INFO sqlalchemy.engine.Engine [cached since 1.924s ago] {'user_id': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'group_id': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

INFO:sqlalchemy.engine.Engine:[cached since 1.924s ago] {'user_id': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'group_id': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

2026-03-14 20:48:33,172 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:33,175 INFO sqlalchemy.engine.Engine [cached since 1.923s ago] {'id': UUID('08d10481-c028-46c7-acfb-590bdfa7cd9b'), 'user_id': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'description': 'Syn od pierwszych miesięcy życia miał trudności z jedzeniem. Często się krztusił i długo trwało zanim nauczył się jeść stałe pokarmy. Nadal ma problem z połykaniem i wolno przybiera na wadze.', 'embedding': '[0.016093164682388306,0.014280412346124649,0.04049387201666832,0.06799551844596863,-0.019980475306510925,0.026532985270023346,-0.021037159487605095,- ... (7759 characters truncated) ... 2555,0.03357609361410141,0.02116205543279648,0.019046299159526825,0.056602392345666885,0.0027289160061627626,0.0468347929418087,0.014031985774636269]', 'group_id': 'bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 1.923s ago] {'id': UUID('08d10481-c028-46c7-acfb-590bdfa7cd9b'), 'user_id': UUID('5c88b4dc-bbe5-461a-8982-ef2d3e10601b'), 'description': 'Syn od pierwszych miesięcy życia miał trudności z jedzeniem. Często się krztusił i długo trwało zanim nauczył się jeść stałe pokarmy. Nadal ma problem z połykaniem i wolno przybiera na wadze.', 'embedding': '[0.016093164682388306,0.014280412346124649,0.04049387201666832,0.06799551844596863,-0.019980475306510925,0.026532985270023346,-0.021037159487605095,- ... (7759 characters truncated) ... 2555,0.03357609361410141,0.02116205543279648,0.019046299159526825,0.056602392345666885,0.0027289160061627626,0.0468347929418087,0.014031985774636269]', 'group_id': 'bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee', 'match_score': 0.0}

2026-03-14 20:48:33,209 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:33,210 INFO sqlalchemy.engine.Engine [cached since 66.02s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 66.02s ago] {'email_1': 'test0007@zebra.pl', 'param_1': 1}

2026-03-14 20:48:33,243 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,245 INFO sqlalchemy.engine.Engine [cached since 7.528s ago] {'user_id_1': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.528s ago] {'user_id_1': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'param_1': 1}

2026-03-14 20:48:33,275 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,277 INFO sqlalchemy.engine.Engine [cached since 7.56s ago] {'user_id_1': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.56s ago] {'user_id_1': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'param_1': 1}

2026-03-14 20:48:33,344 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:33,345 INFO sqlalchemy.engine.Engine [cached since 2.687s ago] {'embedding': '[0.05154179,0.00020815,0.08085739,0.00310334,-0.08716797,-0.02166122,0.01074692,-0.01581976,0.03634819,-0.00687062,0.07993110,0.04965155,-0.03255356, ... (4106 characters truncated) ... ,-0.00189141,-0.05961430,0.05986772,0.05866943,-0.00203134,0.07717549,-0.00506056,0.00996689,0.07968205,0.02879803,0.15309145,0.06576198,-0.00901361]', 'user_id': '5422831f-cf21-4f61-bb22-01a54112c087', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 2.687s ago] {'embedding': '[0.05154179,0.00020815,0.08085739,0.00310334,-0.08716797,-0.02166122,0.01074692,-0.01581976,0.03634819,-0.00687062,0.07993110,0.04965155,-0.03255356, ... (4106 characters truncated) ... ,-0.00189141,-0.05961430,0.05986772,0.05866943,-0.00203134,0.07717549,-0.00506056,0.00996689,0.07968205,0.02879803,0.15309145,0.06576198,-0.00901361]', 'user_id': '5422831f-cf21-4f61-bb22-01a54112c087', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6967, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6967 < threshold 0.72 — nowa grupa

2026-03-14 20:48:33,380 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:33,381 INFO sqlalchemy.engine.Engine [cached since 2.676s ago] {'id': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab'), 'name': 'Oliwkowy Kamień', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#ec4899', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 2.676s ago] {'id': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab'), 'name': 'Oliwkowy Kamień', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#ec4899', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: e9a71a4c-b2de-4a87-ac05-4d527d6745ab
INFO:dataset-notebook:Utworzono profil objawów dla test0007@zebra.pl

2026-03-14 20:48:33,416 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,418 INFO sqlalchemy.engine.Engine [cached since 2.669s ago] {'user_id_1': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'group_id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.669s ago] {'user_id_1': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'group_id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab'), 'param_1': 1}

2026-03-14 20:48:33,450 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:33,452 INFO sqlalchemy.engine.Engine [cached since 2.665s ago] {'member_count_1': 1, 'id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

INFO:sqlalchemy.engine.Engine:[cached since 2.665s ago] {'member_count_1': 1, 'id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}
INFO:app.services.matching_service:Dodano user 5422831f-cf21-4f61-bb22-01a54112c087 do grupy e9a71a4c-b2de-4a87-ac05-4d527d6745ab

2026-03-14 20:48:33,494 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:33,495 INFO sqlalchemy.engine.Engine [cached since 2.28s ago] {'user_id': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'group_id': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

INFO:sqlalchemy.engine.Engine:[cached since 2.28s ago] {'user_id': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'group_id': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

2026-03-14 20:48:33,526 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:33,527 INFO sqlalchemy.engine.Engine [cached since 2.276s ago] {'id': UUID('eae4167c-962e-4cee-b98f-f2c5dcfee782'), 'user_id': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'description': 'Nasze dziecko od małego bardzo mało mówiło. Teraz ma kilka lat i nadal używa głównie gestów. Rozumie dużo, ale nie potrafi wyrazić tego słowami.', 'embedding': '[0.05154178664088249,0.0002081466664094478,0.08085738867521286,0.0031033442355692387,-0.08716797083616257,-0.021661223843693733,0.010746918618679047, ... (7735 characters truncated) ... 14743,-0.005060562863945961,0.009966887533664703,0.07968205213546753,0.02879803441464901,0.1530914455652237,0.0657619759440422,-0.009013611823320389]', 'group_id': 'e9a71a4c-b2de-4a87-ac05-4d527d6745ab', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 2.276s ago] {'id': UUID('eae4167c-962e-4cee-b98f-f2c5dcfee782'), 'user_id': UUID('5422831f-cf21-4f61-bb22-01a54112c087'), 'description': 'Nasze dziecko od małego bardzo mało mówiło. Teraz ma kilka lat i nadal używa głównie gestów. Rozumie dużo, ale nie potrafi wyrazić tego słowami.', 'embedding': '[0.05154178664088249,0.0002081466664094478,0.08085738867521286,0.0031033442355692387,-0.08716797083616257,-0.021661223843693733,0.010746918618679047, ... (7735 characters truncated) ... 14743,-0.005060562863945961,0.009966887533664703,0.07968205213546753,0.02879803441464901,0.1530914455652237,0.0657619759440422,-0.009013611823320389]', 'group_id': 'e9a71a4c-b2de-4a87-ac05-4d527d6745ab', 'match_score': 0.0}

2026-03-14 20:48:33,561 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:33,562 INFO sqlalchemy.engine.Engine [cached since 66.37s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 66.37s ago] {'email_1': 'test0008@zebra.pl', 'param_1': 1}

2026-03-14 20:48:33,594 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,595 INFO sqlalchemy.engine.Engine [cached since 7.878s ago] {'user_id_1': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.878s ago] {'user_id_1': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'param_1': 1}

2026-03-14 20:48:33,625 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,626 INFO sqlalchemy.engine.Engine [cached since 7.91s ago] {'user_id_1': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.91s ago] {'user_id_1': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'param_1': 1}

2026-03-14 20:48:33,882 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:33,884 INFO sqlalchemy.engine.Engine [cached since 3.226s ago] {'embedding': '[-0.01861246,-0.02305472,0.02720427,0.11545838,0.03426404,0.03037735,-0.05075783,0.00952558,0.04303705,-0.00838241,0.05299958,0.07997693,-0.05517856, ... (4126 characters truncated) ... 0.02343686,-0.05070230,-0.01156512,0.03653572,0.03168765,-0.05119546,-0.03467692,-0.05764563,0.05846259,-0.00855320,0.03623848,0.06568575,0.03633334]', 'user_id': '3dc6ec89-ec55-492e-afc8-42a7a26a2808', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 3.226s ago] {'embedding': '[-0.01861246,-0.02305472,0.02720427,0.11545838,0.03426404,0.03037735,-0.05075783,0.00952558,0.04303705,-0.00838241,0.05299958,0.07997693,-0.05517856, ... (4126 characters truncated) ... 0.02343686,-0.05070230,-0.01156512,0.03653572,0.03168765,-0.05119546,-0.03467692,-0.05764563,0.05846259,-0.00855320,0.03623848,0.06568575,0.03633334]', 'user_id': '3dc6ec89-ec55-492e-afc8-42a7a26a2808', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7017, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.7017 < threshold 0.72 — nowa grupa

2026-03-14 20:48:33,920 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:33,921 INFO sqlalchemy.engine.Engine [cached since 3.216s ago] {'id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'name': 'Perłowy Mgła', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 3.216s ago] {'id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'name': 'Perłowy Mgła', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: a3bc3fbb-f3a1-4c34-906e-a6676e30d21c
INFO:dataset-notebook:Utworzono profil objawów dla test0008@zebra.pl

2026-03-14 20:48:33,967 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:33,969 INFO sqlalchemy.engine.Engine [cached since 3.221s ago] {'user_id_1': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.221s ago] {'user_id_1': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

2026-03-14 20:48:34,003 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:34,005 INFO sqlalchemy.engine.Engine [cached since 3.218s ago] {'member_count_1': 1, 'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 3.218s ago] {'member_count_1': 1, 'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}
INFO:app.services.matching_service:Dodano user 3dc6ec89-ec55-492e-afc8-42a7a26a2808 do grupy a3bc3fbb-f3a1-4c34-906e-a6676e30d21c

2026-03-14 20:48:34,042 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:34,044 INFO sqlalchemy.engine.Engine [cached since 2.829s ago] {'user_id': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'group_id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 2.829s ago] {'user_id': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'group_id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

2026-03-14 20:48:34,076 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:34,078 INFO sqlalchemy.engine.Engine [cached since 2.826s ago] {'id': UUID('a112c25f-30f5-4e3c-ab65-6dd6fc58d211'), 'user_id': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'description': 'Córka od niemowlęctwa miała częste napady drgawek. Oprócz tego rozwój ruchowy jest opóźniony. Nadal ma trudności z chodzeniem i utrzymaniem równowagi.', 'embedding': '[-0.018612457439303398,-0.023054715245962143,0.027204271405935287,0.11545838415622711,0.034264035522937775,0.030377354472875595,-0.05075782537460327, ... (7733 characters truncated) ... 8,-0.034676920622587204,-0.05764563009142876,0.05846259370446205,-0.008553195744752884,0.036238476634025574,0.06568574905395508,0.036333341151475906]', 'group_id': 'a3bc3fbb-f3a1-4c34-906e-a6676e30d21c', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 2.826s ago] {'id': UUID('a112c25f-30f5-4e3c-ab65-6dd6fc58d211'), 'user_id': UUID('3dc6ec89-ec55-492e-afc8-42a7a26a2808'), 'description': 'Córka od niemowlęctwa miała częste napady drgawek. Oprócz tego rozwój ruchowy jest opóźniony. Nadal ma trudności z chodzeniem i utrzymaniem równowagi.', 'embedding': '[-0.018612457439303398,-0.023054715245962143,0.027204271405935287,0.11545838415622711,0.034264035522937775,0.030377354472875595,-0.05075782537460327, ... (7733 characters truncated) ... 8,-0.034676920622587204,-0.05764563009142876,0.05846259370446205,-0.008553195744752884,0.036238476634025574,0.06568574905395508,0.036333341151475906]', 'group_id': 'a3bc3fbb-f3a1-4c34-906e-a6676e30d21c', 'match_score': 0.0}

2026-03-14 20:48:34,110 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:34,111 INFO sqlalchemy.engine.Engine [cached since 66.92s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 66.92s ago] {'email_1': 'test0009@zebra.pl', 'param_1': 1}

2026-03-14 20:48:34,143 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,144 INFO sqlalchemy.engine.Engine [cached since 8.427s ago] {'user_id_1': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.427s ago] {'user_id_1': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'param_1': 1}

2026-03-14 20:48:34,177 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,178 INFO sqlalchemy.engine.Engine [cached since 8.462s ago] {'user_id_1': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.462s ago] {'user_id_1': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'param_1': 1}

2026-03-14 20:48:34,246 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:34,248 INFO sqlalchemy.engine.Engine [cached since 3.59s ago] {'embedding': '[0.03400711,0.07946134,0.01549844,0.07987376,-0.00844862,0.02102081,-0.03513885,0.04925289,0.04253214,-0.00983175,0.11092713,-0.03863212,-0.02745391, ... (4123 characters truncated) ... 9,0.05431164,-0.05646853,-0.01383347,0.02728384,0.04386000,0.00226450,0.02402487,-0.01481983,0.03386899,0.03064375,0.07007224,0.06827872,-0.01327370]', 'user_id': '3f428c45-9fa1-4b11-bce4-4c4f471b41a3', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 3.59s ago] {'embedding': '[0.03400711,0.07946134,0.01549844,0.07987376,-0.00844862,0.02102081,-0.03513885,0.04925289,0.04253214,-0.00983175,0.11092713,-0.03863212,-0.02745391, ... (4123 characters truncated) ... 9,0.05431164,-0.05646853,-0.01383347,0.02728384,0.04386000,0.00226450,0.02402487,-0.01481983,0.03386899,0.03064375,0.07007224,0.06827872,-0.01327370]', 'user_id': '3f428c45-9fa1-4b11-bce4-4c4f471b41a3', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7257, group_id=49357027-f555-473a-8c72-cafd78dc5fc2

2026-03-14 20:48:34,285 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,286 INFO sqlalchemy.engine.Engine [generated in 0.00112s] {'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[generated in 0.00112s] {'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Kremowy Przylądek' (score=0.7257)
INFO:dataset-notebook:Utworzono profil objawów dla test0009@zebra.pl

2026-03-14 20:48:34,325 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,326 INFO sqlalchemy.engine.Engine [cached since 3.577s ago] {'user_id_1': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.577s ago] {'user_id_1': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

2026-03-14 20:48:34,359 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:34,360 INFO sqlalchemy.engine.Engine [cached since 3.574s ago] {'member_count_1': 1, 'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 3.574s ago] {'member_count_1': 1, 'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}
INFO:app.services.matching_service:Dodano user 3f428c45-9fa1-4b11-bce4-4c4f471b41a3 do grupy 49357027-f555-473a-8c72-cafd78dc5fc2

2026-03-14 20:48:34,395 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:34,397 INFO sqlalchemy.engine.Engine [cached since 3.181s ago] {'user_id': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'group_id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 3.181s ago] {'user_id': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'group_id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

2026-03-14 20:48:34,426 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:34,428 INFO sqlalchemy.engine.Engine [cached since 3.177s ago] {'id': UUID('78e9c30b-0309-4884-af23-448490c4406e'), 'user_id': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'description': 'Syn urodził się z bardzo małą głową w stosunku do reszty ciała. W miarę dorastania zaczęliśmy zauważać też trudności w nauce i koncentracji.', 'embedding': '[0.034007105976343155,0.07946134358644485,0.015498443506658077,0.07987376302480698,-0.00844862125813961,0.021020811051130295,-0.03513885289430618,0.0 ... (7732 characters truncated) ... 00204,0.024024873971939087,-0.014819826930761337,0.03386899083852768,0.030643753707408905,0.070072241127491,0.0682787224650383,-0.013273696415126324]', 'group_id': '49357027-f555-473a-8c72-cafd78dc5fc2', 'match_score': 0.72570394362568}

INFO:sqlalchemy.engine.Engine:[cached since 3.177s ago] {'id': UUID('78e9c30b-0309-4884-af23-448490c4406e'), 'user_id': UUID('3f428c45-9fa1-4b11-bce4-4c4f471b41a3'), 'description': 'Syn urodził się z bardzo małą głową w stosunku do reszty ciała. W miarę dorastania zaczęliśmy zauważać też trudności w nauce i koncentracji.', 'embedding': '[0.034007105976343155,0.07946134358644485,0.015498443506658077,0.07987376302480698,-0.00844862125813961,0.021020811051130295,-0.03513885289430618,0.0 ... (7732 characters truncated) ... 00204,0.024024873971939087,-0.014819826930761337,0.03386899083852768,0.030643753707408905,0.070072241127491,0.0682787224650383,-0.013273696415126324]', 'group_id': '49357027-f555-473a-8c72-cafd78dc5fc2', 'match_score': 0.72570394362568}

2026-03-14 20:48:34,460 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:34,461 INFO sqlalchemy.engine.Engine [cached since 67.27s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 67.27s ago] {'email_1': 'test0010@zebra.pl', 'param_1': 1}

2026-03-14 20:48:34,493 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,495 INFO sqlalchemy.engine.Engine [cached since 8.778s ago] {'user_id_1': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.778s ago] {'user_id_1': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'param_1': 1}

2026-03-14 20:48:34,526 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,528 INFO sqlalchemy.engine.Engine [cached since 8.811s ago] {'user_id_1': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.811s ago] {'user_id_1': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'param_1': 1}

2026-03-14 20:48:34,603 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:34,605 INFO sqlalchemy.engine.Engine [cached since 3.947s ago] {'embedding': '[-0.02853801,-0.05344073,0.08271850,0.06142168,-0.00604626,-0.04511748,-0.01848769,0.03423043,0.00890278,0.00474999,0.00939463,0.15349925,-0.06569830 ... (4119 characters truncated) ... 0.01787807,-0.05055830,-0.03879233,-0.02825747,0.01900730,-0.01649765,-0.03481504,-0.03758900,0.03226066,0.01176798,0.04888741,0.00975867,0.05785649]', 'user_id': '5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 3.947s ago] {'embedding': '[-0.02853801,-0.05344073,0.08271850,0.06142168,-0.00604626,-0.04511748,-0.01848769,0.03423043,0.00890278,0.00474999,0.00939463,0.15349925,-0.06569830 ... (4119 characters truncated) ... 0.01787807,-0.05055830,-0.03879233,-0.02825747,0.01900730,-0.01649765,-0.03481504,-0.03758900,0.03226066,0.01176798,0.04888741,0.00975867,0.05785649]', 'user_id': '5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6525, group_id=a3bc3fbb-f3a1-4c34-906e-a6676e30d21c
INFO:app.services.matching_service:Score 0.6525 < threshold 0.72 — nowa grupa

2026-03-14 20:48:34,641 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:34,642 INFO sqlalchemy.engine.Engine [cached since 3.937s ago] {'id': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff'), 'name': 'Fioletowy Opal', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 3.937s ago] {'id': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff'), 'name': 'Fioletowy Opal', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 381f180d-adc3-4a20-a80a-76d8ef0793ff
INFO:dataset-notebook:Utworzono profil objawów dla test0010@zebra.pl

2026-03-14 20:48:34,675 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,677 INFO sqlalchemy.engine.Engine [cached since 3.928s ago] {'user_id_1': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'group_id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.928s ago] {'user_id_1': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'group_id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff'), 'param_1': 1}

2026-03-14 20:48:34,710 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:34,711 INFO sqlalchemy.engine.Engine [cached since 3.924s ago] {'member_count_1': 1, 'id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

INFO:sqlalchemy.engine.Engine:[cached since 3.924s ago] {'member_count_1': 1, 'id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}
INFO:app.services.matching_service:Dodano user 5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa do grupy 381f180d-adc3-4a20-a80a-76d8ef0793ff

2026-03-14 20:48:34,746 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:34,749 INFO sqlalchemy.engine.Engine [cached since 3.534s ago] {'user_id': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'group_id': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

INFO:sqlalchemy.engine.Engine:[cached since 3.534s ago] {'user_id': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'group_id': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

2026-03-14 20:48:34,783 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:34,784 INFO sqlalchemy.engine.Engine [cached since 3.533s ago] {'id': UUID('1bcf2386-a99d-4852-a854-e626c01c6054'), 'user_id': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'description': 'Nasza córka ma bardzo elastyczne stawy. Może wyginać ręce i palce w nienaturalny sposób. Często skarży się też na bóle stawów po dłuższym chodzeniu.', 'embedding': '[-0.028538009151816368,-0.05344073474407196,0.08271849900484085,0.06142168119549751,-0.006046263035386801,-0.04511747509241104,-0.01848769001662731,0 ... (7735 characters truncated) ... 853,-0.03481503948569298,-0.037588998675346375,0.03226066008210182,0.011767975986003876,0.048887405544519424,0.009758666157722473,0.0578564889729023]', 'group_id': '381f180d-adc3-4a20-a80a-76d8ef0793ff', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 3.533s ago] {'id': UUID('1bcf2386-a99d-4852-a854-e626c01c6054'), 'user_id': UUID('5c2d418d-9dd0-42a4-b814-f4f09ed8fdaa'), 'description': 'Nasza córka ma bardzo elastyczne stawy. Może wyginać ręce i palce w nienaturalny sposób. Często skarży się też na bóle stawów po dłuższym chodzeniu.', 'embedding': '[-0.028538009151816368,-0.05344073474407196,0.08271849900484085,0.06142168119549751,-0.006046263035386801,-0.04511747509241104,-0.01848769001662731,0 ... (7735 characters truncated) ... 853,-0.03481503948569298,-0.037588998675346375,0.03226066008210182,0.011767975986003876,0.048887405544519424,0.009758666157722473,0.0578564889729023]', 'group_id': '381f180d-adc3-4a20-a80a-76d8ef0793ff', 'match_score': 0.0}

2026-03-14 20:48:34,819 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:34,821 INFO sqlalchemy.engine.Engine [cached since 67.63s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 67.63s ago] {'email_1': 'test0011@zebra.pl', 'param_1': 1}

2026-03-14 20:48:34,852 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,853 INFO sqlalchemy.engine.Engine [cached since 9.137s ago] {'user_id_1': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.137s ago] {'user_id_1': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'param_1': 1}

2026-03-14 20:48:34,888 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,890 INFO sqlalchemy.engine.Engine [cached since 9.173s ago] {'user_id_1': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.173s ago] {'user_id_1': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'param_1': 1}

2026-03-14 20:48:34,961 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:34,962 INFO sqlalchemy.engine.Engine [cached since 4.304s ago] {'embedding': '[-0.00113007,0.02758826,0.03500389,0.03201398,-0.00952320,0.04841944,-0.05751579,-0.01003309,-0.00634426,-0.04225763,0.11307990,0.08122982,-0.0293004 ... (4115 characters truncated) ... 0.05300842,-0.03095408,-0.03886997,0.05529934,-0.01415250,-0.13148144,0.02509263,-0.06897712,-0.00956265,0.03620233,0.06094299,0.01339536,0.03822947]', 'user_id': '868444f3-268e-42fa-ab48-0b29b7a0a19e', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 4.304s ago] {'embedding': '[-0.00113007,0.02758826,0.03500389,0.03201398,-0.00952320,0.04841944,-0.05751579,-0.01003309,-0.00634426,-0.04225763,0.11307990,0.08122982,-0.0293004 ... (4115 characters truncated) ... 0.05300842,-0.03095408,-0.03886997,0.05529934,-0.01415250,-0.13148144,0.02509263,-0.06897712,-0.00956265,0.03620233,0.06094299,0.01339536,0.03822947]', 'user_id': '868444f3-268e-42fa-ab48-0b29b7a0a19e', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8175, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:34,997 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:34,999 INFO sqlalchemy.engine.Engine [cached since 0.7134s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 0.7134s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.8175)
INFO:dataset-notebook:Utworzono profil objawów dla test0011@zebra.pl

2026-03-14 20:48:35,033 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,035 INFO sqlalchemy.engine.Engine [cached since 4.286s ago] {'user_id_1': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.286s ago] {'user_id_1': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:35,069 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:35,070 INFO sqlalchemy.engine.Engine [cached since 4.283s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 4.283s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 868444f3-268e-42fa-ab48-0b29b7a0a19e do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:35,102 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:35,103 INFO sqlalchemy.engine.Engine [cached since 3.888s ago] {'user_id': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 3.888s ago] {'user_id': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:35,133 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:35,134 INFO sqlalchemy.engine.Engine [cached since 3.883s ago] {'id': UUID('9271e512-5a42-4356-b165-63c6b84ad54c'), 'user_id': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'description': 'Syn od małego miał problemy z napięciem mięśniowym. Był bardzo sztywny, a później pojawiły się trudności z chodzeniem. Teraz jego ruchy są powolne i niezgrabne.', 'embedding': '[-0.001130065182223916,0.02758825570344925,0.035003893077373505,0.03201398253440857,-0.009523199871182442,0.04841943830251694,-0.05751578509807587,-0 ... (7745 characters truncated) ... 519836,0.025092627853155136,-0.06897712498903275,-0.00956264790147543,0.0362023264169693,0.06094299256801605,0.01339536439627409,0.03822946920990944]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.817473113536858}

INFO:sqlalchemy.engine.Engine:[cached since 3.883s ago] {'id': UUID('9271e512-5a42-4356-b165-63c6b84ad54c'), 'user_id': UUID('868444f3-268e-42fa-ab48-0b29b7a0a19e'), 'description': 'Syn od małego miał problemy z napięciem mięśniowym. Był bardzo sztywny, a później pojawiły się trudności z chodzeniem. Teraz jego ruchy są powolne i niezgrabne.', 'embedding': '[-0.001130065182223916,0.02758825570344925,0.035003893077373505,0.03201398253440857,-0.009523199871182442,0.04841943830251694,-0.05751578509807587,-0 ... (7745 characters truncated) ... 519836,0.025092627853155136,-0.06897712498903275,-0.00956264790147543,0.0362023264169693,0.06094299256801605,0.01339536439627409,0.03822946920990944]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.817473113536858}

2026-03-14 20:48:35,168 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:35,169 INFO sqlalchemy.engine.Engine [cached since 67.98s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 67.98s ago] {'email_1': 'test0012@zebra.pl', 'param_1': 1}

2026-03-14 20:48:35,200 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,202 INFO sqlalchemy.engine.Engine [cached since 9.485s ago] {'user_id_1': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.485s ago] {'user_id_1': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'param_1': 1}

2026-03-14 20:48:35,234 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,239 INFO sqlalchemy.engine.Engine [cached since 9.522s ago] {'user_id_1': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.522s ago] {'user_id_1': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'param_1': 1}

2026-03-14 20:48:35,380 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:35,382 INFO sqlalchemy.engine.Engine [cached since 4.724s ago] {'embedding': '[0.02631582,0.02412429,0.03351023,0.03258931,-0.09127256,0.01889204,-0.04003090,0.03156361,-0.00876823,-0.03922770,0.09239661,0.11695263,-0.02509193, ... (4114 characters truncated) ... ,0.04220046,-0.08355013,0.01488695,0.06514744,-0.02138219,0.00575161,0.04542048,-0.09511197,0.03497684,-0.01393509,0.10082942,0.05903622,-0.01486600]', 'user_id': 'ed2d0939-2c84-47b3-bb2a-6a42597bb98d', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 4.724s ago] {'embedding': '[0.02631582,0.02412429,0.03351023,0.03258931,-0.09127256,0.01889204,-0.04003090,0.03156361,-0.00876823,-0.03922770,0.09239661,0.11695263,-0.02509193, ... (4114 characters truncated) ... ,0.04220046,-0.08355013,0.01488695,0.06514744,-0.02138219,0.00575161,0.04542048,-0.09511197,0.03497684,-0.01393509,0.10082942,0.05903622,-0.01486600]', 'user_id': 'ed2d0939-2c84-47b3-bb2a-6a42597bb98d', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7134, group_id=e9a71a4c-b2de-4a87-ac05-4d527d6745ab
INFO:app.services.matching_service:Score 0.7134 < threshold 0.72 — nowa grupa

2026-03-14 20:48:35,418 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:35,419 INFO sqlalchemy.engine.Engine [cached since 4.714s ago] {'id': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9'), 'name': 'Jadeitowy Łąka', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#06b6d4', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 4.714s ago] {'id': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9'), 'name': 'Jadeitowy Łąka', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#06b6d4', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: e1fc2c14-04c6-4cd7-b932-7805776a8ba9
INFO:dataset-notebook:Utworzono profil objawów dla test0012@zebra.pl

2026-03-14 20:48:35,454 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,456 INFO sqlalchemy.engine.Engine [cached since 4.708s ago] {'user_id_1': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'group_id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.708s ago] {'user_id_1': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'group_id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9'), 'param_1': 1}

2026-03-14 20:48:35,489 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:35,490 INFO sqlalchemy.engine.Engine [cached since 4.703s ago] {'member_count_1': 1, 'id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

INFO:sqlalchemy.engine.Engine:[cached since 4.703s ago] {'member_count_1': 1, 'id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}
INFO:app.services.matching_service:Dodano user ed2d0939-2c84-47b3-bb2a-6a42597bb98d do grupy e1fc2c14-04c6-4cd7-b932-7805776a8ba9

2026-03-14 20:48:35,537 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:35,544 INFO sqlalchemy.engine.Engine [cached since 4.329s ago] {'user_id': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'group_id': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

INFO:sqlalchemy.engine.Engine:[cached since 4.329s ago] {'user_id': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'group_id': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

2026-03-14 20:48:35,576 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:35,578 INFO sqlalchemy.engine.Engine [cached since 4.327s ago] {'id': UUID('f0411290-b5dd-4265-a1ea-64206e7d2460'), 'user_id': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'description': 'Nasze dziecko rozwijało się prawidłowo do około drugiego roku życia, a potem zaczęło tracić niektóre umiejętności. Przestało mówić kilka słów, które wcześniej używało.', 'embedding': '[0.026315821334719658,0.02412428706884384,0.0335102304816246,0.03258930519223213,-0.09127256274223328,0.018892042338848114,-0.04003090411424637,0.031 ... (7729 characters truncated) ... 9,0.04542047902941704,-0.09511197358369827,0.034976840019226074,-0.013935087248682976,0.10082941502332687,0.059036217629909515,-0.014866002835333347]', 'group_id': 'e1fc2c14-04c6-4cd7-b932-7805776a8ba9', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 4.327s ago] {'id': UUID('f0411290-b5dd-4265-a1ea-64206e7d2460'), 'user_id': UUID('ed2d0939-2c84-47b3-bb2a-6a42597bb98d'), 'description': 'Nasze dziecko rozwijało się prawidłowo do około drugiego roku życia, a potem zaczęło tracić niektóre umiejętności. Przestało mówić kilka słów, które wcześniej używało.', 'embedding': '[0.026315821334719658,0.02412428706884384,0.0335102304816246,0.03258930519223213,-0.09127256274223328,0.018892042338848114,-0.04003090411424637,0.031 ... (7729 characters truncated) ... 9,0.04542047902941704,-0.09511197358369827,0.034976840019226074,-0.013935087248682976,0.10082941502332687,0.059036217629909515,-0.014866002835333347]', 'group_id': 'e1fc2c14-04c6-4cd7-b932-7805776a8ba9', 'match_score': 0.0}

2026-03-14 20:48:35,612 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:35,615 INFO sqlalchemy.engine.Engine [cached since 68.42s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 68.42s ago] {'email_1': 'test0013@zebra.pl', 'param_1': 1}

2026-03-14 20:48:35,649 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,651 INFO sqlalchemy.engine.Engine [cached since 9.934s ago] {'user_id_1': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.934s ago] {'user_id_1': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'param_1': 1}

2026-03-14 20:48:35,683 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,684 INFO sqlalchemy.engine.Engine [cached since 9.967s ago] {'user_id_1': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.967s ago] {'user_id_1': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'param_1': 1}

2026-03-14 20:48:35,747 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:35,749 INFO sqlalchemy.engine.Engine [cached since 5.091s ago] {'embedding': '[0.05182691,0.01194670,-0.01251733,0.02988251,-0.04598738,0.01701358,-0.05570948,-0.04121822,0.06017401,-0.01617072,0.02947733,0.05836194,-0.02402733 ... (4121 characters truncated) ... ,-0.01746113,-0.03948715,-0.01968628,0.02809812,0.05406711,0.02635898,0.03515282,-0.04663210,0.10088472,-0.02399557,0.07112296,0.04828358,0.00512847]', 'user_id': '66682617-540c-4ee3-8863-e8636a1bdbdd', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 5.091s ago] {'embedding': '[0.05182691,0.01194670,-0.01251733,0.02988251,-0.04598738,0.01701358,-0.05570948,-0.04121822,0.06017401,-0.01617072,0.02947733,0.05836194,-0.02402733 ... (4121 characters truncated) ... ,-0.01746113,-0.03948715,-0.01968628,0.02809812,0.05406711,0.02635898,0.03515282,-0.04663210,0.10088472,-0.02399557,0.07112296,0.04828358,0.00512847]', 'user_id': '66682617-540c-4ee3-8863-e8636a1bdbdd', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5970, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.5970 < threshold 0.72 — nowa grupa

2026-03-14 20:48:35,787 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:35,792 INFO sqlalchemy.engine.Engine [cached since 5.087s ago] {'id': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb'), 'name': 'Bursztynowy Topaz', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#06b6d4', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 5.087s ago] {'id': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb'), 'name': 'Bursztynowy Topaz', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#06b6d4', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 3c8705ba-ea53-4263-b938-42b64aee1feb
INFO:dataset-notebook:Utworzono profil objawów dla test0013@zebra.pl

2026-03-14 20:48:35,829 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:35,831 INFO sqlalchemy.engine.Engine [cached since 5.082s ago] {'user_id_1': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'group_id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.082s ago] {'user_id_1': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'group_id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb'), 'param_1': 1}

2026-03-14 20:48:35,863 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:35,865 INFO sqlalchemy.engine.Engine [cached since 5.078s ago] {'member_count_1': 1, 'id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

INFO:sqlalchemy.engine.Engine:[cached since 5.078s ago] {'member_count_1': 1, 'id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}
INFO:app.services.matching_service:Dodano user 66682617-540c-4ee3-8863-e8636a1bdbdd do grupy 3c8705ba-ea53-4263-b938-42b64aee1feb

2026-03-14 20:48:35,897 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:35,899 INFO sqlalchemy.engine.Engine [cached since 4.684s ago] {'user_id': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'group_id': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

INFO:sqlalchemy.engine.Engine:[cached since 4.684s ago] {'user_id': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'group_id': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

2026-03-14 20:48:35,931 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:35,932 INFO sqlalchemy.engine.Engine [cached since 4.681s ago] {'id': UUID('4a823556-bb4d-4960-93f8-9c63ce99df05'), 'user_id': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'description': 'Córka od urodzenia ma problemy ze słuchem. Musimy mówić bardzo głośno, żeby reagowała. Dodatkowo rozwój mowy jest opóźniony.', 'embedding': '[0.05182690918445587,0.01194669958204031,-0.012517333962023258,0.029882512986660004,-0.04598738253116608,0.01701357774436474,-0.055709484964609146,-0 ... (7740 characters truncated) ... 2734,0.03515281900763512,-0.04663209617137909,0.10088472068309784,-0.023995572701096535,0.07112295925617218,0.04828358441591263,0.005128472112119198]', 'group_id': '3c8705ba-ea53-4263-b938-42b64aee1feb', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 4.681s ago] {'id': UUID('4a823556-bb4d-4960-93f8-9c63ce99df05'), 'user_id': UUID('66682617-540c-4ee3-8863-e8636a1bdbdd'), 'description': 'Córka od urodzenia ma problemy ze słuchem. Musimy mówić bardzo głośno, żeby reagowała. Dodatkowo rozwój mowy jest opóźniony.', 'embedding': '[0.05182690918445587,0.01194669958204031,-0.012517333962023258,0.029882512986660004,-0.04598738253116608,0.01701357774436474,-0.055709484964609146,-0 ... (7740 characters truncated) ... 2734,0.03515281900763512,-0.04663209617137909,0.10088472068309784,-0.023995572701096535,0.07112295925617218,0.04828358441591263,0.005128472112119198]', 'group_id': '3c8705ba-ea53-4263-b938-42b64aee1feb', 'match_score': 0.0}

2026-03-14 20:48:35,968 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:35,969 INFO sqlalchemy.engine.Engine [cached since 68.78s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 68.78s ago] {'email_1': 'test0014@zebra.pl', 'param_1': 1}

2026-03-14 20:48:36,000 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,001 INFO sqlalchemy.engine.Engine [cached since 10.28s ago] {'user_id_1': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.28s ago] {'user_id_1': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'param_1': 1}

2026-03-14 20:48:36,031 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,032 INFO sqlalchemy.engine.Engine [cached since 10.32s ago] {'user_id_1': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.32s ago] {'user_id_1': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'param_1': 1}

2026-03-14 20:48:36,106 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:36,107 INFO sqlalchemy.engine.Engine [cached since 5.449s ago] {'embedding': '[0.06421631,0.00213745,-0.00630814,0.00474824,-0.05020940,-0.00640019,-0.00305836,0.02629710,0.00677376,-0.06209185,0.09135442,0.04314631,-0.08393058 ... (4117 characters truncated) ... 0.01890947,0.00779492,-0.01590102,0.00601788,0.02659781,-0.08280694,-0.02975974,-0.10260634,-0.01164956,0.04688635,0.06410020,-0.00216987,0.05183437]', 'user_id': 'c15847cb-ac9d-4898-b501-fcfc9e93aaf3', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 5.449s ago] {'embedding': '[0.06421631,0.00213745,-0.00630814,0.00474824,-0.05020940,-0.00640019,-0.00305836,0.02629710,0.00677376,-0.06209185,0.09135442,0.04314631,-0.08393058 ... (4117 characters truncated) ... 0.01890947,0.00779492,-0.01590102,0.00601788,0.02659781,-0.08280694,-0.02975974,-0.10260634,-0.01164956,0.04688635,0.06410020,-0.00216987,0.05183437]', 'user_id': 'c15847cb-ac9d-4898-b501-fcfc9e93aaf3', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7544, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:36,141 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,143 INFO sqlalchemy.engine.Engine [cached since 1.857s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 1.857s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.7544)
INFO:dataset-notebook:Utworzono profil objawów dla test0014@zebra.pl

2026-03-14 20:48:36,177 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,179 INFO sqlalchemy.engine.Engine [cached since 5.431s ago] {'user_id_1': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.431s ago] {'user_id_1': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:36,212 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:36,213 INFO sqlalchemy.engine.Engine [cached since 5.426s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 5.426s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user c15847cb-ac9d-4898-b501-fcfc9e93aaf3 do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:36,247 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:36,248 INFO sqlalchemy.engine.Engine [cached since 5.033s ago] {'user_id': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 5.033s ago] {'user_id': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:36,280 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:36,281 INFO sqlalchemy.engine.Engine [cached since 5.03s ago] {'id': UUID('c2bf1121-ac38-4b6d-80c6-8f5d6166ab25'), 'user_id': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'description': 'Syn ma bardzo charakterystyczny sposób chodzenia. Chodzi na szeroko rozstawionych nogach i często traci równowagę. Lekarze podejrzewają problem neurologiczny.', 'embedding': '[0.06421630829572678,0.002137451898306608,-0.006308137439191341,0.0047482387162745,-0.0502094030380249,-0.006400193087756634,-0.0030583571642637253,0 ... (7748 characters truncated) ... -0.029759738594293594,-0.10260634124279022,-0.011649561114609241,0.046886347234249115,0.06410019844770432,-0.0021698661148548126,0.05183436721563339]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.754430860809196}

INFO:sqlalchemy.engine.Engine:[cached since 5.03s ago] {'id': UUID('c2bf1121-ac38-4b6d-80c6-8f5d6166ab25'), 'user_id': UUID('c15847cb-ac9d-4898-b501-fcfc9e93aaf3'), 'description': 'Syn ma bardzo charakterystyczny sposób chodzenia. Chodzi na szeroko rozstawionych nogach i często traci równowagę. Lekarze podejrzewają problem neurologiczny.', 'embedding': '[0.06421630829572678,0.002137451898306608,-0.006308137439191341,0.0047482387162745,-0.0502094030380249,-0.006400193087756634,-0.0030583571642637253,0 ... (7748 characters truncated) ... -0.029759738594293594,-0.10260634124279022,-0.011649561114609241,0.046886347234249115,0.06410019844770432,-0.0021698661148548126,0.05183436721563339]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.754430860809196}

2026-03-14 20:48:36,313 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:36,314 INFO sqlalchemy.engine.Engine [cached since 69.12s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 69.12s ago] {'email_1': 'test0015@zebra.pl', 'param_1': 1}

2026-03-14 20:48:36,348 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,349 INFO sqlalchemy.engine.Engine [cached since 10.63s ago] {'user_id_1': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.63s ago] {'user_id_1': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'param_1': 1}

2026-03-14 20:48:36,380 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,381 INFO sqlalchemy.engine.Engine [cached since 10.66s ago] {'user_id_1': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.66s ago] {'user_id_1': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'param_1': 1}

2026-03-14 20:48:36,467 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:36,468 INFO sqlalchemy.engine.Engine [cached since 5.81s ago] {'embedding': '[0.06006022,0.03177680,0.03914336,0.03786058,-0.00566783,-0.01177612,-0.05056935,0.00808808,0.05443942,-0.03629728,0.11514044,0.12822099,0.03269987,0 ... (4112 characters truncated) ... 6,0.03974755,-0.07773713,0.04373819,0.05531845,-0.01608494,0.01919727,0.00467377,-0.01332904,0.02495748,-0.00081165,0.12868978,0.03057407,0.01494474]', 'user_id': 'a6722e60-9084-41e3-a915-8b26ff239e14', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 5.81s ago] {'embedding': '[0.06006022,0.03177680,0.03914336,0.03786058,-0.00566783,-0.01177612,-0.05056935,0.00808808,0.05443942,-0.03629728,0.11514044,0.12822099,0.03269987,0 ... (4112 characters truncated) ... 6,0.03974755,-0.07773713,0.04373819,0.05531845,-0.01608494,0.01919727,0.00467377,-0.01332904,0.02495748,-0.00081165,0.12868978,0.03057407,0.01494474]', 'user_id': 'a6722e60-9084-41e3-a915-8b26ff239e14', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6683, group_id=e1fc2c14-04c6-4cd7-b932-7805776a8ba9
INFO:app.services.matching_service:Score 0.6683 < threshold 0.72 — nowa grupa

2026-03-14 20:48:36,504 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:36,505 INFO sqlalchemy.engine.Engine [cached since 5.8s ago] {'id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'name': 'Złoty Horyzont', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 5.8s ago] {'id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'name': 'Złoty Horyzont', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef
INFO:dataset-notebook:Utworzono profil objawów dla test0015@zebra.pl

2026-03-14 20:48:36,537 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,538 INFO sqlalchemy.engine.Engine [cached since 5.79s ago] {'user_id_1': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.79s ago] {'user_id_1': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

2026-03-14 20:48:36,569 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:36,570 INFO sqlalchemy.engine.Engine [cached since 5.783s ago] {'member_count_1': 1, 'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 5.783s ago] {'member_count_1': 1, 'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}
INFO:app.services.matching_service:Dodano user a6722e60-9084-41e3-a915-8b26ff239e14 do grupy ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef

2026-03-14 20:48:36,604 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:36,606 INFO sqlalchemy.engine.Engine [cached since 5.391s ago] {'user_id': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'group_id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 5.391s ago] {'user_id': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'group_id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

2026-03-14 20:48:36,640 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:36,641 INFO sqlalchemy.engine.Engine [cached since 5.39s ago] {'id': UUID('e950ee35-cf7b-4b6e-8c87-fa30c85cc5ed'), 'user_id': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'description': 'Nasza córka od małego była bardzo spokojna i mało reagowała na otoczenie. Z czasem zauważyliśmy też opóźnienie w rozwoju mowy i trudności w kontaktach z innymi dziećmi.', 'embedding': '[0.06006022170186043,0.031776804476976395,0.039143357425928116,0.037860576063394547,-0.0056678252294659615,-0.011776119470596313,-0.05056934803724289 ... (7754 characters truncated) ... 3,0.004673773888498545,-0.013329035602509975,0.024957481771707535,-0.000811647332739085,0.12868978083133698,0.030574068427085876,0.01494473684579134]', 'group_id': 'ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 5.39s ago] {'id': UUID('e950ee35-cf7b-4b6e-8c87-fa30c85cc5ed'), 'user_id': UUID('a6722e60-9084-41e3-a915-8b26ff239e14'), 'description': 'Nasza córka od małego była bardzo spokojna i mało reagowała na otoczenie. Z czasem zauważyliśmy też opóźnienie w rozwoju mowy i trudności w kontaktach z innymi dziećmi.', 'embedding': '[0.06006022170186043,0.031776804476976395,0.039143357425928116,0.037860576063394547,-0.0056678252294659615,-0.011776119470596313,-0.05056934803724289 ... (7754 characters truncated) ... 3,0.004673773888498545,-0.013329035602509975,0.024957481771707535,-0.000811647332739085,0.12868978083133698,0.030574068427085876,0.01494473684579134]', 'group_id': 'ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef', 'match_score': 0.0}

2026-03-14 20:48:36,673 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:36,679 INFO sqlalchemy.engine.Engine [cached since 69.49s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 69.49s ago] {'email_1': 'test0016@zebra.pl', 'param_1': 1}

2026-03-14 20:48:36,714 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,715 INFO sqlalchemy.engine.Engine [cached since 11s ago] {'user_id_1': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11s ago] {'user_id_1': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'param_1': 1}

2026-03-14 20:48:36,745 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,747 INFO sqlalchemy.engine.Engine [cached since 11.03s ago] {'user_id_1': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.03s ago] {'user_id_1': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'param_1': 1}

2026-03-14 20:48:36,817 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:36,818 INFO sqlalchemy.engine.Engine [cached since 6.16s ago] {'embedding': '[0.01747262,0.00362265,0.01728810,0.02525895,-0.07426370,-0.02183858,-0.01232756,0.06578292,-0.01237863,-0.06345403,0.09125172,0.01847526,-0.03709398 ... (4122 characters truncated) ... 2,0.04425352,0.01164721,0.01015474,-0.01247816,0.07267664,-0.00811435,-0.03369617,-0.05553081,0.02120227,0.01282831,0.04711102,0.06449313,0.02359790]', 'user_id': '762a66ab-a4b5-4e17-82b3-b1f1ed471f2f', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 6.16s ago] {'embedding': '[0.01747262,0.00362265,0.01728810,0.02525895,-0.07426370,-0.02183858,-0.01232756,0.06578292,-0.01237863,-0.06345403,0.09125172,0.01847526,-0.03709398 ... (4122 characters truncated) ... 2,0.04425352,0.01164721,0.01015474,-0.01247816,0.07267664,-0.00811435,-0.03369617,-0.05553081,0.02120227,0.01282831,0.04711102,0.06449313,0.02359790]', 'user_id': '762a66ab-a4b5-4e17-82b3-b1f1ed471f2f', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7380, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:36,853 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,854 INFO sqlalchemy.engine.Engine [cached since 2.568s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.568s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.7380)
INFO:dataset-notebook:Utworzono profil objawów dla test0016@zebra.pl

2026-03-14 20:48:36,887 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:36,888 INFO sqlalchemy.engine.Engine [cached since 6.139s ago] {'user_id_1': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.139s ago] {'user_id_1': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:36,919 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:36,920 INFO sqlalchemy.engine.Engine [cached since 6.134s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 6.134s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 762a66ab-a4b5-4e17-82b3-b1f1ed471f2f do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:36,953 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:36,955 INFO sqlalchemy.engine.Engine [cached since 5.74s ago] {'user_id': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 5.74s ago] {'user_id': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:36,987 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:36,988 INFO sqlalchemy.engine.Engine [cached since 5.737s ago] {'id': UUID('14204d82-badf-4591-bd14-50575abe9fb3'), 'user_id': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'description': 'Syn ma bardzo duży obwód głowy w porównaniu do reszty ciała. Lekarz zauważył to już w pierwszych miesiącach życia. Oprócz tego ma trudności z koordynacją ruchów.', 'embedding': '[0.01747261919081211,0.003622654592618346,0.017288101837038994,0.025258954614400864,-0.07426369935274124,-0.021838584914803505,-0.012327564880251884, ... (7751 characters truncated) ... ,-0.033696167171001434,-0.055530812591314316,0.021202271804213524,0.012828308157622814,0.047111015766859055,0.06449312716722488,0.023597897961735725]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.738048791885376}

INFO:sqlalchemy.engine.Engine:[cached since 5.737s ago] {'id': UUID('14204d82-badf-4591-bd14-50575abe9fb3'), 'user_id': UUID('762a66ab-a4b5-4e17-82b3-b1f1ed471f2f'), 'description': 'Syn ma bardzo duży obwód głowy w porównaniu do reszty ciała. Lekarz zauważył to już w pierwszych miesiącach życia. Oprócz tego ma trudności z koordynacją ruchów.', 'embedding': '[0.01747261919081211,0.003622654592618346,0.017288101837038994,0.025258954614400864,-0.07426369935274124,-0.021838584914803505,-0.012327564880251884, ... (7751 characters truncated) ... ,-0.033696167171001434,-0.055530812591314316,0.021202271804213524,0.012828308157622814,0.047111015766859055,0.06449312716722488,0.023597897961735725]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.738048791885376}

2026-03-14 20:48:37,021 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:37,022 INFO sqlalchemy.engine.Engine [cached since 69.83s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 69.83s ago] {'email_1': 'test0017@zebra.pl', 'param_1': 1}

2026-03-14 20:48:37,054 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,055 INFO sqlalchemy.engine.Engine [cached since 11.34s ago] {'user_id_1': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.34s ago] {'user_id_1': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'param_1': 1}

2026-03-14 20:48:37,088 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,089 INFO sqlalchemy.engine.Engine [cached since 11.37s ago] {'user_id_1': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.37s ago] {'user_id_1': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'param_1': 1}

2026-03-14 20:48:37,145 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:37,146 INFO sqlalchemy.engine.Engine [cached since 6.488s ago] {'embedding': '[0.00474842,-0.01619525,0.06555618,0.11018252,-0.00893738,0.00623266,0.00219766,-0.03308360,0.03633461,-0.00613008,0.09178886,0.00835777,-0.07076817, ... (4121 characters truncated) ... .02067350,-0.04992685,-0.01939118,-0.04204066,-0.00597446,0.08894026,-0.02958523,-0.04260919,0.01610317,0.02453538,0.06646788,0.04258755,-0.00418425]', 'user_id': 'b74b1765-01e8-4f86-8b5b-5bfaecad39d9', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 6.488s ago] {'embedding': '[0.00474842,-0.01619525,0.06555618,0.11018252,-0.00893738,0.00623266,0.00219766,-0.03308360,0.03633461,-0.00613008,0.09178886,0.00835777,-0.07076817, ... (4121 characters truncated) ... .02067350,-0.04992685,-0.01939118,-0.04204066,-0.00597446,0.08894026,-0.02958523,-0.04260919,0.01610317,0.02453538,0.06646788,0.04258755,-0.00418425]', 'user_id': 'b74b1765-01e8-4f86-8b5b-5bfaecad39d9', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7768, group_id=0946e26a-2416-427b-80d3-cb4e30902b5b

2026-03-14 20:48:37,181 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,181 INFO sqlalchemy.engine.Engine [cached since 2.896s ago] {'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 2.896s ago] {'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Fioletowy Cypel' (score=0.7768)
INFO:dataset-notebook:Utworzono profil objawów dla test0017@zebra.pl

2026-03-14 20:48:37,214 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,214 INFO sqlalchemy.engine.Engine [cached since 6.466s ago] {'user_id_1': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.466s ago] {'user_id_1': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

2026-03-14 20:48:37,245 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:37,246 INFO sqlalchemy.engine.Engine [cached since 6.46s ago] {'member_count_1': 1, 'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 6.46s ago] {'member_count_1': 1, 'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}
INFO:app.services.matching_service:Dodano user b74b1765-01e8-4f86-8b5b-5bfaecad39d9 do grupy 0946e26a-2416-427b-80d3-cb4e30902b5b

2026-03-14 20:48:37,279 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:37,280 INFO sqlalchemy.engine.Engine [cached since 6.065s ago] {'user_id': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'group_id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 6.065s ago] {'user_id': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'group_id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

2026-03-14 20:48:37,309 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:37,310 INFO sqlalchemy.engine.Engine [cached since 6.059s ago] {'id': UUID('2ce2a395-45e9-4df0-9187-ad2cf5b45144'), 'user_id': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'description': 'Nasze dziecko ma problemy ze wzrokiem od urodzenia. Nie skupia wzroku na przedmiotach i często mruży oczy.', 'embedding': '[0.004748419392853975,-0.01619524508714676,0.06555618345737457,0.1101825162768364,-0.008937382139265537,0.006232660263776779,0.002197656314820051,-0. ... (7754 characters truncated) ... 3,-0.029585225507616997,-0.042609188705682755,0.016103165224194527,0.02453538030385971,0.06646788120269775,0.04258754849433899,-0.004184253513813019]', 'group_id': '0946e26a-2416-427b-80d3-cb4e30902b5b', 'match_score': 0.77675608119441}

INFO:sqlalchemy.engine.Engine:[cached since 6.059s ago] {'id': UUID('2ce2a395-45e9-4df0-9187-ad2cf5b45144'), 'user_id': UUID('b74b1765-01e8-4f86-8b5b-5bfaecad39d9'), 'description': 'Nasze dziecko ma problemy ze wzrokiem od urodzenia. Nie skupia wzroku na przedmiotach i często mruży oczy.', 'embedding': '[0.004748419392853975,-0.01619524508714676,0.06555618345737457,0.1101825162768364,-0.008937382139265537,0.006232660263776779,0.002197656314820051,-0. ... (7754 characters truncated) ... 3,-0.029585225507616997,-0.042609188705682755,0.016103165224194527,0.02453538030385971,0.06646788120269775,0.04258754849433899,-0.004184253513813019]', 'group_id': '0946e26a-2416-427b-80d3-cb4e30902b5b', 'match_score': 0.77675608119441}

2026-03-14 20:48:37,341 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:37,343 INFO sqlalchemy.engine.Engine [cached since 70.15s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 70.15s ago] {'email_1': 'test0018@zebra.pl', 'param_1': 1}

2026-03-14 20:48:37,373 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,374 INFO sqlalchemy.engine.Engine [cached since 11.66s ago] {'user_id_1': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.66s ago] {'user_id_1': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'param_1': 1}

2026-03-14 20:48:37,406 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,407 INFO sqlalchemy.engine.Engine [cached since 11.69s ago] {'user_id_1': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.69s ago] {'user_id_1': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'param_1': 1}

2026-03-14 20:48:37,464 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:37,465 INFO sqlalchemy.engine.Engine [cached since 6.807s ago] {'embedding': '[0.03305450,0.03662825,0.05656089,0.07057133,0.11451592,-0.00961563,-0.06333817,-0.00244508,0.05543259,0.01454764,0.05847097,0.07241081,-0.05220920,- ... (4108 characters truncated) ... ,0.00773879,-0.07076243,-0.02634197,0.06542242,-0.03418756,-0.09460349,0.01164368,-0.04896037,0.00025778,0.02769493,0.03599296,0.01703266,0.02140410]', 'user_id': '1374fccf-3d87-4616-add2-8a1007bec579', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 6.807s ago] {'embedding': '[0.03305450,0.03662825,0.05656089,0.07057133,0.11451592,-0.00961563,-0.06333817,-0.00244508,0.05543259,0.01454764,0.05847097,0.07241081,-0.05220920,- ... (4108 characters truncated) ... ,0.00773879,-0.07076243,-0.02634197,0.06542242,-0.03418756,-0.09460349,0.01164368,-0.04896037,0.00025778,0.02769493,0.03599296,0.01703266,0.02140410]', 'user_id': '1374fccf-3d87-4616-add2-8a1007bec579', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7201, group_id=a3bc3fbb-f3a1-4c34-906e-a6676e30d21c

2026-03-14 20:48:37,498 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,499 INFO sqlalchemy.engine.Engine [cached since 3.213s ago] {'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 3.213s ago] {'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Perłowy Mgła' (score=0.7201)
INFO:dataset-notebook:Utworzono profil objawów dla test0018@zebra.pl

2026-03-14 20:48:37,530 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,531 INFO sqlalchemy.engine.Engine [cached since 6.782s ago] {'user_id_1': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.782s ago] {'user_id_1': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

2026-03-14 20:48:37,560 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:37,561 INFO sqlalchemy.engine.Engine [cached since 6.775s ago] {'member_count_1': 1, 'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 6.775s ago] {'member_count_1': 1, 'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}
INFO:app.services.matching_service:Dodano user 1374fccf-3d87-4616-add2-8a1007bec579 do grupy a3bc3fbb-f3a1-4c34-906e-a6676e30d21c

2026-03-14 20:48:37,596 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:37,597 INFO sqlalchemy.engine.Engine [cached since 6.382s ago] {'user_id': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'group_id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 6.382s ago] {'user_id': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'group_id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

2026-03-14 20:48:37,629 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:37,630 INFO sqlalchemy.engine.Engine [cached since 6.379s ago] {'id': UUID('f43adc56-e804-4c8a-8283-0701b1b65325'), 'user_id': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'description': 'Córka bardzo późno zaczęła chodzić. Nawet teraz porusza się wolniej niż rówieśnicy i szybko się męczy.', 'embedding': '[0.033054500818252563,0.03662824630737305,0.05656088888645172,0.07057132571935654,0.11451592296361923,-0.009615630842745304,-0.06333816796541214,-0.0 ... (7727 characters truncated) ... 942,0.011643676087260246,-0.0489603690803051,0.0002577800478320569,0.027694929391145706,0.03599295765161514,0.01703266054391861,0.021404104307293892]', 'group_id': 'a3bc3fbb-f3a1-4c34-906e-a6676e30d21c', 'match_score': 0.720056133266919}

INFO:sqlalchemy.engine.Engine:[cached since 6.379s ago] {'id': UUID('f43adc56-e804-4c8a-8283-0701b1b65325'), 'user_id': UUID('1374fccf-3d87-4616-add2-8a1007bec579'), 'description': 'Córka bardzo późno zaczęła chodzić. Nawet teraz porusza się wolniej niż rówieśnicy i szybko się męczy.', 'embedding': '[0.033054500818252563,0.03662824630737305,0.05656088888645172,0.07057132571935654,0.11451592296361923,-0.009615630842745304,-0.06333816796541214,-0.0 ... (7727 characters truncated) ... 942,0.011643676087260246,-0.0489603690803051,0.0002577800478320569,0.027694929391145706,0.03599295765161514,0.01703266054391861,0.021404104307293892]', 'group_id': 'a3bc3fbb-f3a1-4c34-906e-a6676e30d21c', 'match_score': 0.720056133266919}

2026-03-14 20:48:37,662 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:37,663 INFO sqlalchemy.engine.Engine [cached since 70.47s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 70.47s ago] {'email_1': 'test0019@zebra.pl', 'param_1': 1}

2026-03-14 20:48:37,695 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,696 INFO sqlalchemy.engine.Engine [cached since 11.98s ago] {'user_id_1': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.98s ago] {'user_id_1': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'param_1': 1}

2026-03-14 20:48:37,728 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,729 INFO sqlalchemy.engine.Engine [cached since 12.01s ago] {'user_id_1': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.01s ago] {'user_id_1': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'param_1': 1}

2026-03-14 20:48:37,795 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:37,796 INFO sqlalchemy.engine.Engine [cached since 7.137s ago] {'embedding': '[-0.01892479,0.07899610,0.06916965,0.02728094,0.01326281,0.05047319,0.00923034,-0.00531950,-0.06909046,-0.08954705,0.10386625,-0.03138943,0.01654593, ... (4116 characters truncated) ... ,-0.01445107,-0.05109415,0.02512644,-0.06431343,-0.02522040,-0.00203478,0.03497906,0.04777739,0.06095440,0.07899790,0.00858841,0.10518075,0.03620877]', 'user_id': '707471ad-508d-44c9-960f-30b3795623a4', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.137s ago] {'embedding': '[-0.01892479,0.07899610,0.06916965,0.02728094,0.01326281,0.05047319,0.00923034,-0.00531950,-0.06909046,-0.08954705,0.10386625,-0.03138943,0.01654593, ... (4116 characters truncated) ... ,-0.01445107,-0.05109415,0.02512644,-0.06431343,-0.02522040,-0.00203478,0.03497906,0.04777739,0.06095440,0.07899790,0.00858841,0.10518075,0.03620877]', 'user_id': '707471ad-508d-44c9-960f-30b3795623a4', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5631, group_id=49357027-f555-473a-8c72-cafd78dc5fc2
INFO:app.services.matching_service:Score 0.5631 < threshold 0.72 — nowa grupa

2026-03-14 20:48:37,829 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:37,829 INFO sqlalchemy.engine.Engine [cached since 7.124s ago] {'id': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236'), 'name': 'Błękitny Liść', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 7.124s ago] {'id': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236'), 'name': 'Błękitny Liść', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: ad488d0b-6569-40df-ae7a-3ee3758b2236
INFO:dataset-notebook:Utworzono profil objawów dla test0019@zebra.pl

2026-03-14 20:48:37,861 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:37,862 INFO sqlalchemy.engine.Engine [cached since 7.113s ago] {'user_id_1': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'group_id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.113s ago] {'user_id_1': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'group_id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236'), 'param_1': 1}

2026-03-14 20:48:37,894 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:37,895 INFO sqlalchemy.engine.Engine [cached since 7.109s ago] {'member_count_1': 1, 'id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

INFO:sqlalchemy.engine.Engine:[cached since 7.109s ago] {'member_count_1': 1, 'id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}
INFO:app.services.matching_service:Dodano user 707471ad-508d-44c9-960f-30b3795623a4 do grupy ad488d0b-6569-40df-ae7a-3ee3758b2236

2026-03-14 20:48:37,929 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:37,930 INFO sqlalchemy.engine.Engine [cached since 6.715s ago] {'user_id': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'group_id': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

INFO:sqlalchemy.engine.Engine:[cached since 6.715s ago] {'user_id': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'group_id': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

2026-03-14 20:48:37,963 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:37,964 INFO sqlalchemy.engine.Engine [cached since 6.713s ago] {'id': UUID('b1b456b6-3aeb-414f-b21a-d9af972f1b15'), 'user_id': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'description': 'Syn ma bardzo cienką i delikatną skórę. Nawet małe zadrapania długo się goją i zostawiają ślady. Zawsze jego skóra była blada', 'embedding': '[-0.018924785777926445,0.07899609953165054,0.06916964799165726,0.027280941605567932,0.013262811116874218,0.05047319084405899,0.009230340830981731,-0. ... (7747 characters truncated) ... 11253619,0.03497905656695366,0.04777739197015762,0.06095440313220024,0.0789978951215744,0.008588409051299095,0.10518074780702591,0.03620877116918564]', 'group_id': 'ad488d0b-6569-40df-ae7a-3ee3758b2236', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 6.713s ago] {'id': UUID('b1b456b6-3aeb-414f-b21a-d9af972f1b15'), 'user_id': UUID('707471ad-508d-44c9-960f-30b3795623a4'), 'description': 'Syn ma bardzo cienką i delikatną skórę. Nawet małe zadrapania długo się goją i zostawiają ślady. Zawsze jego skóra była blada', 'embedding': '[-0.018924785777926445,0.07899609953165054,0.06916964799165726,0.027280941605567932,0.013262811116874218,0.05047319084405899,0.009230340830981731,-0. ... (7747 characters truncated) ... 11253619,0.03497905656695366,0.04777739197015762,0.06095440313220024,0.0789978951215744,0.008588409051299095,0.10518074780702591,0.03620877116918564]', 'group_id': 'ad488d0b-6569-40df-ae7a-3ee3758b2236', 'match_score': 0.0}

2026-03-14 20:48:37,995 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:37,996 INFO sqlalchemy.engine.Engine [cached since 70.8s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 70.8s ago] {'email_1': 'test0020@zebra.pl', 'param_1': 1}

2026-03-14 20:48:38,027 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,029 INFO sqlalchemy.engine.Engine [cached since 12.31s ago] {'user_id_1': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.31s ago] {'user_id_1': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'param_1': 1}

2026-03-14 20:48:38,063 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,064 INFO sqlalchemy.engine.Engine [cached since 12.35s ago] {'user_id_1': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.35s ago] {'user_id_1': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'param_1': 1}

2026-03-14 20:48:38,125 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:38,127 INFO sqlalchemy.engine.Engine [cached since 7.468s ago] {'embedding': '[0.04319208,-0.02134780,0.03202399,-0.00329261,-0.05966554,0.01480454,0.01183619,0.00278676,-0.00415839,0.05860940,0.02414868,0.04609299,-0.02881385, ... (4127 characters truncated) ... ,0.03191640,-0.04824365,-0.02592349,0.08538253,0.05275400,-0.03937469,0.04862729,-0.03971009,0.03450912,-0.03004707,0.06216454,0.03933803,0.04431497]', 'user_id': 'cc449367-fd68-44d3-9922-3f150cba95f6', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.468s ago] {'embedding': '[0.04319208,-0.02134780,0.03202399,-0.00329261,-0.05966554,0.01480454,0.01183619,0.00278676,-0.00415839,0.05860940,0.02414868,0.04609299,-0.02881385, ... (4127 characters truncated) ... ,0.03191640,-0.04824365,-0.02592349,0.08538253,0.05275400,-0.03937469,0.04862729,-0.03971009,0.03450912,-0.03004707,0.06216454,0.03933803,0.04431497]', 'user_id': 'cc449367-fd68-44d3-9922-3f150cba95f6', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6701, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6701 < threshold 0.72 — nowa grupa

2026-03-14 20:48:38,170 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:38,176 INFO sqlalchemy.engine.Engine [cached since 7.471s ago] {'id': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'name': 'Złoty Lawenda', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 7.471s ago] {'id': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'name': 'Złoty Lawenda', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 70b3efbb-3c9b-44db-bf24-f453515ab3dd
INFO:dataset-notebook:Utworzono profil objawów dla test0020@zebra.pl

2026-03-14 20:48:38,215 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,219 INFO sqlalchemy.engine.Engine [cached since 7.47s ago] {'user_id_1': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.47s ago] {'user_id_1': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

2026-03-14 20:48:38,257 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:38,263 INFO sqlalchemy.engine.Engine [cached since 7.477s ago] {'member_count_1': 1, 'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 7.477s ago] {'member_count_1': 1, 'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}
INFO:app.services.matching_service:Dodano user cc449367-fd68-44d3-9922-3f150cba95f6 do grupy 70b3efbb-3c9b-44db-bf24-f453515ab3dd

2026-03-14 20:48:38,302 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:38,304 INFO sqlalchemy.engine.Engine [cached since 7.089s ago] {'user_id': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'group_id': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 7.089s ago] {'user_id': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'group_id': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

2026-03-14 20:48:38,337 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:38,339 INFO sqlalchemy.engine.Engine [cached since 7.088s ago] {'id': UUID('d30b7251-6914-4f07-918a-247cab6c74c6'), 'user_id': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'description': 'Nasze dziecko ma problemy z koordynacją ruchową. Trudno mu łapać piłkę, rysować czy zapinać guziki. Nie lubi bawić się w zabawy sprawnościowe.', 'embedding': '[0.04319207742810249,-0.02134779654443264,0.032023992389440536,-0.003292607609182596,-0.05966553837060928,0.014804542995989323,0.011836189776659012,0 ... (7738 characters truncated) ... 1705,0.04862729460000992,-0.039710093289613724,0.034509122371673584,-0.03004707396030426,0.0621645413339138,0.03933802619576454,0.044314973056316376]', 'group_id': '70b3efbb-3c9b-44db-bf24-f453515ab3dd', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 7.088s ago] {'id': UUID('d30b7251-6914-4f07-918a-247cab6c74c6'), 'user_id': UUID('cc449367-fd68-44d3-9922-3f150cba95f6'), 'description': 'Nasze dziecko ma problemy z koordynacją ruchową. Trudno mu łapać piłkę, rysować czy zapinać guziki. Nie lubi bawić się w zabawy sprawnościowe.', 'embedding': '[0.04319207742810249,-0.02134779654443264,0.032023992389440536,-0.003292607609182596,-0.05966553837060928,0.014804542995989323,0.011836189776659012,0 ... (7738 characters truncated) ... 1705,0.04862729460000992,-0.039710093289613724,0.034509122371673584,-0.03004707396030426,0.0621645413339138,0.03933802619576454,0.044314973056316376]', 'group_id': '70b3efbb-3c9b-44db-bf24-f453515ab3dd', 'match_score': 0.0}

2026-03-14 20:48:38,374 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:38,378 INFO sqlalchemy.engine.Engine [cached since 71.18s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 71.18s ago] {'email_1': 'test0021@zebra.pl', 'param_1': 1}

2026-03-14 20:48:38,412 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,415 INFO sqlalchemy.engine.Engine [cached since 12.7s ago] {'user_id_1': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.7s ago] {'user_id_1': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'param_1': 1}

2026-03-14 20:48:38,447 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,449 INFO sqlalchemy.engine.Engine [cached since 12.73s ago] {'user_id_1': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.73s ago] {'user_id_1': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'param_1': 1}

2026-03-14 20:48:38,522 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:38,523 INFO sqlalchemy.engine.Engine [cached since 7.865s ago] {'embedding': '[0.00362472,-0.03290118,0.02499859,0.10442706,-0.08267198,0.02936028,-0.00266391,-0.01057005,-0.00546879,-0.02693137,0.03738308,-0.04636299,-0.003045 ... (4115 characters truncated) ... -0.01936999,-0.06936683,-0.03178545,-0.04438496,0.07722978,0.00364223,0.00968812,-0.01864357,0.08928104,0.01698751,0.05323985,0.09742282,-0.06482635]', 'user_id': 'b475c76b-9158-442c-8fca-62d9ae8c1afc', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 7.865s ago] {'embedding': '[0.00362472,-0.03290118,0.02499859,0.10442706,-0.08267198,0.02936028,-0.00266391,-0.01057005,-0.00546879,-0.02693137,0.03738308,-0.04636299,-0.003045 ... (4115 characters truncated) ... -0.01936999,-0.06936683,-0.03178545,-0.04438496,0.07722978,0.00364223,0.00968812,-0.01864357,0.08928104,0.01698751,0.05323985,0.09742282,-0.06482635]', 'user_id': 'b475c76b-9158-442c-8fca-62d9ae8c1afc', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6884, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6884 < threshold 0.72 — nowa grupa

2026-03-14 20:48:38,559 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:38,560 INFO sqlalchemy.engine.Engine [cached since 7.855s ago] {'id': UUID('965b3861-f29a-43cd-8e70-6474097fafa6'), 'name': 'Szafirowy Przylądek', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#ec4899', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 7.855s ago] {'id': UUID('965b3861-f29a-43cd-8e70-6474097fafa6'), 'name': 'Szafirowy Przylądek', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#ec4899', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 965b3861-f29a-43cd-8e70-6474097fafa6
INFO:dataset-notebook:Utworzono profil objawów dla test0021@zebra.pl

2026-03-14 20:48:38,594 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,594 INFO sqlalchemy.engine.Engine [cached since 7.846s ago] {'user_id_1': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'group_id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.846s ago] {'user_id_1': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'group_id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6'), 'param_1': 1}

2026-03-14 20:48:38,624 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:38,625 INFO sqlalchemy.engine.Engine [cached since 7.838s ago] {'member_count_1': 1, 'id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

INFO:sqlalchemy.engine.Engine:[cached since 7.838s ago] {'member_count_1': 1, 'id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}
INFO:app.services.matching_service:Dodano user b475c76b-9158-442c-8fca-62d9ae8c1afc do grupy 965b3861-f29a-43cd-8e70-6474097fafa6

2026-03-14 20:48:38,659 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:38,660 INFO sqlalchemy.engine.Engine [cached since 7.445s ago] {'user_id': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'group_id': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

INFO:sqlalchemy.engine.Engine:[cached since 7.445s ago] {'user_id': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'group_id': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

2026-03-14 20:48:38,693 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:38,694 INFO sqlalchemy.engine.Engine [cached since 7.443s ago] {'id': UUID('c438496a-301a-4d5f-abfa-be929d285abc'), 'user_id': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'description': 'Córka od urodzenia ma bardzo słabe mięśnie twarzy. Często ma otwarte usta i trudniej jej wyraźnie mówić. Jest apatyczna.', 'embedding': '[0.0036247242242097855,-0.032901182770729065,0.024998586624860764,0.10442706197500229,-0.08267197757959366,0.02936028130352497,-0.0026639082934707403 ... (7740 characters truncated) ... 289982,0.009688121266663074,-0.018643565475940704,0.08928104490041733,0.01698751375079155,0.0532398521900177,0.09742282330989838,-0.0648263469338417]', 'group_id': '965b3861-f29a-43cd-8e70-6474097fafa6', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 7.443s ago] {'id': UUID('c438496a-301a-4d5f-abfa-be929d285abc'), 'user_id': UUID('b475c76b-9158-442c-8fca-62d9ae8c1afc'), 'description': 'Córka od urodzenia ma bardzo słabe mięśnie twarzy. Często ma otwarte usta i trudniej jej wyraźnie mówić. Jest apatyczna.', 'embedding': '[0.0036247242242097855,-0.032901182770729065,0.024998586624860764,0.10442706197500229,-0.08267197757959366,0.02936028130352497,-0.0026639082934707403 ... (7740 characters truncated) ... 289982,0.009688121266663074,-0.018643565475940704,0.08928104490041733,0.01698751375079155,0.0532398521900177,0.09742282330989838,-0.0648263469338417]', 'group_id': '965b3861-f29a-43cd-8e70-6474097fafa6', 'match_score': 0.0}

2026-03-14 20:48:38,728 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:38,729 INFO sqlalchemy.engine.Engine [cached since 71.54s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 71.54s ago] {'email_1': 'test0022@zebra.pl', 'param_1': 1}

2026-03-14 20:48:38,760 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,761 INFO sqlalchemy.engine.Engine [cached since 13.04s ago] {'user_id_1': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.04s ago] {'user_id_1': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'param_1': 1}

2026-03-14 20:48:38,791 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,793 INFO sqlalchemy.engine.Engine [cached since 13.08s ago] {'user_id_1': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.08s ago] {'user_id_1': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'param_1': 1}

2026-03-14 20:48:38,859 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:38,860 INFO sqlalchemy.engine.Engine [cached since 8.202s ago] {'embedding': '[0.06472842,0.02412557,-0.01942814,0.01216511,-0.00991623,0.04569457,-0.05341364,0.02674445,-0.02239661,-0.01848341,0.01029617,0.05204862,-0.05255574 ... (4119 characters truncated) ... 0.04163727,-0.01804171,-0.05463418,0.06713843,-0.01687901,-0.12249288,0.01541799,-0.06688940,-0.01664776,0.02794164,0.03253588,0.03362912,0.06345035]', 'user_id': '2a82c12b-b9de-4d1e-a2e7-20adab89fab1', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 8.202s ago] {'embedding': '[0.06472842,0.02412557,-0.01942814,0.01216511,-0.00991623,0.04569457,-0.05341364,0.02674445,-0.02239661,-0.01848341,0.01029617,0.05204862,-0.05255574 ... (4119 characters truncated) ... 0.04163727,-0.01804171,-0.05463418,0.06713843,-0.01687901,-0.12249288,0.01541799,-0.06688940,-0.01664776,0.02794164,0.03253588,0.03362912,0.06345035]', 'user_id': '2a82c12b-b9de-4d1e-a2e7-20adab89fab1', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8091, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:38,894 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,895 INFO sqlalchemy.engine.Engine [cached since 4.61s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 4.61s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.8091)
INFO:dataset-notebook:Utworzono profil objawów dla test0022@zebra.pl

2026-03-14 20:48:38,928 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:38,930 INFO sqlalchemy.engine.Engine [cached since 8.181s ago] {'user_id_1': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.181s ago] {'user_id_1': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:38,961 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:38,962 INFO sqlalchemy.engine.Engine [cached since 8.176s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 8.176s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 2a82c12b-b9de-4d1e-a2e7-20adab89fab1 do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:38,997 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:38,998 INFO sqlalchemy.engine.Engine [cached since 7.783s ago] {'user_id': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 7.783s ago] {'user_id': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:39,031 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:39,035 INFO sqlalchemy.engine.Engine [cached since 7.784s ago] {'id': UUID('a14e3ad3-6414-47e0-86b7-6406f27b7780'), 'user_id': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'description': 'Syn od kilku lat ma coraz większy problem z bieganiem. Wcześniej radził sobie dobrze, ale z czasem jego mięśnie nóg wydają się słabsze.', 'embedding': '[0.06472841650247574,0.024125566706061363,-0.01942814327776432,0.012165111489593983,-0.009916228242218494,0.04569457471370697,-0.053413644433021545,0 ... (7738 characters truncated) ... 513,0.015417992137372494,-0.06688939779996872,-0.016647761687636375,0.027941640466451645,0.03253588452935219,0.03362911567091942,0.06345035135746002]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.809058166630055}

INFO:sqlalchemy.engine.Engine:[cached since 7.784s ago] {'id': UUID('a14e3ad3-6414-47e0-86b7-6406f27b7780'), 'user_id': UUID('2a82c12b-b9de-4d1e-a2e7-20adab89fab1'), 'description': 'Syn od kilku lat ma coraz większy problem z bieganiem. Wcześniej radził sobie dobrze, ale z czasem jego mięśnie nóg wydają się słabsze.', 'embedding': '[0.06472841650247574,0.024125566706061363,-0.01942814327776432,0.012165111489593983,-0.009916228242218494,0.04569457471370697,-0.053413644433021545,0 ... (7738 characters truncated) ... 513,0.015417992137372494,-0.06688939779996872,-0.016647761687636375,0.027941640466451645,0.03253588452935219,0.03362911567091942,0.06345035135746002]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.809058166630055}

2026-03-14 20:48:39,070 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:39,073 INFO sqlalchemy.engine.Engine [cached since 71.88s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 71.88s ago] {'email_1': 'test0023@zebra.pl', 'param_1': 1}

2026-03-14 20:48:39,105 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,107 INFO sqlalchemy.engine.Engine [cached since 13.39s ago] {'user_id_1': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.39s ago] {'user_id_1': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'param_1': 1}

2026-03-14 20:48:39,139 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,144 INFO sqlalchemy.engine.Engine [cached since 13.43s ago] {'user_id_1': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.43s ago] {'user_id_1': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'param_1': 1}

2026-03-14 20:48:39,221 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:39,222 INFO sqlalchemy.engine.Engine [cached since 8.564s ago] {'embedding': '[0.02938039,-0.01470889,0.02369665,0.01164538,-0.06185067,0.02765666,-0.01423237,-0.02074103,0.05931488,0.01143016,0.01714928,0.09691372,0.00000147,0 ... (4119 characters truncated) ... 882,-0.00400681,0.00332479,0.02516567,0.09164411,0.03168909,0.02037974,0.00682234,0.01089526,0.06828275,0.00183170,0.13546987,0.00786121,-0.01526106]', 'user_id': '163d3299-d0f2-4682-9011-96ec3cb030a4', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 8.564s ago] {'embedding': '[0.02938039,-0.01470889,0.02369665,0.01164538,-0.06185067,0.02765666,-0.01423237,-0.02074103,0.05931488,0.01143016,0.01714928,0.09691372,0.00000147,0 ... (4119 characters truncated) ... 882,-0.00400681,0.00332479,0.02516567,0.09164411,0.03168909,0.02037974,0.00682234,0.01089526,0.06828275,0.00183170,0.13546987,0.00786121,-0.01526106]', 'user_id': '163d3299-d0f2-4682-9011-96ec3cb030a4', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6718, group_id=e9a71a4c-b2de-4a87-ac05-4d527d6745ab
INFO:app.services.matching_service:Score 0.6718 < threshold 0.72 — nowa grupa

2026-03-14 20:48:39,258 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:39,260 INFO sqlalchemy.engine.Engine [cached since 8.554s ago] {'id': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c'), 'name': 'Złoty Brzoza', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 8.554s ago] {'id': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c'), 'name': 'Złoty Brzoza', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: ce577c16-4dd0-445e-8e55-96b461abf41c
INFO:dataset-notebook:Utworzono profil objawów dla test0023@zebra.pl

2026-03-14 20:48:39,297 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,298 INFO sqlalchemy.engine.Engine [cached since 8.549s ago] {'user_id_1': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'group_id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.549s ago] {'user_id_1': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'group_id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c'), 'param_1': 1}

2026-03-14 20:48:39,335 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:39,336 INFO sqlalchemy.engine.Engine [cached since 8.55s ago] {'member_count_1': 1, 'id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

INFO:sqlalchemy.engine.Engine:[cached since 8.55s ago] {'member_count_1': 1, 'id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}
INFO:app.services.matching_service:Dodano user 163d3299-d0f2-4682-9011-96ec3cb030a4 do grupy ce577c16-4dd0-445e-8e55-96b461abf41c

2026-03-14 20:48:39,368 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:39,370 INFO sqlalchemy.engine.Engine [cached since 8.155s ago] {'user_id': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'group_id': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

INFO:sqlalchemy.engine.Engine:[cached since 8.155s ago] {'user_id': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'group_id': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

2026-03-14 20:48:39,399 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:39,400 INFO sqlalchemy.engine.Engine [cached since 8.149s ago] {'id': UUID('beeab70e-8b24-4386-8556-6184a003f1e8'), 'user_id': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'description': 'Nasze dziecko bardzo wolno uczy się nowych rzeczy. Potrzebuje dużo powtórzeń, żeby zapamiętać proste czynności.', 'embedding': '[0.02938038855791092,-0.014708888716995716,0.023696649819612503,0.011645382270216942,-0.06185067445039749,0.027656659483909607,-0.014232365414500237, ... (7742 characters truncated) ... 888,0.006822340190410614,0.010895255021750927,0.06828275322914124,0.00183169636875391,0.13546986877918243,0.007861205376684666,-0.015261064283549786]', 'group_id': 'ce577c16-4dd0-445e-8e55-96b461abf41c', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 8.149s ago] {'id': UUID('beeab70e-8b24-4386-8556-6184a003f1e8'), 'user_id': UUID('163d3299-d0f2-4682-9011-96ec3cb030a4'), 'description': 'Nasze dziecko bardzo wolno uczy się nowych rzeczy. Potrzebuje dużo powtórzeń, żeby zapamiętać proste czynności.', 'embedding': '[0.02938038855791092,-0.014708888716995716,0.023696649819612503,0.011645382270216942,-0.06185067445039749,0.027656659483909607,-0.014232365414500237, ... (7742 characters truncated) ... 888,0.006822340190410614,0.010895255021750927,0.06828275322914124,0.00183169636875391,0.13546986877918243,0.007861205376684666,-0.015261064283549786]', 'group_id': 'ce577c16-4dd0-445e-8e55-96b461abf41c', 'match_score': 0.0}

2026-03-14 20:48:39,430 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:39,431 INFO sqlalchemy.engine.Engine [cached since 72.24s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 72.24s ago] {'email_1': 'test0024@zebra.pl', 'param_1': 1}

2026-03-14 20:48:39,463 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,464 INFO sqlalchemy.engine.Engine [cached since 13.75s ago] {'user_id_1': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.75s ago] {'user_id_1': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'param_1': 1}

2026-03-14 20:48:39,498 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,499 INFO sqlalchemy.engine.Engine [cached since 13.78s ago] {'user_id_1': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.78s ago] {'user_id_1': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'param_1': 1}

2026-03-14 20:48:39,555 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:39,556 INFO sqlalchemy.engine.Engine [cached since 8.898s ago] {'embedding': '[-0.09482034,0.03773231,0.08726986,0.05980779,-0.00643651,-0.06643806,-0.03057097,0.08790338,0.05846317,0.01170441,0.04685832,0.06017014,-0.05628748, ... (4123 characters truncated) ... 7,0.00944080,-0.03684212,0.04150508,-0.05192474,0.07891987,0.00959015,-0.01756023,-0.06179715,0.05060396,0.03915527,0.06036740,0.03859885,0.04559767]', 'user_id': '14157ded-23d6-47a4-bd34-720ecfc09225', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 8.898s ago] {'embedding': '[-0.09482034,0.03773231,0.08726986,0.05980779,-0.00643651,-0.06643806,-0.03057097,0.08790338,0.05846317,0.01170441,0.04685832,0.06017014,-0.05628748, ... (4123 characters truncated) ... 7,0.00944080,-0.03684212,0.04150508,-0.05192474,0.07891987,0.00959015,-0.01756023,-0.06179715,0.05060396,0.03915527,0.06036740,0.03859885,0.04559767]', 'user_id': '14157ded-23d6-47a4-bd34-720ecfc09225', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6607, group_id=381f180d-adc3-4a20-a80a-76d8ef0793ff
INFO:app.services.matching_service:Score 0.6607 < threshold 0.72 — nowa grupa

2026-03-14 20:48:39,593 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:39,593 INFO sqlalchemy.engine.Engine [cached since 8.888s ago] {'id': UUID('b239d74f-86fd-4a12-b3d4-ade068475954'), 'name': 'Fioletowy Polana', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 8.888s ago] {'id': UUID('b239d74f-86fd-4a12-b3d4-ade068475954'), 'name': 'Fioletowy Polana', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: b239d74f-86fd-4a12-b3d4-ade068475954
INFO:dataset-notebook:Utworzono profil objawów dla test0024@zebra.pl

2026-03-14 20:48:39,628 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,629 INFO sqlalchemy.engine.Engine [cached since 8.88s ago] {'user_id_1': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'group_id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.88s ago] {'user_id_1': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'group_id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954'), 'param_1': 1}

2026-03-14 20:48:39,659 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:39,663 INFO sqlalchemy.engine.Engine [cached since 8.876s ago] {'member_count_1': 1, 'id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

INFO:sqlalchemy.engine.Engine:[cached since 8.876s ago] {'member_count_1': 1, 'id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}
INFO:app.services.matching_service:Dodano user 14157ded-23d6-47a4-bd34-720ecfc09225 do grupy b239d74f-86fd-4a12-b3d4-ade068475954

2026-03-14 20:48:39,696 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:39,697 INFO sqlalchemy.engine.Engine [cached since 8.481s ago] {'user_id': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'group_id': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

INFO:sqlalchemy.engine.Engine:[cached since 8.481s ago] {'user_id': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'group_id': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

2026-03-14 20:48:39,727 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:39,728 INFO sqlalchemy.engine.Engine [cached since 8.477s ago] {'id': UUID('20f84d4b-a185-4dc3-a19f-ad0d7c1fe6eb'), 'user_id': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'description': 'Córka ma bardzo małe dłonie i stopy w porównaniu do reszty ciała. Lekarze zwrócili na to uwagę podczas badań.', 'embedding': '[-0.09482034295797348,0.037732310593128204,0.0872698649764061,0.05980778858065605,-0.0064365132711827755,-0.06643806397914886,-0.030570970848202705,0 ... (7767 characters truncated) ... 51071548,-0.017560232430696487,-0.06179714575409889,0.0506039634346962,0.0391552709043026,0.0603673979640007,0.03859885036945343,0.04559767246246338]', 'group_id': 'b239d74f-86fd-4a12-b3d4-ade068475954', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 8.477s ago] {'id': UUID('20f84d4b-a185-4dc3-a19f-ad0d7c1fe6eb'), 'user_id': UUID('14157ded-23d6-47a4-bd34-720ecfc09225'), 'description': 'Córka ma bardzo małe dłonie i stopy w porównaniu do reszty ciała. Lekarze zwrócili na to uwagę podczas badań.', 'embedding': '[-0.09482034295797348,0.037732310593128204,0.0872698649764061,0.05980778858065605,-0.0064365132711827755,-0.06643806397914886,-0.030570970848202705,0 ... (7767 characters truncated) ... 51071548,-0.017560232430696487,-0.06179714575409889,0.0506039634346962,0.0391552709043026,0.0603673979640007,0.03859885036945343,0.04559767246246338]', 'group_id': 'b239d74f-86fd-4a12-b3d4-ade068475954', 'match_score': 0.0}

2026-03-14 20:48:39,761 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:39,762 INFO sqlalchemy.engine.Engine [cached since 72.57s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 72.57s ago] {'email_1': 'test0025@zebra.pl', 'param_1': 1}

2026-03-14 20:48:39,794 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,795 INFO sqlalchemy.engine.Engine [cached since 14.08s ago] {'user_id_1': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.08s ago] {'user_id_1': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'param_1': 1}

2026-03-14 20:48:39,828 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,829 INFO sqlalchemy.engine.Engine [cached since 14.11s ago] {'user_id_1': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.11s ago] {'user_id_1': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'param_1': 1}

2026-03-14 20:48:39,893 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:39,894 INFO sqlalchemy.engine.Engine [cached since 9.236s ago] {'embedding': '[0.02128638,0.02214613,0.02542376,0.01552286,-0.02946646,0.02252626,-0.05946945,0.02115858,0.01407175,-0.04199671,0.07189140,0.05347178,-0.02574514,0 ... (4122 characters truncated) ... ,0.03653670,-0.00070668,-0.03307658,0.07703535,-0.01762371,-0.01540657,0.03883592,-0.05737233,0.02075333,0.05934899,0.06073152,0.06037147,0.03859269]', 'user_id': 'ab0aa10f-73e1-4b47-8939-55b8f12d5369', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 9.236s ago] {'embedding': '[0.02128638,0.02214613,0.02542376,0.01552286,-0.02946646,0.02252626,-0.05946945,0.02115858,0.01407175,-0.04199671,0.07189140,0.05347178,-0.02574514,0 ... (4122 characters truncated) ... ,0.03653670,-0.00070668,-0.03307658,0.07703535,-0.01762371,-0.01540657,0.03883592,-0.05737233,0.02075333,0.05934899,0.06073152,0.06037147,0.03859269]', 'user_id': 'ab0aa10f-73e1-4b47-8939-55b8f12d5369', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7957, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:39,927 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,928 INFO sqlalchemy.engine.Engine [cached since 5.642s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 5.642s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.7957)
INFO:dataset-notebook:Utworzono profil objawów dla test0025@zebra.pl

2026-03-14 20:48:39,962 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:39,963 INFO sqlalchemy.engine.Engine [cached since 9.214s ago] {'user_id_1': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.214s ago] {'user_id_1': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:39,992 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:39,993 INFO sqlalchemy.engine.Engine [cached since 9.207s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 9.207s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user ab0aa10f-73e1-4b47-8939-55b8f12d5369 do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:40,026 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:40,027 INFO sqlalchemy.engine.Engine [cached since 8.812s ago] {'user_id': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 8.812s ago] {'user_id': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:40,057 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:40,058 INFO sqlalchemy.engine.Engine [cached since 8.807s ago] {'id': UUID('55cce107-81ab-4bee-9ef0-cf809b66c8f9'), 'user_id': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'description': 'Syn od małego miał trudności z utrzymaniem równowagi. Nawet teraz często się przewraca bez wyraźnego powodu.', 'embedding': '[0.021286379545927048,0.022146129980683327,0.02542375586926937,0.015522860921919346,-0.029466455802321434,0.02252625860273838,-0.059469446539878845,0 ... (7735 characters truncated) ... 62559,0.03883592411875725,-0.057372331619262695,0.02075332961976528,0.05934899300336838,0.060731519013643265,0.06037146598100662,0.03859269246459007]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.795725990360739}

INFO:sqlalchemy.engine.Engine:[cached since 8.807s ago] {'id': UUID('55cce107-81ab-4bee-9ef0-cf809b66c8f9'), 'user_id': UUID('ab0aa10f-73e1-4b47-8939-55b8f12d5369'), 'description': 'Syn od małego miał trudności z utrzymaniem równowagi. Nawet teraz często się przewraca bez wyraźnego powodu.', 'embedding': '[0.021286379545927048,0.022146129980683327,0.02542375586926937,0.015522860921919346,-0.029466455802321434,0.02252625860273838,-0.059469446539878845,0 ... (7735 characters truncated) ... 62559,0.03883592411875725,-0.057372331619262695,0.02075332961976528,0.05934899300336838,0.060731519013643265,0.06037146598100662,0.03859269246459007]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.795725990360739}

2026-03-14 20:48:40,094 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:40,096 INFO sqlalchemy.engine.Engine [cached since 72.9s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 72.9s ago] {'email_1': 'test0026@zebra.pl', 'param_1': 1}

2026-03-14 20:48:40,129 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,134 INFO sqlalchemy.engine.Engine [cached since 14.42s ago] {'user_id_1': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.42s ago] {'user_id_1': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'param_1': 1}

2026-03-14 20:48:40,168 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,177 INFO sqlalchemy.engine.Engine [cached since 14.46s ago] {'user_id_1': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.46s ago] {'user_id_1': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'param_1': 1}

2026-03-14 20:48:40,252 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:40,253 INFO sqlalchemy.engine.Engine [cached since 9.595s ago] {'embedding': '[0.02563284,-0.00708233,0.02807121,0.05348954,0.01676044,-0.03376588,-0.02741250,0.00455368,0.02974731,-0.00456058,0.07170793,0.07958625,-0.10019911, ... (4114 characters truncated) ... .00504141,-0.03697908,-0.04458900,-0.00168618,0.00232167,-0.08841027,-0.06558406,-0.05576924,0.01586569,0.06311200,0.03085251,-0.01728964,0.06425572]', 'user_id': '6d7d08b5-a36e-4b92-b788-2406faa45e65', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 9.595s ago] {'embedding': '[0.02563284,-0.00708233,0.02807121,0.05348954,0.01676044,-0.03376588,-0.02741250,0.00455368,0.02974731,-0.00456058,0.07170793,0.07958625,-0.10019911, ... (4114 characters truncated) ... .00504141,-0.03697908,-0.04458900,-0.00168618,0.00232167,-0.08841027,-0.06558406,-0.05576924,0.01586569,0.06311200,0.03085251,-0.01728964,0.06425572]', 'user_id': '6d7d08b5-a36e-4b92-b788-2406faa45e65', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8270, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:40,292 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,294 INFO sqlalchemy.engine.Engine [cached since 6.009s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.009s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.8270)
INFO:dataset-notebook:Utworzono profil objawów dla test0026@zebra.pl

2026-03-14 20:48:40,326 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,327 INFO sqlalchemy.engine.Engine [cached since 9.579s ago] {'user_id_1': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.579s ago] {'user_id_1': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:40,360 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:40,361 INFO sqlalchemy.engine.Engine [cached since 9.574s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 9.574s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 6d7d08b5-a36e-4b92-b788-2406faa45e65 do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:40,394 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:40,396 INFO sqlalchemy.engine.Engine [cached since 9.18s ago] {'user_id': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 9.18s ago] {'user_id': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:40,428 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:40,429 INFO sqlalchemy.engine.Engine [cached since 9.178s ago] {'id': UUID('4144299f-ab31-4a1c-8f46-35fa1df9c707'), 'user_id': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'description': 'Nasze dziecko ma bardzo wysokie podbicie stóp i nietypowy sposób chodzenia. Często skarży się też na bóle nóg.', 'embedding': '[0.025632839649915695,-0.007082325406372547,0.02807120606303215,0.05348953604698181,0.016760440543293953,-0.03376587852835655,-0.027412502095103264,0 ... (7759 characters truncated) ... 05,-0.06558405607938766,-0.055769238620996475,0.015865685418248177,0.06311199814081192,0.030852507799863815,-0.017289644107222557,0.0642557218670845]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.826977133750916}

INFO:sqlalchemy.engine.Engine:[cached since 9.178s ago] {'id': UUID('4144299f-ab31-4a1c-8f46-35fa1df9c707'), 'user_id': UUID('6d7d08b5-a36e-4b92-b788-2406faa45e65'), 'description': 'Nasze dziecko ma bardzo wysokie podbicie stóp i nietypowy sposób chodzenia. Często skarży się też na bóle nóg.', 'embedding': '[0.025632839649915695,-0.007082325406372547,0.02807120606303215,0.05348953604698181,0.016760440543293953,-0.03376587852835655,-0.027412502095103264,0 ... (7759 characters truncated) ... 05,-0.06558405607938766,-0.055769238620996475,0.015865685418248177,0.06311199814081192,0.030852507799863815,-0.017289644107222557,0.0642557218670845]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.826977133750916}

2026-03-14 20:48:40,461 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:40,464 INFO sqlalchemy.engine.Engine [cached since 73.27s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 73.27s ago] {'email_1': 'test0027@zebra.pl', 'param_1': 1}

2026-03-14 20:48:40,499 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,505 INFO sqlalchemy.engine.Engine [cached since 14.79s ago] {'user_id_1': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.79s ago] {'user_id_1': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'param_1': 1}

2026-03-14 20:48:40,535 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,536 INFO sqlalchemy.engine.Engine [cached since 14.82s ago] {'user_id_1': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.82s ago] {'user_id_1': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'param_1': 1}

2026-03-14 20:48:40,630 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:40,632 INFO sqlalchemy.engine.Engine [cached since 9.974s ago] {'embedding': '[0.01335831,-0.00793532,-0.00166413,0.16073908,0.04493880,0.05321838,0.03189824,0.02730003,0.05400140,0.00619523,-0.03482690,-0.02658237,-0.09876566, ... (4123 characters truncated) ... ,0.02952432,0.01812626,-0.04458192,-0.02687006,0.02164251,0.03197502,0.01198954,0.00216121,0.00947267,-0.02402180,-0.02401545,0.03252517,-0.05780310]', 'user_id': 'a07138f7-4ebb-4f18-9626-280a943ccec1', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 9.974s ago] {'embedding': '[0.01335831,-0.00793532,-0.00166413,0.16073908,0.04493880,0.05321838,0.03189824,0.02730003,0.05400140,0.00619523,-0.03482690,-0.02658237,-0.09876566, ... (4123 characters truncated) ... ,0.02952432,0.01812626,-0.04458192,-0.02687006,0.02164251,0.03197502,0.01198954,0.00216121,0.00947267,-0.02402180,-0.02401545,0.03252517,-0.05780310]', 'user_id': 'a07138f7-4ebb-4f18-9626-280a943ccec1', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.5542, group_id=a3bc3fbb-f3a1-4c34-906e-a6676e30d21c
INFO:app.services.matching_service:Score 0.5542 < threshold 0.72 — nowa grupa

2026-03-14 20:48:40,665 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:40,666 INFO sqlalchemy.engine.Engine [cached since 9.961s ago] {'id': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3'), 'name': 'Zielony Szczyt', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#8b5cf6', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 9.961s ago] {'id': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3'), 'name': 'Zielony Szczyt', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#8b5cf6', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: a14e380d-ea0e-4155-ad55-129c3838c2d3
INFO:dataset-notebook:Utworzono profil objawów dla test0027@zebra.pl

2026-03-14 20:48:40,698 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,699 INFO sqlalchemy.engine.Engine [cached since 9.95s ago] {'user_id_1': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'group_id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.95s ago] {'user_id_1': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'group_id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3'), 'param_1': 1}

2026-03-14 20:48:40,732 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:40,733 INFO sqlalchemy.engine.Engine [cached since 9.946s ago] {'member_count_1': 1, 'id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

INFO:sqlalchemy.engine.Engine:[cached since 9.946s ago] {'member_count_1': 1, 'id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}
INFO:app.services.matching_service:Dodano user a07138f7-4ebb-4f18-9626-280a943ccec1 do grupy a14e380d-ea0e-4155-ad55-129c3838c2d3

2026-03-14 20:48:40,766 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:40,767 INFO sqlalchemy.engine.Engine [cached since 9.552s ago] {'user_id': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'group_id': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

INFO:sqlalchemy.engine.Engine:[cached since 9.552s ago] {'user_id': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'group_id': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

2026-03-14 20:48:40,801 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:40,802 INFO sqlalchemy.engine.Engine [cached since 9.551s ago] {'id': UUID('fe976d90-2b8c-45b9-8e31-56823d5093a0'), 'user_id': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'description': 'Córka od urodzenia ma problemy z oddychaniem podczas snu. Często budzi się w nocy i jest bardzo zmęczona w ciągu dnia.', 'embedding': '[0.013358310796320438,-0.007935324683785439,-0.0016641296679154038,0.16073907911777496,0.044938795268535614,0.053218383342027664,0.031898241490125656 ... (7747 characters truncated) ... ,0.011989536695182323,0.002161207841709256,0.009472670033574104,-0.024021796882152557,-0.024015454575419426,0.03252517431974411,-0.05780309811234474]', 'group_id': 'a14e380d-ea0e-4155-ad55-129c3838c2d3', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 9.551s ago] {'id': UUID('fe976d90-2b8c-45b9-8e31-56823d5093a0'), 'user_id': UUID('a07138f7-4ebb-4f18-9626-280a943ccec1'), 'description': 'Córka od urodzenia ma problemy z oddychaniem podczas snu. Często budzi się w nocy i jest bardzo zmęczona w ciągu dnia.', 'embedding': '[0.013358310796320438,-0.007935324683785439,-0.0016641296679154038,0.16073907911777496,0.044938795268535614,0.053218383342027664,0.031898241490125656 ... (7747 characters truncated) ... ,0.011989536695182323,0.002161207841709256,0.009472670033574104,-0.024021796882152557,-0.024015454575419426,0.03252517431974411,-0.05780309811234474]', 'group_id': 'a14e380d-ea0e-4155-ad55-129c3838c2d3', 'match_score': 0.0}

2026-03-14 20:48:40,836 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:40,837 INFO sqlalchemy.engine.Engine [cached since 73.64s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 73.64s ago] {'email_1': 'test0028@zebra.pl', 'param_1': 1}

2026-03-14 20:48:40,868 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,869 INFO sqlalchemy.engine.Engine [cached since 15.15s ago] {'user_id_1': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.15s ago] {'user_id_1': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'param_1': 1}

2026-03-14 20:48:40,902 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:40,903 INFO sqlalchemy.engine.Engine [cached since 15.19s ago] {'user_id_1': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.19s ago] {'user_id_1': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'param_1': 1}

2026-03-14 20:48:40,965 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:40,966 INFO sqlalchemy.engine.Engine [cached since 10.31s ago] {'embedding': '[0.01685104,-0.01106609,0.05569013,0.04483964,-0.02937248,-0.02580776,0.00791711,0.00445086,0.02262715,0.01351364,0.06707020,0.10776126,-0.07474468,0 ... (4116 characters truncated) ... 62,0.03752411,0.01292058,-0.03561299,0.07150263,0.03683193,-0.01148808,0.01510018,-0.03985501,0.04711135,0.05270527,0.09393537,0.00243185,0.06528758]', 'user_id': '8ffb8904-559c-41d7-9026-e59c42329174', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 10.31s ago] {'embedding': '[0.01685104,-0.01106609,0.05569013,0.04483964,-0.02937248,-0.02580776,0.00791711,0.00445086,0.02262715,0.01351364,0.06707020,0.10776126,-0.07474468,0 ... (4116 characters truncated) ... 62,0.03752411,0.01292058,-0.03561299,0.07150263,0.03683193,-0.01148808,0.01510018,-0.03985501,0.04711135,0.05270527,0.09393537,0.00243185,0.06528758]', 'user_id': '8ffb8904-559c-41d7-9026-e59c42329174', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7621, group_id=70b3efbb-3c9b-44db-bf24-f453515ab3dd

2026-03-14 20:48:40,999 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,001 INFO sqlalchemy.engine.Engine [cached since 6.716s ago] {'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 6.716s ago] {'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Złoty Lawenda' (score=0.7621)
INFO:dataset-notebook:Utworzono profil objawów dla test0028@zebra.pl

2026-03-14 20:48:41,034 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,035 INFO sqlalchemy.engine.Engine [cached since 10.29s ago] {'user_id_1': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.29s ago] {'user_id_1': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

2026-03-14 20:48:41,065 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:41,067 INFO sqlalchemy.engine.Engine [cached since 10.28s ago] {'member_count_1': 1, 'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 10.28s ago] {'member_count_1': 1, 'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}
INFO:app.services.matching_service:Dodano user 8ffb8904-559c-41d7-9026-e59c42329174 do grupy 70b3efbb-3c9b-44db-bf24-f453515ab3dd

2026-03-14 20:48:41,099 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:41,100 INFO sqlalchemy.engine.Engine [cached since 9.885s ago] {'user_id': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'group_id': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 9.885s ago] {'user_id': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'group_id': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

2026-03-14 20:48:41,132 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:41,133 INFO sqlalchemy.engine.Engine [cached since 9.882s ago] {'id': UUID('591ec882-d021-4671-85c4-81882dab83f9'), 'user_id': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'description': 'Syn ma trudności z kontrolą ruchów rąk. Czasami pojawiają się mimowolne ruchy, których nie potrafi zatrzymać.', 'embedding': '[0.016851041465997696,-0.011066090315580368,0.055690132081508636,0.044839635491371155,-0.029372481629252434,-0.025807758793234825,0.00791711173951625 ... (7727 characters truncated) ... 664,0.015100176446139812,-0.03985501453280449,0.047111354768276215,0.05270526930689812,0.09393537044525146,0.0024318473879247904,0.06528757512569427]', 'group_id': '70b3efbb-3c9b-44db-bf24-f453515ab3dd', 'match_score': 0.762093924346385}

INFO:sqlalchemy.engine.Engine:[cached since 9.882s ago] {'id': UUID('591ec882-d021-4671-85c4-81882dab83f9'), 'user_id': UUID('8ffb8904-559c-41d7-9026-e59c42329174'), 'description': 'Syn ma trudności z kontrolą ruchów rąk. Czasami pojawiają się mimowolne ruchy, których nie potrafi zatrzymać.', 'embedding': '[0.016851041465997696,-0.011066090315580368,0.055690132081508636,0.044839635491371155,-0.029372481629252434,-0.025807758793234825,0.00791711173951625 ... (7727 characters truncated) ... 664,0.015100176446139812,-0.03985501453280449,0.047111354768276215,0.05270526930689812,0.09393537044525146,0.0024318473879247904,0.06528757512569427]', 'group_id': '70b3efbb-3c9b-44db-bf24-f453515ab3dd', 'match_score': 0.762093924346385}

2026-03-14 20:48:41,174 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:41,183 INFO sqlalchemy.engine.Engine [cached since 73.99s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 73.99s ago] {'email_1': 'test0029@zebra.pl', 'param_1': 1}

2026-03-14 20:48:41,217 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,220 INFO sqlalchemy.engine.Engine [cached since 15.5s ago] {'user_id_1': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.5s ago] {'user_id_1': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'param_1': 1}

2026-03-14 20:48:41,253 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,255 INFO sqlalchemy.engine.Engine [cached since 15.54s ago] {'user_id_1': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.54s ago] {'user_id_1': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'param_1': 1}

2026-03-14 20:48:41,328 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:41,332 INFO sqlalchemy.engine.Engine [cached since 10.67s ago] {'embedding': '[0.06847955,0.02291247,0.04036279,0.05222929,-0.00772262,0.07978032,-0.03672557,0.02019345,0.01219579,-0.01494820,-0.00346323,0.01492726,-0.04724446, ... (4113 characters truncated) ... 245,0.02560424,0.00605564,0.01289658,0.01440665,0.02500080,0.01531586,0.05111585,-0.01813026,0.01613093,0.05466240,0.03824420,0.02656125,-0.00340921]', 'user_id': '38e4b980-12b1-4214-86c8-f8afca40ba29', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 10.67s ago] {'embedding': '[0.06847955,0.02291247,0.04036279,0.05222929,-0.00772262,0.07978032,-0.03672557,0.02019345,0.01219579,-0.01494820,-0.00346323,0.01492726,-0.04724446, ... (4113 characters truncated) ... 245,0.02560424,0.00605564,0.01289658,0.01440665,0.02500080,0.01531586,0.05111585,-0.01813026,0.01613093,0.05466240,0.03824420,0.02656125,-0.00340921]', 'user_id': '38e4b980-12b1-4214-86c8-f8afca40ba29', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7673, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:41,366 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,367 INFO sqlalchemy.engine.Engine [cached since 7.082s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.082s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.7673)
INFO:dataset-notebook:Utworzono profil objawów dla test0029@zebra.pl

2026-03-14 20:48:41,399 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,400 INFO sqlalchemy.engine.Engine [cached since 10.65s ago] {'user_id_1': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 10.65s ago] {'user_id_1': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:41,430 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:41,431 INFO sqlalchemy.engine.Engine [cached since 10.64s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 10.64s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 38e4b980-12b1-4214-86c8-f8afca40ba29 do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:41,464 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:41,465 INFO sqlalchemy.engine.Engine [cached since 10.25s ago] {'user_id': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 10.25s ago] {'user_id': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:41,496 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:41,497 INFO sqlalchemy.engine.Engine [cached since 10.25s ago] {'id': UUID('b88e9730-5cb2-4ae0-9f4d-b99191a276c8'), 'user_id': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'description': 'Nasze dziecko ma bardzo niską tolerancję na wysiłek. Po krótkiej zabawie musi długo odpoczywać. Często jest zmęczone.', 'embedding': '[0.06847955286502838,0.02291247248649597,0.04036279022693634,0.05222928524017334,-0.007722621317952871,0.07978031784296036,-0.036725569516420364,0.02 ... (7756 characters truncated) ... 0.05111585184931755,-0.018130257725715637,0.016130927950143814,0.054662398993968964,0.038244202733039856,0.026561252772808075,-0.0034092124551534653]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.767262367336473}

INFO:sqlalchemy.engine.Engine:[cached since 10.25s ago] {'id': UUID('b88e9730-5cb2-4ae0-9f4d-b99191a276c8'), 'user_id': UUID('38e4b980-12b1-4214-86c8-f8afca40ba29'), 'description': 'Nasze dziecko ma bardzo niską tolerancję na wysiłek. Po krótkiej zabawie musi długo odpoczywać. Często jest zmęczone.', 'embedding': '[0.06847955286502838,0.02291247248649597,0.04036279022693634,0.05222928524017334,-0.007722621317952871,0.07978031784296036,-0.036725569516420364,0.02 ... (7756 characters truncated) ... 0.05111585184931755,-0.018130257725715637,0.016130927950143814,0.054662398993968964,0.038244202733039856,0.026561252772808075,-0.0034092124551534653]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.767262367336473}

2026-03-14 20:48:41,531 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:41,532 INFO sqlalchemy.engine.Engine [cached since 74.34s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 74.34s ago] {'email_1': 'test0030@zebra.pl', 'param_1': 1}

2026-03-14 20:48:41,565 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,566 INFO sqlalchemy.engine.Engine [cached since 15.85s ago] {'user_id_1': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.85s ago] {'user_id_1': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'param_1': 1}

2026-03-14 20:48:41,598 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,600 INFO sqlalchemy.engine.Engine [cached since 15.88s ago] {'user_id_1': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.88s ago] {'user_id_1': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'param_1': 1}

2026-03-14 20:48:41,710 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:41,718 INFO sqlalchemy.engine.Engine [cached since 11.06s ago] {'embedding': '[0.06316520,-0.00194942,0.03590528,0.05773230,-0.05324122,0.00328639,-0.04048980,0.02262555,0.07954865,-0.04414427,0.01418231,0.12773399,-0.01734388, ... (4123 characters truncated) ... 71,0.03138116,-0.04212644,0.03658513,0.04799293,0.04513752,0.00904397,0.02689573,-0.05071231,0.03528810,0.03273147,0.07506850,0.00290412,-0.00741978]', 'user_id': 'fc829384-d102-4995-b558-ae18eebf547a', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 11.06s ago] {'embedding': '[0.06316520,-0.00194942,0.03590528,0.05773230,-0.05324122,0.00328639,-0.04048980,0.02262555,0.07954865,-0.04414427,0.01418231,0.12773399,-0.01734388, ... (4123 characters truncated) ... 71,0.03138116,-0.04212644,0.03658513,0.04799293,0.04513752,0.00904397,0.02689573,-0.05071231,0.03528810,0.03273147,0.07506850,0.00290412,-0.00741978]', 'user_id': 'fc829384-d102-4995-b558-ae18eebf547a', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7476, group_id=ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef

2026-03-14 20:48:41,750 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,754 INFO sqlalchemy.engine.Engine [cached since 7.469s ago] {'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 7.469s ago] {'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Złoty Horyzont' (score=0.7476)
INFO:dataset-notebook:Utworzono profil objawów dla test0030@zebra.pl

2026-03-14 20:48:41,791 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,793 INFO sqlalchemy.engine.Engine [cached since 11.04s ago] {'user_id_1': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.04s ago] {'user_id_1': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

2026-03-14 20:48:41,827 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:41,828 INFO sqlalchemy.engine.Engine [cached since 11.04s ago] {'member_count_1': 1, 'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 11.04s ago] {'member_count_1': 1, 'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}
INFO:app.services.matching_service:Dodano user fc829384-d102-4995-b558-ae18eebf547a do grupy ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef

2026-03-14 20:48:41,861 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:41,862 INFO sqlalchemy.engine.Engine [cached since 10.65s ago] {'user_id': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'group_id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 10.65s ago] {'user_id': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'group_id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

2026-03-14 20:48:41,891 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:41,892 INFO sqlalchemy.engine.Engine [cached since 10.64s ago] {'id': UUID('70731a4e-b7f8-4693-9623-9759bdc7b3f1'), 'user_id': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'description': 'Córka rozwijała się dobrze przez pierwsze lata, ale w ostatnim czasie zauważyliśmy pogorszenie pamięci i koncentracji. Zaczęła też mieć trudności z mówieniem.', 'embedding': '[0.06316519528627396,-0.0019494188018143177,0.03590528294444084,0.057732295244932175,-0.053241223096847534,0.003286391030997038,-0.0404898002743721,0 ... (7745 characters truncated) ... 3,0.02689572609961033,-0.050712306052446365,0.035288095474243164,0.032731473445892334,0.07506850361824036,0.002904118737205863,-0.007419775240123272]', 'group_id': 'ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef', 'match_score': 0.747617251958008}

INFO:sqlalchemy.engine.Engine:[cached since 10.64s ago] {'id': UUID('70731a4e-b7f8-4693-9623-9759bdc7b3f1'), 'user_id': UUID('fc829384-d102-4995-b558-ae18eebf547a'), 'description': 'Córka rozwijała się dobrze przez pierwsze lata, ale w ostatnim czasie zauważyliśmy pogorszenie pamięci i koncentracji. Zaczęła też mieć trudności z mówieniem.', 'embedding': '[0.06316519528627396,-0.0019494188018143177,0.03590528294444084,0.057732295244932175,-0.053241223096847534,0.003286391030997038,-0.0404898002743721,0 ... (7745 characters truncated) ... 3,0.02689572609961033,-0.050712306052446365,0.035288095474243164,0.032731473445892334,0.07506850361824036,0.002904118737205863,-0.007419775240123272]', 'group_id': 'ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef', 'match_score': 0.747617251958008}

2026-03-14 20:48:41,926 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:41,930 INFO sqlalchemy.engine.Engine [cached since 74.74s ago] {'email_1': 'test0031@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 74.74s ago] {'email_1': 'test0031@zebra.pl', 'param_1': 1}

2026-03-14 20:48:41,965 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,966 INFO sqlalchemy.engine.Engine [cached since 16.25s ago] {'user_id_1': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.25s ago] {'user_id_1': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'param_1': 1}

2026-03-14 20:48:41,996 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:41,998 INFO sqlalchemy.engine.Engine [cached since 16.28s ago] {'user_id_1': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.28s ago] {'user_id_1': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'param_1': 1}

2026-03-14 20:48:42,077 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:42,078 INFO sqlalchemy.engine.Engine [cached since 11.42s ago] {'embedding': '[-0.04065738,0.01212426,-0.00753331,0.04401057,-0.05801678,0.08276802,-0.07687130,-0.00277035,-0.01339988,-0.08128019,0.10911841,-0.05799676,-0.07442 ... (4122 characters truncated) ... -0.00435389,-0.06474969,-0.00588544,-0.04823296,0.04891653,0.00174102,-0.00117493,-0.01782887,0.00830225,0.07255785,0.06204468,0.07157822,0.00179555]', 'user_id': '723cb7f6-7261-491c-9754-713ef458c312', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 11.42s ago] {'embedding': '[-0.04065738,0.01212426,-0.00753331,0.04401057,-0.05801678,0.08276802,-0.07687130,-0.00277035,-0.01339988,-0.08128019,0.10911841,-0.05799676,-0.07442 ... (4122 characters truncated) ... -0.00435389,-0.06474969,-0.00588544,-0.04823296,0.04891653,0.00174102,-0.00117493,-0.01782887,0.00830225,0.07255785,0.06204468,0.07157822,0.00179555]', 'user_id': '723cb7f6-7261-491c-9754-713ef458c312', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6393, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6393 < threshold 0.72 — nowa grupa

2026-03-14 20:48:42,111 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:42,112 INFO sqlalchemy.engine.Engine [cached since 11.41s ago] {'id': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e'), 'name': 'Kryształowy Ostoja', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 11.41s ago] {'id': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e'), 'name': 'Kryształowy Ostoja', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: e4af521a-c6e9-4a68-ae6f-01d847476a0e
INFO:dataset-notebook:Utworzono profil objawów dla test0031@zebra.pl

2026-03-14 20:48:42,146 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,147 INFO sqlalchemy.engine.Engine [cached since 11.4s ago] {'user_id_1': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'group_id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.4s ago] {'user_id_1': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'group_id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e'), 'param_1': 1}

2026-03-14 20:48:42,177 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:42,179 INFO sqlalchemy.engine.Engine [cached since 11.39s ago] {'member_count_1': 1, 'id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

INFO:sqlalchemy.engine.Engine:[cached since 11.39s ago] {'member_count_1': 1, 'id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}
INFO:app.services.matching_service:Dodano user 723cb7f6-7261-491c-9754-713ef458c312 do grupy e4af521a-c6e9-4a68-ae6f-01d847476a0e

2026-03-14 20:48:42,212 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:42,213 INFO sqlalchemy.engine.Engine [cached since 11s ago] {'user_id': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'group_id': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

INFO:sqlalchemy.engine.Engine:[cached since 11s ago] {'user_id': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'group_id': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

2026-03-14 20:48:42,242 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:42,244 INFO sqlalchemy.engine.Engine [cached since 10.99s ago] {'id': UUID('0ca7894c-99c9-4dd9-8b23-f254f5dc0f87'), 'user_id': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'description': 'Syn ma rzadki zespół genetyczny. Lekarze zwrócili uwagę na charakterystyczne rysy twarzy i wadę serca wykrytą w pierwszych miesiącach. Rozwój jest opóźniony — zarówno ruchowy, jak i mowa. Szukam innych rodzin z podobnym rozpoznaniem, żeby wymienić się doświadczeniami i radami.', 'embedding': '[-0.04065737873315811,0.012124263681471348,-0.007533313240855932,0.04401056841015816,-0.058016784489154816,0.0827680230140686,-0.07687129825353622,-0 ... (7747 characters truncated) ... 2,-0.0011749264085665345,-0.017828866839408875,0.00830224622040987,0.07255785167217255,0.06204467639327049,0.07157821953296661,0.0017955465009436011]', 'group_id': 'e4af521a-c6e9-4a68-ae6f-01d847476a0e', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 10.99s ago] {'id': UUID('0ca7894c-99c9-4dd9-8b23-f254f5dc0f87'), 'user_id': UUID('723cb7f6-7261-491c-9754-713ef458c312'), 'description': 'Syn ma rzadki zespół genetyczny. Lekarze zwrócili uwagę na charakterystyczne rysy twarzy i wadę serca wykrytą w pierwszych miesiącach. Rozwój jest opóźniony — zarówno ruchowy, jak i mowa. Szukam innych rodzin z podobnym rozpoznaniem, żeby wymienić się doświadczeniami i radami.', 'embedding': '[-0.04065737873315811,0.012124263681471348,-0.007533313240855932,0.04401056841015816,-0.058016784489154816,0.0827680230140686,-0.07687129825353622,-0 ... (7747 characters truncated) ... 2,-0.0011749264085665345,-0.017828866839408875,0.00830224622040987,0.07255785167217255,0.06204467639327049,0.07157821953296661,0.0017955465009436011]', 'group_id': 'e4af521a-c6e9-4a68-ae6f-01d847476a0e', 'match_score': 0.0}

2026-03-14 20:48:42,277 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:42,279 INFO sqlalchemy.engine.Engine [cached since 75.09s ago] {'email_1': 'test0032@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 75.09s ago] {'email_1': 'test0032@zebra.pl', 'param_1': 1}

2026-03-14 20:48:42,313 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,314 INFO sqlalchemy.engine.Engine [cached since 16.6s ago] {'user_id_1': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.6s ago] {'user_id_1': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'param_1': 1}

2026-03-14 20:48:42,344 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,345 INFO sqlalchemy.engine.Engine [cached since 16.63s ago] {'user_id_1': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.63s ago] {'user_id_1': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'param_1': 1}

2026-03-14 20:48:42,423 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:42,424 INFO sqlalchemy.engine.Engine [cached since 11.77s ago] {'embedding': '[0.00356450,-0.00188978,0.06244483,0.17104818,0.00768385,0.01518742,0.02755576,0.00531690,-0.01179499,-0.04224526,0.07512607,-0.06380000,-0.03719694, ... (4124 characters truncated) ... ,-0.02537674,-0.06108051,0.00693715,-0.08897395,0.00285630,0.10489723,-0.06279655,0.00429963,0.04317474,0.05373727,0.05147626,-0.00755068,0.03552921]', 'user_id': 'b58072a2-85a0-478d-9910-33193921e290', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 11.77s ago] {'embedding': '[0.00356450,-0.00188978,0.06244483,0.17104818,0.00768385,0.01518742,0.02755576,0.00531690,-0.01179499,-0.04224526,0.07512607,-0.06380000,-0.03719694, ... (4124 characters truncated) ... ,-0.02537674,-0.06108051,0.00693715,-0.08897395,0.00285630,0.10489723,-0.06279655,0.00429963,0.04317474,0.05373727,0.05147626,-0.00755068,0.03552921]', 'user_id': 'b58072a2-85a0-478d-9910-33193921e290', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.8614, group_id=0946e26a-2416-427b-80d3-cb4e30902b5b

2026-03-14 20:48:42,458 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,459 INFO sqlalchemy.engine.Engine [cached since 8.174s ago] {'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.174s ago] {'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Fioletowy Cypel' (score=0.8614)
INFO:dataset-notebook:Utworzono profil objawów dla test0032@zebra.pl

2026-03-14 20:48:42,494 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,496 INFO sqlalchemy.engine.Engine [cached since 11.75s ago] {'user_id_1': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 11.75s ago] {'user_id_1': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

2026-03-14 20:48:42,528 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:42,529 INFO sqlalchemy.engine.Engine [cached since 11.74s ago] {'member_count_1': 1, 'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 11.74s ago] {'member_count_1': 1, 'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}
INFO:app.services.matching_service:Dodano user b58072a2-85a0-478d-9910-33193921e290 do grupy 0946e26a-2416-427b-80d3-cb4e30902b5b

2026-03-14 20:48:42,562 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:42,564 INFO sqlalchemy.engine.Engine [cached since 11.35s ago] {'user_id': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'group_id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 11.35s ago] {'user_id': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'group_id': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

2026-03-14 20:48:42,596 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:42,597 INFO sqlalchemy.engine.Engine [cached since 11.35s ago] {'id': UUID('3ca7c83b-092c-47c2-be08-c96782d154ba'), 'user_id': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'description': 'Nasza córka od urodzenia ma bardzo jasną skórę i włosy oraz ogromną wrażliwość na światło. Na słońcu musi mieć okulary i krem z wysokim filtrem. Wzrok się pogarsza i ma problemy z widzeniem w jasnym świetle. Chciałabym porozmawiać z opiekunami dzieci z podobnymi objawami.', 'embedding': '[0.003564500482752919,-0.0018897766713052988,0.06244483217597008,0.17104817926883698,0.007683853153139353,0.01518742274492979,0.027555756270885468,0. ... (7766 characters truncated) ... 117,-0.06279654800891876,0.004299625754356384,0.04317474365234375,0.05373727157711983,0.05147625878453255,-0.0075506786815822124,0.03552921116352081]', 'group_id': '0946e26a-2416-427b-80d3-cb4e30902b5b', 'match_score': 0.861422019728007}

INFO:sqlalchemy.engine.Engine:[cached since 11.35s ago] {'id': UUID('3ca7c83b-092c-47c2-be08-c96782d154ba'), 'user_id': UUID('b58072a2-85a0-478d-9910-33193921e290'), 'description': 'Nasza córka od urodzenia ma bardzo jasną skórę i włosy oraz ogromną wrażliwość na światło. Na słońcu musi mieć okulary i krem z wysokim filtrem. Wzrok się pogarsza i ma problemy z widzeniem w jasnym świetle. Chciałabym porozmawiać z opiekunami dzieci z podobnymi objawami.', 'embedding': '[0.003564500482752919,-0.0018897766713052988,0.06244483217597008,0.17104817926883698,0.007683853153139353,0.01518742274492979,0.027555756270885468,0. ... (7766 characters truncated) ... 117,-0.06279654800891876,0.004299625754356384,0.04317474365234375,0.05373727157711983,0.05147625878453255,-0.0075506786815822124,0.03552921116352081]', 'group_id': '0946e26a-2416-427b-80d3-cb4e30902b5b', 'match_score': 0.861422019728007}

2026-03-14 20:48:42,632 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:42,641 INFO sqlalchemy.engine.Engine [cached since 75.45s ago] {'email_1': 'test0033@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 75.45s ago] {'email_1': 'test0033@zebra.pl', 'param_1': 1}

2026-03-14 20:48:42,677 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,679 INFO sqlalchemy.engine.Engine [cached since 16.96s ago] {'user_id_1': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.96s ago] {'user_id_1': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'param_1': 1}

2026-03-14 20:48:42,712 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,716 INFO sqlalchemy.engine.Engine [cached since 17s ago] {'user_id_1': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17s ago] {'user_id_1': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'param_1': 1}

2026-03-14 20:48:42,822 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:42,823 INFO sqlalchemy.engine.Engine [cached since 12.17s ago] {'embedding': '[0.00324010,0.03528883,0.01623064,0.02319103,0.00498012,0.03557366,-0.06555472,0.03319512,-0.00234534,-0.00213419,0.10988733,0.04733023,-0.03571055,0 ... (4112 characters truncated) ... ,0.06370711,-0.03197044,0.00025816,0.06819256,0.02255599,-0.09575196,0.00821021,-0.09152125,-0.01165437,0.08122701,0.04064836,-0.01009514,0.04314223]', 'user_id': '2972a91d-980f-486f-bc04-3db94311403f', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 12.17s ago] {'embedding': '[0.00324010,0.03528883,0.01623064,0.02319103,0.00498012,0.03557366,-0.06555472,0.03319512,-0.00234534,-0.00213419,0.10988733,0.04733023,-0.03571055,0 ... (4112 characters truncated) ... ,0.06370711,-0.03197044,0.00025816,0.06819256,0.02255599,-0.09575196,0.00821021,-0.09152125,-0.01165437,0.08122701,0.04064836,-0.01009514,0.04314223]', 'user_id': '2972a91d-980f-486f-bc04-3db94311403f', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7831, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:42,857 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,858 INFO sqlalchemy.engine.Engine [cached since 8.573s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 8.573s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Jadeitowy Topaz' (score=0.7831)
INFO:dataset-notebook:Utworzono profil objawów dla test0033@zebra.pl

2026-03-14 20:48:42,889 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:42,890 INFO sqlalchemy.engine.Engine [cached since 12.14s ago] {'user_id_1': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.14s ago] {'user_id_1': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:42,921 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:42,922 INFO sqlalchemy.engine.Engine [cached since 12.14s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 12.14s ago] {'member_count_1': 1, 'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.matching_service:Dodano user 2972a91d-980f-486f-bc04-3db94311403f do grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b

2026-03-14 20:48:42,957 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:42,959 INFO sqlalchemy.engine.Engine [cached since 11.74s ago] {'user_id': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 11.74s ago] {'user_id': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'group_id': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:42,992 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:42,994 INFO sqlalchemy.engine.Engine [cached since 11.74s ago] {'id': UUID('935add56-d6fb-483f-a71d-066645c264a5'), 'user_id': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'description': 'Syn w pierwszych latach chodził i biegał normalnie. Z czasem zaczęły się problemy z wchodzeniem po schodach i wstawaniem z podłogi. Mięśnie nóg słabną i lekarze mówią o postępującej chorobie. Szukam wsparcia u innych rodziców dzieci z osłabieniem mięśni.', 'embedding': '[0.0032400996424257755,0.03528883308172226,0.016230640932917595,0.023191029205918312,0.004980121739208698,0.03557366132736206,-0.06555471569299698,0. ... (7754 characters truncated) ... 284,0.00821021106094122,-0.0915212482213974,-0.011654370464384556,0.08122701197862625,0.04064835608005524,-0.010095140896737576,0.043142225593328476]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.783069823154195}

INFO:sqlalchemy.engine.Engine:[cached since 11.74s ago] {'id': UUID('935add56-d6fb-483f-a71d-066645c264a5'), 'user_id': UUID('2972a91d-980f-486f-bc04-3db94311403f'), 'description': 'Syn w pierwszych latach chodził i biegał normalnie. Z czasem zaczęły się problemy z wchodzeniem po schodach i wstawaniem z podłogi. Mięśnie nóg słabną i lekarze mówią o postępującej chorobie. Szukam wsparcia u innych rodziców dzieci z osłabieniem mięśni.', 'embedding': '[0.0032400996424257755,0.03528883308172226,0.016230640932917595,0.023191029205918312,0.004980121739208698,0.03557366132736206,-0.06555471569299698,0. ... (7754 characters truncated) ... 284,0.00821021106094122,-0.0915212482213974,-0.011654370464384556,0.08122701197862625,0.04064835608005524,-0.010095140896737576,0.043142225593328476]', 'group_id': 'a2644a80-31b4-430d-9a1d-7d1cbc922e9b', 'match_score': 0.783069823154195}

2026-03-14 20:48:43,029 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:43,031 INFO sqlalchemy.engine.Engine [cached since 75.84s ago] {'email_1': 'test0034@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 75.84s ago] {'email_1': 'test0034@zebra.pl', 'param_1': 1}

2026-03-14 20:48:43,062 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,064 INFO sqlalchemy.engine.Engine [cached since 17.35s ago] {'user_id_1': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.35s ago] {'user_id_1': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'param_1': 1}

2026-03-14 20:48:43,097 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,098 INFO sqlalchemy.engine.Engine [cached since 17.38s ago] {'user_id_1': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.38s ago] {'user_id_1': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'param_1': 1}

2026-03-14 20:48:43,180 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:43,181 INFO sqlalchemy.engine.Engine [cached since 12.52s ago] {'embedding': '[0.02757196,0.01328567,0.02481148,0.05242810,-0.04515982,0.04171716,-0.02732848,0.00267225,0.03408952,-0.00443872,0.08149105,0.05033277,-0.00256741,0 ... (4131 characters truncated) ... 7,-0.01512209,-0.02511447,0.01505300,0.07255845,0.02898844,-0.00110894,0.03566266,-0.01132006,0.04366769,0.05158577,0.10216629,0.04196608,0.01611272]', 'user_id': '822a087c-e205-4fb7-b8f8-b1154d544525', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 12.52s ago] {'embedding': '[0.02757196,0.01328567,0.02481148,0.05242810,-0.04515982,0.04171716,-0.02732848,0.00267225,0.03408952,-0.00443872,0.08149105,0.05033277,-0.00256741,0 ... (4131 characters truncated) ... 7,-0.01512209,-0.02511447,0.01505300,0.07255845,0.02898844,-0.00110894,0.03566266,-0.01132006,0.04366769,0.05158577,0.10216629,0.04196608,0.01611272]', 'user_id': '822a087c-e205-4fb7-b8f8-b1154d544525', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7069, group_id=ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef
INFO:app.services.matching_service:Score 0.7069 < threshold 0.72 — nowa grupa

2026-03-14 20:48:43,215 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:43,216 INFO sqlalchemy.engine.Engine [cached since 12.51s ago] {'id': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7'), 'name': 'Miedziany Szałwia', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 12.51s ago] {'id': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7'), 'name': 'Miedziany Szałwia', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f59e0b', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 6c079d41-d7ef-4c7f-a66d-f116425206d7
INFO:dataset-notebook:Utworzono profil objawów dla test0034@zebra.pl

2026-03-14 20:48:43,251 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,252 INFO sqlalchemy.engine.Engine [cached since 12.5s ago] {'user_id_1': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'group_id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.5s ago] {'user_id_1': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'group_id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7'), 'param_1': 1}

2026-03-14 20:48:43,283 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:43,285 INFO sqlalchemy.engine.Engine [cached since 12.5s ago] {'member_count_1': 1, 'id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

INFO:sqlalchemy.engine.Engine:[cached since 12.5s ago] {'member_count_1': 1, 'id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}
INFO:app.services.matching_service:Dodano user 822a087c-e205-4fb7-b8f8-b1154d544525 do grupy 6c079d41-d7ef-4c7f-a66d-f116425206d7

2026-03-14 20:48:43,320 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:43,321 INFO sqlalchemy.engine.Engine [cached since 12.11s ago] {'user_id': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'group_id': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

INFO:sqlalchemy.engine.Engine:[cached since 12.11s ago] {'user_id': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'group_id': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

2026-03-14 20:48:43,354 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:43,355 INFO sqlalchemy.engine.Engine [cached since 12.1s ago] {'id': UUID('45cde552-d45e-4515-82ca-110d7ccb11b2'), 'user_id': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'description': 'Córka od niemowlęctwa miała napady drgawek. Rozwój ruchowy i mowy jest opóźniony. Zauważyliśmy też, że ma trudności w kontaktach z rówieśnikami, unika zabawy w grupie i preferuje stałe rytuały. Szukam osób, które łączą napady z opóźnieniem rozwoju i trudnościami w relacjach.', 'embedding': '[0.02757195569574833,0.013285667635500431,0.024811482056975365,0.05242810398340225,-0.045159824192523956,0.041717156767845154,-0.027328483760356903,0 ... (7786 characters truncated) ... 6715,0.035662658512592316,-0.011320063844323158,0.04366769269108772,0.05158577114343643,0.10216628760099411,0.04196608066558838,0.016112718731164932]', 'group_id': '6c079d41-d7ef-4c7f-a66d-f116425206d7', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 12.1s ago] {'id': UUID('45cde552-d45e-4515-82ca-110d7ccb11b2'), 'user_id': UUID('822a087c-e205-4fb7-b8f8-b1154d544525'), 'description': 'Córka od niemowlęctwa miała napady drgawek. Rozwój ruchowy i mowy jest opóźniony. Zauważyliśmy też, że ma trudności w kontaktach z rówieśnikami, unika zabawy w grupie i preferuje stałe rytuały. Szukam osób, które łączą napady z opóźnieniem rozwoju i trudnościami w relacjach.', 'embedding': '[0.02757195569574833,0.013285667635500431,0.024811482056975365,0.05242810398340225,-0.045159824192523956,0.041717156767845154,-0.027328483760356903,0 ... (7786 characters truncated) ... 6715,0.035662658512592316,-0.011320063844323158,0.04366769269108772,0.05158577114343643,0.10216628760099411,0.04196608066558838,0.016112718731164932]', 'group_id': '6c079d41-d7ef-4c7f-a66d-f116425206d7', 'match_score': 0.0}

2026-03-14 20:48:43,391 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:43,393 INFO sqlalchemy.engine.Engine [cached since 76.2s ago] {'email_1': 'test0035@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 76.2s ago] {'email_1': 'test0035@zebra.pl', 'param_1': 1}

2026-03-14 20:48:43,423 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,424 INFO sqlalchemy.engine.Engine [cached since 17.71s ago] {'user_id_1': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.71s ago] {'user_id_1': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'param_1': 1}

2026-03-14 20:48:43,458 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,459 INFO sqlalchemy.engine.Engine [cached since 17.74s ago] {'user_id_1': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.74s ago] {'user_id_1': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'param_1': 1}

2026-03-14 20:48:43,616 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:43,618 INFO sqlalchemy.engine.Engine [cached since 12.96s ago] {'embedding': '[-0.00427173,-0.03807261,0.03503965,0.11128008,0.01171245,0.06910677,-0.04751356,0.00549761,-0.00845607,-0.09053448,0.09199640,0.02677314,-0.05865995 ... (4117 characters truncated) ... ,-0.06978745,-0.01950942,0.04640239,-0.06138863,0.02860493,0.10799035,-0.01256528,0.06458238,0.03804803,0.09035820,-0.02077129,0.04188471,0.07195602]', 'user_id': '8b226ce4-42f9-437b-8512-3fcbaeaa51a8', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 12.96s ago] {'embedding': '[-0.00427173,-0.03807261,0.03503965,0.11128008,0.01171245,0.06910677,-0.04751356,0.00549761,-0.00845607,-0.09053448,0.09199640,0.02677314,-0.05865995 ... (4117 characters truncated) ... ,-0.06978745,-0.01950942,0.04640239,-0.06138863,0.02860493,0.10799035,-0.01256528,0.06458238,0.03804803,0.09035820,-0.02077129,0.04188471,0.07195602]', 'user_id': '8b226ce4-42f9-437b-8512-3fcbaeaa51a8', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6868, group_id=0946e26a-2416-427b-80d3-cb4e30902b5b
INFO:app.services.matching_service:Score 0.6868 < threshold 0.72 — nowa grupa

2026-03-14 20:48:43,657 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:43,660 INFO sqlalchemy.engine.Engine [cached since 12.95s ago] {'id': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361'), 'name': 'Turkusowy Przylądek', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#ec4899', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 12.95s ago] {'id': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361'), 'name': 'Turkusowy Przylądek', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#ec4899', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 6e09cb1a-0a9b-4321-8192-c71fbb654361
INFO:dataset-notebook:Utworzono profil objawów dla test0035@zebra.pl

2026-03-14 20:48:43,694 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,695 INFO sqlalchemy.engine.Engine [cached since 12.95s ago] {'user_id_1': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'group_id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.95s ago] {'user_id_1': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'group_id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361'), 'param_1': 1}

2026-03-14 20:48:43,726 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:43,727 INFO sqlalchemy.engine.Engine [cached since 12.94s ago] {'member_count_1': 1, 'id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

INFO:sqlalchemy.engine.Engine:[cached since 12.94s ago] {'member_count_1': 1, 'id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}
INFO:app.services.matching_service:Dodano user 8b226ce4-42f9-437b-8512-3fcbaeaa51a8 do grupy 6e09cb1a-0a9b-4321-8192-c71fbb654361

2026-03-14 20:48:43,762 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:43,764 INFO sqlalchemy.engine.Engine [cached since 12.55s ago] {'user_id': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'group_id': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

INFO:sqlalchemy.engine.Engine:[cached since 12.55s ago] {'user_id': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'group_id': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

2026-03-14 20:48:43,797 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:43,798 INFO sqlalchemy.engine.Engine [cached since 12.55s ago] {'id': UUID('f0a8da6a-caab-426e-b986-867e13c8b139'), 'user_id': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'description': 'Nasze dziecko ma rzadką chorobę skóry. Nawet lekkie otarcie powoduje pęcherze i rany. Skóra jest bardzo wrażliwa, musimy unikać urazów i nosić odpowiednie ubrania. Codzienna pielęgnacja zajmuje dużo czasu. Chciałabym poznać inne rodziny z podobnym doświadczeniem.', 'embedding': '[-0.004271731246262789,-0.0380726084113121,0.03503965213894844,0.11128008365631104,0.011712453328073025,0.06910676509141922,-0.04751356318593025,0.00 ... (7745 characters truncated) ... 96469,-0.012565278448164463,0.06458237767219543,0.03804802522063255,0.0903581976890564,-0.020771294832229614,0.04188470542430878,0.07195602357387543]', 'group_id': '6e09cb1a-0a9b-4321-8192-c71fbb654361', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 12.55s ago] {'id': UUID('f0a8da6a-caab-426e-b986-867e13c8b139'), 'user_id': UUID('8b226ce4-42f9-437b-8512-3fcbaeaa51a8'), 'description': 'Nasze dziecko ma rzadką chorobę skóry. Nawet lekkie otarcie powoduje pęcherze i rany. Skóra jest bardzo wrażliwa, musimy unikać urazów i nosić odpowiednie ubrania. Codzienna pielęgnacja zajmuje dużo czasu. Chciałabym poznać inne rodziny z podobnym doświadczeniem.', 'embedding': '[-0.004271731246262789,-0.0380726084113121,0.03503965213894844,0.11128008365631104,0.011712453328073025,0.06910676509141922,-0.04751356318593025,0.00 ... (7745 characters truncated) ... 96469,-0.012565278448164463,0.06458237767219543,0.03804802522063255,0.0903581976890564,-0.020771294832229614,0.04188470542430878,0.07195602357387543]', 'group_id': '6e09cb1a-0a9b-4321-8192-c71fbb654361', 'match_score': 0.0}

2026-03-14 20:48:43,835 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:43,836 INFO sqlalchemy.engine.Engine [cached since 76.64s ago] {'email_1': 'test0036@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 76.64s ago] {'email_1': 'test0036@zebra.pl', 'param_1': 1}

2026-03-14 20:48:43,867 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,868 INFO sqlalchemy.engine.Engine [cached since 18.15s ago] {'user_id_1': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.15s ago] {'user_id_1': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'param_1': 1}

2026-03-14 20:48:43,903 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:43,904 INFO sqlalchemy.engine.Engine [cached since 18.19s ago] {'user_id_1': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.19s ago] {'user_id_1': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'param_1': 1}

2026-03-14 20:48:43,985 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:43,987 INFO sqlalchemy.engine.Engine [cached since 13.33s ago] {'embedding': '[0.07030116,0.08585179,0.02370717,-0.00766444,-0.04161232,-0.00877653,-0.03259695,0.04713777,0.02493184,-0.04173093,0.15035328,-0.02521786,-0.0143168 ... (4114 characters truncated) ... 3,0.06682546,-0.05399825,0.01582835,0.00779666,0.02554552,-0.02941273,0.01103749,-0.00998414,0.04152611,0.11590604,0.07783013,0.01799326,-0.00458612]', 'user_id': 'fb4a069f-7667-48cd-bede-5ee7f639e91a', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 13.33s ago] {'embedding': '[0.07030116,0.08585179,0.02370717,-0.00766444,-0.04161232,-0.00877653,-0.03259695,0.04713777,0.02493184,-0.04173093,0.15035328,-0.02521786,-0.0143168 ... (4114 characters truncated) ... 3,0.06682546,-0.05399825,0.01582835,0.00779666,0.02554552,-0.02941273,0.01103749,-0.00998414,0.04152611,0.11590604,0.07783013,0.01799326,-0.00458612]', 'user_id': 'fb4a069f-7667-48cd-bede-5ee7f639e91a', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7358, group_id=49357027-f555-473a-8c72-cafd78dc5fc2

2026-03-14 20:48:44,020 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,022 INFO sqlalchemy.engine.Engine [cached since 9.737s ago] {'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 9.737s ago] {'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}
INFO:app.services.matching_service:Dopasowano do grupy 'Kremowy Przylądek' (score=0.7358)
INFO:dataset-notebook:Utworzono profil objawów dla test0036@zebra.pl

2026-03-14 20:48:44,054 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,055 INFO sqlalchemy.engine.Engine [cached since 13.31s ago] {'user_id_1': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.31s ago] {'user_id_1': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

2026-03-14 20:48:44,086 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:44,088 INFO sqlalchemy.engine.Engine [cached since 13.3s ago] {'member_count_1': 1, 'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 13.3s ago] {'member_count_1': 1, 'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}
INFO:app.services.matching_service:Dodano user fb4a069f-7667-48cd-bede-5ee7f639e91a do grupy 49357027-f555-473a-8c72-cafd78dc5fc2

2026-03-14 20:48:44,129 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:44,132 INFO sqlalchemy.engine.Engine [cached since 12.92s ago] {'user_id': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'group_id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 12.92s ago] {'user_id': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'group_id': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

2026-03-14 20:48:44,171 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:44,175 INFO sqlalchemy.engine.Engine [cached since 12.92s ago] {'id': UUID('95ba2954-3b45-42a8-b704-ee364672d238'), 'user_id': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'description': 'Syn jest znacznie niższy od rówieśników i ma nietypowe proporcje ciała — krótsze kończyny, większą głowę. Rozwój intelektualny przebiega inaczej niż u innych dzieci. Szukam kontaktu z rodzicami dzieci z niskim wzrostem i specyficznymi proporcjami.', 'embedding': '[0.07030116021633148,0.08585178852081299,0.02370717190206051,-0.007664441596716642,-0.04161232337355614,-0.008776531554758549,-0.032596949487924576,0 ... (7724 characters truncated) ... 16,0.011037491261959076,-0.009984143078327179,0.041526105254888535,0.11590603739023209,0.07783012837171555,0.01799326203763485,-0.004586119670420885]', 'group_id': '49357027-f555-473a-8c72-cafd78dc5fc2', 'match_score': 0.735833055004453}

INFO:sqlalchemy.engine.Engine:[cached since 12.92s ago] {'id': UUID('95ba2954-3b45-42a8-b704-ee364672d238'), 'user_id': UUID('fb4a069f-7667-48cd-bede-5ee7f639e91a'), 'description': 'Syn jest znacznie niższy od rówieśników i ma nietypowe proporcje ciała — krótsze kończyny, większą głowę. Rozwój intelektualny przebiega inaczej niż u innych dzieci. Szukam kontaktu z rodzicami dzieci z niskim wzrostem i specyficznymi proporcjami.', 'embedding': '[0.07030116021633148,0.08585178852081299,0.02370717190206051,-0.007664441596716642,-0.04161232337355614,-0.008776531554758549,-0.032596949487924576,0 ... (7724 characters truncated) ... 16,0.011037491261959076,-0.009984143078327179,0.041526105254888535,0.11590603739023209,0.07783012837171555,0.01799326203763485,-0.004586119670420885]', 'group_id': '49357027-f555-473a-8c72-cafd78dc5fc2', 'match_score': 0.735833055004453}

2026-03-14 20:48:44,213 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:44,218 INFO sqlalchemy.engine.Engine [cached since 77.02s ago] {'email_1': 'test0037@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 77.02s ago] {'email_1': 'test0037@zebra.pl', 'param_1': 1}

2026-03-14 20:48:44,250 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,252 INFO sqlalchemy.engine.Engine [cached since 18.54s ago] {'user_id_1': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.54s ago] {'user_id_1': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'param_1': 1}

2026-03-14 20:48:44,288 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,292 INFO sqlalchemy.engine.Engine [cached since 18.58s ago] {'user_id_1': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.58s ago] {'user_id_1': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'param_1': 1}

2026-03-14 20:48:44,387 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:44,389 INFO sqlalchemy.engine.Engine [cached since 13.73s ago] {'embedding': '[-0.04889190,0.02603507,0.03682069,0.13733561,0.04717958,0.02982132,0.00959142,-0.01830708,-0.08336570,-0.02694358,-0.01512973,-0.00830407,-0.0636148 ... (4122 characters truncated) ... 5996245,-0.01051713,0.06121320,-0.03601494,-0.00067902,-0.01072216,0.00640437,-0.01767183,-0.00162629,-0.04036200,-0.03081183,-0.08087548,0.03437871]', 'user_id': 'ed64c67e-2f08-4847-a242-6ce4c8706b8c', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 13.73s ago] {'embedding': '[-0.04889190,0.02603507,0.03682069,0.13733561,0.04717958,0.02982132,0.00959142,-0.01830708,-0.08336570,-0.02694358,-0.01512973,-0.00830407,-0.0636148 ... (4122 characters truncated) ... 5996245,-0.01051713,0.06121320,-0.03601494,-0.00067902,-0.01072216,0.00640437,-0.01767183,-0.00162629,-0.04036200,-0.03081183,-0.08087548,0.03437871]', 'user_id': 'ed64c67e-2f08-4847-a242-6ce4c8706b8c', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6451, group_id=ee9f537e-dc5a-4927-ac9c-7fb86211aa09
INFO:app.services.matching_service:Score 0.6451 < threshold 0.72 — nowa grupa

2026-03-14 20:48:44,424 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:44,425 INFO sqlalchemy.engine.Engine [cached since 13.72s ago] {'id': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9'), 'name': 'Różowy Wiąz', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 13.72s ago] {'id': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9'), 'name': 'Różowy Wiąz', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 816e4d87-bfa7-4db8-ae3a-c5a62b9452b9
INFO:dataset-notebook:Utworzono profil objawów dla test0037@zebra.pl

2026-03-14 20:48:44,459 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,460 INFO sqlalchemy.engine.Engine [cached since 13.71s ago] {'user_id_1': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'group_id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.71s ago] {'user_id_1': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'group_id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9'), 'param_1': 1}

2026-03-14 20:48:44,495 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:44,496 INFO sqlalchemy.engine.Engine [cached since 13.71s ago] {'member_count_1': 1, 'id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

INFO:sqlalchemy.engine.Engine:[cached since 13.71s ago] {'member_count_1': 1, 'id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}
INFO:app.services.matching_service:Dodano user ed64c67e-2f08-4847-a242-6ce4c8706b8c do grupy 816e4d87-bfa7-4db8-ae3a-c5a62b9452b9

2026-03-14 20:48:44,527 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:44,528 INFO sqlalchemy.engine.Engine [cached since 13.31s ago] {'user_id': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'group_id': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

INFO:sqlalchemy.engine.Engine:[cached since 13.31s ago] {'user_id': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'group_id': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

2026-03-14 20:48:44,561 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:44,563 INFO sqlalchemy.engine.Engine [cached since 13.31s ago] {'id': UUID('12638951-593d-46a3-884a-e64a1c1c1362'), 'user_id': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'description': 'Córka bardzo źle znosi zimno. Już przy lekkim chłodzie skarży się na bóle stawów i mięśni i jest bardzo zmęczona. Unikamy wychodzenia w chłodne dni bez odpowiedniego ubrania. Chciałabym porozmawiać z kimś, kto ma dziecko z podobną nietolerancją zimna i bólami.', 'embedding': '[-0.04889190196990967,0.026035066694021225,0.03682069107890129,0.1373356133699417,0.047179583460092545,0.02982131950557232,0.00959142204374075,-0.018 ... (7748 characters truncated) ... .0064043705351650715,-0.01767183467745781,-0.0016262868884950876,-0.040362000465393066,-0.03081182762980461,-0.08087547868490219,0.03437871113419533]', 'group_id': '816e4d87-bfa7-4db8-ae3a-c5a62b9452b9', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 13.31s ago] {'id': UUID('12638951-593d-46a3-884a-e64a1c1c1362'), 'user_id': UUID('ed64c67e-2f08-4847-a242-6ce4c8706b8c'), 'description': 'Córka bardzo źle znosi zimno. Już przy lekkim chłodzie skarży się na bóle stawów i mięśni i jest bardzo zmęczona. Unikamy wychodzenia w chłodne dni bez odpowiedniego ubrania. Chciałabym porozmawiać z kimś, kto ma dziecko z podobną nietolerancją zimna i bólami.', 'embedding': '[-0.04889190196990967,0.026035066694021225,0.03682069107890129,0.1373356133699417,0.047179583460092545,0.02982131950557232,0.00959142204374075,-0.018 ... (7748 characters truncated) ... .0064043705351650715,-0.01767183467745781,-0.0016262868884950876,-0.040362000465393066,-0.03081182762980461,-0.08087547868490219,0.03437871113419533]', 'group_id': '816e4d87-bfa7-4db8-ae3a-c5a62b9452b9', 'match_score': 0.0}

2026-03-14 20:48:44,598 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:44,599 INFO sqlalchemy.engine.Engine [cached since 77.41s ago] {'email_1': 'test0038@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 77.41s ago] {'email_1': 'test0038@zebra.pl', 'param_1': 1}

2026-03-14 20:48:44,629 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,630 INFO sqlalchemy.engine.Engine [cached since 18.91s ago] {'user_id_1': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.91s ago] {'user_id_1': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'param_1': 1}

2026-03-14 20:48:44,662 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,663 INFO sqlalchemy.engine.Engine [cached since 18.95s ago] {'user_id_1': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.95s ago] {'user_id_1': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'param_1': 1}

2026-03-14 20:48:44,753 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:44,754 INFO sqlalchemy.engine.Engine [cached since 14.1s ago] {'embedding': '[-0.00540748,0.00222416,0.00491506,0.06387140,-0.01106724,0.03297364,-0.04895859,0.00524651,-0.02610833,-0.08080780,0.00154180,0.03302890,-0.12283825 ... (4114 characters truncated) ... 9,0.00628596,0.05518406,-0.03526846,0.04167383,0.05576174,0.01206238,-0.08801210,0.00842931,-0.00674603,0.12008683,0.00686444,0.10063449,-0.02614483]', 'user_id': '48c7beb8-52e5-4a28-a784-fbcf737ab655', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 14.1s ago] {'embedding': '[-0.00540748,0.00222416,0.00491506,0.06387140,-0.01106724,0.03297364,-0.04895859,0.00524651,-0.02610833,-0.08080780,0.00154180,0.03302890,-0.12283825 ... (4114 characters truncated) ... 9,0.00628596,0.05518406,-0.03526846,0.04167383,0.05576174,0.01206238,-0.08801210,0.00842931,-0.00674603,0.12008683,0.00686444,0.10063449,-0.02614483]', 'user_id': '48c7beb8-52e5-4a28-a784-fbcf737ab655', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6008, group_id=e816d3a6-a075-45f7-92c4-3d1f38818ea9
INFO:app.services.matching_service:Score 0.6008 < threshold 0.72 — nowa grupa

2026-03-14 20:48:44,789 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:44,790 INFO sqlalchemy.engine.Engine [cached since 14.09s ago] {'id': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834'), 'name': 'Rubinowy Leszczyna', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 14.09s ago] {'id': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834'), 'name': 'Rubinowy Leszczyna', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#10b981', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 352f2599-4ee9-4f18-9f3b-52bb7cf71834
INFO:dataset-notebook:Utworzono profil objawów dla test0038@zebra.pl

2026-03-14 20:48:44,825 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:44,826 INFO sqlalchemy.engine.Engine [cached since 14.08s ago] {'user_id_1': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'group_id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.08s ago] {'user_id_1': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'group_id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834'), 'param_1': 1}

2026-03-14 20:48:44,861 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:44,867 INFO sqlalchemy.engine.Engine [cached since 14.08s ago] {'member_count_1': 1, 'id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

INFO:sqlalchemy.engine.Engine:[cached since 14.08s ago] {'member_count_1': 1, 'id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}
INFO:app.services.matching_service:Dodano user 48c7beb8-52e5-4a28-a784-fbcf737ab655 do grupy 352f2599-4ee9-4f18-9f3b-52bb7cf71834

2026-03-14 20:48:44,928 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:44,933 INFO sqlalchemy.engine.Engine [cached since 13.72s ago] {'user_id': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'group_id': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

INFO:sqlalchemy.engine.Engine:[cached since 13.72s ago] {'user_id': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'group_id': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

2026-03-14 20:48:44,972 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:44,974 INFO sqlalchemy.engine.Engine [cached since 13.72s ago] {'id': UUID('5b6e6bb3-5147-4f06-9ac8-eb1cde316fbf'), 'user_id': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'description': 'Nasze dziecko od urodzenia ma problemy z wątrobą. Musi być na specjalnej diecie i przyjmować leki. Często jest zmęczone i ma gorsze dni. Kontrole i badania są regularne. Szukam wsparcia u innych opiekunów dzieci z chorobami wątroby.', 'embedding': '[-0.005407482851296663,0.002224164782091975,0.004915060941129923,0.06387139856815338,-0.011067238636314869,0.03297364339232445,-0.04895859211683273,0 ... (7728 characters truncated) ... 3,-0.08801209926605225,0.008429312147200108,-0.006746028549969196,0.12008682638406754,0.006864435970783234,0.10063448548316956,-0.026144828647375107]', 'group_id': '352f2599-4ee9-4f18-9f3b-52bb7cf71834', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 13.72s ago] {'id': UUID('5b6e6bb3-5147-4f06-9ac8-eb1cde316fbf'), 'user_id': UUID('48c7beb8-52e5-4a28-a784-fbcf737ab655'), 'description': 'Nasze dziecko od urodzenia ma problemy z wątrobą. Musi być na specjalnej diecie i przyjmować leki. Często jest zmęczone i ma gorsze dni. Kontrole i badania są regularne. Szukam wsparcia u innych opiekunów dzieci z chorobami wątroby.', 'embedding': '[-0.005407482851296663,0.002224164782091975,0.004915060941129923,0.06387139856815338,-0.011067238636314869,0.03297364339232445,-0.04895859211683273,0 ... (7728 characters truncated) ... 3,-0.08801209926605225,0.008429312147200108,-0.006746028549969196,0.12008682638406754,0.006864435970783234,0.10063448548316956,-0.026144828647375107]', 'group_id': '352f2599-4ee9-4f18-9f3b-52bb7cf71834', 'match_score': 0.0}

2026-03-14 20:48:45,428 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:45,429 INFO sqlalchemy.engine.Engine [cached since 78.24s ago] {'email_1': 'test0039@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 78.24s ago] {'email_1': 'test0039@zebra.pl', 'param_1': 1}

2026-03-14 20:48:45,461 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:45,467 INFO sqlalchemy.engine.Engine [cached since 19.75s ago] {'user_id_1': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 19.75s ago] {'user_id_1': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'param_1': 1}

2026-03-14 20:48:45,706 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:45,707 INFO sqlalchemy.engine.Engine [cached since 19.99s ago] {'user_id_1': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 19.99s ago] {'user_id_1': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'param_1': 1}

2026-03-14 20:48:46,386 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:46,387 INFO sqlalchemy.engine.Engine [cached since 15.73s ago] {'embedding': '[0.01121321,-0.02642005,0.07666986,-0.00780478,-0.03839779,0.03250229,-0.01939848,0.05636066,-0.01808712,-0.03177845,0.05907066,0.04992855,-0.0246421 ... (4117 characters truncated) ... ,-0.02268526,-0.09051596,-0.02882741,0.01965513,0.05179970,-0.00992501,0.03165512,-0.00850836,0.00812220,0.08115149,0.00125487,0.03817646,0.07394842]', 'user_id': '483d244f-12e5-48e4-9703-a7400f454f14', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 15.73s ago] {'embedding': '[0.01121321,-0.02642005,0.07666986,-0.00780478,-0.03839779,0.03250229,-0.01939848,0.05636066,-0.01808712,-0.03177845,0.05907066,0.04992855,-0.0246421 ... (4117 characters truncated) ... ,-0.02268526,-0.09051596,-0.02882741,0.01965513,0.05179970,-0.00992501,0.03165512,-0.00850836,0.00812220,0.08115149,0.00125487,0.03817646,0.07394842]', 'user_id': '483d244f-12e5-48e4-9703-a7400f454f14', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.6934, group_id=a2644a80-31b4-430d-9a1d-7d1cbc922e9b
INFO:app.services.matching_service:Score 0.6934 < threshold 0.72 — nowa grupa

2026-03-14 20:48:46,423 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:46,424 INFO sqlalchemy.engine.Engine [cached since 15.72s ago] {'id': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358'), 'name': 'Złoty Jarząb', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 15.72s ago] {'id': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358'), 'name': 'Złoty Jarząb', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: b12cb335-a91d-40d1-9522-6b0b58ca1358
INFO:dataset-notebook:Utworzono profil objawów dla test0039@zebra.pl

2026-03-14 20:48:46,457 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:46,458 INFO sqlalchemy.engine.Engine [cached since 15.71s ago] {'user_id_1': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'group_id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.71s ago] {'user_id_1': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'group_id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358'), 'param_1': 1}

2026-03-14 20:48:46,494 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:46,497 INFO sqlalchemy.engine.Engine [cached since 15.71s ago] {'member_count_1': 1, 'id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

INFO:sqlalchemy.engine.Engine:[cached since 15.71s ago] {'member_count_1': 1, 'id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}
INFO:app.services.matching_service:Dodano user 483d244f-12e5-48e4-9703-a7400f454f14 do grupy b12cb335-a91d-40d1-9522-6b0b58ca1358

2026-03-14 20:48:46,530 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:46,531 INFO sqlalchemy.engine.Engine [cached since 15.32s ago] {'user_id': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'group_id': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

INFO:sqlalchemy.engine.Engine:[cached since 15.32s ago] {'user_id': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'group_id': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

2026-03-14 20:48:46,564 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:46,566 INFO sqlalchemy.engine.Engine [cached since 15.32s ago] {'id': UUID('ca8d7cc7-2c1c-45b4-b796-4e008dd569a0'), 'user_id': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'description': 'Syn ma rzadkie zaburzenie dotyczące kości. Kości są kruche i łatwo dochodzi do złamań nawet przy niewielkich urazach. Unikamy zabaw ruchowych i sportu. Każde upadki są dla nas stresujące. Chciałabym wymienić się doświadczeniami z innymi rodzicami.', 'embedding': '[0.01121321227401495,-0.026420049369335175,0.07666986435651779,-0.007804784458130598,-0.03839779272675514,0.03250228986144066,-0.019398484379053116,0 ... (7740 characters truncated) ... 95,0.031655121594667435,-0.00850836094468832,0.008122201077640057,0.08115149289369583,0.0012548738159239292,0.038176462054252625,0.07394842058420181]', 'group_id': 'b12cb335-a91d-40d1-9522-6b0b58ca1358', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 15.32s ago] {'id': UUID('ca8d7cc7-2c1c-45b4-b796-4e008dd569a0'), 'user_id': UUID('483d244f-12e5-48e4-9703-a7400f454f14'), 'description': 'Syn ma rzadkie zaburzenie dotyczące kości. Kości są kruche i łatwo dochodzi do złamań nawet przy niewielkich urazach. Unikamy zabaw ruchowych i sportu. Każde upadki są dla nas stresujące. Chciałabym wymienić się doświadczeniami z innymi rodzicami.', 'embedding': '[0.01121321227401495,-0.026420049369335175,0.07666986435651779,-0.007804784458130598,-0.03839779272675514,0.03250228986144066,-0.019398484379053116,0 ... (7740 characters truncated) ... 95,0.031655121594667435,-0.00850836094468832,0.008122201077640057,0.08115149289369583,0.0012548738159239292,0.038176462054252625,0.07394842058420181]', 'group_id': 'b12cb335-a91d-40d1-9522-6b0b58ca1358', 'match_score': 0.0}

2026-03-14 20:48:46,601 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.email AS users_email, users.password_hash AS users_password_hash, users.display_name AS users_display_name, users.avatar_url AS users_avatar_url, users.role AS users_role, users.age_range AS users_age_range, users.is_active AS users_is_active, users.created_at AS users_created_at, users.updated_at AS users_updated_at
FROM users
WHERE users.email = %(email_1)s
 LIMIT %(param_1)s

2026-03-14 20:48:46,603 INFO sqlalchemy.engine.Engine [cached since 79.41s ago] {'email_1': 'test0040@zebra.pl', 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 79.41s ago] {'email_1': 'test0040@zebra.pl', 'param_1': 1}

2026-03-14 20:48:46,634 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:46,635 INFO sqlalchemy.engine.Engine [cached since 20.92s ago] {'user_id_1': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 20.92s ago] {'user_id_1': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'param_1': 1}

2026-03-14 20:48:46,666 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles
WHERE symptom_profiles.user_id = %(user_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:46,667 INFO sqlalchemy.engine.Engine [cached since 20.95s ago] {'user_id_1': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 20.95s ago] {'user_id_1': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'param_1': 1}

2026-03-14 20:48:46,753 INFO sqlalchemy.engine.Engine
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

INFO:sqlalchemy.engine.Engine:
        SELECT
            sp.id          AS profile_id,
            sp.group_id,
            sp.user_id,
            1 - (sp.embedding <=> CAST(%(embedding)s AS vector)) AS similarity
        FROM symptom_profiles sp
        WHERE sp.user_id   != %(user_id)s
          AND sp.group_id  IS NOT NULL
          AND sp.embedding IS NOT NULL
        ORDER BY sp.embedding <=> CAST(%(embedding)s AS vector)
        LIMIT %(top_k)s

2026-03-14 20:48:46,755 INFO sqlalchemy.engine.Engine [cached since 16.1s ago] {'embedding': '[-0.02489986,-0.03176655,0.03558000,0.06576180,-0.00917443,0.02557730,-0.03912626,0.01446302,0.00272050,-0.06377712,0.03209919,0.05064070,-0.05731698 ... (4115 characters truncated) ... 071,-0.00383277,0.00530092,0.05264902,0.03616565,0.05863358,0.01586241,0.02070871,-0.04402200,0.00354682,0.04389520,0.02114235,0.04379646,0.00026475]', 'user_id': 'fc285e54-cb25-423e-bce2-d2216733d294', 'top_k': 5}

INFO:sqlalchemy.engine.Engine:[cached since 16.1s ago] {'embedding': '[-0.02489986,-0.03176655,0.03558000,0.06576180,-0.00917443,0.02557730,-0.03912626,0.01446302,0.00272050,-0.06377712,0.03209919,0.05064070,-0.05731698 ... (4115 characters truncated) ... 071,-0.00383277,0.00530092,0.05264902,0.03616565,0.05863358,0.01586241,0.02070871,-0.04402200,0.00354682,0.04389520,0.02114235,0.04379646,0.00026475]', 'user_id': 'fc285e54-cb25-423e-bce2-d2216733d294', 'top_k': 5}
INFO:app.services.matching_service:Najlepsze dopasowanie: score=0.7028, group_id=352f2599-4ee9-4f18-9f3b-52bb7cf71834
INFO:app.services.matching_service:Score 0.7028 < threshold 0.72 — nowa grupa

2026-03-14 20:48:46,793 INFO sqlalchemy.engine.Engine INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO groups (id, name, description, cluster_id, is_active, member_count, accent_color, keywords, age_range, symptom_category, avg_match_score, centroid, admin_note, admin_note_by, admin_note_at) VALUES (%(id)s::UUID, %(name)s, %(description)s, %(cluster_id)s, %(is_active)s, %(member_count)s, %(accent_color)s, %(keywords)s::TEXT[], %(age_range)s, %(symptom_category)s, %(avg_match_score)s, %(centroid)s, %(admin_note)s, %(admin_note_by)s::UUID, %(admin_note_at)s) RETURNING groups.created_at, groups.updated_at

2026-03-14 20:48:46,794 INFO sqlalchemy.engine.Engine [cached since 16.09s ago] {'id': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0'), 'name': 'Miedziany Wzgórze', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}

INFO:sqlalchemy.engine.Engine:[cached since 16.09s ago] {'id': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0'), 'name': 'Miedziany Wzgórze', 'description': 'Grupa tymczasowa. Zostanie uzupełniona przy retrain.', 'cluster_id': None, 'is_active': True, 'member_count': 0, 'accent_color': '#f97316', 'keywords': None, 'age_range': None, 'symptom_category': None, 'avg_match_score': None, 'centroid': None, 'admin_note': None, 'admin_note_by': None, 'admin_note_at': None}
INFO:app.services.matching_service:Utworzono nową grupę: 764bce6a-f8e1-4319-8d54-50cbf3bde1e0
INFO:dataset-notebook:Utworzono profil objawów dla test0040@zebra.pl

2026-03-14 20:48:46,828 INFO sqlalchemy.engine.Engine SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT group_members.user_id AS group_members_user_id, group_members.group_id AS group_members_group_id, group_members.joined_at AS group_members_joined_at
FROM group_members
WHERE group_members.user_id = %(user_id_1)s::UUID AND group_members.group_id = %(group_id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:46,832 INFO sqlalchemy.engine.Engine [cached since 16.08s ago] {'user_id_1': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'group_id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.08s ago] {'user_id_1': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'group_id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0'), 'param_1': 1}

2026-03-14 20:48:46,865 INFO sqlalchemy.engine.Engine UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET member_count=(groups.member_count + %(member_count_1)s), updated_at=now() WHERE groups.id = %(id_1)s::UUID

2026-03-14 20:48:46,868 INFO sqlalchemy.engine.Engine [cached since 16.08s ago] {'member_count_1': 1, 'id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

INFO:sqlalchemy.engine.Engine:[cached since 16.08s ago] {'member_count_1': 1, 'id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}
INFO:app.services.matching_service:Dodano user fc285e54-cb25-423e-bce2-d2216733d294 do grupy 764bce6a-f8e1-4319-8d54-50cbf3bde1e0

2026-03-14 20:48:46,910 INFO sqlalchemy.engine.Engine INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

INFO:sqlalchemy.engine.Engine:INSERT INTO group_members (user_id, group_id) VALUES (%(user_id)s::UUID, %(group_id)s::UUID) RETURNING group_members.joined_at

2026-03-14 20:48:46,916 INFO sqlalchemy.engine.Engine [cached since 15.7s ago] {'user_id': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'group_id': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

INFO:sqlalchemy.engine.Engine:[cached since 15.7s ago] {'user_id': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'group_id': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

2026-03-14 20:48:46,954 INFO sqlalchemy.engine.Engine INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

INFO:sqlalchemy.engine.Engine:INSERT INTO symptom_profiles (id, user_id, description, embedding, group_id, match_score) VALUES (%(id)s::UUID, %(user_id)s::UUID, %(description)s, %(embedding)s, %(group_id)s::UUID, %(match_score)s) RETURNING symptom_profiles.created_at, symptom_profiles.updated_at

2026-03-14 20:48:46,959 INFO sqlalchemy.engine.Engine [cached since 15.71s ago] {'id': UUID('998ce5fc-00d2-421a-9626-82b8bd623ca6'), 'user_id': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'description': 'Córka od małego ma problemy z nerkami. Wymaga stałej diety, ograniczenia pewnych produktów i regularnych badań. Czasami musi być w szpitalu. Szukam grupy rodziców dzieci z chorobami nerek, żeby wspierać się nawzajem i dzielić praktycznymi radami.', 'embedding': '[-0.024899858981370926,-0.03176654502749443,0.03558000177145004,0.06576180458068848,-0.009174427017569542,0.025577303022146225,-0.039126258343458176, ... (7744 characters truncated) ... 27,0.020708713680505753,-0.04402200132608414,0.003546819556504488,0.04389519989490509,0.021142346784472466,0.04379645735025406,0.0002647535875439644]', 'group_id': '764bce6a-f8e1-4319-8d54-50cbf3bde1e0', 'match_score': 0.0}

INFO:sqlalchemy.engine.Engine:[cached since 15.71s ago] {'id': UUID('998ce5fc-00d2-421a-9626-82b8bd623ca6'), 'user_id': UUID('fc285e54-cb25-423e-bce2-d2216733d294'), 'description': 'Córka od małego ma problemy z nerkami. Wymaga stałej diety, ograniczenia pewnych produktów i regularnych badań. Czasami musi być w szpitalu. Szukam grupy rodziców dzieci z chorobami nerek, żeby wspierać się nawzajem i dzielić praktycznymi radami.', 'embedding': '[-0.024899858981370926,-0.03176654502749443,0.03558000177145004,0.06576180458068848,-0.009174427017569542,0.025577303022146225,-0.039126258343458176, ... (7744 characters truncated) ... 27,0.020708713680505753,-0.04402200132608414,0.003546819556504488,0.04389519989490509,0.021142346784472466,0.04379645735025406,0.0002647535875439644]', 'group_id': '764bce6a-f8e1-4319-8d54-50cbf3bde1e0', 'match_score': 0.0}

2026-03-14 20:48:46,995 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.group_id AS symptom_profiles_group_id
FROM symptom_profiles

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.group_id AS symptom_profiles_group_id
FROM symptom_profiles

2026-03-14 20:48:46,997 INFO sqlalchemy.engine.Engine [generated in 0.00135s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00135s] {}

2026-03-14 20:48:47,027 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:47,029 INFO sqlalchemy.engine.Engine [generated in 0.00170s] {'group_id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

INFO:sqlalchemy.engine.Engine:[generated in 0.00170s] {'group_id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

2026-03-14 20:48:47,063 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:47,064 INFO sqlalchemy.engine.Engine [cached since 12.78s ago] {'id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 12.78s ago] {'id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09'), 'param_1': 1}

2026-03-14 20:48:47,096 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:47,098 INFO sqlalchemy.engine.Engine [generated in 0.00205s] {'group_id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

INFO:sqlalchemy.engine.Engine:[generated in 0.00205s] {'group_id_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

2026-03-14 20:48:47,130 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:47,132 INFO sqlalchemy.engine.Engine [generated in 0.00152s] {'keywords': ['zdiagnozowaną', 'rzadką', 'chorobę', 'metaboliczną', 'nawet'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

INFO:sqlalchemy.engine.Engine:[generated in 0.00152s] {'keywords': ['zdiagnozowaną', 'rzadką', 'chorobę', 'metaboliczną', 'nawet'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

2026-03-14 20:48:47,161 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:47,224 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:47,227 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:47,228 INFO sqlalchemy.engine.Engine [generated in 0.00113s] {'pk_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}

INFO:sqlalchemy.engine.Engine:[generated in 0.00113s] {'pk_1': UUID('ee9f537e-dc5a-4927-ac9c-7fb86211aa09')}
INFO:app.services.group_characteristics:Charakterystyki grupy ee9f537e-dc5a-4927-ac9c-7fb86211aa09 zaktualizowane: keywords=['zdiagnozowaną', 'rzadką', 'chorobę', 'metaboliczną', 'nawet'], category=Neurologiczne, age_range=None, avg_score=0.0

2026-03-14 20:48:47,290 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:47,291 INFO sqlalchemy.engine.Engine [cached since 0.264s ago] {'group_id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

INFO:sqlalchemy.engine.Engine:[cached since 0.264s ago] {'group_id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

2026-03-14 20:48:47,321 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:47,322 INFO sqlalchemy.engine.Engine [cached since 13.04s ago] {'id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.04s ago] {'id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834'), 'param_1': 1}

2026-03-14 20:48:47,354 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:47,355 INFO sqlalchemy.engine.Engine [cached since 0.2593s ago] {'group_id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

INFO:sqlalchemy.engine.Engine:[cached since 0.2593s ago] {'group_id_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

2026-03-14 20:48:47,386 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:47,388 INFO sqlalchemy.engine.Engine [cached since 0.2577s ago] {'keywords': ['nasze', 'urodzenia', 'problemy', 'wątrobą', 'musi'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

INFO:sqlalchemy.engine.Engine:[cached since 0.2577s ago] {'keywords': ['nasze', 'urodzenia', 'problemy', 'wątrobą', 'musi'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

2026-03-14 20:48:47,422 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:47,485 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:47,486 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:47,487 INFO sqlalchemy.engine.Engine [cached since 0.2605s ago] {'pk_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}

INFO:sqlalchemy.engine.Engine:[cached since 0.2605s ago] {'pk_1': UUID('352f2599-4ee9-4f18-9f3b-52bb7cf71834')}
INFO:app.services.group_characteristics:Charakterystyki grupy 352f2599-4ee9-4f18-9f3b-52bb7cf71834 zaktualizowane: keywords=['nasze', 'urodzenia', 'problemy', 'wątrobą', 'musi'], category=Neurologiczne, age_range=None, avg_score=0.0

2026-03-14 20:48:47,548 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:47,550 INFO sqlalchemy.engine.Engine [cached since 0.5227s ago] {'group_id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

INFO:sqlalchemy.engine.Engine:[cached since 0.5227s ago] {'group_id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

2026-03-14 20:48:47,582 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:47,585 INFO sqlalchemy.engine.Engine [cached since 13.3s ago] {'id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.3s ago] {'id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361'), 'param_1': 1}

2026-03-14 20:48:47,619 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:47,626 INFO sqlalchemy.engine.Engine [cached since 0.5302s ago] {'group_id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

INFO:sqlalchemy.engine.Engine:[cached since 0.5302s ago] {'group_id_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

2026-03-14 20:48:47,662 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:47,663 INFO sqlalchemy.engine.Engine [cached since 0.5328s ago] {'keywords': ['nasze', 'rzadką', 'chorobę', 'skóry', 'nawet'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

INFO:sqlalchemy.engine.Engine:[cached since 0.5328s ago] {'keywords': ['nasze', 'rzadką', 'chorobę', 'skóry', 'nawet'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

2026-03-14 20:48:47,692 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:47,753 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:47,754 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:47,755 INFO sqlalchemy.engine.Engine [cached since 0.5287s ago] {'pk_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}

INFO:sqlalchemy.engine.Engine:[cached since 0.5287s ago] {'pk_1': UUID('6e09cb1a-0a9b-4321-8192-c71fbb654361')}
INFO:app.services.group_characteristics:Charakterystyki grupy 6e09cb1a-0a9b-4321-8192-c71fbb654361 zaktualizowane: keywords=['nasze', 'rzadką', 'chorobę', 'skóry', 'nawet'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:47,814 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:47,816 INFO sqlalchemy.engine.Engine [cached since 0.7886s ago] {'group_id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

INFO:sqlalchemy.engine.Engine:[cached since 0.7886s ago] {'group_id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

2026-03-14 20:48:47,848 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:47,849 INFO sqlalchemy.engine.Engine [cached since 13.56s ago] {'id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.56s ago] {'id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e'), 'param_1': 1}

2026-03-14 20:48:47,882 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:47,883 INFO sqlalchemy.engine.Engine [cached since 0.7868s ago] {'group_id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

INFO:sqlalchemy.engine.Engine:[cached since 0.7868s ago] {'group_id_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

2026-03-14 20:48:47,913 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:47,978 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:47,979 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:47,981 INFO sqlalchemy.engine.Engine [cached since 0.7541s ago] {'pk_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}

INFO:sqlalchemy.engine.Engine:[cached since 0.7541s ago] {'pk_1': UUID('e4af521a-c6e9-4a68-ae6f-01d847476a0e')}
INFO:app.services.group_characteristics:Charakterystyki grupy e4af521a-c6e9-4a68-ae6f-01d847476a0e zaktualizowane: keywords=['rzadki', 'zespół', 'genetyczny', 'lekarze', 'zwrócili'], category=Genetyczne, age_range=None, avg_score=0.0

2026-03-14 20:48:48,042 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:48,043 INFO sqlalchemy.engine.Engine [cached since 1.016s ago] {'group_id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

INFO:sqlalchemy.engine.Engine:[cached since 1.016s ago] {'group_id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

2026-03-14 20:48:48,078 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:48,080 INFO sqlalchemy.engine.Engine [cached since 13.79s ago] {'id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 13.79s ago] {'id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358'), 'param_1': 1}

2026-03-14 20:48:48,114 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:48,116 INFO sqlalchemy.engine.Engine [cached since 1.02s ago] {'group_id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

INFO:sqlalchemy.engine.Engine:[cached since 1.02s ago] {'group_id_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

2026-03-14 20:48:48,150 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:48,155 INFO sqlalchemy.engine.Engine [cached since 1.025s ago] {'keywords': ['kości', 'rzadkie', 'zaburzenie', 'dotyczące', 'kruche'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

INFO:sqlalchemy.engine.Engine:[cached since 1.025s ago] {'keywords': ['kości', 'rzadkie', 'zaburzenie', 'dotyczące', 'kruche'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

2026-03-14 20:48:48,189 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:48,252 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:48,254 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:48,256 INFO sqlalchemy.engine.Engine [cached since 1.029s ago] {'pk_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}

INFO:sqlalchemy.engine.Engine:[cached since 1.029s ago] {'pk_1': UUID('b12cb335-a91d-40d1-9522-6b0b58ca1358')}
INFO:app.services.group_characteristics:Charakterystyki grupy b12cb335-a91d-40d1-9522-6b0b58ca1358 zaktualizowane: keywords=['kości', 'rzadkie', 'zaburzenie', 'dotyczące', 'kruche'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:48,314 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:48,315 INFO sqlalchemy.engine.Engine [cached since 1.288s ago] {'group_id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

INFO:sqlalchemy.engine.Engine:[cached since 1.288s ago] {'group_id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

2026-03-14 20:48:48,346 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:48,348 INFO sqlalchemy.engine.Engine [cached since 14.06s ago] {'id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.06s ago] {'id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff'), 'param_1': 1}

2026-03-14 20:48:48,379 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:48,380 INFO sqlalchemy.engine.Engine [cached since 1.284s ago] {'group_id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

INFO:sqlalchemy.engine.Engine:[cached since 1.284s ago] {'group_id_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

2026-03-14 20:48:48,414 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:48,415 INFO sqlalchemy.engine.Engine [cached since 1.285s ago] {'keywords': ['nasza', 'elastyczne', 'stawy', 'może', 'wyginać'], 'symptom_category': 'Mięśniowo-szkieletowe', 'avg_match_score': 0.0, 'groups_id': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

INFO:sqlalchemy.engine.Engine:[cached since 1.285s ago] {'keywords': ['nasza', 'elastyczne', 'stawy', 'może', 'wyginać'], 'symptom_category': 'Mięśniowo-szkieletowe', 'avg_match_score': 0.0, 'groups_id': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

2026-03-14 20:48:48,446 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:48,510 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:48,511 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:48,512 INFO sqlalchemy.engine.Engine [cached since 1.286s ago] {'pk_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}

INFO:sqlalchemy.engine.Engine:[cached since 1.286s ago] {'pk_1': UUID('381f180d-adc3-4a20-a80a-76d8ef0793ff')}
INFO:app.services.group_characteristics:Charakterystyki grupy 381f180d-adc3-4a20-a80a-76d8ef0793ff zaktualizowane: keywords=['nasza', 'elastyczne', 'stawy', 'może', 'wyginać'], category=Mięśniowo-szkieletowe, age_range=None, avg_score=0.0

2026-03-14 20:48:48,570 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:48,571 INFO sqlalchemy.engine.Engine [cached since 1.544s ago] {'group_id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

INFO:sqlalchemy.engine.Engine:[cached since 1.544s ago] {'group_id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

2026-03-14 20:48:48,603 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:48,605 INFO sqlalchemy.engine.Engine [cached since 14.32s ago] {'id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.32s ago] {'id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954'), 'param_1': 1}

2026-03-14 20:48:48,636 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:48,638 INFO sqlalchemy.engine.Engine [cached since 1.542s ago] {'group_id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

INFO:sqlalchemy.engine.Engine:[cached since 1.542s ago] {'group_id_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

2026-03-14 20:48:48,670 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:48,671 INFO sqlalchemy.engine.Engine [cached since 1.541s ago] {'keywords': ['małe', 'dłonie', 'stopy', 'porównaniu', 'reszty'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

INFO:sqlalchemy.engine.Engine:[cached since 1.541s ago] {'keywords': ['małe', 'dłonie', 'stopy', 'porównaniu', 'reszty'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

2026-03-14 20:48:48,702 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:48,766 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:48,767 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:48,768 INFO sqlalchemy.engine.Engine [cached since 1.541s ago] {'pk_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}

INFO:sqlalchemy.engine.Engine:[cached since 1.541s ago] {'pk_1': UUID('b239d74f-86fd-4a12-b3d4-ade068475954')}
INFO:app.services.group_characteristics:Charakterystyki grupy b239d74f-86fd-4a12-b3d4-ade068475954 zaktualizowane: keywords=['małe', 'dłonie', 'stopy', 'porównaniu', 'reszty'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:48,826 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:48,826 INFO sqlalchemy.engine.Engine [cached since 1.799s ago] {'group_id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

INFO:sqlalchemy.engine.Engine:[cached since 1.799s ago] {'group_id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

2026-03-14 20:48:48,857 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:48,869 INFO sqlalchemy.engine.Engine [cached since 14.58s ago] {'id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.58s ago] {'id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb'), 'param_1': 1}

2026-03-14 20:48:48,904 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:48,906 INFO sqlalchemy.engine.Engine [cached since 1.81s ago] {'group_id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

INFO:sqlalchemy.engine.Engine:[cached since 1.81s ago] {'group_id_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

2026-03-14 20:48:48,939 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:48,941 INFO sqlalchemy.engine.Engine [cached since 1.811s ago] {'keywords': ['urodzenia', 'problemy', 'słuchem', 'musimy', 'mówić'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

INFO:sqlalchemy.engine.Engine:[cached since 1.811s ago] {'keywords': ['urodzenia', 'problemy', 'słuchem', 'musimy', 'mówić'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

2026-03-14 20:48:48,973 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:49,035 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:49,036 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:49,038 INFO sqlalchemy.engine.Engine [cached since 1.811s ago] {'pk_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}

INFO:sqlalchemy.engine.Engine:[cached since 1.811s ago] {'pk_1': UUID('3c8705ba-ea53-4263-b938-42b64aee1feb')}
INFO:app.services.group_characteristics:Charakterystyki grupy 3c8705ba-ea53-4263-b938-42b64aee1feb zaktualizowane: keywords=['urodzenia', 'problemy', 'słuchem', 'musimy', 'mówić'], category=Neurologiczne, age_range=None, avg_score=0.0

2026-03-14 20:48:49,097 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:49,099 INFO sqlalchemy.engine.Engine [cached since 2.071s ago] {'group_id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.071s ago] {'group_id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

2026-03-14 20:48:49,133 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:49,134 INFO sqlalchemy.engine.Engine [cached since 14.85s ago] {'id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 14.85s ago] {'id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9'), 'param_1': 1}

2026-03-14 20:48:49,168 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:49,170 INFO sqlalchemy.engine.Engine [cached since 2.074s ago] {'group_id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.074s ago] {'group_id_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

2026-03-14 20:48:49,200 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:49,201 INFO sqlalchemy.engine.Engine [cached since 2.071s ago] {'keywords': ['znosi', 'zimno', 'lekkim', 'chłodzie', 'skarży'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.071s ago] {'keywords': ['znosi', 'zimno', 'lekkim', 'chłodzie', 'skarży'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

2026-03-14 20:48:49,231 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:49,299 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:49,300 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:49,302 INFO sqlalchemy.engine.Engine [cached since 2.075s ago] {'pk_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.075s ago] {'pk_1': UUID('816e4d87-bfa7-4db8-ae3a-c5a62b9452b9')}
INFO:app.services.group_characteristics:Charakterystyki grupy 816e4d87-bfa7-4db8-ae3a-c5a62b9452b9 zaktualizowane: keywords=['znosi', 'zimno', 'lekkim', 'chłodzie', 'skarży'], category=Neurologiczne, age_range=None, avg_score=0.0

2026-03-14 20:48:49,361 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:49,362 INFO sqlalchemy.engine.Engine [cached since 2.335s ago] {'group_id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.335s ago] {'group_id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

2026-03-14 20:48:49,396 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:49,397 INFO sqlalchemy.engine.Engine [cached since 15.11s ago] {'id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.11s ago] {'id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9'), 'param_1': 1}

2026-03-14 20:48:49,430 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:49,431 INFO sqlalchemy.engine.Engine [cached since 2.335s ago] {'group_id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.335s ago] {'group_id_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

2026-03-14 20:48:49,464 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:49,465 INFO sqlalchemy.engine.Engine [cached since 2.335s ago] {'keywords': ['nasze', 'rozwijało', 'prawidłowo', 'około', 'drugiego'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.335s ago] {'keywords': ['nasze', 'rozwijało', 'prawidłowo', 'około', 'drugiego'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

2026-03-14 20:48:49,495 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:49,561 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:49,566 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:49,571 INFO sqlalchemy.engine.Engine [cached since 2.345s ago] {'pk_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.345s ago] {'pk_1': UUID('e1fc2c14-04c6-4cd7-b932-7805776a8ba9')}
INFO:app.services.group_characteristics:Charakterystyki grupy e1fc2c14-04c6-4cd7-b932-7805776a8ba9 zaktualizowane: keywords=['nasze', 'rozwijało', 'prawidłowo', 'około', 'drugiego'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:49,636 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:49,640 INFO sqlalchemy.engine.Engine [cached since 2.613s ago] {'group_id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.613s ago] {'group_id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

2026-03-14 20:48:49,672 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:49,683 INFO sqlalchemy.engine.Engine [cached since 15.4s ago] {'id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.4s ago] {'id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9'), 'param_1': 1}

2026-03-14 20:48:49,716 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:49,717 INFO sqlalchemy.engine.Engine [cached since 2.621s ago] {'group_id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.621s ago] {'group_id_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

2026-03-14 20:48:49,748 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:49,749 INFO sqlalchemy.engine.Engine [cached since 2.619s ago] {'keywords': ['serca', 'wymaga', 'nasze', 'urodziło', 'wadą'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.619s ago] {'keywords': ['serca', 'wymaga', 'nasze', 'urodziło', 'wadą'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

2026-03-14 20:48:49,779 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:49,843 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:49,844 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:49,845 INFO sqlalchemy.engine.Engine [cached since 2.619s ago] {'pk_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}

INFO:sqlalchemy.engine.Engine:[cached since 2.619s ago] {'pk_1': UUID('e816d3a6-a075-45f7-92c4-3d1f38818ea9')}
INFO:app.services.group_characteristics:Charakterystyki grupy e816d3a6-a075-45f7-92c4-3d1f38818ea9 zaktualizowane: keywords=['serca', 'wymaga', 'nasze', 'urodziło', 'wadą'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:49,904 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:49,905 INFO sqlalchemy.engine.Engine [cached since 2.878s ago] {'group_id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

INFO:sqlalchemy.engine.Engine:[cached since 2.878s ago] {'group_id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

2026-03-14 20:48:49,936 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:49,937 INFO sqlalchemy.engine.Engine [cached since 15.65s ago] {'id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.65s ago] {'id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab'), 'param_1': 1}

2026-03-14 20:48:49,968 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:49,969 INFO sqlalchemy.engine.Engine [cached since 2.873s ago] {'group_id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

INFO:sqlalchemy.engine.Engine:[cached since 2.873s ago] {'group_id_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

2026-03-14 20:48:49,999 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:50,000 INFO sqlalchemy.engine.Engine [cached since 2.87s ago] {'keywords': ['nasze', 'małego', 'mało', 'mówiło', 'kilka'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

INFO:sqlalchemy.engine.Engine:[cached since 2.87s ago] {'keywords': ['nasze', 'małego', 'mało', 'mówiło', 'kilka'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

2026-03-14 20:48:50,031 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:50,092 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:50,093 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:50,095 INFO sqlalchemy.engine.Engine [cached since 2.868s ago] {'pk_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}

INFO:sqlalchemy.engine.Engine:[cached since 2.868s ago] {'pk_1': UUID('e9a71a4c-b2de-4a87-ac05-4d527d6745ab')}
INFO:app.services.group_characteristics:Charakterystyki grupy e9a71a4c-b2de-4a87-ac05-4d527d6745ab zaktualizowane: keywords=['nasze', 'małego', 'mało', 'mówiło', 'kilka'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:50,157 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:50,158 INFO sqlalchemy.engine.Engine [cached since 3.131s ago] {'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 3.131s ago] {'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

2026-03-14 20:48:50,217 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:50,218 INFO sqlalchemy.engine.Engine [cached since 15.93s ago] {'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 15.93s ago] {'id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2'), 'param_1': 1}

2026-03-14 20:48:50,257 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:50,260 INFO sqlalchemy.engine.Engine [cached since 3.164s ago] {'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 3.164s ago] {'group_id_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

2026-03-14 20:48:50,300 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:50,363 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:50,365 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:50,366 INFO sqlalchemy.engine.Engine [cached since 3.14s ago] {'pk_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}

INFO:sqlalchemy.engine.Engine:[cached since 3.14s ago] {'pk_1': UUID('49357027-f555-473a-8c72-cafd78dc5fc2')}
INFO:app.services.group_characteristics:Charakterystyki grupy 49357027-f555-473a-8c72-cafd78dc5fc2 zaktualizowane: keywords=['dzieci', 'ciała', 'rówieśników', 'trudności', 'nasze'], category=Neurologiczne, age_range=None, avg_score=0.487

2026-03-14 20:48:50,434 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:50,435 INFO sqlalchemy.engine.Engine [cached since 3.407s ago] {'group_id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

INFO:sqlalchemy.engine.Engine:[cached since 3.407s ago] {'group_id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

2026-03-14 20:48:50,468 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:50,470 INFO sqlalchemy.engine.Engine [cached since 16.18s ago] {'id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.18s ago] {'id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3'), 'param_1': 1}

2026-03-14 20:48:50,506 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:50,511 INFO sqlalchemy.engine.Engine [cached since 3.415s ago] {'group_id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

INFO:sqlalchemy.engine.Engine:[cached since 3.415s ago] {'group_id_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

2026-03-14 20:48:50,548 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:50,552 INFO sqlalchemy.engine.Engine [cached since 3.422s ago] {'keywords': ['urodzenia', 'problemy', 'oddychaniem', 'podczas', 'budzi'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

INFO:sqlalchemy.engine.Engine:[cached since 3.422s ago] {'keywords': ['urodzenia', 'problemy', 'oddychaniem', 'podczas', 'budzi'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

2026-03-14 20:48:50,582 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:50,639 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:50,641 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:50,642 INFO sqlalchemy.engine.Engine [cached since 3.415s ago] {'pk_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}

INFO:sqlalchemy.engine.Engine:[cached since 3.415s ago] {'pk_1': UUID('a14e380d-ea0e-4155-ad55-129c3838c2d3')}
INFO:app.services.group_characteristics:Charakterystyki grupy a14e380d-ea0e-4155-ad55-129c3838c2d3 zaktualizowane: keywords=['urodzenia', 'problemy', 'oddychaniem', 'podczas', 'budzi'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:50,701 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:50,702 INFO sqlalchemy.engine.Engine [cached since 3.675s ago] {'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 3.675s ago] {'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:50,763 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:50,764 INFO sqlalchemy.engine.Engine [cached since 16.48s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.48s ago] {'id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b'), 'param_1': 1}

2026-03-14 20:48:50,796 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:50,797 INFO sqlalchemy.engine.Engine [cached since 3.701s ago] {'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 3.701s ago] {'group_id_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

2026-03-14 20:48:50,828 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:50,888 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:50,889 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:50,890 INFO sqlalchemy.engine.Engine [cached since 3.664s ago] {'pk_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}

INFO:sqlalchemy.engine.Engine:[cached since 3.664s ago] {'pk_1': UUID('a2644a80-31b4-430d-9a1d-7d1cbc922e9b')}
INFO:app.services.group_characteristics:Charakterystyki grupy a2644a80-31b4-430d-9a1d-7d1cbc922e9b zaktualizowane: keywords=['trudności', 'chodzi', 'utrzymaniem', 'równowagi', 'dzieci'], category=Neurologiczne, age_range=None, avg_score=0.699

2026-03-14 20:48:50,965 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:50,971 INFO sqlalchemy.engine.Engine [cached since 3.943s ago] {'group_id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

INFO:sqlalchemy.engine.Engine:[cached since 3.943s ago] {'group_id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

2026-03-14 20:48:51,005 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:51,009 INFO sqlalchemy.engine.Engine [cached since 16.72s ago] {'id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.72s ago] {'id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6'), 'param_1': 1}

2026-03-14 20:48:51,049 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:51,052 INFO sqlalchemy.engine.Engine [cached since 3.956s ago] {'group_id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

INFO:sqlalchemy.engine.Engine:[cached since 3.956s ago] {'group_id_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

2026-03-14 20:48:51,083 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:51,085 INFO sqlalchemy.engine.Engine [cached since 3.955s ago] {'keywords': ['urodzenia', 'słabe', 'mięśnie', 'twarzy', 'otwarte'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

INFO:sqlalchemy.engine.Engine:[cached since 3.955s ago] {'keywords': ['urodzenia', 'słabe', 'mięśnie', 'twarzy', 'otwarte'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.0, 'groups_id': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

2026-03-14 20:48:51,116 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:51,179 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:51,180 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:51,181 INFO sqlalchemy.engine.Engine [cached since 3.954s ago] {'pk_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}

INFO:sqlalchemy.engine.Engine:[cached since 3.954s ago] {'pk_1': UUID('965b3861-f29a-43cd-8e70-6474097fafa6')}
INFO:app.services.group_characteristics:Charakterystyki grupy 965b3861-f29a-43cd-8e70-6474097fafa6 zaktualizowane: keywords=['urodzenia', 'słabe', 'mięśnie', 'twarzy', 'otwarte'], category=Neurologiczne, age_range=None, avg_score=0.0

2026-03-14 20:48:51,241 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:51,242 INFO sqlalchemy.engine.Engine [cached since 4.215s ago] {'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 4.215s ago] {'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

2026-03-14 20:48:51,277 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:51,278 INFO sqlalchemy.engine.Engine [cached since 16.99s ago] {'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 16.99s ago] {'id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b'), 'param_1': 1}

2026-03-14 20:48:51,312 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:51,314 INFO sqlalchemy.engine.Engine [cached since 4.218s ago] {'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 4.218s ago] {'group_id_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

2026-03-14 20:48:51,347 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:51,408 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:51,409 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:51,411 INFO sqlalchemy.engine.Engine [cached since 4.184s ago] {'pk_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}

INFO:sqlalchemy.engine.Engine:[cached since 4.184s ago] {'pk_1': UUID('0946e26a-2416-427b-80d3-cb4e30902b5b')}
INFO:app.services.group_characteristics:Charakterystyki grupy 0946e26a-2416-427b-80d3-cb4e30902b5b zaktualizowane: keywords=['oczy', 'urodzenia', 'problemy', 'jasną', 'skórę'], category=Inne, age_range=None, avg_score=0.546

2026-03-14 20:48:51,473 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:51,475 INFO sqlalchemy.engine.Engine [cached since 4.448s ago] {'group_id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

INFO:sqlalchemy.engine.Engine:[cached since 4.448s ago] {'group_id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

2026-03-14 20:48:51,508 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:51,509 INFO sqlalchemy.engine.Engine [cached since 17.22s ago] {'id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.22s ago] {'id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c'), 'param_1': 1}

2026-03-14 20:48:51,539 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:51,541 INFO sqlalchemy.engine.Engine [cached since 4.445s ago] {'group_id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

INFO:sqlalchemy.engine.Engine:[cached since 4.445s ago] {'group_id_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

2026-03-14 20:48:51,572 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:51,573 INFO sqlalchemy.engine.Engine [cached since 4.443s ago] {'keywords': ['nasze', 'wolno', 'uczy', 'nowych', 'rzeczy'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

INFO:sqlalchemy.engine.Engine:[cached since 4.443s ago] {'keywords': ['nasze', 'wolno', 'uczy', 'nowych', 'rzeczy'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

2026-03-14 20:48:51,603 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:51,667 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:51,669 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:51,670 INFO sqlalchemy.engine.Engine [cached since 4.443s ago] {'pk_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}

INFO:sqlalchemy.engine.Engine:[cached since 4.443s ago] {'pk_1': UUID('ce577c16-4dd0-445e-8e55-96b461abf41c')}
INFO:app.services.group_characteristics:Charakterystyki grupy ce577c16-4dd0-445e-8e55-96b461abf41c zaktualizowane: keywords=['nasze', 'wolno', 'uczy', 'nowych', 'rzeczy'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:51,732 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:51,733 INFO sqlalchemy.engine.Engine [cached since 4.706s ago] {'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 4.706s ago] {'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

2026-03-14 20:48:51,765 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:51,769 INFO sqlalchemy.engine.Engine [cached since 17.48s ago] {'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.48s ago] {'id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef'), 'param_1': 1}

2026-03-14 20:48:51,804 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:51,806 INFO sqlalchemy.engine.Engine [cached since 4.71s ago] {'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 4.71s ago] {'group_id_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

2026-03-14 20:48:51,835 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:51,836 INFO sqlalchemy.engine.Engine [cached since 4.706s ago] {'keywords': ['zauważyliśmy', 'trudności', 'nasza', 'małego', 'spokojna'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.374, 'groups_id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 4.706s ago] {'keywords': ['zauważyliśmy', 'trudności', 'nasza', 'małego', 'spokojna'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.374, 'groups_id': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

2026-03-14 20:48:51,867 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:51,931 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:51,933 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:51,934 INFO sqlalchemy.engine.Engine [cached since 4.708s ago] {'pk_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}

INFO:sqlalchemy.engine.Engine:[cached since 4.708s ago] {'pk_1': UUID('ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef')}
INFO:app.services.group_characteristics:Charakterystyki grupy ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef zaktualizowane: keywords=['zauważyliśmy', 'trudności', 'nasza', 'małego', 'spokojna'], category=Neurologiczne, age_range=None, avg_score=0.374

2026-03-14 20:48:51,999 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:52,005 INFO sqlalchemy.engine.Engine [cached since 4.978s ago] {'group_id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

INFO:sqlalchemy.engine.Engine:[cached since 4.978s ago] {'group_id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

2026-03-14 20:48:52,041 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:52,048 INFO sqlalchemy.engine.Engine [cached since 17.76s ago] {'id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 17.76s ago] {'id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0'), 'param_1': 1}

2026-03-14 20:48:52,085 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:52,089 INFO sqlalchemy.engine.Engine [cached since 4.993s ago] {'group_id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

INFO:sqlalchemy.engine.Engine:[cached since 4.993s ago] {'group_id_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

2026-03-14 20:48:52,124 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:52,129 INFO sqlalchemy.engine.Engine [cached since 4.999s ago] {'keywords': ['małego', 'problemy', 'nerkami', 'wymaga', 'stałej'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

INFO:sqlalchemy.engine.Engine:[cached since 4.999s ago] {'keywords': ['małego', 'problemy', 'nerkami', 'wymaga', 'stałej'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

2026-03-14 20:48:52,172 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:52,235 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:52,237 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:52,239 INFO sqlalchemy.engine.Engine [cached since 5.012s ago] {'pk_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}

INFO:sqlalchemy.engine.Engine:[cached since 5.012s ago] {'pk_1': UUID('764bce6a-f8e1-4319-8d54-50cbf3bde1e0')}
INFO:app.services.group_characteristics:Charakterystyki grupy 764bce6a-f8e1-4319-8d54-50cbf3bde1e0 zaktualizowane: keywords=['małego', 'problemy', 'nerkami', 'wymaga', 'stałej'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:52,301 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:52,302 INFO sqlalchemy.engine.Engine [cached since 5.275s ago] {'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 5.275s ago] {'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

2026-03-14 20:48:52,337 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:52,338 INFO sqlalchemy.engine.Engine [cached since 18.05s ago] {'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.05s ago] {'id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd'), 'param_1': 1}

2026-03-14 20:48:52,375 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:52,377 INFO sqlalchemy.engine.Engine [cached since 5.281s ago] {'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 5.281s ago] {'group_id_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

2026-03-14 20:48:52,409 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:52,472 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:52,474 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:52,475 INFO sqlalchemy.engine.Engine [cached since 5.249s ago] {'pk_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}

INFO:sqlalchemy.engine.Engine:[cached since 5.249s ago] {'pk_1': UUID('70b3efbb-3c9b-44db-bf24-f453515ab3dd')}
INFO:app.services.group_characteristics:Charakterystyki grupy 70b3efbb-3c9b-44db-bf24-f453515ab3dd zaktualizowane: keywords=['nasze', 'problemy', 'koordynacją', 'ruchową', 'trudno'], category=Inne, age_range=None, avg_score=0.381

2026-03-14 20:48:52,537 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:52,538 INFO sqlalchemy.engine.Engine [cached since 5.511s ago] {'group_id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

INFO:sqlalchemy.engine.Engine:[cached since 5.511s ago] {'group_id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

2026-03-14 20:48:52,569 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:52,569 INFO sqlalchemy.engine.Engine [cached since 18.28s ago] {'id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.28s ago] {'id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee'), 'param_1': 1}

2026-03-14 20:48:52,602 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:52,604 INFO sqlalchemy.engine.Engine [cached since 5.508s ago] {'group_id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

INFO:sqlalchemy.engine.Engine:[cached since 5.508s ago] {'group_id_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

2026-03-14 20:48:52,636 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:52,638 INFO sqlalchemy.engine.Engine [cached since 5.508s ago] {'keywords': ['pierwszych', 'życia', 'trudności', 'jedzeniem', 'krztusił'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

INFO:sqlalchemy.engine.Engine:[cached since 5.508s ago] {'keywords': ['pierwszych', 'życia', 'trudności', 'jedzeniem', 'krztusił'], 'symptom_category': 'Inne', 'avg_match_score': 0.0, 'groups_id': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

2026-03-14 20:48:52,667 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:52,731 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:52,732 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:52,734 INFO sqlalchemy.engine.Engine [cached since 5.508s ago] {'pk_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}

INFO:sqlalchemy.engine.Engine:[cached since 5.508s ago] {'pk_1': UUID('bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee')}
INFO:app.services.group_characteristics:Charakterystyki grupy bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee zaktualizowane: keywords=['pierwszych', 'życia', 'trudności', 'jedzeniem', 'krztusił'], category=Inne, age_range=None, avg_score=0.0

2026-03-14 20:48:52,796 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:52,798 INFO sqlalchemy.engine.Engine [cached since 5.771s ago] {'group_id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

INFO:sqlalchemy.engine.Engine:[cached since 5.771s ago] {'group_id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

2026-03-14 20:48:52,832 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:52,834 INFO sqlalchemy.engine.Engine [cached since 18.55s ago] {'id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.55s ago] {'id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236'), 'param_1': 1}

2026-03-14 20:48:52,870 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:52,877 INFO sqlalchemy.engine.Engine [cached since 5.781s ago] {'group_id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

INFO:sqlalchemy.engine.Engine:[cached since 5.781s ago] {'group_id_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

2026-03-14 20:48:52,909 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:52,910 INFO sqlalchemy.engine.Engine [cached since 5.78s ago] {'keywords': ['cienką', 'delikatną', 'skórę', 'nawet', 'małe'], 'symptom_category': 'Mięśniowo-szkieletowe', 'avg_match_score': 0.0, 'groups_id': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

INFO:sqlalchemy.engine.Engine:[cached since 5.78s ago] {'keywords': ['cienką', 'delikatną', 'skórę', 'nawet', 'małe'], 'symptom_category': 'Mięśniowo-szkieletowe', 'avg_match_score': 0.0, 'groups_id': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

2026-03-14 20:48:52,943 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:53,007 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:53,009 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:53,010 INFO sqlalchemy.engine.Engine [cached since 5.784s ago] {'pk_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}

INFO:sqlalchemy.engine.Engine:[cached since 5.784s ago] {'pk_1': UUID('ad488d0b-6569-40df-ae7a-3ee3758b2236')}
INFO:app.services.group_characteristics:Charakterystyki grupy ad488d0b-6569-40df-ae7a-3ee3758b2236 zaktualizowane: keywords=['cienką', 'delikatną', 'skórę', 'nawet', 'małe'], category=Mięśniowo-szkieletowe, age_range=None, avg_score=0.0

2026-03-14 20:48:53,073 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:53,075 INFO sqlalchemy.engine.Engine [cached since 6.047s ago] {'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 6.047s ago] {'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

2026-03-14 20:48:53,109 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:53,111 INFO sqlalchemy.engine.Engine [cached since 18.83s ago] {'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 18.83s ago] {'id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c'), 'param_1': 1}

2026-03-14 20:48:53,145 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:53,146 INFO sqlalchemy.engine.Engine [cached since 6.05s ago] {'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 6.05s ago] {'group_id_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

2026-03-14 20:48:53,175 INFO sqlalchemy.engine.Engine UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

INFO:sqlalchemy.engine.Engine:UPDATE groups SET updated_at=now(), keywords=%(keywords)s::TEXT[], symptom_category=%(symptom_category)s, avg_match_score=%(avg_match_score)s WHERE groups.id = %(groups_id)s::UUID

2026-03-14 20:48:53,177 INFO sqlalchemy.engine.Engine [cached since 6.047s ago] {'keywords': ['niemowlęctwa', 'częste', 'napady', 'drgawek', 'oprócz'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.36, 'groups_id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 6.047s ago] {'keywords': ['niemowlęctwa', 'częste', 'napady', 'drgawek', 'oprócz'], 'symptom_category': 'Neurologiczne', 'avg_match_score': 0.36, 'groups_id': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

2026-03-14 20:48:53,209 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:53,276 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:53,280 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:53,289 INFO sqlalchemy.engine.Engine [cached since 6.062s ago] {'pk_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}

INFO:sqlalchemy.engine.Engine:[cached since 6.062s ago] {'pk_1': UUID('a3bc3fbb-f3a1-4c34-906e-a6676e30d21c')}
INFO:app.services.group_characteristics:Charakterystyki grupy a3bc3fbb-f3a1-4c34-906e-a6676e30d21c zaktualizowane: keywords=['niemowlęctwa', 'częste', 'napady', 'drgawek', 'oprócz'], category=Neurologiczne, age_range=None, avg_score=0.36

2026-03-14 20:48:53,355 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles JOIN group_members ON group_members.user_id = symptom_profiles.user_id
WHERE group_members.group_id = %(group_id_1)s::UUID

2026-03-14 20:48:53,362 INFO sqlalchemy.engine.Engine [cached since 6.335s ago] {'group_id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

INFO:sqlalchemy.engine.Engine:[cached since 6.335s ago] {'group_id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

2026-03-14 20:48:53,400 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(id_1)s::UUID
 LIMIT %(param_1)s

2026-03-14 20:48:53,404 INFO sqlalchemy.engine.Engine [cached since 19.12s ago] {'id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7'), 'param_1': 1}

INFO:sqlalchemy.engine.Engine:[cached since 19.12s ago] {'id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7'), 'param_1': 1}

2026-03-14 20:48:53,438 INFO sqlalchemy.engine.Engine SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

INFO:sqlalchemy.engine.Engine:SELECT users.age_range AS users_age_range
FROM users JOIN group_members ON group_members.user_id = users.id
WHERE group_members.group_id = %(group_id_1)s::UUID AND users.age_range IS NOT NULL

2026-03-14 20:48:53,440 INFO sqlalchemy.engine.Engine [cached since 6.344s ago] {'group_id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

INFO:sqlalchemy.engine.Engine:[cached since 6.344s ago] {'group_id_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

2026-03-14 20:48:53,473 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-03-14 20:48:53,539 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:48:53,541 INFO sqlalchemy.engine.Engine SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

INFO:sqlalchemy.engine.Engine:SELECT groups.id AS groups_id, groups.name AS groups_name, groups.description AS groups_description, groups.cluster_id AS groups_cluster_id, groups.is_active AS groups_is_active, groups.member_count AS groups_member_count, groups.created_at AS groups_created_at, groups.updated_at AS groups_updated_at, groups.accent_color AS groups_accent_color, groups.keywords AS groups_keywords, groups.age_range AS groups_age_range, groups.symptom_category AS groups_symptom_category, groups.avg_match_score AS groups_avg_match_score, groups.centroid AS groups_centroid, groups.admin_note AS groups_admin_note, groups.admin_note_by AS groups_admin_note_by, groups.admin_note_at AS groups_admin_note_at
FROM groups
WHERE groups.id = %(pk_1)s::UUID

2026-03-14 20:48:53,542 INFO sqlalchemy.engine.Engine [cached since 6.316s ago] {'pk_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}

INFO:sqlalchemy.engine.Engine:[cached since 6.316s ago] {'pk_1': UUID('6c079d41-d7ef-4c7f-a66d-f116425206d7')}
INFO:app.services.group_characteristics:Charakterystyki grupy 6c079d41-d7ef-4c7f-a66d-f116425206d7 zaktualizowane: keywords=['napady', 'niemowlęctwa', 'drgawek', 'rozwój', 'ruchowy'], category=Neurologiczne, age_range=None, avg_score=0.0

2026-03-14 20:48:53,604 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

Nowo utworzonych profili objawów: 40
Zaktualizowanych profili objawów: 0

In [7]:
# Diagnostyka: liczba profili i rozkład po grupach

with get_db() as db:
    total_profiles = db.query(SymptomProfile).count()
    print(f"Liczba profili objawów w bazie: {total_profiles}")

    rows = (
        db.query(SymptomProfile.group_id)
        .all()
    )


group_ids = [row[0] for row in rows]
counts = Counter(group_ids)

print("\nRozkład liczby profili w grupach:")
for group_id, cnt in counts.items():
    print(f"  grupa={group_id}: {cnt} profili")

2026-03-14 20:49:42,708 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-03-14 20:49:42,711 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles) AS anon_1

INFO:sqlalchemy.engine.Engine:SELECT count(*) AS count_1
FROM (SELECT symptom_profiles.id AS symptom_profiles_id, symptom_profiles.user_id AS symptom_profiles_user_id, symptom_profiles.description AS symptom_profiles_description, symptom_profiles.embedding AS symptom_profiles_embedding, symptom_profiles.group_id AS symptom_profiles_group_id, symptom_profiles.match_score AS symptom_profiles_match_score, symptom_profiles.created_at AS symptom_profiles_created_at, symptom_profiles.updated_at AS symptom_profiles_updated_at
FROM symptom_profiles) AS anon_1

2026-03-14 20:49:42,713 INFO sqlalchemy.engine.Engine [generated in 0.00230s] {}

INFO:sqlalchemy.engine.Engine:[generated in 0.00230s] {}

Liczba profili objawów w bazie: 40
2026-03-14 20:49:42,772 INFO sqlalchemy.engine.Engine SELECT symptom_profiles.group_id AS symptom_profiles_group_id
FROM symptom_profiles

INFO:sqlalchemy.engine.Engine:SELECT symptom_profiles.group_id AS symptom_profiles_group_id
FROM symptom_profiles

2026-03-14 20:49:42,774 INFO sqlalchemy.engine.Engine [cached since 55.78s ago] {}

INFO:sqlalchemy.engine.Engine:[cached since 55.78s ago] {}

2026-03-14 20:49:42,805 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

Rozkład liczby profili w grupach:
  grupa=a2644a80-31b4-430d-9a1d-7d1cbc922e9b: 9 profili
  grupa=ee9f537e-dc5a-4927-ac9c-7fb86211aa09: 1 profili
  grupa=e816d3a6-a075-45f7-92c4-3d1f38818ea9: 1 profili
  grupa=49357027-f555-473a-8c72-cafd78dc5fc2: 3 profili
  grupa=3c8705ba-ea53-4263-b938-42b64aee1feb: 1 profili
  grupa=0946e26a-2416-427b-80d3-cb4e30902b5b: 3 profili
  grupa=bb90910c-36eb-4467-ba7d-1b5b5e4ed1ee: 1 profili
  grupa=e9a71a4c-b2de-4a87-ac05-4d527d6745ab: 1 profili
  grupa=a3bc3fbb-f3a1-4c34-906e-a6676e30d21c: 2 profili
  grupa=381f180d-adc3-4a20-a80a-76d8ef0793ff: 1 profili
  grupa=e1fc2c14-04c6-4cd7-b932-7805776a8ba9: 1 profili
  grupa=ccfcab6e-ad44-4c44-a3f4-f89c9067e6ef: 2 profili
  grupa=ad488d0b-6569-40df-ae7a-3ee3758b2236: 1 profili
  grupa=70b3efbb-3c9b-44db-bf24-f453515ab3dd: 2 profili
  grupa=965b3861-f29a-43cd-8e70-6474097fafa6: 1 profili
  grupa=ce577c16-4dd0-445e-8e55-96b461abf41c: 1 profili
  grupa=b239d74f-86fd-4a12-b3d4-ade068475954: 1 profili
  grupa=a14e380d-ea0e-4155-ad55-129c3838c2d3: 1 profili
  grupa=e4af521a-c6e9-4a68-ae6f-01d847476a0e: 1 profili
  grupa=6c079d41-d7ef-4c7f-a66d-f116425206d7: 1 profili
  grupa=6e09cb1a-0a9b-4321-8192-c71fbb654361: 1 profili
  grupa=816e4d87-bfa7-4db8-ae3a-c5a62b9452b9: 1 profili
  grupa=352f2599-4ee9-4f18-9f3b-52bb7cf71834: 1 profili
  grupa=b12cb335-a91d-40d1-9522-6b0b58ca1358: 1 profili
  grupa=764bce6a-f8e1-4319-8d54-50cbf3bde1e0: 1 profili

In [8]:
# Eksperyment ML: prosta klasteryzacja KMeans na embeddingach

from sklearn.cluster import KMeans

# Weźmy embeddingi dla opisów z JSON-a (bez czytania z bazy)
texts = [rec["description"] for rec in records]
embeddings = generate_embeddings_batch(texts)

X = np.array(embeddings)
print("Macierz embeddingów:", X.shape)

# Przy niewielkiej liczbie rekordów spróbujmy np. 3 klastry
n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init="auto")
cluster_labels = kmeans.fit_predict(X)

# Podgląd wyników w DataFrame
ml_df = pd.DataFrame(
    {
        "email": [rec["email"] for rec in records],
        "cluster": cluster_labels,
    }
)

display(ml_df.head())
print("\nLiczność klastrów:")
print(ml_df["cluster"].value_counts())

Batches: 100%|██████████| 2/2 [00:01<00:00,  1.74it/s]

Macierz embeddingów: (40, 384)

               email  cluster
0  test0001@zebra.pl        1
1  test0002@zebra.pl        2
2  test0003@zebra.pl        2
3  test0004@zebra.pl        1
4  test0005@zebra.pl        0

Liczność klastrów:
cluster
1    17
0    13
2    10
Name: count, dtype: int64

In [9]:
def run_full_seed(dry_run: bool = False) -> None:
    """Wysokopoziomowa funkcja do ponownego uruchamiania całego seeda.

    Kroki:
    - wczytanie JSON,
    - stworzenie użytkowników,
    - stworzenie / aktualizacja profili objawów i dopasowanie grup.
    """
    global DRY_RUN, records
    DRY_RUN = dry_run

    # wczytaj dane
    records = load_dataset(DATA_PATH)
    logger.info("Start seeda. Rekordów: %d (DRY_RUN=%s)", len(records), DRY_RUN)

    created = 0
    existing = 0
    profiles_created = 0
    profiles_updated = 0

    with get_db() as db:
        for rec in records:
            # użytkownik
            user_before = db.query(User).filter(User.email == rec["email"]).first()
            user = create_user_from_record(db, rec)
            if user_before is None:
                created += 1
            else:
                existing += 1

            # profil objawów
            existing_profile = (
                db.query(SymptomProfile)
                .filter(SymptomProfile.user_id == user.id)
                .first()
            )
            profile = create_or_update_symptom_profile(db, user, rec["description"])
            if existing_profile is None:
                profiles_created += 1
            else:
                profiles_updated += 1

        if not DRY_RUN:
            # Uzupełnienie charakterystyk grup (gdy Celery nie działa).
            group_ids = {row[0] for row in db.query(SymptomProfile.group_id).all() if row[0] is not None}
            for gid in group_ids:
                update_group_characteristics(db, str(gid))

        if DRY_RUN:
            logger.info("DRY_RUN=True — wykonuję rollback zmian")
            db.rollback()
        else:
            logger.info("Zatwierdzam zmiany w bazie")

    print("Seed zakończony:\n")
    print(f"  Nowo utworzonych użytkowników: {created}")
    print(f"  Użytkownicy już istniejący:   {existing}")
    print(f"  Nowo utworzonych profili:     {profiles_created}")
    print(f"  Zaktualizowanych profili:     {profiles_updated}")


# Przykład użycia:
# run_full_seed(dry_run=True)  # test bez zapisywania do bazy
# run_full_seed(dry_run=False) # realny seed do bazy